### ISSUE TITLE
Add composite action folders to dependabot config

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse#1025]
## Description

It does not appear as though dependabot explicitly searches through composite action folders for action version upgrades. According to [this StackOverflow post however](https://stackoverflow.com/a/74997644/3277713), we should be able to get dependabot to check these versions by explicitly adding the various action folders to the dependabot config.

## Additional context

Originally from https://github.com/WordPress/openverse/pull/997/files#r1146996028

**Comment by AdarshRawat1** [comment]
Requesting permission to contribute to this feature.

**Comment by AetherUnbound** [comment]
I've assigned you Adarsh, please go ahead! 😄

**Comment by sarayourfriend** [comment]
@AdarshRawat1 Are you still interested in working on this issue? I've unassigned you for now, but please comment back again if you'd still like to take it on.

**Comment by ngken0995** [comment]
@AetherUnbound and @sarayourfriend There are four actions in `.github/actions`:

- `build-docs`
- `get-changes`
- `load-img`
- `setup-env`

Here is an example to include in `dependabot.yml`:

```
  - package-ecosystem: github-actions
    directory: /actions/build-docs
    schedule:
      interval: weekly
```
Please let me know if I'm the right track to include all four in `dependabot.yml`

**Comment by sarayourfriend** [comment]
That looks like a good start, @ngken0995. Please use the monthly interval to match the rest of the configuration. It will also need the same label configuration as the existing `github-actions` entry.
