### ISSUE TITLE
http  in api response

### ISSUE THREAD

**Issue by lmwp** [WordPress/openverse#1061]
## Description
On WP 6.2 RC5, when I use the Openverse API, the json in the response contains HTTP urls instead of HTTP**S** (*thumbnail, detail_url, related_url*)
## Reproduction

1.  Open a publication and Click on Block Inserter
2.  Open a publication and Click on Block Inserter
3.  Click in tab Media to insert an openverse media
4.  Choose Openverse and choose a new image.
To test try just use : 
https://api.openverse.engineering/v1/images/cd410bfb-cdd6-48b7-a4cd-d0579dee2046/
5. See error.

## Screenshots

{
    "id": "cd410bfb-cdd6-48b7-a4cd-d0579dee2046",
    "title": "Soldattorpsskylt, Mo Härads kompani nr 105. Jönköpings regemente.",
    "indexed_on": "2022-12-25T07:10:57.039858Z",
    "foreign_landing_url": "https://digitaltmuseum.se/021018505863",
    "url": "https://mm.dimu.org/image/02349TDMx8Fw?dimension=1200x1200",
    "creator": null,
    "creator_url": null,
    "license": "pdm",
    "license_version": "1.0",
    "license_url": "https://creativecommons.org/publicdomain/mark/1.0/",
    "provider": "europeana",
    "source": "europeana",
    "category": null,
    "filesize": null,
    "filetype": null,
    "tags": [],
    "attribution": "\"Soldattorpsskylt, Mo Härads kompani nr 105. Jönköpings regemente.\" is marked with Public Domain Mark 1.0. To view the terms, visit https://creativecommons.org/publicdomain/mark/1.0/.",
    "fields_matched": [],
    "mature": false,
    "height": null,
    "width": null,
    "thumbnail": "[http://api.openverse.engineering/v1/images/cd410bfb-cdd6-48b7-a4cd-d0579dee2046/thumb/](https://api.openverse.engineering/v1/images/cd410bfb-cdd6-48b7-a4cd-d0579dee2046/thumb/)",
    "detail_url": "[http://api.openverse.engineering/v1/images/cd410bfb-cdd6-48b7-a4cd-d0579dee2046/](https://api.openverse.engineering/v1/images/cd410bfb-cdd6-48b7-a4cd-d0579dee2046/)",
    "related_url": "[http://api.openverse.engineering/v1/images/cd410bfb-cdd6-48b7-a4cd-d0579dee2046/related/](https://api.openverse.engineering/v1/images/cd410bfb-cdd6-48b7-a4cd-d0579dee2046/related/)"
}
## Environment

Test on WP 6.2 RC5

- Device: 
- OS: 
- Browser: 
- Version: 
- Other info:

**Comment by dhruvkb** [comment]
This has been fixed. The next prod deploy of the API should update the responses.
