### ISSUE TITLE
Analytics event: `RIGHT_CLICK_IMAGE`

### ISSUE THREAD

**Issue by dhruvkb** [WordPress/openverse#1086]
## Description

The goal is to 

- add the type for event `RIGHT_CLICK_IMAGE` to the `Events` type.
  https://github.com/WordPress/openverse/blob/839418fabb0972ec3c3ccf48c72fd64cbba03cb9/frontend/src/types/analytics.ts#L12

- fire this event from the appropriate location in the codebase using the `useAnalytics` composable.
  https://github.com/WordPress/openverse/blob/839418fabb0972ec3c3ccf48c72fd64cbba03cb9/frontend/src/composables/use-analytics.ts#L11

## Reference

https://github.com/WordPress/openverse/blob/839418fabb0972ec3c3ccf48c72fd64cbba03cb9/rfcs/analytics/20221006-implementation_plan_frontend.md?plain=1#L413

## Additional information

- [RFC](https://github.com/WordPress/openverse/blob/main/rfcs/analytics/20221006-implementation_plan_frontend.md#events)
- [Example usage in `VHomeGallery.vue`](https://github.com/WordPress/openverse/blob/839418fabb0972ec3c3ccf48c72fd64cbba03cb9/frontend/src/components/VHomeGallery/VHomeGallery.vue#L128-L134)

**Comment by CouldBeFree** [comment]
@dhruvkb I want to resolve this issue.

**Comment by dhruvkb** [comment]
Surely and please do @CouldBeFree.

**Comment by CouldBeFree** [comment]
While running the project, I am facing this issue.
Looks like somebody removed those files and now that's causing those errors.
We have somehow fixed this issue.
@dhruvkb do you have those files, or maybe they appear in different branches?
<img width="656" alt="Screenshot 2023-04-09 at 12 37 49" src="https://user-images.githubusercontent.com/25415541/230765818-db832f77-cd55-4a2a-88e8-7933344c1f51.png">

**Comment by dhruvkb** [comment]
Please run

```console
$ just frontend/run i18n
```

or, if you don't have `just`,

```console
$ pnpm --filter=frontend run i18n
```

And retry what you were doing. The translation files should've been automatically generated but if they weren't for some reason, the above commands should fix it.
