### ISSUE TITLE
Analytics event: `TOGGLE_FILTERS`

### ISSUE THREAD

**Issue by dhruvkb** [WordPress/openverse#1088]
## Description

The goal is to 

- add the type for event `TOGGLE_FILTERS` to the `Events` type.
  https://github.com/WordPress/openverse/blob/839418fabb0972ec3c3ccf48c72fd64cbba03cb9/frontend/src/types/analytics.ts#L12

- fire this event from the appropriate location in the codebase using the `useAnalytics` composable.
  https://github.com/WordPress/openverse/blob/839418fabb0972ec3c3ccf48c72fd64cbba03cb9/frontend/src/composables/use-analytics.ts#L11

## Reference

https://github.com/WordPress/openverse/blob/839418fabb0972ec3c3ccf48c72fd64cbba03cb9/rfcs/analytics/20221006-implementation_plan_frontend.md?plain=1#L435

## Additional information

- [RFC](https://github.com/WordPress/openverse/blob/main/rfcs/analytics/20221006-implementation_plan_frontend.md#events)
- [Example usage in `VHomeGallery.vue`](https://github.com/WordPress/openverse/blob/839418fabb0972ec3c3ccf48c72fd64cbba03cb9/frontend/src/components/VHomeGallery/VHomeGallery.vue#L128-L134)

**Comment by AdarshRawat1** [comment]
@dhruvkb  May I take on this issue? If successful, I would be interested in addressing additional issues under "Analytics event" as well.

**Comment by dhruvkb** [comment]
Sure @AdarshRawat1, you can definitely work on this! If you need any assistance or clarifications, feel free to post them here on this issue as comments.
