### ISSUE TITLE
"Add stack label" CI/CD step fails on PRs from forks

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse#1090]
## Description

The auth token we provide for CI/CD workflow does not have the permissions necessary to run on forks.
This means that that the CI/CD on forks is failing.

## Reproduction

1. See https://github.com/WordPress/openverse/actions/runs/4562891150/jobs/8050684128?pr=1062

## Environment

https://github.com/WordPress/openverse/blob/839418fabb0972ec3c3ccf48c72fd64cbba03cb9/.github/workflows/ci_cd.yml#L148

Priority high because the community PRs are failing CI.

**Comment by dhruvkb** [comment]
The entire `label_new_pr.yml` → `label_pr.yml` → `label_pr.py` can be hugely simplified (if not entirely removed) using [action/labeler](https://github.com/actions/labeler).
