### ISSUE TITLE
Remove the Community Involvement handbook page

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse#1093]
## Description

The [Community Involvement handbook page](https://make.wordpress.org/openverse/handbook/openverse-catalog/community-involvement/) is either outdated or already implemented by way of the [provider DAG refactors](https://github.com/WordPress/openverse-catalog/milestone/8) milestone and [DAG sync scripts](https://github.com/WordPress/openverse-catalog/pull/711). It can likely be entirely removed.

**Comment by sarayourfriend** [comment]
Done!
