### ISSUE TITLE
Remove the provider ingestion script refactor handbook page

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse#1095]
## Description

The [provider ingestion script refactor guide](https://make.wordpress.org/openverse/handbook/openverse-catalog/provider-ingestion-script-refactor-guide/) handbook page is no longer needed since [the provider DAG refactor milestone](https://github.com/WordPress/openverse-catalog/milestone/8) has been completed.

**Comment by sarayourfriend** [comment]
Done!
