### ISSUE TITLE
Make `setup-env` action use `github.token`

### ISSUE THREAD

**Issue by dhruvkb** [WordPress/openverse#1102]
## Problem

Since `./github/actions/setup-env` is a GitHub action, it does not have access to secrets when it's invoked from a job step. So it has been configured to accept the `github_token` input via which the `${{ secrets.GITHUB_TOKEN }}` value is provided to it.

## Description

Actions can [access GitHub token from the `github` context using `${{ github.token }}`](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#using-the-github_token-in-a-workflow). This means we don't need to explicitly pass this token to the action and can use it inside the action directly.

## Implementation

1. Remove the `github_token` input here.
    https://github.com/WordPress/openverse/blob/1a58c9caa9f78dd350b593e2555d1a974dc089df/.github/actions/setup-env/action.yml#L17-L19

2. Replace `inputs.github_token` with `github.token` here.
   https://github.com/WordPress/openverse/blob/1a58c9caa9f78dd350b593e2555d1a974dc089df/.github/actions/setup-env/action.yml#L32

3. From the `ci_cd.yml` workflow, remove all occurrences of passing the GitHub token to the action, e.g.
   https://github.com/WordPress/openverse/blob/1a58c9caa9f78dd350b593e2555d1a974dc089df/.github/workflows/ci_cd.yml#L131

**Comment by sumit-158** [comment]
@dhruvkb Can I take this?

**Comment by dhruvkb** [comment]
Sure @sumit-158. Go ahead!

**Comment by dhruvkb** [comment]
Fixed in #1123.
