### ISSUE TITLE
`just frontend/init` fails

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse#1142]
## Reproduction

1. Start the analytics stack by running `just frontend/up` and `just frontend/init` on the `main` branch.
1. Checkout a PR that adds analytics events, like #1118 or #1158.
2. Run `just frontend/init` to add the event added in the PR to Plausible.
3. See error.

## Screenshots

```

/Users/obulat/Documents/openverse/openverse/frontend/bin/get-custom-event-names.js:26
    (s) => s.name.escapedText === "Events"
                  ^

TypeError: Cannot read properties of undefined (reading 'escapedText')
    at .../openverse/frontend/bin/get-custom-event-names.js:26:19
    at Array.find (<anonymous>)
    at main (/Users/obulat/Documents/openverse/openverse/frontend/bin/get-custom-event-names.js:25:44)
    at Object.<anonymous> (.../openverse/frontend/bin/get-custom-event-names.js:33:1)
    at Module._compile (node:internal/modules/cjs/loader:1191:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1245:10)
    at Module.load (node:internal/modules/cjs/loader:1069:32)
    at Function.Module._load (node:internal/modules/cjs/loader:904:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:22:47
error: Recipe `init` failed on line 27 with exit code 1

```

## Additional context

Adding a check for undefined fixes the issue:
```
   const eventsType = sourceFile.statements.find(
-    (s) => s.name.escapedText === "Events"
+    (s) => s.name?.escapedText === "Events"
   )
   const eventNames = eventsType.type.members.map((m) => m.name.escapedText)

```

**Comment by obulat** [comment]
> @obulat I am not able to reproduce this error on `main`. Do you have the contents of the `src/types/analytics.ts` file when this failed? As long as that TS file is valid, this should not raise an error.

I saw this error when I checked out the PR that adds an analytics event, and tried just frontend/up and just frontend/init. It might have something to do with the additional events?

**Comment by dhruvkb** [comment]
If the PR you're referring to is #1118, it's not updated with `main` and doesn't have the code for setting up custom events. The `setup_plausible.sh` script in that PR only sets up the domain.

**Comment by obulat** [comment]
> If the PR you're referring to is #1118, it's not updated with `main` and doesn't have the code for setting up custom events. The `setup_plausible.sh` script in that PR only sets up the domain.

This happens on other PRs, too. I rebased #1158 on the latest main, and if I do `just down` and try to start the analytics stack again by running `just frontend/up` and `just frontend/init`, I get this error. Its seems that some of the `ts` `statements` don't have a `name` property.
