### ISSUE TITLE
Use consistent Docker user names

### ISSUE THREAD

**Issue by dhruvkb** [WordPress/openverse#1145]
## Problem

Our services use an interesting mix of usernames for users created inside Docker.

| Service | Username |
|-|-|
| api | [opener](https://github.com/WordPress/openverse/blob/5106dc3e73d0b55f8eb0bfb8375c103c93402c1a/api/Dockerfile#L76) |
| ingestion_server | [ingestionu](https://github.com/WordPress/openverse/blob/5106dc3e73d0b55f8eb0bfb8375c103c93402c1a/ingestion_server/Dockerfile#L58) |
| catalog | [airflow](https://github.com/WordPress/openverse-catalog/blob/46281fc9fda60ab2df0df6d85043565dfc51b12d/docker/airflow/Dockerfile#L51) |

## Description

We should use the same, or a similar format of, names for these users.

**Comment by sarayourfriend** [comment]
@krysal Can you add more details about how to do this/what it will take to do? It's labelled good first issue now but I'm not sure I would know where to start :sweat_smile:. I kind of assume there would be complications with this too :thinking:

**Comment by tejaswarathe** [comment]
@dhruvkb Does a naming scheme like apiuser, ingestionuser, airflowuser?

Does the below change look good or do we need to check more impact?

```
RUN useradd --create-home apiuser \
  && chown -R apiuser /static
USER apiuser

COPY --chown=apiuser --from=packages openverse-attribution /packages/python/openverse-attribution/

COPY --chown=apiuser . /api/
```

**Comment by dhruvkb** [comment]
@tejaswarathe I think a naming scheme of service + "_user" would be a good place to start.

After changing a name, do a search in the entire codebase (`git grep`) to see if that username appears anywhere else in the repo. That will give you an idea of where else it has been used.

One more way to check and be more confident in the change would be to open a PR with your changes. That would let our CI + CD job check everything and determine if everything is working normally.

**Comment by sarayourfriend** [comment]
What is the utility in using a different username per service? Wouldn't that complicate scripts using `docker compose exec`?

**Comment by dhruvkb** [comment]
That's true @sarayourfriend and I agree. I was recommending different usernames because it's closer to [what's currently happening](https://github.com/WordPress/openverse/issues/1145#issue-1656979785). We're already setting the `DC_USER` env var in the `justfile`s for the API and the catalog so it would be a matter of finding-and-replacing the username for both of those services.

@tejaswarathe maybe just using the same username everywhere might be better, something like "ov_user" maybe? "[opener](https://github.com/WordPress/openverse/blob/5106dc3e73d0b55f8eb0bfb8375c103c93402c1a/api/Dockerfile#L76)" is too informal and is a name we use to refer to ourselves so not ideal for a container username.
