### ISSUE TITLE
Extract Python scripts out of GitHub workflows

### ISSUE THREAD

**Issue by dhruvkb** [WordPress/openverse#1148]
## Problem

Because of their ease of use, the use of Python-based scripts inside GitHub workflows has increased a lot.

https://github.com/WordPress/openverse/blob/46a19a5776e747fd2b6111787222f2e6efc5afe3/.github/workflows/ci_cd.yml#L78

https://github.com/WordPress/openverse/blob/46a19a5776e747fd2b6111787222f2e6efc5afe3/.github/workflows/ci_cd.yml#L828

https://github.com/WordPress/openverse/blob/46a19a5776e747fd2b6111787222f2e6efc5afe3/.github/workflows/deploy-production-api.yml#L62

https://github.com/WordPress/openverse/blob/46a19a5776e747fd2b6111787222f2e6efc5afe3/.github/workflows/deploy-production-nuxt.yml#L62

https://github.com/WordPress/openverse/blob/46a19a5776e747fd2b6111787222f2e6efc5afe3/.github/workflows/deploy-staging-api.yml#L62

https://github.com/WordPress/openverse/blob/46a19a5776e747fd2b6111787222f2e6efc5afe3/.github/workflows/deploy-staging-nuxt.yml#L62

These Python scripts are not being linted, formatted or checked in any way. Contrast this with Bash scripts inside workflows that are linted by ShellCheck.

## Description

The solution is to keep them in a directory inside the codebase, possibly with `automations/python`.

## Additional context

- They can be kept separate from `automations/python` too, considering their usage, but these are all standalone scripts that do not need any packages to be installed.

- In fact, the last 4 Python scripts referenced above (in the ECS deployment workflows) are basically identical, and can be replaced by a single one that takes arguments using `argparse`.

**Comment by rahulbollisetty** [comment]
Hi , I would like to work on this issue, could you please tell me where ```argparse``` is needed, as I see none of the above python scripts needs input.

**Comment by dhruvkb** [comment]
@rahulbollisetty your point is valid. I was wrong, `argparse` might not be needed for this. These scripts can read continue to read environment variables as they do now.
