### ISSUE TITLE
Add Openverse to https://github.com/public-apis/public-apis

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse#117]
We should add Openverse to this list of free, public APIs. It would give us some new users and make developers more aware of the project!

**Comment by himanshu007-creator** [comment]
Hi , i would like to work on this issue

**Comment by dhruvkb** [comment]
@himanshu007-creator please do so. Based on their classification scheme, it seems like their [Photography](https://github.com/public-apis/public-apis#photography) section is the best match for Openverse _as of now_.

In the future we could also add Openverse to [Music](https://github.com/public-apis/public-apis#music) and [Video](https://github.com/public-apis/public-apis#video).

**Comment by krysal** [comment]
Perhaps this could include removing the Creative Commons API from the "Open Source Projects" category too, and given the case, wouldn't it be better to wait until the official release?

**Comment by dhruvkb** [comment]
Good point @krysal, blocking this issue till the official release announcement.

**Comment by zackkrida** [comment]
This is unblocked, anyone can add https://api.openverse.engineering/v1 to these lists and remove https://api.creativecommons.engineering/v1

**Comment by zackkrida** [comment]
@vinsout , please do! You could technically add Openverse to the Photography _and_ Music sections, if they allow a single source to be in multiple lists, since Openverse now supports audio as well.

**Comment by vinsout** [comment]
Ok, thanks, the README.md of public-apis need 4 "arguments" : 
- API : Openverse
- Descriptions : ?
- Auth : ?
- HTTPS : ?
- CORS : ?

Could you tell me what i have to write for the description, the Auth options, HTTPS (yes/no), and CORS (Yes/No/Unknown)?

**Comment by sarayourfriend** [comment]
All four of those remain the same from the Creative Commons Catalogue entry :slightly_smiling_face:

**Comment by zackkrida** [comment]
That's right:

![CleanShot 2022-05-19 at 09 26 34@2x](https://user-images.githubusercontent.com/6351754/169304347-49107236-f6e6-4cd5-ae40-a46f29b9cbfe.png)


Your PR can also _remove_ (or rename) the Creative Commons Catalog entry, @vinsout!

**Comment by vinsout** [comment]
ok thanks, i will rename the "Creative Commons Catalog" API to "Openverse" and adding it on the Photography and Music sections

**Comment by vinsout** [comment]
[here](https://github.com/public-apis/public-apis/blob/master/CONTRIBUTING.md#pull-request-guidelines) they saying to not put the api in multiple categories. So on where category I have to put the api ?

**Comment by sarayourfriend** [comment]
Thanks for looking into this @vinsout. I think it makes sense to keep it just in the Open Source Projects categories that the CC entry was in.

**Comment by vinsout** [comment]
Ok so i just rename it.

**Comment by vinsout** [comment]
> This is unblocked, anyone can add https://api.openverse.engineering/v1 to these lists and remove https://api.creativecommons.engineering/v1

And change the url

**Comment by sarayourfriend** [comment]
Yup!

**Comment by vinsout** [comment]
I created the Pull Request, i hope he will be accepted

**Comment by vinsout** [comment]
Hello everyone, did you see the [pull request](https://github.com/public-apis/public-apis/pull/3160) ? and this [issues](https://github.com/public-apis/public-apis/issues/3104) they share ?

**Comment by zackkrida** [comment]
Ah, thanks @vinsout, how unfortunate that the owners of the repository aren't communicating clearly with the maintainers. Thank you for your effort. @WordPress/openverse team what do you think here? It might be best to not spend too much effort on this and close this issue.

**Comment by vinsout** [comment]
I have send a message on the PR to have the new repo because they talk about a clone of the public-api repo (on the issues where they talk about there problems). I found two repo the repo public-api-dev/public-api and the repo public-api-list/public-api-list and I don't know what is the correct repo to follow. I will

**Comment by zackkrida** [comment]
I think a big part of the problem is that the 'official' repo still has the most traffic and a very large audience, and the forks do not yet. At least the 'Creative Commons' entry on the official list still points to Openverse!

**Comment by zackkrida** [comment]
Given the chaos surrounding this public-apis project that is out of our hands, I'm going to close this iusse. Thanks for your help @vinsout
