### ISSUE TITLE
Clear the done column of the project board weekly

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse#1170]
## Description

Our old project board had automation which would clear the "Merged" and "Closed" columns every week:

https://github.com/WordPress/openverse/blob/900d0f3cf1ed488cfa3fe17662fe080f72b8bc3a/.github/workflows/pr_project_automation.yml#L33-L45

https://github.com/WordPress/openverse/blob/main/.github/GITHUB.md#pr-project-automation

We will want to add similar automation to the new [project board](https://github.com/orgs/WordPress/projects/75/views/1)

## Additional context

Part of the effort of #818

**Comment by obulat** [comment]
The simplest solution would be to use the UI to set up auto-archiving closed issues that are older than x weeks:

<img width="1002" alt="Screenshot 2023-04-12 at 5 47 50 PM" src="https://user-images.githubusercontent.com/15233243/231495422-6d2bd1da-4616-4a08-8356-50acf5beefe6.png">

**Comment by AetherUnbound** [comment]
I saw that! When I was thinking about this yesterday, I somehow thought that would cause issues to disappear before they should (depending on timing) or show up for multiple weeks 🤔 but now that I'm thinking about it again with a clearer head, I think this would work great!

**Comment by obulat** [comment]
We could also set it to older than 2 weeks, so that we have ample time to review them in the meetings.

**Comment by AetherUnbound** [comment]
In that case we might see the same item multiple weeks in a row, but I guess that's an easier problem to deal with 🙂

**Comment by AetherUnbound** [comment]
![image](https://user-images.githubusercontent.com/10214785/231593558-4ae4db0e-1bf5-4614-a3ea-0b46e10ff3b5.png)

Okay, I've set up an auto-archive policy: https://github.com/orgs/WordPress/projects/75/workflows/6899393
