### ISSUE TITLE
Missing gap between media titles and primary CTA on single result pages

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse#1203]
Single result pages are missing a gap between the pink CTA button and the title of the work. Marking this as **high priority** as it's a visual regression that is prominent on pages seen by most users.

Example: https://openverse.org/image/579a9509-f0a5-4e00-b938-03ec1e308309?q=Netherlands

<img width="947" alt="CleanShot 2023-04-14 at 13 14 28@2x" src="https://user-images.githubusercontent.com/6351754/232112817-fb41fbb5-0e6a-42ee-80ec-27edeb2a9ca9.png">

**Comment by obulat** [comment]
I can't see this issue in prod now:
<img width="922" alt="Screenshot 2023-05-02 at 6 33 39 PM" src="https://user-images.githubusercontent.com/15233243/235714264-4e7063c3-8e70-4c6a-ae68-a0b5db45ac40.png">
