### ISSUE TITLE
Extract entrypoints to separate shell scripts

### ISSUE THREAD

**Issue by dhruvkb** [WordPress/openverse#1226]
## Current situation

The entrypoints for services `s3` and `load_to_s3` are written inside the `docker-compose.yml` file. 

https://github.com/WordPress/openverse/blob/63d8b5d722666ec418a674fc3137f3a5a4b65e20/docker-compose.yml#L76

https://github.com/WordPress/openverse/blob/63d8b5d722666ec418a674fc3137f3a5a4b65e20/docker-compose.yml#L112

This 
- makes them more complicated as they have to be written using `sh/bash -c ''`
- requires double escaping of vars to prevent expansion on the host
- prevents them from being checked by ShellCheck, concealing possible errors

## Suggested improvement

This can be improved by extracting the entrypoints to `*-entrypoint.sh` files inside `docker/minio/` and only referring to them from here.

## Benefit

This will simplify the workflow and bring them under the coverage of our very capable linting system.

**Comment by MukulKolpe** [comment]
Hi @dhruvkb, this looks exciting! Can I work on this issue?

**Comment by dhruvkb** [comment]
Sure @MukulKolpe, please do.

**Comment by dhruvkb** [comment]
Tagging @arun-chib in a comment so that they can be assigned.
