### ISSUE TITLE
Send `main` CI failures to alerts channel

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse#1228]
## Problem

Following up on #1066, it isn't clear when something has happened that needs to be looked into. Additionally, because the notifications do not get sent to the alerts channel, the MSR for the week could easily not notice notifications alerting us to an issue with the build or staging deployment pipelines.

## Description

Two related requests:

1. Create a page in the documentation site describing what each of the checks and their potential statuses mean. For example, for `emit-docs`, describe what it means when it passes, when it is skipped, and when it fails, and where to look and investigate to find the cause of problems when they exist. Link this page in the Slack message.
2. When anything fails (or is incorrectly skipped) send the Slack message to the alerts channel instead of the notification channel.

## Additional context

I'm happy to work on this in my spare time this week during MSR as it is primarily an improvement to help MSR. However, I'll need help from @dhruvkb to understand the different states for each check to know when the "skipped" state is an issue. Based on the discussion in the original PR, my understanding was that skipped _could_ be an issue, but I think my understanding must not have been clear on the intentions.

**Comment by dhruvkb** [comment]
I've added some documentation about the reporting action in #1001. I'm happy to provide additional input, with that being a good starting point.

**Comment by sarayourfriend** [comment]
I'm upgrading this to high because we have missed these messages.

I've also opened https://github.com/WordPress/openverse/issues/2360 to supplement this, also at high priority.

**Comment by zackkrida** [comment]
@sarayourfriend I've self-assigned the supplemental PR and can work on it tomorrow.

**Comment by dhruvkb** [comment]
I think this is sufficiently solved by #2360 and #2404.

**Comment by sarayourfriend** [comment]
This issue is to change the channel the notifications are sent to in order to better match their intended purpose. Right now they go to the notifications channel which gets flooded with deployments, emails, new PRs/discussions, and other things. Because these messages in particular need to be triaged, it's easy for them to get lost.

We could argue that failed deployment notifications should also go to the alerts channel, in fact.
