### ISSUE TITLE
Integrity error causes oauth registration view to 500

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse#1232]
## Sentry link

https://openverse.sentry.io/share/issue/8780a79fd7a04eaab42f1f53fe528583/

## Description

https://github.com/WordPress/openverse/blob/697f62f01a32cb7fcf2f4a7627650a113cba40da/api/catalog/api/views/oauth2_views.py#L130-L146

The above code should be wrapped in a try/except and handle integrity errors with a proper descriptive 400 rather than 500.

## Additional context

Marking priority medium as our app should not 500.

**Comment by AetherUnbound** [comment]
The Sentry issue is no longer available, and we don't have any Sentry issues that match a search on "integrity" over the last 90 days. I believe this was resolved by #3444
