### ISSUE TITLE
Remove the discussion issue template

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse#1238]
## Problem

We use GitHub discussions for discussions, not issues (is my understanding), yet we have a "discussions" issue template, adding yet another template to our vast list of issue templates.

## Description

Remove the discussion issue template.

## Additional context

I think we should remove Infrastructure Improvement Suggestion as well. If this template is meant to encourge requests to improve developer experience, we should have an explicit issue template for documentation improvements, though that could be easily tied in with "code quality improvements" by changing the name of the code quality template to "Documentation and code quality improvements".

I think we should also remove the "project thread" template as (a) it is not _that_ often used, (b) it is used only internally (community contributors are never using it), and therefore (c) we could keep the template in the documentation site, to be copied from there whenever a new one needs to be made. We could probably do the same for the Airflow and Sentry issues as well. They are also only used by maintainers.

Reducing the number of templates is imperative to me. If a new contributor tries to open an issue, rather than the templates helping guide them to give the best issue possible, the list of issue templates is overwhelming and practically baffling. At the very least we could do to sort them better, perhaps by adding some kind of prefix to the internal-only templates that forces them to be sorted to the bottom of the list.

**Comment by dhruvkb** [comment]
Linking to a [post on GitHub's blog](https://github.blog/2023-01-09-github-discussions-just-got-better-with-category-forms/) about discussion having their own templates, called "category forms".

**Comment by zackkrida** [comment]
Thanks, @metabiswadeep! Do comment here if you have any questions or run into issues.

**Comment by metabiswadeep** [comment]
Do I remove the project_thread, airflow and sentry templates as well?

**Comment by krysal** [comment]
We haven't discussed what to do with those templates yet. I favor removing the **Infrastructure Improvement Suggestion** and **Sentry Bug** templates (just adding a label doesn't provide much value over the existing Bug issue type), and moving the **Project Thread** template to the documentation site, as Sara suggests, it could go under a page like the [Implementation Plan Template](https://docs.openverse.org/projects/templates/implementation-plan.html).

I think we could also merge the **Component spec** and **Design Changes** and move the **Airflow Alert** template to the docs site, but these need inputs from peers.

@metabiswadeep So to sum up, you can delete the **Infrastructure Improvement Suggestion** and **Sentry Bug** templates. We'll create another issue to move the others.
