### ISSUE TITLE
Maybe add Openverse to WP bug tracking code?

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse#124]
I noticed this code in the wp.org repo:

https://github.com/WordPress/wordpress.org/blob/c54eb93f3f27d02bba495f6a418db2316e9a03c6/wordpress.org/public_html/style/trac/wp-trac.js#L56

Might it make sense to add Openverse to this list? Tagging @sarayourfriend since you have a bit more ecosystem knowledge than I do.

**Comment by sarayourfriend** [comment]
We could add it there, though I'm not sure exactly how that is used (I clicked around wp.org for a while and couldn't find any manifestion of it). Alternatively we could just add it to the welcome box message for https://make.wordpress.org/openverse/

**Comment by zackkrida** [comment]
I'll ask around and see if anyone knows where these are used.

**Comment by zackkrida** [comment]
From @ryelle in Slack:

https://wordpress.slack.com/archives/C02QB8GMM/p1639596057393200

> I don’t know if they’re displayed anywhere, but it’s used to show redirection messages for projects that use other trackers (github, mostly). Like if you go to https://meta.trac.wordpress.org/newticket and try to change the component to Pattern Directory, it’ll ask you to create a github issue instead.

**Comment by sarayourfriend** [comment]
Cool! Sounds like we could do both then.
