### ISSUE TITLE
Update documentation links to point to monorepo

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse#1248]
## Problem

@krysal reports that the [Documentation guidelines document](https://docs.openverse.org/guides/documentation/guidelines.html) includes links to the openverse-api repository.

## Description

Search the repository for references to `openverse-api` and `openverse-frontend` and `openverse-catalog` and update them all to reference the monorepo. Where appropriate, add a note about the fact that the code was moved (not sure if necessary but it may be useful context for some specific cases).

## Additional context

Marked as high because links to the old repositories are "extra" stale in that they'll never have up to date information.

**Comment by zackkrida** [comment]
These references were fixed and further documentation restructuring took place which removed the file referenced here.
