### ISSUE TITLE
Add language labels

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse#126]
I propose we add language specific labels to make it easier for contributors to know what PRs they are capable of working on:

- `🐘 tech: PHP`
- `🐍 tech: Python`
- `🟨 tech: JavaScript`

As examples.

**Comment by obulat** [comment]
I agree, it's a nice way for contributors to find issues they can work on. We could also add a link to search issues by language.

**Comment by zackkrida** [comment]
It was difficult to find an emoji for JavaScript, weird that it doesn't have an animal mascot in hindsight!

**Comment by dhruvkb** [comment]
I like this idea. We could, in the future, expand this to refer to "technologies" in the stack instead of purely languages but this is a great start for new contributors.

**Comment by zackkrida** [comment]
I like the idea of a 'flat' label for tech _and_ languages, I don't see a reason to differentiate. Revised my proposal; thanks!

**Comment by dhruvkb** [comment]
Nice! I'd say this issue is ready for implementation!

**Comment by zackkrida** [comment]
Draft PR created!

**Comment by AetherUnbound** [comment]
What's the level of granularity we're comfortable with here? Would we like to have ones for "Django" and "Airflow"? Is Python specific enough?

**Comment by zackkrida** [comment]
@AetherUnbound I think those are perfect examples of things we could label! Any big libraries, like Vue or even Nuxt on the front-end, seem like worthwhile additions. 

Maybe any piece of technology large enough to have its own conferences haha
