### ISSUE TITLE
Raise an exception if a space is found in URL fields

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse#1279]
## Description

Based on [this discussion](https://github.com/WordPress/openverse-catalog/pull/1003#issuecomment-1447467476) - URLs which get written to TSV should not have spaces in them. It should be up to the provider scripts to handle how those spaces are handled, but we should know before they make it into the database that there's an issue with the URLs.

We can add this in the URL validation step of `MediaStore`:

https://github.com/WordPress/openverse-catalog/blob/9d758e9fea1087cbb2761f96674a7686c788a5ce/openverse_catalog/dags/common/storage/media.py#L129-L132

**Comment by ngken0995** [comment]
Hello @AetherUnbound, Can I be assigned to work on this?

**Comment by dhruvkb** [comment]
Sure @ngken0995!
