### ISSUE TITLE
Upgrade to Python 3.11

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse#1370]
## Description

[Python 3.11 is finally out](https://docs.python.org/3/whatsnew/3.11.html), and with it comes a tremendous potential speedup:

> Python 3.11 is between 10-60% faster than Python 3.10. On average, we measured a 1.25x speedup on the standard benchmark suite.

There are also some other exciting changes, including [`TypedDict` optional fields improvements](https://docs.python.org/3/whatsnew/3.11.html#whatsnew311-pep655), [enriched exceptions](https://docs.python.org/3/whatsnew/3.11.html#whatsnew311-pep678), and [finer-grained exceptions](https://docs.python.org/3/whatsnew/3.11.html#whatsnew311-pep657).

We should try to get on this version as soon as possible, but unfortunately we're dependent on Airflow being Python 3.11 compatible. Work is being done upstream to accomplish this, and we should try to monitor it closely!

https://github.com/apache/airflow/issues/27292

https://github.com/apache/airflow/pull/27264

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by dhruvkb** [comment]
😄 The action item from 2022-11-03 was finally completed.

**Comment by sarayourfriend** [comment]
Closing this as finished, in favour of just using https://github.com/WordPress/openverse/issues/663 to upgrade Airflow.
