### ISSUE TITLE
Update repo Figma links to public urls

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse#138]
The current Figma links in our READMEs require a logged in user, we should switch to the new public url I believe @panchovm has created.

**Comment by panchovm** [comment]
I checked the permissions in both files and opened them unlogged, and they are working correctly. Here are the sharable links nonetheless.
1. [Releases file. Audio release](https://www.figma.com/file/w60dl1XPUvSaRncv1Utmnb/Openverse-Releases?node-id=0%3A1)
2. [Design Library](https://www.figma.com/file/GIIQ4sDbaToCfFQyKMvzr8/Openverse-Design-Library?node-id=0%3A1)

**Comment by panchovm** [comment]
The README was updated with the links. Closing this issue
