### ISSUE TITLE
Capture Phylopic creator even if only first or last name is defined

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse#1381]
## Problem

Current logic in the Phylopic provider script dictates that a first and last name must be defined in order to capture creator information:

https://github.com/WordPress/openverse-catalog/blob/1506d6d9d391d7d12c8f5c515737623218036928/openverse_catalog/dags/providers/provider_api_scripts/phylopic.py#L164-L167

Per @obulat's comment (https://github.com/WordPress/openverse-catalog/pull/747#discussion_r1003049795):

> I think it would be nice to add the submitter if there is a first_name OR last_name. Does that ever happen?

## Description

We should investigate if the case where one of these fields is `None` ever occurs, and capture creator information even if one of those fields is missing.

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by krysal** [comment]
This issue is not relevant since the move to PhyloPic API v2.
