### ISSUE TITLE
Use pytest-env to set up API key shims for testing

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse#1382]
## Problem

Presently we use a copy of the `env.template` file when testing (via the [`just dotenv`](https://github.com/WordPress/openverse-catalog/blob/a3f4a426c33909cc0f40b80f4ea5d68cd54fe7c6/justfile#L39-L41) recipe [here in the CI/CD workflow](https://github.com/WordPress/openverse-catalog/blob/8ee7fb72fbd619e568bfceaeab6e6a436386dca3/.github/workflows/ci_cd.yml#L113-L114))

The env template includes placeholders for the various API keys we use:

https://github.com/WordPress/openverse-catalog/blob/895e907b6f9594b4d43db6a07eae0b3cb4a0e7d0/env.template#L27-L34

Per @krysal's comment (https://github.com/WordPress/openverse-catalog/pull/795#discussion_r1002134568):

> Do you think we should let these variables with no value instead of the "not_set" string? 🤔 That way the scripts that require it will fail with a more clear error, before even trying to make a request, but as it's currently they take the string as the API key.

## Description

We should comment these fields out from the `env.template` file but still keep them present as examples (just like the [`env.template` files for the API](https://github.com/WordPress/openverse-api/blob/c38ddfee022fce3f72c4894a804a5577f526abeb/api/env.template)). Particularly now that we are no longer retrieving those values at DAG parse time as part of the provider refactor, we no longer need to have these defined in the environment whenever running the project. Leaving them undefined will give us more obvious errors during local DAG testing if we happen to forget to populate a variable.

We _do_ need placeholder values for testing though. That's where we might use the [pytest-env](https://pypi.org/project/pytest-env/) plugin to define these with placeholders in the [`pytest.ini` file](https://github.com/WordPress/openverse-catalog/blob/b4ef93ce5f825e4ae0e3ba3814340ec42ade7fa2/pytest.ini).

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by ngken0995** [comment]
@AetherUnbound  What are the placeholder value in [pytest.ini](https://github.com/WordPress/openverse/blob/main/catalog/pytest.ini)?

**Comment by AetherUnbound** [comment]
@ngken0995 any value will do! You can just use "placeholder" or "apikey" for testing

**Comment by ngken0995** [comment]
@AetherUnbound  I have commented all `AIRFLOW_VAR_API_KEY` from `env.template` and add them to `pytest.ini `. Also, install `pytest-env` and `pipfile` and `pipfile.lock` was updated automatically. What is the best way to test the changes?

**Comment by AetherUnbound** [comment]
I believe if the tests run successfully, that should be sufficient! The tests will fail otherwise if the API keys aren't defined in the `env.template`.
