### ISSUE TITLE
Remove unnecessary boilerplate implementations of `get_media_type`

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse#1385]
## Current Situation

In https://github.com/WordPress/openverse-catalog/pull/821 we introduced a default implementation for `ProviderDataIngester::get_media_type` that removes the need for a large number of boilerplate-y implementations of the function in existing provider classes.

## Suggested Improvement

We can remove those unnecessary lines of code now that the default implementation covers them. This only applies to providers that handle a single media type.

## Benefit

Less code :slightly_smiling_face: 

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by sarayourfriend** [comment]
That's the basic idea. I can't remember exactly now, but there might be some cases where it's still necessary to keep the provider-specific implementation, but that some parts of the method could be replaced with a call to `super::get_media_type`. In other words, you're on the right track, just make sure that you only remove the parts that the base class implements but keep any provider-specific aspects of the implementation.

**Comment by zaharoian** [comment]
Interested in this issue!
