### ISSUE TITLE
Sync a README template with project meta info

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse#139]
## Description

We should find a way to sync the README header for each project like we do other files. See #64 for some additional context.

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by dhruvkb** [comment]
+1 for a consistent `README.md` but I'm not too sure about syncing it centrally because the `README.md` files will have certain distinct bits.

- Repo title
- Status badges
- Introduction
- Tech stack
- (feel free to edit and add more if you can recall)

**Comment by sarayourfriend** [comment]
Unneeded since monorepo switch
