### ISSUE TITLE
Move DAG documentation generation check out of test CI/CD step

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse#1403]
## Description

Presently the DAG documentation generation step exists within the "test" CI/CD block:

https://github.com/WordPress/openverse-catalog/blob/8ee7fb72fbd619e568bfceaeab6e6a436386dca3/.github/workflows/ci_cd.yml#L92-L114

This was done because the files necessary to run the doc generation (e.g. `openverse_catalog/utilities`) aren't mounted in the production `docker-compose.yml` file (though they are [mounted in the dev one](https://github.com/WordPress/openverse-catalog/blob/b4ef93ce5f825e4ae0e3ba3814340ec42ade7fa2/docker-compose.override.yml#L95)).

https://github.com/WordPress/openverse-catalog/blob/8ee7fb72fbd619e568bfceaeab6e6a436386dca3/.github/workflows/ci_cd.yml#L105-L108

I think our best bet here is to actually publish the dev artifact in a [similar manner as the prod one](https://github.com/WordPress/openverse-catalog/blob/8ee7fb72fbd619e568bfceaeab6e6a436386dca3/.github/workflows/ci_cd.yml#L81), then use it in the test & DAG documentation generation steps [similar to the way we use the prod one in the publish step](https://github.com/WordPress/openverse-catalog/blob/8ee7fb72fbd619e568bfceaeab6e6a436386dca3/.github/workflows/ci_cd.yml#L133-L137).

We could alternatively change the `just` recipes for the `generate-dag-docs` step to 1) not pull up the other dependencies ([which currently happens via the `_deps` recipe](https://github.com/WordPress/openverse-catalog/blob/516d7674be2a9e619b13a550ac611c82d413bccc/justfile#L112)) and 2) explicitly mount the entire `openverse_catalog` directory when running the DAG documentation generation step. We don't actually need any of the dev dependencies, so we can certainly use the production image artifact for this task, it's just a matter of mounting everything and using the right docker-compose file!

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by sarayourfriend** [comment]
@AetherUnbound Is this issue still relevant since the monorepo changes?

**Comment by AetherUnbound** [comment]
Thanks for checking up on this, yes it is still relevant: https://github.com/WordPress/openverse/blob/f676e57e2dbe9e92f568d413ade83ce6c2f38f9b/.github/workflows/ci_cd.yml#L291

This should be easier to adjust now that we're in the monorepo though, since we do a better job of caching the build steps. Perhaps with a setup similar to the [`django-checks`](https://github.com/WordPress/openverse/blob/f676e57e2dbe9e92f568d413ade83ce6c2f38f9b/.github/workflows/ci_cd.yml#L392) we do for the API!

**Comment by sarayourfriend** [comment]
Cool! We should re-write this issue in light of the new monorepo context then. I removed the help wanted label and added the ticket work required one.

**Comment by AetherUnbound** [comment]
I actually completely misinterpreted the existing CI/CD setup - this _is_ part of the [`catalog-checks`](https://docs.openverse.org/meta/ci_cd/jobs/catalog.html#catalog-checks) step, which is _different_ from the [`test-cat`](https://docs.openverse.org/meta/ci_cd/jobs/catalog.html#test-cat) step! @dhruvkb already split this out, so this can be closed! 😄
