### ISSUE TITLE
Add verbose logging option to `ProviderDataIngester`

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse#1420]
## Description

When troubleshooting a provider API script using the new `ProviderDataIngester` class, it can be difficult sometimes to tell at which step in the execution an issue is happening or what the data is at that step.

It would be useful to have logging at a high level of verbosity which could be used locally in test scenarios to see what the values are at each step in the process (e.g. `get_next_query_params`, `get_batch`, `get_batch_data`, `process_batch`, etc.

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by nicoepp** [comment]
Hi, I'm interested in implementing this feature.
