### ISSUE TITLE
Configure pools & priority weights

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse#1436]
## Description

Airflow provides two tools for managing concurrency across DAGs: [pools](https://airflow.apache.org/docs/apache-airflow/stable/concepts/pools.html) and [priority weights](https://airflow.apache.org/docs/apache-airflow/stable/concepts/priority-weight.html). Pools allow us to set up a set number of "slots"; tasks can then reserve any number of slots, and the task will only run when the requisite number of slots are available within the pool ([the data refresh DAG uses a pool for example](https://github.com/WordPress/openverse-catalog/blob/3ee97b6cbe45337bec6289bd77b9a57512a82522/openverse_catalog/dags/data_refresh/data_refresh_task_factory.py#L155)). Priority weights on the other hand factor into how Airflow determines _which_ job to run when a pool slot is available. This can be useful in scenarios where multiple DAGs access a single resource which must be gated by a pool, but we always want to prioritize running a specific DAG over all the others.

A perfect example of how we could utilize both of the above is for iNaturalist & the data refresh. We recently tried to [run both iNaturalist and the data refreshes](https://wordpress.slack.com/archives/C02012JB00N/p1661977997137679) simultaneously with undesirable results (both DAGs timed out and the database ended up restarting itself). In this case, we might want to leverage a "database units" pool for the tasks that use significant database resources. Airflow now lets us reserve more than one slot per task too.

For example if we had 10 "DB units" available, the image data refresh would take up all 10 of those slots, whereas the audio data refresh could take up 2 or 3 slots and iNaturalist could take up 5. We'd then assign the data refreshes with a particularly high priority weight. This would mean that in cases when both `@weekly` and `@monthly` correspond to the same day, Airflow would prioritize scheduling the image data refresh first, and then Airflow would prevent any other DAGs running which required "DB units" via the pools.

This could also be a candidate for config-via-Variables for easier troubleshooting/testing in production as well.

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by sarayourfriend** [comment]
@AetherUnbound I seem to recall we have some pools configured now, at least in production (https://github.com/WordPress/openverse/pull/2352)

Can we close this issue, in light of that, or is there still more to do? If there's still more to do, can you update the text of the issue to explain how it would work with/compare to the changes from https://github.com/WordPress/openverse/pull/2352 (and beyond)?

**Comment by AetherUnbound** [comment]
Great question, I think we've got this reasonably covered by the pools we're using along with the checks we run prior to ES-related DAGs. Closing!
