### ISSUE TITLE
Support locale based locale paths in WordPress theme

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse#144]
## Problem

In WordPress/openverse-frontend#701 we switched Openverse to use path based routing. This means that translated routes will now begin with a string prefix like `/es` for Spanish and so on. 

We need to prefix the Openverse Iframe URL with these strings in the WordPress theme.

Doing this work prevents several issues:

- Makes Openverse stateless, so we can use much more aggressive caching and reduce load to our origin servers
- Fixes issues with translations not loading on the initial visit to a Rosetta site
- Fixes translations 'sticking' from one locale to the next, in odd cases

This work will be a prerequisite of any upcoming Openverse deployments.

## Questions

- Which exact strings are used in the URLs? What format of country code is it?
- Confirm we have that data in PHP

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by sarayourfriend** [comment]
Closed by https://github.com/WordPress/wordpress.org/pull/61
