### ISSUE TITLE
Trigger audio waveform generation after the audio refresh

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse#1442]
## Problem

Currently we manually generate waveforms after an audio refresh is complete. Ideally, we could trigger this process directly in the audio refresh DAG.

## Additional context

We may want to wait on this until after the thumbnails service is migrated to a standalone service. 

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by sarayourfriend** [comment]
@zackkrida I wonder if we still need this? If so, we definitely can't wait until the thumbnail service is standalone (that isn't happening anymore), so we'll need to think of a different way to do it. Should this be blocked or pulled into the result augmentation/backfilling/self-crawling work later on? Or would it even be possible to add awf to the catalog and generate waveforms at ingestion time? We don't catalogue _that_ many audio files, but would it be prohibitive to generate wave forms for all the ones that do not yet have them? It would certainly be nice to get rid of the management command and just pull it into our regular ETL flow...

**Comment by sarayourfriend** [comment]
Similar to my rationale in https://github.com/WordPress/openverse/issues/2468#issuecomment-2323157000, I don't believe we need this issue, or at least cannot justify it at this moment. Waveform requests make up a tiny portion of our overall traffic and as a whole are non-problematic aside from [the occasional bug with the waveform generation code itself](https://github.com/WordPress/openverse/issues/4676) (which would affect a DAG just as well).

If we get to a point where we rely on waveforms for search relevancy or the like, we can revisit eagerly generating them. For now, we don't have a reason to do that.

@zackkrida if you feel differently, please reopen this as you please :slightly_smiling_face:
