### ISSUE TITLE
Allow data refresh poke interval to be configured per media type

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse#1472]
## Description

Presently the data refresh poke interval can only be configured by an environment variable across all data refresh DAGs:

https://github.com/WordPress/openverse-catalog/blob/3ee97b6cbe45337bec6289bd77b9a57512a82522/openverse_catalog/dags/data_refresh/data_refresh_task_factory.py#L143

It would be ideal to allow each media type to have its own poke interval. For instance, audio data refreshes could probably be every minute, whereas for the image data refresh 15 minutes makes more sense.

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by ngken0995** [comment]
@AetherUnbound and @obulat Can I work on this?

**Comment by ngken0995** [comment]
@AetherUnbound trying my best to become a full stack engineer.

**Comment by AetherUnbound** [comment]
You're doing excellent 😄 we're happy to help support those efforts! If you have any broader questions about the project, please feel free to ask them or chat about them with us in our Make WP Slack organization 🙂
