### ISSUE TITLE
Add `sentry` label for issues originating from a Sentry report

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse#154]
## Description

I suppose we can just search for the string `sentry.io` inside the issue body, but a label is easier to use I think? Anyway, it would be nice to see how many issues we get from Sentry and what patterns we see around resolving them.

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by chukkyiii** [comment]
Just to make sure, Is this just to add sentry labels to issues that contain anything to do with sentry?
I was thinking maybe adding a `.github/labeler.yml`?

```yml
# Adds sentry label depending on the regex
sentry:
    - '(sentry)'
```

**Comment by dhruvkb** [comment]
@chukkyiii I suppose this issue needs two steps, preferably two separate PRs:

## Adding the label
- Check out the [labels file](https://github.com/WordPress/openverse/blob/c3f3466d2047af49381ce6df924b9ff41b6ea2fd/automations/data/labels.yml). This file syncs labels across all our repos.
- Add a group named "tooling" with a label named "sentry". Use a color that's not being used by any other (Sentry's branding color `#362D59` would be nice I guess). Pick an emoji that denotes Sentry (I thinking bugs, e.g. 🐞).

## Updating our labeller script
- Check out the [labeller script](https://github.com/WordPress/openverse/blob/c3f3466d2047af49381ce6df924b9ff41b6ea2fd/automations/python/label_pr.py). This script is invoked for all new PRs.
- Add a check to scan for the word Sentry in the issue body. If found, apply the "🐞 tooling: sentry" label we defined earlier (in addition to whatever other labels the script would apply).

**Comment by AetherUnbound** [comment]
Reopening this, as we'll need to update the labeller script as well
