### ISSUE TITLE
Create runbook for handling reported media

### ISSUE THREAD

**Issue by stacimc** [WordPress/openverse#1541]
## Current Situation

WordPress/openverse-catalog#513 adds Slack reporting of reported media, with links to the Django admin page where these media can be manually reviewed and de-indexed/etc if necessary. There is however no clear process or SLA documented for this.

## Suggested Improvement

We should write a runbook for handling reported media which should address:
* SLAs for when media reports need to be addressed
* Explicitly assign responsiblity for handling reports
* Explicitly document rules for addressing the various kinds of reports (DMCA, mature content, 'other')

As part of this work we may find that the current Slack configuration is no longer optimal; for example we may want to direct the alerts to a different channel.

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by sarayourfriend** [comment]
I'm closing this in favour of the #383 project, which supersedes the approach assumed by this issue.
