### ISSUE TITLE
Add "good first issue" for to contribution notes

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse#156]
## Description

In the past we've put together this link in order to gather all "good first issue" and "help wanted" issues across all our repos: https://github.com/issues?q=is%3Aopen+is%3Aissue+repo%3AWordPress%2Fopenverse-catalog+repo%3AWordPress%2Fopenverse+repo%3AWordPress%2Fopenverse-api+repo%3AWordPress%2Fopenverse-frontend+archived%3Afalse+label%3A%22good+first+issue%22+label%3A%22help+wanted%22

It would be great to add this somewhere in the README so contributors have easy access!

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by chukkyiii** [comment]
Hey I would like to contribute with this!

**Comment by AetherUnbound** [comment]
Thanks for volunteering @chukkyiii! :smile: I'll assign you the issue :rocket:

**Comment by chukkyiii** [comment]
Hey, sorry, I saw that there is already a link doing the same thing, do you want it from the issues tab?

**Comment by AetherUnbound** [comment]
Whoops, sorry I didn't realize one was already there! Yes, ideally I'd like to replace it with the link above, since it has more options for sorting/filtering issues.

**Comment by AetherUnbound** [comment]
Hey @chukkyiii! Would you still like to tackle this issue?

**Comment by vinsout** [comment]
Hello, Can I resume this issue ?

**Comment by AetherUnbound** [comment]
Sure, I'll assign it to you @vinsout 🙂

**Comment by vinsout** [comment]
i have to add the link specified above on the README file, right ?

**Comment by AetherUnbound** [comment]
That's right, we just want to [replace the existing link with this one](https://github.com/WordPress/openverse/issues/156#issuecomment-1090713090).
