### ISSUE TITLE
Create Openverse GitHub activity overview dashboard

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse#157]
In a chat with our newest sponsored contributor @stacimc it was mentioned how difficult it is to get a handle on all the various repositories and communication feeds that exist for Openverse.

For anything completely open (basically just excluding the Making WordPress Slack and private infrastructure stuff) it would be nice to have a small website that shows a running dashboard view of everything happening in the Openverse repositories and probably pulls the RSS feed of the make blog as well. Optionally you could log in and it would add an additional "participating" column for things you're specifically tagged to review or have been mentioned in.

Might be a fun way to explore Nuxt 3 :slightly_smiling_face:

**Comment by zackkrida** [comment]
Completed! It's called [Overvue](https://github.com/sarayourfriend/openverse-overvue) and will likely be merged into this repository once we resolve #192.
