### ISSUE TITLE
Create `model_3d` provider API scripts & associated DAGs

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse#1574]
## Problem

After all the preliminary work is done, we need some provider API scripts to test the process and start ingesting `model_3d` data.

## Description

Create the `model_3d` provider API scripts using the _new provider API script_ template updated in WordPress/openverse#1575 for `model_3d` providers.

## Additional context

3D model sources are documented in the spreadsheet in WordPress/openverse#1592

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by sarayourfriend** [comment]
Closing as 3d models are indefinitely on hold and no work should be done on them until we re-plan this project.
