### ISSUE TITLE
Update the `new provider API script template` with the `model_3d` provider 

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse#1575]
## Problem

"Create a new provider API script" template only has audio and image provider templates. 

## Description

We need to update the [new provider API script template](https://github.com/WordPress/openverse-catalog/tree/main/openverse_catalog/templates) with the model_3d provider.

## Additional context

This template can be used to create and pre-fill a new provider script. This is done to make the process of script creation easier for new contributors.

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by sarayourfriend** [comment]
Closing as 3d models are indefinitely on hold and no work should be done on them until we re-plan this project.
