### ISSUE TITLE
Create a subclass of MediaStore for `model_3d`: `Model3DStore`

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse#1576]
## Problem

We need to clean the 3D Models data before saving it to a TSV.

## Description

Catalog uses the [MediaStore](https://github.com/WordPress/openverse-catalog/blob/9538f38401e5428b32dc14c5d5ba7ef50af87a96/openverse_catalog/dags/common/storage/media.py#L39) class to clean up the ingested data and to save it to TSV files. To add support for `model_3d` media type, we need to create a `Model3DStore` subclass that would be similar to `AudioStore` and `MediaStore`. 

## Additional context

This will be in `openverse_catalog/dags/common/storage/model_3d.py`, and will use the data fields defined in WordPress/openverse#1588.

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by sarayourfriend** [comment]
Closing as 3d models are indefinitely on hold and no work should be done on them until we re-plan this project.
