### ISSUE TITLE
Truncate data refresh percent change report to 3 digits after the decimal

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse#1581]
## Description

PR WordPress/openverse-catalog#636 added a count difference reporting message after the data refresh has been run. Part of this count is the percent change, which is given as a float. The difficulty with printing a straight float is that the numbers after the decimal can vary wildly. Here are a few examples:

> Record count difference for audio: 174,290 → 817,198
> Change: +642,908 (+368.8725687073269% Δ)

> Record count difference for image: 563,561,088 → 564,775,616
> Change: +1,214,528 (+0.21550955625949816% Δ)

> Record count difference for image: 579,553,984 → 579,554,880
> Change: +896 (+0.0001546016462204149% Δ)

We have a wide range of potential digits (in the hundreds to hundredths of a percent) and it can be hard to capture the level of information we would like for all cases. I think it would be best for us to have **3 significant digits after the decimal or closest zero, rounded up**. This would mean for the above three cases the output would be:

- `368.8725687073269` -> `368.873`
- `0.21550955625949816` -> `0.216`
- `0.0001546016462204149` -> `0.000155`

## Alternatives

Leave as is, or do some basic string truncation which could leave us with values like `0.000%`.

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by mattfergoda** [comment]
I'll work on this one!
