### ISSUE TITLE
Add `model_3d` database columns to `db_columns.py`

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse#1584]
## Problem

Based on the data fields defined in WordPress/openverse#1588, we should add the database columns to [`db_columns.py`](https://github.com/WordPress/openverse-catalog/blob/main/openverse_catalog/dags/common/storage/db_columns.py).

## Description

Create a list of all the database columns (`3D_MODEL_TABLE_COLUMNS`) in  [`openverse_catalog/dags/common/storage/db_columns.py`](https://github.com/WordPress/openverse-catalog/blob/main/openverse_catalog/dags/common/storage/db_columns.py).

For any new columns that do not exist in `audio` or `image` media type, a column definition should be first added to [`openverse_catalog/dags/common/storage/columns.py`](https://github.com/WordPress/openverse-catalog/blob/b44f3398d89450c6bfe765e03c832c241d5067c5/openverse_catalog/dags/common/storage/columns.py).

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by sarayourfriend** [comment]
Closing as 3d models are indefinitely on hold and no work should be done on them until we re-plan this project.
