### ISSUE TITLE
Create a popularity calculation view for `model_3d`

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse#1586]
## Problem

model_3d needs a popularity calculation view defined in the local_postgres image.

## Description

Materialized view definitions necessary for popularity data should be located in `https://github.com/WordPress/openverse-catalog/docker/local_postgres/0009_openledger_3d_model_view.sql`.
If any additional views need to be created, they should probably be added here as well, similarly to the `audio_set` view in the `openledger_audio_model_view.sql`.

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by sarayourfriend** [comment]
Closing as 3d models are indefinitely on hold and no work should be done on them until we re-plan this project.
