### ISSUE TITLE
Define necessary fields & schema for model_3d table & associated data

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse#1588]
## Problem

The prerequisite step of adding 3D Model Support in the Catalog is defining the data fields and schema. We can always update the fields later when necessary, but we should have a more or less comprehensive list to start working.

## Description

Below is the proposed schema for the `model_3d` table in the catalog database taken from the [3D Model Support RFC](https://github.com/WordPress/openverse/blob/main/rfcs/20220221-3d_model_support.md#proposed-schema). It is subject to change based on discussions that happen in the RFC, here and elsewhere.

Many of the fields towards the end are taken from examples on SketchFab (e.g. https://sketchfab.com/3d-models/charmanders-midnight-snack-57866c01da20414ba81885206acbcc85)

| Field | Type | Description |
| --- | --- | --- |
| `identifier` | `UUID` | Identifier for the record |
| `created_on` | `timestamp` | Time the record was created |
| `updated_on` | `timestamp` | Time the record was updated |
| `ingestion_type` | `varchar` | What generated the record |
| `provider` | `varchar` | Provider API that the model comes from |
| `source` | `varchar` | Source within the provider (e.g. NASA on Flickr), typically the same as `provider` |
| `foreign_id` | `varchar` | Identifier that the provider uses for this model |
| `foreign_landing_url` | `varchar` | URL on the provider that displays the "single-result" page for this model |
| `url` | `varchar` | URL to the actual asset itself (e.g. the image URL) |
| `thumbnail` | `varchar` | Thumbnail URL |
| `filesize` | `integer` | Size of the file |
| `license` | `varchar` | License for the model |
| `license_version` | `varchar` | Version of the model's license |
| `creator` | `varchar` | Creator ID of the model from the provider |
| `creator_url` | `varchar` | URL to the creator's page on the provider's site |
| `title` | `varchar` | Title of the model |
| `meta_data` | `jsonb` | Uncategorized metadata for the model |
| `tags` | `jsonb` | Tags that describe the model, for use in searching |
| `watermarked` | `bool` | Whether the model is watermarked - is this needed for 3D models? |
| `last_synced_with_source` | `timestamp` | Time the record was last updated from the provider |
| `removed_from_source` | `bool` | Whether the model has been removed from the upstream source |
| `category` | `varchar` | Category for the model (is this where we'll make the distinction between 3D printers, game assets, etc.?) |
| `filetype` | `varchar` | File type of the primary file for the model |
| `alt_files` | `jsonb` | Additional file types for the model |
| `vertices` | `integer` | Number of vertices within the model |
| `textures` | `integer` | Number of [textures](https://en.wikibooks.org/wiki/Blender_3D:_Noob_to_Pro/Materials_and_Textures) the model uses |
| `materials` | `integer` | Number of [materials](https://en.wikibooks.org/wiki/Blender_3D:_Noob_to_Pro/Materials_and_Textures) the model uses |
| `uv_mapping` | `bool` | Whether the model contains [UV Mapping](https://en.wikipedia.org/wiki/UV_mapping) |
| `vertex_colors` | `bool` | Whether the model contains [vertex colors](https://help.sketchfab.com/hc/en-us/articles/210765623-Vertex-Colors) |
| `pbr` | `bool` | Whether the model supports [physically based rendering](https://en.wikipedia.org/wiki/Physically_based_rendering) |
| `rigged_geometries` | `bool` | Whether the model supports [rigging for animation](https://dreamfarmstudios.com/blog/what-is-3d-rigging/) |
| `animations` | `integer` | Number of animations the model has |
| `morph_geometries` | `integer` | Number of [morph targets for animation](https://en.wikipedia.org/wiki/Morph_target_animation) |

## Additional context

What is the best place for documenting the catalog models? We currently have all the data field documentation collocated with code, right? I think it would be nice to have it published separately as well.

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by sarayourfriend** [comment]
Closing as 3d models are indefinitely on hold and no work should be done on them until we re-plan this project.
