### ISSUE TITLE
Database Unification

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse#159]
### Discussed in https://github.com/WordPress/openverse/discussions/120

<div type='discussions-op-text'>

<sup>Originally posted by **AetherUnbound** December  6, 2021</sup>
**Audience**: Openverse team & community
**Purpose**: Describe our current data infrastructure and propose a more unified/simpler solution
**Outline**:
* Current infrastructure
    * Description
    * Problem with the current infra
* Proposed infrastructure
    * Single database
    * Single source of truth
    * Increase responsibility of provider API scripts
    * Separating popularity information
* Benefits

### Description

Presently we have two databases: the Catalog database and the API database (henceforth "Catalog" and "API"). These databases reflect each other quite closely, although the Catalog is almost entirely unindexed. When a provider API script is run, it generates a TSV that is then loaded into the Catalog database. Some cleaning is performed at this point (e.g. verifying license information), but there are no constraints to what can be added to the Catalog. 

Every day, the data from a given media table (e.g. `image`) is loaded onto an associated materialized view. This view adds on standardized popularity information for the media. Once a month, calculations are run across all images for a given provider to determine the standardized popularity constant, which is then used to normalize popularity across all images. It's worth noting that the provider field used to group the media is also unindexed.

Once a week, the ingestion server initiates a "data refresh". During this process, it establishes a connection from the API to the Catalog using a foreign data wrapper. The server creates a temporary table that mirrors the media table on the API but without any indices. It then copies data from the media materialized view in the Catalog into this temporary table. It performs cleaning on the media data, then attempts to re-apply the indices that are present on the production table. Currently these indices do not get renamed to the appropriate names after the go-live swap, and the index re-application has not run successfully since July 2021. Theoretically, once the indices have been successfully re-applied, the temporary table is swapped for the production one.

After all the above steps are completed, the Elasticsearch cluster is reindexed and the API can serve this new data.

### Problems with the current infrastructure

Here are a few (non-exhaustive) issues I've identified with the current infrastructure.

* Two databases means double the AWS infrastructure costs.
* The delay between provider ingestion & serving new data is incredibly long, optimistically at least 36 hours if everything succeeds.
* Two schemas opens the databases up to schema drift and can become difficult to maintain over time.
* The lack of indices on the Catalog makes it expensive (in both compute and developer time) to troubleshoot and investigate data integrity problems.
* There is a duplication of effort on data cleaning, since it occurs both during the provider ingestion and after the data has been copied to the API.
* Indices should not need to be recreated on data that should already be conforming to the constraints they define. Doing so is expensive and time-consuming, and any errors that come up during the process require restarting it from the beginning.
* The ingestion server makes it difficult to start up from a previously failed step.
* Indices on the temp table are not renamed to match the production ones, which make them conflict with the indices Django is expecting during migrations.
* Data that does not meet any production constraints can be added to the Catalog and the data integrity issue caused by them will not be identified until a data refresh is attempted.

## Proposed infrastructure

I believe that the best way to improve our infrastructure is to collapse the two databases into a single database and have a single source of truth for the schema and migrations. This would involve increasing the scope of the provider API scripts and removing the ingestion server entirely. I also recommend that we modify our materialized views to make new data accessible to the API as soon as possible.

### Single database

As far as I can tell, there is not a significant and binding advantage to maintaining two databases. It would be feasible to have the provider API scripts and API server interact with the same database. Additional care could be taken on ingestion to ensure that the provider API data is cleaned and meets the constraints of the database.

This also shortens the time it takes for new data to be made available in the API; as soon as the new data has been loaded into the table, it's ready to be served by the API.

This would cut down our AWS costs considerably, since we would no longer be maintaining two costly databases.

### Single source of truth

Ideally we would be able to refer to a single source of truth for this single database rather than maintain multiple implementations of the models. This could be accomplished by adding a new `openverse-database` repository to our project. This repository would provide some interface to the models (that both the catalog and API can use) and a mechanism for migrating the database. We have a choice between two major libraries here: Flask (SQLAlchemy) or Django.

Since the API is already using Django, this could be developed as a Django plugin. The models could then be used by both the catalog and API, although only one server should be given the "migration" mechanism (or have an entirely different process carved out for database migration). Airflow uses Flask/SQLAlchemy, which might cause problems/conflicts in the runtime environment if we also attempt to enable the use of Django models in the provider API scripts. Django does not have first class/plugin support for materialized views and extensions, as far as I can tell. This could make some of our migrations tedious & repetitive.

Alternatively, we could define the database models using SQLAlchemy. SQLAlchemy does provide plugin support for materialized views, functions, and extensions[^1]. With it we could leverage other popular and rapidly growing API frameworks on the API server end, like FastAPI[^2]. This wouldn't necessarily require an immediate re-write of the API; we could set the Django models as "unmanaged" and have them reference the tables defined by this database repo. That would present some amount of duplication until the API had been re-written in a framework compatible with SQLAlchemy.

### Increase responsibility of provider API scripts

One key piece of this infrastructure is pushing as much of the data integrity checks, data cleaning, and data ingestion time into the provider API scripts as possible. Airflow can manage this process quite easily. Performing this piece in Airflow gives us access to all of the Airflow notification & reporting infrastructure as well, so we can be notified immediately of data integrity issues.

I believe we can add complexity at this step without affecting the ease of contribution for community contributed provider API scripts. It would require expanding our provider API script utilities to encompass this complexity/functionality.

This has the added advantage of centralizing all of the data ingestion steps in the catalog, rather than having them be spread across the catalog and the ingestion server.

### Separating popularity information

Our current data structure requires refreshing a materialized view in order to make any new data available to the API (among other steps). This is required so that standardized popularity data can be added for each media. It may be possible to have the API interact directly with the media tables without popularity data and move that information to a separate table/matview. This table would be joined to the media table when reindexing Elasticsearch, potentially with a sensible default for missing data. The materialized view refresh could then occur asynchronously without affecting the presence of new data.

This does bring up the question of "what do we do with data that does not yet have popularity data". Should it be indexed in Elasticsearch anyway? At what priority/popularity level? I think it behooves us to show the user every image we might have for something, even if we display images without popularity data last.

### Diagram of proposal

![Data Unification Proposal@2x](https://user-images.githubusercontent.com/10214785/144929170-b025df4c-654e-4bc2-b2ce-7b5920cf9a27.png)

<details><summary>Image description</summary>

The image is a set of two "swimlane" diagrams describing the current infrastructure and the proposed infrastructure. Both diagrams have steps which use certain shapes to showcase which database they interact with. Runtime duration information is provided where available.

The top diagram is composed of three lanes, "Catalog", "Ingestion Server", "API" from top to bottom. The diagram represents the following flow:
1. Provider API script ingestion (catalog database, variable duration)
1. Refresh media matview (catalog database, occurs daily, ~12 hrs duration)
1. Refresh media popularity matview (catalog database, occurs monthly, ~20 hrs duration)
1. Copy data from upstream (both databases, occurs weekly, ~5 hrs duration)
1. Clean data (API database, ~14.5 hrs duration)
1. Re-apply indices (API database, duration unknown)
1. Go-live table swap (API database)
1. Elasticsearch reindex (API database)
1. Serve new data (API database)

The bottom diagram is only two lanes, "Catalog" and "API" from top to bottom. The diagram represents the following flow (only a single database is referenced for all steps):
1. Provider API script ingestion
2. Clean data, match indices
3. Refresh media popularity matview (occurs monthly)
5. Elasticsearch reindex
5. Serve new data

</details>

## Benefits

The following are the projected benefits of the proposed system:

* Reduced costs (single database)
* Reduced schema drift, DDL duplication, and maintenance burden (single source of truth)
* Shorter lag between ingesting new data and serving it to users (removal of ingestion server, separating popularity information)
* Better reporting and troubleshooting, reduced data integrity errors (more responsibility on provider API scripts run in Airflow)

[^1]: https://github.com/olirice/alembic_utils
[^2]: https://fastapi.tiangolo.com/
[^3]: https://www.lucidchart.com/pages/tutorial/swimlane-diagram
</div>

**Comment by AetherUnbound** [comment]
A great deal of discussion occurred in #120, but the general consensus was that further testing would be needed before determining a clear path forward.

**Comment by sarayourfriend** [comment]
@AetherUnbound Is this still considered high priority? It would be nice to find an answer to this question but it doesn't seem to be blocking anything nor is it something we'll be able to address any time soon as far as I understand it. Would it make sense to move this down to medium?

**Comment by AetherUnbound** [comment]
Definitely, thanks for calling that out @sarayourfriend. I think we're a ways from this effort, but it's something I'd still like to pursue eventually!

**Comment by sarayourfriend** [comment]
@AetherUnbound Is this still a viable project? If we wanted to do this it seems like something we'd need to block out a significant amount of time for including a project plan and at least one implementation plan, along with other serious considerations. Would it be better to close this issue and open a new one (referencing this one and the other discussions/resources we have related to it) in the future if we decide we can prioritise this significant undertaking?

**Comment by AetherUnbound** [comment]
That's a good idea 🙂 and a helpful reminder that closing issues doesn't necessarily mean we'll never do them. We can close this for now until we feel we can prioritize this undertaking.
