### ISSUE TITLE
Public domain media not using the Creative Commons Public Domain Mark

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse#161]
### Discussed in https://github.com/WordPress/openverse/discussions/89

<div type='discussions-op-text'>

<sup>Originally posted by **zackkrida** October  5, 2021</sup>
Currently, Openverse does _not_ include public domain works unless they use the Public Domain Mark `PDM` tool from Creative Commons[^1]. This is because without PDM, a work may be:

- in the 'public domain'
- have 'no known copyright restrictions'

in one jurisdiction, but _could_ in others. Here are CC's recommendations for when _not_ to use `PDM` in their entirety[^2]:

> The Public Domain Mark is recommended for works that are free of known copyright around the world. These will typically be very old works.  It is not recommended for use with works that are in the public domain in some jurisdictions if they also known to be restricted by copyright in others.
>
> A work may have limited or “hybrid” public domain status for several reasons.  Some jurisdictions have unusually long copyright terms, which may mean that a work free from copyright restrictions most everywhere in the world could still be protected by the copyright laws of that particular country.  Sometimes a work is no longer restricted by copyright in a jurisdiction because the author or owner failed to comply with local formalities such as renewal, where those formalities apply.  It could also be the case for works that are deemed not protected by copyright by operation of law in a particular jurisdiction, but that are afforded protection under the copyright laws of other jurisdictions.
>
> CC does not recommend the Public Domain Mark for works with limited, hybrid public domain status at this time.

We need to decide if we want to continue this practice or support these works.

[^1]: [Public Domain Mark 1.0](https://creativecommons.org/publicdomain/mark/1.0/)
[^2]: [PDM Guidelines](https://creativecommons.org/share-your-work/public-domain/pdm/)</div>

**Comment by AetherUnbound** [comment]
Consensus seems to be[^1]:

> display a message saying something like "this work has not been marked as PDM nor CC0 but it belongs to the public domain in some jurisdictions" and link to a page that details the legal implications.
> From the value proposition perspective, we do want to boost the use of PDM content. The best experience for its correct use is the work we that need to do.

[^1]: https://github.com/WordPress/openverse/discussions/89#discussioncomment-1437945

**Comment by sarayourfriend** [comment]
How can we codify this and close the issue? Is there technical work that needs to be done to resolve this? @zackkrida maybe you have an idea as the original discussion author?

**Comment by dhruvkb** [comment]
I had updated the package only for the sake of completeness, and I have not checked if we actually have works with any of the extra licenses added in the update.

**Comment by zackkrida** [comment]
@sarayourfriend my general recommendation would be that we close this and spin it into a (potential) project for including non-Creative Commons licensed works into Openverse. 

That would probably involve tasks like establishing criteria for what sufficiently "open" licenses are which meet the project ethics and objectives, a task which _itself_ would require us to more explicitly define those terms. 

It's a large undertaking and one we would need to consider carefully, weighing it against efforts to continue to identify and include all of the, likely hundreds of millions, of CC-licensed works that are not yet part of Openverse.

**Comment by sarayourfriend** [comment]
Sounds good! I'd love to see that project through, one day :slightly_smiling_face:. Closing this as won't do, for now.
