### ISSUE TITLE
Let's talk documentation

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse#162]
### Discussed in https://github.com/WordPress/openverse/discussions/87

<div type='discussions-op-text'>

<sup>Originally posted by **zackkrida** October  5, 2021</sup>
We'll ultimately want to improve our code documentation in all repositories, and generate the handbook pages so that it's kept in sync with the repositories. This way we will have duplication, but also consistency and redundancy. We need to figure out a way to do this!</div>

**Comment by AetherUnbound** [comment]
Consensus was something like Sphinx + reST. This was already done in the API in WordPress/openverse-api#427. We'll need to set up something similar for the following:

- [ ] Ingestion server
- [ ] Analytics server
- [ ] Catalog

**Comment by dhruvkb** [comment]
I'm thinking of ways to use the existing Sphinx setup from the API to also document the ingestion server and analytics. That will prevent the need to have 3 independent Sphinx setups in the same repo.

**Comment by sarayourfriend** [comment]
@dhruvkb If we do the monorepo migration after all, it seems we could close this issue as not-needed, right?

**Comment by dhruvkb** [comment]
The monorepo will merge documentation for the API, ingestion server, automations and frontend but it still excludes the infra and catalog for now. We can close this and open specific issues (if needed) in those repos.
