### ISSUE TITLE
Catalog database/ingestion overhaul

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse#1662]
## Description

This issue will serve as a parent issue for all work related to the database & ingestion overhaul described [in this discussion](https://github.com/WordPress/openverse/issues/159). While the plan of action is not yet determined, we can start making assessments and begin experimentation.

## Tasks

- 

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by obulat** [comment]
@AetherUnbound , do you think we can close this issue in favor of the projects that we have for this?

**Comment by AetherUnbound** [comment]
Yep! This issue is outdated and can be closed in favor of #3935 and #416
