### ISSUE TITLE
Unify data refresh/provider cleaning

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse#1663]
## Problem

Some cleaning steps are replicated across the provider API scripts and the ingestion server's [data refresh cleaning](https://github.com/WordPress/openverse-api/blob/main/ingestion_server/ingestion_server/cleanup.py).

## Description

Where possible, we should pull as much of these data cleaning steps as we can backwards into the provider scripts. The operations are so repeated on the data refresh end that we could save a significant amount of time during data refresh by having all of this data cleaning done prior to inserting the data into the catalog.

This will involve work in both the catalog and API repos. It may also require performing a single-pass cleaning operation to the existing records within the catalog.

### Depends on

- [ ] WordPress/openverse#1557
- [ ] WordPress/openverse#700
- [ ] WordPress/openverse-api#782 

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by krysal** [comment]
The cleanup steps were removed from the ingestion server –except for the tags step since we want to keep it now– given the catalog data was corrected whithin #3415. This is done.
