### ISSUE TITLE
Add ability to remove Openverse integration with WordPress

### ISSUE THREAD

**Issue by annezazu** [WordPress/openverse#167]
## Problem

Some folks may not want there to be access to Openverse from their WordPress site (in either direction - to submit images or to find them). This came up in the [FSE Outreach Program's All Things Media Hallway Hangout](https://make.wordpress.org/test/2022/02/16/hallway-hangout-all-things-media/):

>We ended the call agreeing that the ability to disable Openverse integration will also be important. This has come up with the pattern directory too and feels standard at this point to have this kind of opt in optionality.

## Description

Allow a way to easily disable Openverse access.  I imagine inspiration can be taken from the block plugin directory and block pattern directory integration.

**Comment by sarayourfriend** [comment]
@WordPress/openverse-maintainers Can we use something other than GitHub issues to track things like "ideas for future integrations" etc? This issue doesn't really have anything actionable, it's just a note for us to keep in mind whenever we start to work on an actual core integration.

**Comment by dhruvkb** [comment]
I do like that everything we're working on or planning to work on is in a single place. We could probably make a new status like "status: future" or "status: ideation" that suggests something is not currently being worked on but should be considered later on? We can put these tickets in a separate column in our projects (separate from the Backlog).

**Comment by sarayourfriend** [comment]
The "priority" label is the one that doesn't make sense to me. Even if it's low priority it still indicates _a_ priority implying that it is in some way actionable.

At the very least we could make it "blocked" but that still feels incorrect to me.

**Comment by zackkrida** [comment]
I don't make the association that 'importance' (priority) implies actionability, but I also think that `💬 talk: discussion` would indicate that that the action to take would _be_ discussion itself.

**Comment by panchovm** [comment]
That is a great idea. Thanks for bringing it @annezazu

We can keep the `talk: discussion` label until putting down concerns, possible features, and scope. Once reaching that scenario, add the `needs design` label to start proposing a UX flow.

And agree with @sarayourfriend about the no need for a priority label. I would add removing the `aspect: code` label too.
