### ISSUE TITLE
PRs created with labels via GH CLI fail label check

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse#175]
## Description

It would appear that there are some cases where the label check fails even though a PR is opened with the correct labels. These failures persist across re-runs of the label check GHA and are only resolved by removing the labels and re-adding them in a separate step.

## Reproduction

1. Submit a PR using the GH CLI (`gh pr create`)
2. During the metadata step, add the required labels (e.g. `priority: medium`, `aspect: dx`, `goal: improvement`)
3. Observe that the PR label check fails even though the labels exist on the PR
4. (Optional) Re-run the label check GHA and observe that it fails again

## Expectation

If a PR is submitted with the appropriate labels, the PR label check should pass.

## Additional context

See WordPress/openverse-catalog#372

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by dhruvkb** [comment]
A combined solution for this and #75 would be optimal.

**Comment by sarayourfriend** [comment]
I opened an issue recently in the Podman repositories and they use something like slash commands in the body of the issue to automatically assign the correct label. Something like:

```md
## Aspect
<!-- Please choose one and remove the others

/aspect:text
/aspect:dx
/aspect:interface
/aspect:accessibility
/aspect:code
```

And so on.

**Comment by sarayourfriend** [comment]
Although if an issue exists for the PR then copying the labels from the issue probably makes some sense, at least as a starting point. But you'd have to decide how to manage multiple issues in that case.

**Comment by dhruvkb** [comment]
It seems the ideal solution to this is:
- getting the linked issue and using that to set the labels
- if the PR is linked to 0/>1 issues, setting the "status: awaiting triage" label to skip the label check
- running the label check only after the above steps have completed and using the latest info from the PR instead of the event context to prevent repeat failures.

**Comment by zackkrida** [comment]
@dhruvkb that's a really excellent idea, that _also_ fixes the issue we have with external contributors who can't assign labels to their own PRs.
