### ISSUE TITLE
Disable discussions on every repo after preserving their history

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse#177]
## Problem

We'd like to stop using GitHub discussions, but don't want to lose all of the historical discussion. We also don't want to migrate these discussion _replies_ manually, as it would be a lot of work. Disabling the discussions feature on our repos causes links to the discussions to 404. 

## Description

Using the [GitHub's GraphQL Explorer](https://docs.github.com/en/graphql/overview/explorer) we can write a query that gets all discussions and their replies (including both levels of threading/nesting) for a repository:

```graphql
query { 
	repository(name: "openverse", owner: "wordpress") {
    discussions(first: 20) {
      nodes {
        title
        body
        comments(first: 100) {
          nodes {
            id
            author {
              login
            }
            body
            replies(first: 100) {
              nodes {
                author {
                  login
                }
                body
                id
              }
            }
          }
        }
      }
    }
  }
}
```

We could then format these and post them as issues. This would let us ensure that all discussion contents are accessible while archiving the GitHub feature.

## Questions

- Where do we want to preserve these? As issues? Adding the replies to the existing issues @AetherUnbound created?
-  Are we okay with discussion links 404-ing, even if this information is available elsewhere? We could also search for and replace discussion urls in issues + PRs with the new links if needed.

**Comment by sarayourfriend** [comment]
This is done, and in fact we've gone back to using discussions for some things anyway.
