### ISSUE TITLE
Refine RFC deadlines

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse#179]
We have two somewhat contradictory statements in @sarayourfriend's RFC README file:

> Allow for a minimum of 5 days for review by contributors and the community.

> A deadline for feedback (typically two weeks from the date the RFC is originally shared unless there are extenuating circumstances)

Basically, do we want to give folks 1 week or two weeks (5 or ten business days, respectively) for feedback?

**Comment by AetherUnbound** [comment]
It sounds like we want a due date that's at least 2 weeks out from the RFC publish date, but prevent merging before at least 5 business days have elapsed even if the requisite feedback is received. If the due date passes without the requisite feedback (which ideally shouldn't happen), then the deadline has passed and it can be merged. I see those as lower and upper bounds (though the wording could certainly be clarified).

**Comment by zackkrida** [comment]
> I see those as lower and upper bounds (though the wording could certainly be clarified).

That makes perfect sense! Yes, let's keep it as-is and find a way to clarify the language. Thanks 😅

**Comment by AetherUnbound** [comment]
One way to phrase it:
> Merge after the due date (usually two weeks out) or after the RFC has received the requisite approvals, **no sooner than 5 days after the RFC is published**.

**Comment by sarayourfriend** [comment]
I think we landed pretty cleanly on 2 weeks, so closing this issue as resolved.
