### ISSUE TITLE
Rename or remove the `api/catalog` directory

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse#1799]
## Problem

The majority of code for the Openverse API lives in a directory called https://github.com/WordPress/openverse/tree/main/api/catalog. Given that the Openverse catalog now lives in this repository at https://github.com/WordPress/openverse/tree/main/catalog, this name is quite confusing. 

## Description

This folder should be renamed to something else, or removed, if possible. Could all it's contents be lifted up one level into https://github.com/WordPress/openverse/tree/main/api/?

**Comment by dhruvkb** [comment]
A new project initiated with Django 4.2 resembles this. Here we have a top-level directory named `api/` (same as current `api/` in repo root), inside which we have two directories.

- `api/`: contains all project configurations, must be named after the project (currently the `catalog/` directory)
- `search/`: app, contains the actual code, can be named whatever you want, search is a good example (currently the `catalog/api/` directory)

```text
api/ 
├── api
│  ├── __init__.py
│  ├── asgi.py
│  ├── settings.py
│  ├── urls.py
│  └── wsgi.py
├── manage.py
└── search
   ├── __init__.py
   ├── admin.py
   ├── apps.py
   ├── migrations
   │  └── __init__.py
   ├── models.py
   ├── tests.py
   └── views.py
```

So yes, it is possible to move `catalog/api/` up one level, rename it to something else (other than `api/`, that's occupied by the project directory) and would be better aligned with the Django "standard" layout.

But would involve a significant refactoring of all imports, and tools like `isort` that have been configured according to the current layout.

**Comment by dhruvkb** [comment]
I'd label this as a "🟩 priority: low" though. Agreed it is confusing, but from the root of the project, `api/` and `catalog/` are pretty distinct and a small notice about the bad current name should suffice to clear up the confusion till we can take out the time for this refactor.

**Comment by dhruvkb** [comment]
I've changed my opinion on the priority and want it to remain medium because I just noticed that PyCharm doesn't recognise the right `catalog` in the imports.

<img width="703" alt="Screenshot 2023-04-23 at 6 03 16 AM" src="https://user-images.githubusercontent.com/16580576/233815470-fdede7cf-6fce-49bd-b7d4-812c36598177.png">
