### ISSUE TITLE
Add notes for why certain warnings are filtered/ignored in testing

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse#1805]
In #1227 we added a few warnings filters as part of the effort to utilize `pytest.ini` files ([context](https://github.com/WordPress/openverse/pull/1227#discussion_r1169176383)). The catalog `pytest.ini` has documentation for each ignoration:

https://github.com/WordPress/openverse/blob/aedc9c16ce5ed11709e2b6f0b42bad77ea1eb19b/catalog/pytest.ini#L21-L36

Where possible, we should try and add similar documentation to the [API](https://github.com/WordPress/openverse/blob/main/api/pytest.ini) and [ingestion server](https://github.com/WordPress/openverse/blob/main/ingestion_server/pytest.ini) `pytest.ini` files.

**Comment by rahulsindhu01** [comment]
Can i do this?

**Comment by AetherUnbound** [comment]
@rahulsindhu01 please go ahead! I'll assign this issue to you 😄 The best strategy here would likely be to comment out the warning filters (so the tests _do_ emit warnings), then determine what might be emitting those warnings and note them in the comments similar to the catalog example above. If a removed filter doesn't change the output (as in, no warnings occur even after removing the filter), then that means the filter is no longer relevant and can be removed entirely. Let us know if you have any other questions!

**Comment by rahulsindhu01** [comment]
@AetherUnbound can i do it the day after tomorrow
because exams going on. They will end tomorrow

**Comment by rahulsindhu01** [comment]
@AetherUnbound ive created a pull request. you can check that and please inform if there are some areas where i could have done better
it wasnt a big task but yeah
