### ISSUE TITLE
Include `WordPress/openverse-infrastructure` in automations

### ISSUE THREAD

**Issue by dhruvkb** [WordPress/openverse#181]
## Description

The new repository `WordPress/openverse-infrastructure` is not covered by any automations or sync processes. It should be brought under the `WordPress/openverse` umbrella.

## Expectation

`WordPress/openverse-infrastructure` should be covered by this repo and follow the same processes as all others.

## Additional context

This can cause slight changes across many files, we can make sub-issues to tackle them individually or cover them in one PR.

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by AetherUnbound** [comment]
I believe this should be covered in #194, are there any aspects of the automation I'm forgetting that aren't covered by that?

**Comment by sarayourfriend** [comment]
I think that's it Madison, we can close this. If @dhruvkb objects we can re-open :slightly_smiling_face:
