### ISSUE TITLE
Add Pygments vue-lexer extension to docs site to support vue syntax highlighting in codeblocks

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse#1810]
## Problem

Sphinx uses Pygments to syntax highlight code blocks. Pygments does not support Vue by default, so vue codeblocks cannot be syntax higlighted.

## Description

We can add https://github.com/testdrivenio/vue-lexer to the doc site. It doesn't look perfect, there are very old PRs dangling, but it should cover most of our documentation use cases for Vue.

**Comment by dhruvkb** [comment]
Since Vue syntax is so similar to HTML, it seems using HTML as the language adequately works for this.

<img width="1073" alt="Screenshot 2023-04-18 at 5 46 02 PM" src="https://user-images.githubusercontent.com/16580576/232797198-6b0227be-ead0-4e9c-8668-55fc0496fa3f.png">

**Comment by sarayourfriend** [comment]
Sounds good to me! That does look fine, indeed.
