### ISSUE TITLE
Source thumbnails sent to photon are too small 

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse#1811]
In #898 we introduced functionality which sends the URL of the upstream thumbnail to Photon if it's available and it's not from Phylopic. The motivation was so we can get the thumbnails faster and prevent timing out when images are too large.

However, many sources use unacceptably small thumbnails, with sizes in the 150-240px range, that look absolutely terrible and significantly degrade the user experience of Openverse. This is particularly evident for Flickr where many popular images are inherently older, and have very, very small thumbnails.

In the immediate we should reverse this change, and consider reimplementing after:

1. Establishing minimum size requirements for storing a thumbnail value; clean up existing fields which do not meet the criteria
2. or, store additional thumbnail metadata, including dimensions, so we can configure which ones to display in the frontend

**Comment by krysal** [comment]
@AetherUnbound I created #1811 to delete the bad thumbnails after the data refresh, so we can leave this issue closed.

Howerver, another one will be needed for this point:

> Establishing minimum size requirements for storing a thumbnail value

I think that will be part of WordPress/openverse#855 ?
