### ISSUE TITLE
Replace usage of `ACCESS_TOKEN` with `GITHUB_TOKEN`

### ISSUE THREAD

**Issue by dhruvkb** [WordPress/openverse#182]
## Problem

Currently we use a secret `ACCESS_TOKEN` containing @dhruvkb's PAT to run many actions. This can be replaced with the [`GITHUB_TOKEN` secret](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#about-the-github_token-secret) or [`github.token` context](https://docs.github.com/en/actions/learn-github-actions/contexts#github-context) provided within GitHub Actions themselves.

## Description

Replace the custom secret `ACCESS_TOKEN` with the built-in `GITHUB_TOKEN`.

## Alternatives

`ACCESS_TOKEN` has the advantage that I get a lot of credit for making PRs, applying labels and moving cards in our Project  boards. I also got a Hacktoberfest T-shirt with little effort.

Just kidding, `GITHUB_TOKEN` is always better as that's one less secret to take care of (and reduces my presence from the bus factor).

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by sarayourfriend** [comment]
> ACCESS_TOKEN has the advantage that I get a lot of credit for making PRs, applying labels and moving cards in our Project boards. I also got a Hacktoberfest T-shirt with little effort.

:joy:

**Comment by RishiKumarRay** [comment]
@dhruvkb can i go for this, assign me

**Comment by dhruvkb** [comment]
Sure @RishiKumarRay, you can work on it!

**Comment by zackkrida** [comment]
@dhruvkb I decided to raise the priority of this a bit because 1. It seems like a quick change, and 2. Some people expressed confusion this week thinking that you were responding and making changes yourself, haha.
