### ISSUE TITLE
Handle flakiness in Playwright

### ISSUE THREAD

**Issue by dhruvkb** [WordPress/openverse#1825]
## Description

Playwright tests can be flaky, which can cause the visual regression test to fail in CI and cause the deployment of the frontend to be skipped. While we do get a notification when the expected deployment does not go through, this is a major pain for the deployer to re-run the job and wait for the process to repeat.

## Solution

Most flakiness goes away on a second re-run of the VR tests so we should run visual regression tests with a [retry value](https://playwright.dev/docs/test-retries#retries) of 2. While this will not solve the root cause of the flakiness, it can prevent this flakiness from cancelling frontend deployments.

## Additional improvement

The CI workflow should be updated to report a list of all flaky tests at the end of the run so that appropriate steps can be taken to solve the root of the flakiness.

**Comment by obulat** [comment]
Closing this issue because we have guidelines on how to handle flakiness: https://docs.openverse.org/general/test.html#flaky-tests
