### ISSUE TITLE
Update Python workflows to run on Python 3.10

### ISSUE THREAD

**Issue by dhruvkb** [WordPress/openverse#183]
## Description

- Test if the workflows work fine on Python 3.10. 
- Update workflow YAMLs to use "3.10" as the Python version.

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by MukulKolpe** [comment]
Hey @dhruvkb can I work on this issue?

**Comment by dhruvkb** [comment]
@MukulKolpe yes, please!
