### ISSUE TITLE
[Quality] Use a `make_insert_query` function in test_sql.py

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse#1835]
## Current Situation
https://github.com/WordPress/openverse-catalog/pull/196#discussion_r719781512

We are currently crafting the insert string every time we need one.

See WordPress/openverse-catalog#196

## Suggested Improvement

We could potentially move this into a utility function so we don't have to define the SQL every time we need it.

## Benefit
Reduced LOC, single point of change in the future.

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by kuephi** [comment]
Hi! will have a go at this.
