### ISSUE TITLE
Swap views during popularity calculation rather than delete

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse#1838]
## Problem

Currently the media view tables are dropped immediately as a first step when recalculating image popularity. This can be problematic, as the calculations can take upwards of 12 hours. If an ingestion is attempted during this time, it will immediately fail because the view it points to doesn't exist.

## Description

Instead of dropping the view immediately, we should look at doing a go-live table swap similar to the end of the data refresh process. This would allow us to populate the new view, swap them in a single transaction, then drop the old view. This process would not incur any downtime.

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by krysal** [comment]
@AetherUnbound @stacimc I assume this issue will be unnecessary after #433 is complete. Should we close it now?

**Comment by AetherUnbound** [comment]
I think we actually addressed this when we moved the management of the data refresh steps into Airflow! We're guaranteed now not to run a data refresh until the table recreation is complete, so we no longer have to worry about this case. I'll close this!
