### ISSUE TITLE
Include DAGs.md in documentation

### ISSUE THREAD

**Issue by dhruvkb** [WordPress/openverse#1847]
## Description

The catalog emits a `DAGs.md` file that contains a lot of great information about the DAGs. This file is a very good candidate for inclusion in the documentation site.

## Implementation

It's unclear how a file that's written inside the `catalog/` dir (for Docker container bind mount reasons) could be included in the docs. One approach might be symlinks but I'm unaware of how good support for symlinks is in Git and on Windows.

**Comment by AetherUnbound** [comment]
My goodness, the power of the monorepo!! ✨ This is a _fantastic_ idea!

The current `generate-dag-docs` recipe actually moves the file once it's generated: https://github.com/WordPress/openverse/blob/75c5a68ab4016c212f1bb68c21225a857dd9f60c/catalog/justfile#L120

So we could just as easily move it under `documentation/` at that step! There's no need for it to stay in the `catalog/` directory 😄

**Comment by dhruvkb** [comment]
> My goodness, the power of the monorepo!! ✨

So much good stuff keeps appearing.

**Comment by ngken0995** [comment]
Hello @dhruvkb and @AetherUnbound, 

I would like to work on this issue and I created a PR above. Please take a look and any suggestion is appreciated.
