### ISSUE TITLE
Additional Django admin moderation tools improvements

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse#1885]
| Start Date | ETA        | Project Lead | Actual Ship Date |
| ---------- | ---------- | ------------ | ---------------- |
| YYYY-MM-DD | YYYY-MM-DD | TBD          | TBD              |

## Description

https://github.com/WordPress/openverse/issues/383 begins the work to create a usable Django admin experience for moderators. We need to continue iterating on these tools to improve them.

Two suggestions we've already received are:

1. A grid view for images
2. Custom keyboard shortcuts to make keyboard navigation faster so moderators can move more quickly through the queue

## Documents

- [ ] Project Proposal
- [ ] Implementation Plan

## Prior Art

https://github.com/WordPress/openverse/issues/383

**Comment by AetherUnbound** [comment]
This project was not completed in 2023 and we are closing it in favor of prioritizing other work. Closing this issue.
