### ISSUE TITLE
RFC Request: Browser Extension

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse#190]
## Problem

The Openverse browser extension is a nice additional way for users to interact with Openverse. Early on we decided to continue to maintain it. We haven't done much with it yet, but intend to do so in the upcoming months. 

## Description

We should develop an RFC for revitalizing and publishing the Openverse browser extension. Some questions I have:

- How can we reuse code from the frontend in the extension?
- How can we make the extension easier to maintain?
- How can we make sure the extension is accessible?
- How can we monitor usage of the browser extension, to validate its existence?
- What are the goals of the extension; what can/should it offer that Openverse doesn't? Are there unique advantages or disadvantages to extensions?

## Alternatives

We could deprecate the extension and cease development.

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by zackkrida** [comment]
I suspect the best path forward is to make very simple and small changes to the current extension and publish it as a beta while we look into writing an extension using our existing frontend components. That work might involve the creation of some form of monorepo where we can separate our frontend components from our routes as a standalone package, that could then be used in the extension.

**Comment by dhruvkb** [comment]
Closed because development on the extension has been discontinued.
