### ISSUE TITLE
Remove Sphinx live view port forwarded to API container

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse#1909]
## Problem

The API docker-compose service is still configured to forward to port 3000, but nothing runs there anymore because our documentation exists and is built elsewhere now.

## Description

Remove the port 3000 entry in the `web` service of the docker-compose stack.

**Comment by KaitoMizukami** [comment]
Can you assign me to this issue ?

**Comment by YashGaur000** [comment]
Removed the port 3000 entry in the web service of the docker-compose stack.

**Comment by krysal** [comment]
Fixed in #2808.
