### ISSUE TITLE
Update audio categories

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse#195]
## Problem

The frontend audio categories are out of sync with the categories present in the API (see wordpress/openverse-api#526). [That URL](https://api.openverse.engineering/v1/audio/?q=cat&categories=sound) now returns:

```
HTTP 400 Bad Request
Allow: GET, HEAD, OPTIONS
Content-Type: application/json
Vary: Accept

{
    "detail": {
        "categories": [
            "Invalid category: sound. Available options: {'audiobook', 'music', 'news', 'pronunciation', 'podcast', 'sound_effect'}"
        ]
    }
}
```

## Alternatives

We may want to ultimately explore an API endpoint that provides the list of categories rather than having them hard-coded on the frontend *and* the API.

## Additional context

We need a pull request that updates the list of `audioCategories` in the `filters.ts` constants file to the correct categories:

`['audiobook', 'music', 'news', 'pronunciation', 'podcast', 'sound_effect']`

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by zackkrida** [comment]
Updated in the frontend in WordPress/openverse-frontend#1168.
Still pending work in the API WordPress/openverse-api#583, which could use code review when you have time @AetherUnbound

**Comment by zackkrida** [comment]
Completed in the above PRs.
