### ISSUE TITLE
Move `js` and `python` dir into a top-level parent dir

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse#196]
This repo now contains RFCs and may potentially become a monorepo (see #192). It might be beneficial to take the existing `js` and `python` folders and move them into a top level `scripts` folder now that this repo is home to more than just utility scripts.

**Comment by dhruvkb** [comment]
Bikeshedding, I wanted to propose the name be something more descriptive like "automations" because "scripts" is too broad imo. But I definitely agree with the idea of moving these and accordingly updating the `README.md` file.
