### ISSUE TITLE
PR review reminders skips PRs if they have any update within the urgency period

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse#1984]
## Description

If a PR is low urgency and unreviewed for 4 days and then the author pushes a rebase, the PR's "urgency" clock will get reset back to 0.

https://github.com/WordPress/openverse/blob/2710483a50bec736909eac4a73ef189842e07e01/catalog/dags/maintenance/pr_review_reminders/pr_review_reminders.py#L80-L86

## Additional context

I think we should change this to ping since the last request for review. If a PR isn't ready for review yet, the author should draft it.

I've had a lot of PRs get skipped over for reminders because I am diligent in keeping PRs rebased and updated while waiting for reviews. The reminders are effectively useless in the current configuration except for PRs that are totally ignored. With our recent discussions about PR review timeliness and having too many PRs open, I think this change will help make the reminders more useful for our current goals.

Marked high because these reminders are meant to help us review PRs in a timely manner and the current approach is not achieving that. If it's too noisy after this change, we can make further refinements, perhaps looking for specific types of updates to index against, rather than the undraft/open date.

**Comment by obulat** [comment]
Great catch! I haven't seen the PR review reminders on my PRs (even the ones that are more than 2 weeks old) in a long time because I regularly rebase them :)
