### ISSUE TITLE
Update analytics documentation to include instructions for enabling the analytics feature flag

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse#1988]
## Problem

The analytics documentation covers every other aspect of setting up analytics locally, but does not mention the need to enable the feature flag. This left me confused for 15 minutes trying to debug why the analytics proxy didn't work. I only finally discovered the issue after deciding to check the code to see if something else was going on and discovered that the feature flag needed to be flipped. I had jump through three files of code (and then remember how to flip feature flags locally) to figure it out.

## Description

Update [the analytics documentation](https://docs.openverse.org/frontend/guides/analytics.html) to include instructions about the feature flags and potentially disable the feature flag proxy locally so that Nuxt doesn't log a red-herring message about forwarding `/api/events`.

**Comment by zackkrida** [comment]
In addition to this @sarayourfriend, would it make sense to enable analytics by default in local development?

**Comment by sarayourfriend** [comment]
I thought about making that the suggestion but if you do that and do _not_ have plausible running, it will log an error every time it's unable to reach plausible. Those error logs are kind of annoying locally and a red-herring for anyone who doesn't care about analytics at that moment.

We could make it slightly more complicated by checking if Plausible is reachable in the local environment during configuration and only enabling it if it is, but it'd take a bit of thinking to figure out how best to implement that.
