### ISSUE TITLE
Add a Playwright fixture that allows retrieving POST request parameters

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse#1992]
## Problem

Currently, we use the following code to extract the Analytics payloads from POST requests in Playwright tests:
```
 page.on("request", (req) => {
    if (req.method() === "POST") {
      const requestData = req.postDataJSON()
      if (requestData?.n == "SELECT_EXTERNAL_SOURCE") {
        eventData = JSON.parse(requestData?.p)
      }
    }
  })
```
This code is repeated in every test that tests analytics.

## Description

Abstract this out into a utility or [custom Playwright fixture](https://playwright.dev/docs/test-fixtures#creating-a-fixture) that provides this more generally (like a list of all events that get sent that can be asserted against).

## Additional context

Based on [quote from @sarayourfriend 's comment](https://github.com/WordPress/openverse/pull/1158#discussion_r1183136611)

**Comment by zackkrida** [comment]
Added in #1158
