### ISSUE TITLE
[Meta] Release note generation & versioning

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse#20]
Ideally, we should have the same process for automatically generating release notes in each repository. We can use the existing process in the front end on all three repositories, or a new approach/format if preferred. 

After this is standardized, we should make a release of each repository, to use with our initial deployment. 

I also think we should switch the frontend back to [SemVer](https://semver.org/) instead of CalVer, so it uses the same versioning scheme as the other two repositories. 

CC: @dhruvkb @obulat @krysal

**Comment by dhruvkb** [comment]
👍  for switching to SemVer for consistency with other repos.

**Comment by dhruvkb** [comment]
Closing as all relevant PRs have been merged.
