### ISSUE TITLE
Move CONTRIBUTING.md to documentation site

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse#2008]
## Description

Our current contributing guide exists locally in the repository: https://github.com/WordPress/openverse/blob/523a3599c34463275ce57c4e4ce6c14de1baefbd/CONTRIBUTING.md

It would be ideal to move this into the documentation site at docs.openverse.org, where most of our other quickstart/contributor information exists!

**Note**: When we convert this into Sphinx, we should also emphasize further the verbiage about choosing more than one good first issue - https://github.com/WordPress/openverse/blob/209cd44abed611ae4a2ef97ea77e8d2b0b612a53/CONTRIBUTING.md#friendly-notes (we've had a few folks ask about this, so it seems useful to highlight it better).

This would involve moving the file from it's current position into `documentation/general`, adding a callout for the above using a [MyST callout](https://myst-tools.org/docs/mystjs/admonitions), and then linking from the current `CONTRIBUTING.md` to the new location on the docs site.

**Comment by shivamganwani** [comment]
@AetherUnbound I'd like to pick this up

**Comment by zackkrida** [comment]
Thanks, @shivamganwani! Please just ping `@WordPress/openverse-maintainers` here if you have any questions 😄

**Comment by shivamganwani** [comment]
@WordPress/openverse-maintainers
I think I found an issue, not sure. 
In the Contributing section of the Readme there is this line `See the [CONTRIBUTING.md](https://github.com/WordPress/openverse/blob/main/CONTRIBUTING.md) file for details.`

Now I click on the link and it takes me to contributing guidelines page. All good till now.
Now I scroll down and there is a part where the below links are present 
```
[GitHub contribution practices](https://docs.openverse.org/reference/github_contribution_practices.html)
[Dev flow](https://docs.openverse.org/reference/dev_flow.html)
[General setup guide](https://docs.openverse.org/guides/general_setup.html)
[Quickstart guide](https://docs.openverse.org/guides/quickstart.html)
```

Here comes the issue, all these links take me to 404 Not found. Can someone explain if this is really an issue or am I doing something wrong.

**Comment by shivamganwani** [comment]
@AetherUnbound so we're making a separate ticket or fixing this in this one?

**Comment by AetherUnbound** [comment]
Do you mind including that in your changes in #2030? 😄

**Comment by shivamganwani** [comment]
Not at all @AetherUnbound
