### ISSUE TITLE
Update project thread issue template to mention using docs.openverse.org links for plans

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse#2011]
## Problem

Currently in our project thread issue bodies we link to the _pull requests_ for implementation plans and project plans. 

If documents are given addendums, as discussed in #2009, these references will be out of date.

## Description

After project and implementation plans are approved, update the project thread to use the docs.openverse.org links for these documents. 

We need to add documentation for this where appropriate, likely in the issue template for project threads:

https://github.com/WordPress/openverse/blob/main/.github/ISSUE_TEMPLATE/project_thread.md

Namely, some text similar to the following in a comment:

> Once a document is merged, please update the link to point at the published document on our documentation site: https://docs.openverse.org/projects/index.html

**Comment by SadiyahK** [comment]
Hi, I'm looking to start contributing to open-source. This looks like a manageable first issue for me, please can I be assigned?

**Comment by dhruvkb** [comment]
Sure @SadiyahK, please go ahead!
