### ISSUE TITLE
Add additional checks to ingestion server healthcheck endpoint

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse#2019]
## Problem

The ingestion server healthcheck endpoint returns 200 without actually doing any checks for things like database or Elasticsearch connectivity. The endpoint could return 200 even if the ingestion server lost database or ES connectivity, both of which are necessary for the critical paths of the application.

## Description

Similar to https://github.com/WordPress/openverse-api/issues/14 and https://github.com/WordPress/openverse-api/issues/1079 for the API, we should add some new checks to the healthcheck endpoint. At minimum, we should confirm that the databases and Elasticsearch are all accessible.

## Additional context

Optionally, we may want to add a check for the indexer workers and for running task healthchecks, but that is probably more involved (requires a bit more thought to how best to do it and what conditions to look for) so we can defer that. The most high value checks are the connectivity ones above.

**Comment by dhruvkb** [comment]
Should we also add the entrypoint logic from the API that waits for ES to be up before initialising the ingestion server?

https://github.com/WordPress/openverse/blob/e78b0bc8c1a0b4438912b7843973bbfeb5c877e6/api/run.sh#L5-L9

**Comment by sarayourfriend** [comment]
We can, sure. If we follow the same approach as the API though, the new checks would be behind query params and wouldn't fail the "baseline" healthcheck (which is more of an "are you on" check), so I don't think it's imperative for _this_ issue.

My only concern with these scripts is that the container looks up but is unresponsive for a bit. It'd be nice if we spun up a small http server (`python -m http.server` kind of thing) just to respond to requests on the exposed port to say "waiting for ES to initialise" so that it's obvious what's happening from the dev's perspective.

**Comment by dhruvkb** [comment]
I think this problem of waiting for the ES to be ready is only specific to local development (correct me if this assumption is invalid). Because in prod, the ES server is already ready and isn't being started alongside the API/ingestion server container so the entrypoint will immediately yield.

In dev, where we have access to the logs with `just logs <web|ingestion_server>`, running a small HTTP server, while we concurrently wait (approx 5-10 seconds) for ES to be ready, seems overkill. If we just look up the logs of the container, we will see it repeatedly print the message "Waiting for Elasticsearch connection...".

**Comment by sarayourfriend** [comment]
Yes it is only an issue in dev and indeed only in dev do we have this implemented anyway. The live configurations do none of this waiting.

> running a small HTTP server, while we concurrently wait (approx 5-10 seconds) for ES to be ready, seems overkill. If we just look up the logs of the container, we will see it repeatedly print the message "Waiting for Elasticsearch connection...".

This is true for people familiar with the project, but for a new contributor there's nothing to indicate this expectation, especially as the `ps` recipe prompts you immediately to try making requests to the services.

This feels like a separate issue anyway though. Waiting for ES isn't necessary to implement these additional checks and implementing them won't change anything about the way the local environment behaves (so long as the checks are behind query parameters, as they are in the API, and I don't know why they wouldn't be).
