### ISSUE TITLE
Only skip documentation build for dependabot when not updating documentation dependencies

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse#2022]
## Description

See https://github.com/WordPress/openverse/pull/1998#issuecomment-1533622959

 and

https://github.com/WordPress/openverse/pull/1998#issuecomment-1533635158

We should build and confirm docs stability for documentation dependency updates, so the check should be updated to only skip if the changes aren't for documentation.

**Comment by AetherUnbound** [comment]
I think we _can't_ emit docs on PRs that dependabot opens due to permissions issues, unfortunately 😕 I believe that's why that check is present in the first place

**Comment by sarayourfriend** [comment]
Interesting, we should still be able to run the build, at least to confirm that it doesn't have errors.
