### ISSUE TITLE
Add a `recreate` recipe for the frontend

### ISSUE THREAD

**Issue by dhruvkb** [WordPress/openverse#2028]
## Problem

The API project has a `recreate` recipe that takes down the Docker container, deletes all volumes, rebuilds the Docker image, and initialises the API. It's very handy.

https://github.com/WordPress/openverse/blob/b4adc87c4e3cd7c9bdc879affda17fa21791c9ad/api/justfile#L48

The repo root has a `recreate` recipe too, that does the same but for all Docker-based projects.

https://github.com/WordPress/openverse/blob/b4adc87c4e3cd7c9bdc879affda17fa21791c9ad/justfile#L188

The frontend lacks a `recreate` recipe that does a similar thing for it.

## Description

Add a `recreate` recipe for the frontend (or more generally the entire monorepo) that

- removes all `node_modules` (repo root as well as each individual workspace)
- deletes `pnpm` caches
- reinstalls all pacakges afresh
- runs `frontend/init`

Also call this `recreate` recipe from the root justfile `recreate`.

## Additional context

This is different compared to the API `recreate` because the frontend dev environment is not Docker-based (but it could be in the future, that's a separate discussion).

**Comment by Aditya062003** [comment]
I would be interested in making a contribution to this issue. Kindly assign it to me.
