### ISSUE TITLE
3D Model Support

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse#203]
Tracking issue for 3D Model Support in Openverse.

[View the RFC here](https://github.com/WordPress/openverse/blob/main/rfcs/20220221-3d_model_support.md)

## Milestones

- [Frontend](https://github.com/WordPress/openverse-frontend/milestone/6)
- [API](https://github.com/WordPress/openverse-api/milestone/1)
- [Catalog](https://github.com/WordPress/openverse-catalog/milestone/7)

**Comment by sarayourfriend** [comment]
Deprioritised to focus on improving existing media types and other projects. If we decide to take this on again in the future we'll go through a new process of planning that takes the existing planning work into account.
