### ISSUE TITLE
Unify logging approach between API tests and ingestion server tests

### ISSUE THREAD

**Issue by dhruvkb** [WordPress/openverse#2031]
## Problem

The logs for the `test-api` job are written in the CI + CD workflow.

https://github.com/WordPress/openverse/blob/b4adc87c4e3cd7c9bdc879affda17fa21791c9ad/.github/workflows/ci_cd.yml#L379-L390

The logs for the `test-ing` job are written inside the Python test file.

https://github.com/WordPress/openverse/blob/b4adc87c4e3cd7c9bdc879affda17fa21791c9ad/ingestion_server/test/integration_test.py#L435-L440

## Description

The goal is to use a consistent approach to writing the logs for both test suites.

**Comment by ashiramin** [comment]
@dhruvkb Can I take on this issue?

**Comment by dhruvkb** [comment]
Sure @ashiramin, please do!

**Comment by ashiramin** [comment]
Thank you. @dhruvkb which of the two ways is a more preferred approach for logging?

**Comment by ashiramin** [comment]
@dhruvkb have this PR up for review https://github.com/WordPress/openverse/pull/2380
