### ISSUE TITLE
Move catalog's README information into documentation site, update just commands

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse#2034]
## Description

Now that the monorepo move is complete and the catalog is part of this repo, we need to update the documentation in the catalog README.md: https://github.com/WordPress/openverse/blob/c20262cad8944d324b49176678b16b230bc57e2e/catalog/README.md#L1-L0

The best way to tackle this would probably be to split the sections up and add them to `documentation/reference/background.md` and `documentation/guides/general.md` for background information and the quick start guide respectively. Then the `just` commands should be updated to reflect the new way of running them (i.e. starting from the root directory and running `just catalog/<command>` or `just <command>` instead.

The documentation about directory structure is useful and could remain in the README.md file's current location, but it will also need to be updated.

## Additional context

Identified while working on #2023

**Comment by AetherUnbound** [comment]
This is related to #3204 but not completed by it.

**Comment by ngken0995** [comment]
@AetherUnbound I created a PR for this issue. can I be assigned?
