### ISSUE TITLE
Use a consistent Python test module naming pattern

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse#2039]
## Current Situation

Tests in the catalog are named `test_{module}.py` whereas tests in the API are named `{module}_test.py`.

## Suggested Improvement

It'd be nice to have a single, consistent pattern for naming test modules. My vote is to move everything to the catalog pattern as across both test suites we use the pattern `test_{description}` for test functions.

## Benefit

Using a consistent pattern for test module names across all Python tests would reduce the cognitive load when creating new test modules.

Using the same pattern for test modules and test functions further reduces that cognitive load (only one pattern to remember).

**Comment by harsitagarwalla187** [comment]
@sarayourfriend Do i have to change the naming convention of the files in [api/test](https://github.com/WordPress/openverse/tree/b172950486dcb690adf228375247ce7a150ab847/api/test) to test_{module}.py ?

**Comment by sarayourfriend** [comment]
Yup, that's it :slightly_smiling_face:. If you'd like to work on this, leave a comment and I will assign it to you.

**Comment by harsitagarwalla187** [comment]
@sarayourfriend Assign it to me.
