### ISSUE TITLE
Write an RFC for monorepo support

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse#205]
After the discussion in #192, it seems like we're ready for an RFC for monorepo adoption. This will focus on the _specific implementation_, how to best transition, and what specific configuration and automation changes we will need to make.

**Comment by sarayourfriend** [comment]
@zackkrida shall we close the discussion issue in favor of this one?

**Comment by sarayourfriend** [comment]
This is so exciting! I'm glad that it almost works!

> I could not figure out how to get the setup-node-env action working with a subdirectory of the repo. This is a big blocker; as far as I can tell it would require changes to the action. It's possible I'm missing something or getting something incorrect. I would love to be proven wrong!

I think, at least for setup-node-env, that it would indeed run at the root of the repository, and that would have to be part of our monorepo approach. If pipenv started supporting true monorepos then we'd manage the monorepo configuration at the root of the repo as well.

One of the advantages of running node at the root of our repo for everything would be that our automations would also be just another package.

However, this pre-supposes that we do the work to create a true `pnpm` managed monorepo where the nuxt app is _just a package_ in the monorepo.

If pipenv started support monorepos, as I said, it would also be at the root and each of our python projects would _just be packages_ inside the monorepo.

I think if we treat the nuxt project as a package with a pnpm node monorepo project at the root then we wouldn't have the same scoping issues.

What do you think?

**Comment by zackkrida** [comment]
@sarayourfriend that's a good point I overlooked, that we could treat it like a more conventional monorepo that bundles multiple JS or python packages into one repo. I admittedly didn't even consider it because it seems to really muddy the barriers between all our codebases. That said, it's definitely doable. I'll experiment with it a bit in fauxpenverse today!

**Comment by krysal** [comment]
Was this an attempt to unify all the four repositories into one (frontend, API, catalog, browser extension) or the frontend with the browser extension?

**Comment by zackkrida** [comment]
@krysal essentially it was moving the `openverse-frontend` repo into the `openverse` repo.

**Comment by AetherUnbound** [comment]
One thing to consider - many of our CI/CD actions for the API & catalog run `just` commands. `just` _can_ be run in a subdirectory, so it seems like we could use `run` commands with `working-directory` to manage those cases. Is it just the node setup that was causing trouble with your testing, or were there other actions that made it difficult too?

**Comment by zackkrida** [comment]
@AetherUnbound any of our commands using run steps and executing shell scripts can be scoped to the proper directories easily. The only issue is with 3rd party actions that interact with files, expect them to be in the repo root, and don't expose any configuration.

**Comment by AetherUnbound** [comment]
Got it. I know that the docker steps also allow the context/dockerfile to be specified. Would it be a great effort to identify exactly which 3rd party actions are causing us trouble and draw up a plan for tackling them?

**Comment by sarayourfriend** [comment]
@zackkrida What are the next steps here? Are we putting this on the back-burner for now?

**Comment by zackkrida** [comment]
In case it's not obvious, this was deprioritized as I didn't have the bandwidth to work on it. @dhruvkb has recently expressed renewed interest.
