### ISSUE TITLE
Stack labeller breaks down when no filter is satisfied

### ISSUE THREAD

**Issue by dhruvkb** [WordPress/openverse#2055]
## Description

The stack labeller sends a blank array of labels to GitHub which leads to the action failing. Add an `if` condition to apply a triage label in case no labels match.

## Reproduction

See failing workflow run: https://github.com/WordPress/openverse/actions/runs/4907807817/jobs/8763157232?pr=2054

## Screenshots

```
RequestError [HttpError]: Invalid request.

No subschema in "anyOf" matched.
For 'anyOf/0', {"labels"=>[]} is not an array.
For 'anyOf/1', {"labels"=>[]} is not an array.
1 item required; only 0 were supplied.
```

**Comment by shashank-k1ngalpha** [comment]
Hi @dhruvkb , Can you assign this to me and please advise on how I can get involved?

**Comment by dhruvkb** [comment]
@shashank-k1ngalpha we have a job in the [CI + CD workflow](https://github.com/WordPress/openverse/blob/0642022fb9c81d0ae49a1ed8ac726bf8509febcd/.github/workflows/ci_cd.yml#L118) called `add-stack-label`: 

https://github.com/WordPress/openverse/blob/0642022fb9c81d0ae49a1ed8ac726bf8509febcd/.github/workflows/ci_cd.yml#L118

This job takes a list of stacks that have changed as `needs.get-changes.outputs.changes`...

https://github.com/WordPress/openverse/blob/0642022fb9c81d0ae49a1ed8ac726bf8509febcd/.github/workflows/ci_cd.yml#L138

...and applies labels corresponding to those stacks using the GitHub API.

https://github.com/WordPress/openverse/blob/0642022fb9c81d0ae49a1ed8ac726bf8509febcd/.github/workflows/ci_cd.yml#L144

For some reason, this did not work as expected [here](https://github.com/WordPress/openverse/actions/runs/4907807817/jobs/8763157232?pr=2054) so we need to look at the logs and find what went wrong and how to fix it.

**Comment by shashank-k1ngalpha** [comment]
@dhruvkb , Do actions need any permissions to run? Not able to run ci_cd.yml

**Comment by dhruvkb** [comment]
Yes @shashank-k1ngalpha, you won't be able to run the action. The only debugging option is to refer to the linked logs of the failed run.

**Comment by shashank-k1ngalpha** [comment]
@dhruvkb ,In logs I could see the that in the labels returns null list. Can we check in if the length of array is null or if the list is empty before sending it as request?

REQ;
body: '{"labels":[]}'

RESP:
No subschema in "anyOf" matched.
For 'anyOf/0', {"labels"=>[]} is not an array.
For 'anyOf/1', {"labels"=>[]} is not an [`array.`]

ACTUAL CODE:
if (labels.len == 0) {
              labels.push("🚦 status: awaiting triage", "🏷 status: label work required")
            }

MODIFIED CODE:
if (labels.len <= 0 || labels==[]) {
              labels.push("🚦 status: awaiting triage", "🏷 status: label work required")
            }

**Comment by dhruvkb** [comment]
@shashank-k1ngalpha if the labels array is empty, the length will be zero. But you've made an important discovery. In JavaScript, the length of an array is `.length` (and not `.len` as written in the code)!

https://github.com/WordPress/openverse/blob/8bd7c4525ce0275b4ee95448c1de6639461624b8/.github/workflows/ci_cd.yml#L141

This should be fixed by

```diff
-             if (labels.len == 0) {
+             if (!labels.length) { 
```

Would you like to open a PR for this?

**Comment by shashank-k1ngalpha** [comment]
@dhruvkb , Thanks for the correction opened PR for the same.
