### ISSUE TITLE
Replace `kebap-case` within brackets in locale files with `camelCase`

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse#2059]
## Problem

We use `kebap-case` in the locale string interpolations that are replaced by `VueI18n`. These should be replaced with `camelCase` to prevent errors in `Nuxt3`'s version of i18n. 

## Description

The keys that use `kebap-case` should be replaced with keys with `camelCase`. Care should be taken to check if they are correctly interpolated in the components.
Before
`Shown because {feat-name} is {feat-state}`
After
`Shown because {featName} is {feat-State}`

## Alternatives

There might be a way to fix the handling of dashes by @nuxjs/i18n 8, but it's probably easier to just replace the strings (there are about 13 of them).

## Additional context

If you update to the version of nuxt i18n that's compatible with Nuxt 3 (8), you'll get the following errors:
```
 ERROR  [unplugin-vue-i18n]  Unterminated closing brace (error code: 7) in /src/locales/en.json                                                                   2:40:38 PM
  target message: Shown because {feat-name} is {feat-state}
  target message path: pref-page.explanation

  1  |  Shown because {feat-name} is {feat-state}
```

**Comment by dhruvkb** [comment]
I marked this as good-first because @obulat has clearly defined the work to be done.

**Comment by sajeremy** [comment]
I'd like to take on the issue if it hasn't already been resolved.  @WordPress/openverse-maintainers

**Comment by obulat** [comment]
Sure, go ahead, @sajeremy! I'm assigning the issue to you.

**Comment by sajeremy** [comment]
Apologies, I accidentally closed the last pull request. I meant to respond to your last message in the review with my note below: 

I can definitely replace all the kebap-case keys with camelCase. As a clarification, should I only change kebap-case keys that have a matching interpolated string or should I change all the keys in the json file into camelCase? For instance, on line 449 `"copy-license"` is kebap-case but there is no interpolated string using this key. If the latter, I can probably make a quick script to convert all kebap case to camelCase.

I also started the changes with just the `src/locales/scripts/en.json5` file and noticed a similar pattern for the files in the `test/locales/ `sub-directory. Would you like the interpolated strings and keys changed to camelCase for these files as well and any other locations?

**Comment by obulat** [comment]
Sorry for late response. I think it would make maintenance easier if we changed all of the keys to camel ase, even if they are not interpolated. Thank you for noticing the test locales! I completely forgot about then when opening the issue.

Also, in .vue components, we have functional 'i18n' components that sometime have <template> with a kebab-cased key, we would need to replace those keys, too.
