### ISSUE TITLE
Add openverse-infrastructure to github.yml

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse#206]
## Description

The `openverse-infrastructure` repo was added to the projects to sync in #194. However, it was never added to the `github.yml` data file: 
https://github.com/WordPress/openverse/blob/main/data/github.yml

As a result, the label values do not get synced with that repo.

## Reproduction

Observe that openverse-infrastructure is missing from this run: https://github.com/WordPress/openverse/runs/5729339868?check_suite_focus=true

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by zackkrida** [comment]
Oops, I went to make a PR for this in the GitHub UI and accidentally committed directly. Fixed!
