### ISSUE TITLE
Filter apply button cut off in Firefox mobile if address bar is on the bottom

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse#2062]
## Description

It appears that the filter tab's "Apply" button gets cut off on Firefox mobile if the address bar is set to be on the bottom.

## Reproduction

1. Visit openverse.org 
2. Make a search
3. Open the filter and observe the screenshot

## Screenshots

![signal-2023-05-07-100019_002](https://user-images.githubusercontent.com/10214785/236906075-cb79db2f-5012-4bf3-a653-daf1d2aea955.png)

## Environment

- Device: Google Pixel 7
- OS: Android 13
- Browser: Firefox

**Comment by Aditya062003** [comment]
I would be interested in making a contribution to this issue. Kindly assign it to me.

**Comment by AetherUnbound** [comment]
Awesome, I've assigned this to you @Aditya062003!

**Comment by obulat** [comment]
@Aditya062003, I've removed your assignment from this issue because the PR I opened for a different issue will also fix this one. Please, feel free to pick another "good first issue"!
