### ISSUE TITLE
Make linting more contributor-friendly

### ISSUE THREAD

**Issue by dhruvkb** [WordPress/openverse#2068]
## Problem

Linting is one of the first steps for a new contributor. When a contributor tries to push their changes, the linting step ensures that any common pitfalls, style differences etc. get caught and reported.

## Description

Our lint setup is extremely complicated. It needs

- Node.js
  - including Node.js dependencies
- Docker
- just

This makes it harder for a new contributor with a partial or incomplete setup to be able to work on the project. It's even more problematic if these technologies aren't even directly relevant to the task at hand, for example Docker and Node.js are never used in the documentation process at all but needed just for linting!

Alternatively, some might opt not to lint at all and instead push changes and let CI (or another maintainer) lint it for them. This is not optimal.

## Solution

The solution is to make client-side linting as free of these dependencies as possible and relegate some of the more contrived linting steps (like frontend unit tests) to a separate lint step that only runs on the CI side.

Alternatively we must improve our documentation and mark all these technologies as required. This will make the inital barrier to entry but the end result will inevitably be a smoother dev workflow as these technologies are always good to know for any developer.

## Alternatives

The alternative is to document that users need not lint locally and can let CI run the linting for them. This has the drawback of losing autofix and adds the manual effort of comprehending the output (often cryptic to a newbie) and making the required changes (often the output does not specified what's needed to be done).

**Comment by sarayourfriend** [comment]
> The solution is to make client-side linting as free of these dependencies as possible and relegate some of the more contrived linting steps (like frontend unit tests) to a separate lint step that only runs on the CI side.

@dhruvkb Do you have suggestions for how to do this? One that comes to mind is to have a docker image configured with all the tools we use for linting instead of using pre-commit.

As for the frontend unit tests, it seems like we could just remove them from the linting steps. There's no material reason I can think of for them to be in the linting steps if the API or catalog unit tests aren't.

**Comment by dhruvkb** [comment]
Removing the frontend unit-tests is a good actionable point.

Additionally, we have support for dev-containers so [this Docker-based workflow](https://code.visualstudio.com/docs/devcontainers/containers) is one possibility if blessed and properly documentation.

**Comment by sarayourfriend** [comment]
My concern with dev containers is that unless someone on the team is using it for regular development then we'll forget to make sure it works on a regular basis such that we could recommend it.
