### ISSUE TITLE
Customized buttons update

### ISSUE THREAD

**Issue by fcoveram** [WordPress/openverse#2078]
## Problem

Project Core user interface improvement (#415) covers a series of updates of VButton components, and therefore, an overall frontend improvement. As pointed out in the design file’s component specs page, customized buttons generated from this base component are out of this change.

## Description

As discussed in the last prioritization meeting, we decided to update the Content link and Load more components once finished the project. 

This ticket introduces the [new design](https://www.figma.com/file/q4agvQxXI0ywTjwl36qkMe/Customized-buttons-update?type=design&node-id=22-13656) for both components.

### Load more

* [Component specs](https://www.figma.com/file/q4agvQxXI0ywTjwl36qkMe/Customized-buttons-update?type=design&node-id=912-9785&t=8aVsjj4iJVqxieJY-4) in the Figma file
* [Figma component](https://www.figma.com/file/GIIQ4sDbaToCfFQyKMvzr8/Openverse-Design-Library?type=design&node-id=4799-12417&t=cohVFMFy7ESupLVR-4) in Design Library

<img src="https://github.com/WordPress/openverse/assets/895819/fc5f3e69-598a-4eb1-b54b-c8a0fd8c6928" alt="Resting, hover, and focus states of Load more component" width="500">

### Content link

* [Component specs](https://www.figma.com/file/q4agvQxXI0ywTjwl36qkMe/Customized-buttons-update?type=design&node-id=912-9786&t=8aVsjj4iJVqxieJY-4) in the Figma file
* [Figma component](https://www.figma.com/file/GIIQ4sDbaToCfFQyKMvzr8/Openverse-Design-Library?type=design&node-id=4799-12386&t=cohVFMFy7ESupLVR-4) in Design Library

<img src="https://github.com/WordPress/openverse/assets/895819/b3c4c5f9-0d6d-4c3b-bcec-1e9813c46c81" alt="Resting, hover, and focus states of Content link component" width="400">

### Components in place

Here is the [design page](https://www.figma.com/file/q4agvQxXI0ywTjwl36qkMe/Customized-buttons-update?type=design&node-id=22-13656) where both components are placed in "All content" results for all breakpoints.

![Mockups of all Openverse breakpoints with the new Content link and Load more components](https://github.com/WordPress/openverse/assets/895819/8c66e2e3-cefe-4443-a29b-1b2be42951eb)

## Additional context
* Design files
   * [Figma mockups](https://www.figma.com/file/q4agvQxXI0ywTjwl36qkMe/Customized-buttons-update?type=design&node-id=22-13656)
   * [Figma components](https://www.figma.com/file/GIIQ4sDbaToCfFQyKMvzr8/Openverse-Design-Library?type=design&node-id=4799-12442&t=cohVFMFy7ESupLVR-4) in Design Library
* Project related: #415 
* Ticket related: #2083

**Comment by obulat** [comment]
Changes in both buttons have been implemented.
