### ISSUE TITLE
Enable content link for no results and add pill in switcher popover item

### ISSUE THREAD

**Issue by fcoveram** [WordPress/openverse#2083]
## Problem

Currently, Openverse doesn't allow users to land on the meta search page from "All content" results when a search query doesn't bring results. The media link button shows a disabled state and we're missing the opportunity to show external sources.

## Description

We can improve this flow by applying three changes

### Enable the content type link

In "All content" results, content type link needs to show a "No results" label in the result area, and look and behave as described in #2078. The page should look like the following mockup.

<img width="1717" alt="All content results page with the content type link enabled" src="https://github.com/WordPress/openverse/assets/895819/7d5e1361-cf4d-479b-9b59-3f966f5ef98d">

### Add a variant to the status pill ([Figma component](https://www.figma.com/file/GIIQ4sDbaToCfFQyKMvzr8/Openverse-Design-Library?type=design&node-id=1753-3893&t=upKy3Stkw8fpuYiH-4))

<img src="https://github.com/WordPress/openverse/assets/895819/914ebec0-470a-416a-a6ca-3e7c6eaa779c" width="120">

'
The [pill component](https://docs.openverse.org/storybook/?path=/story/components-vpill--default-story&globals=backgrounds.grid:false) has a new variant and the following new styles:
* Height: `24px`
* Text style: `Time` style with `uppercase` text transformation
* Paddings: `8px` for left and right
* "No results" variant with "dark charcoal 10" as background

### Switcher item ([Figma component](https://www.figma.com/file/GIIQ4sDbaToCfFQyKMvzr8/Openverse-Design-Library?type=design&node-id=3835-10885&t=upKy3Stkw8fpuYiH-4))

The [component](https://docs.openverse.org/storybook/?path=/story/components-vcontentswitcher-vsearchtypes--default-story&globals=backgrounds.grid:false) doesn't change any space or visual style for the resting, hover, and focus status, but check icon replaces the status pill when the content type is selected. See the prototype gif below.

<img src="https://github.com/WordPress/openverse/assets/895819/f35412e8-7dbd-493b-b10a-aafb517e7e17" alt="Cursor pointer showing the status of popover items of switcher" width="300">

## Additional context
* [Figma file](https://www.figma.com/file/q4agvQxXI0ywTjwl36qkMe/Customized-buttons-update?type=design&node-id=923-11742&t=2CbcKXAHD8lM0e5u-4)
* New design for content link component (#2078)

**Comment by obulat** [comment]
I am a bit concerned about the "No results" pill in the switcher popover and its effect on the perceived performance for our users.

It would not change anything for the "All content" views, but will require us to send additional requests for Image and Audio views.

Currently, if you search for `cat` images, Nuxt only sends one request to the `/image` endpoint. However, if we need to display the "No results" pill in the content switcher, we would have to _send requests for all media types on single media search view_ on to decide if we should or shouldn't display it. We would probably do it on the first search for the search term. So, if the user is searching for "cat" images, we would still send 2 requests for both media types (or 3-4 in the future, when we add media types). Sending requests for other media types when the user opens the content switcher would make the switcher much slower.

We currently only display "No results" in the content links on the All content views (where we already loaded both media types and know that there are no results. The content switcher popover does not display anything about the number of results. The users can land on a page without results for a different media type if they use the content switcher popover. Do we really want to introduce the new pill, @WordPress/openverse-frontend ?

My vote would be for making the content links at the top of the "All content" view clickable even if there are no results (now, they are disabled in such case), but not add "No results" pill to the content switcher.

**Comment by fcoveram** [comment]
I follow your concern @obulat. Thanks for bringing this up. Waiting for other folks to chime in and share their thoughts on the performance impact and what efforts this proposal requires.

> My vote would be for making the content links at the top of the "All content" view clickable even if there are no results (now, they are disabled in such case), but not add "No results" pill to the content switcher.

I'm happy with this solution if folks consider it better.

**Comment by zackkrida** [comment]
@obulat's suggestion is right, especially concerning performance. I didn't think of that but it's very important.

**Comment by fcoveram** [comment]
So let's continue with enabling the content type link for "no results" and dismiss the "pill in switcher" idea.
