### ISSUE TITLE
Boxed audio layout should not be seekable

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse#2124]
Currently the boxed audio component, visible on the all results view, is seekable by keyboard (but not by mouse). This is not the intended behavior for the component. It was deemed too small for this seeking functionality to be useful.

We need to make this boxed audio layout not seekable, and make sure it uses the correct `ariaLabel`	in `VAudioTrack`.

**Comment by Tanmay-Tiwaricyber** [comment]
Identify the component: Locate the code or file that defines the boxed audio component, which is currently seekable by the keyboard.

Disable seeking functionality: Within the component code, find the section responsible for the seekable behavior. This could involve event listeners or functions related to seeking. Disable or remove this code to prevent seeking functionality.

Implement correct layout: Modify the boxed audio layout to ensure it is visually and functionally suitable for its intended purpose. Adjust the size, positioning, or any other relevant properties to align with the desired design.

Update ariaLabel in VAudioTrack: Locate the VAudioTrack component or file that handles the audio track. Ensure that the correct ariaLabel is specified, providing an appropriate description for the boxed audio component. Update the ariaLabel property accordingly.

Test the changes: Verify that the boxed audio component is no longer seekable by the keyboard. Use a mouse to confirm that seeking functionality is disabled. Additionally, ensure that the correct ariaLabel is being announced or displayed for accessibility purposes.

Make necessary adjustments: If any issues or unexpected behaviors arise after the changes, debug and make adjustments as needed until the desired behavior and layout are achieved.
