### ISSUE TITLE
Update sensitive browsing designs to allow re-blurring of search results

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse#2130]
> **This is blocked** until further user feedback or testing indicates it is necessary.

## Problem

The [sensitive browsing project proposal](https://docs.openverse.org/projects/proposals/trust_and_safety/detecting_sensitive_textual_content/20230309-project_proposal_detecting_sensitive_textual_content.html#frontend) includes one feature not present in the [design files](https://github.com/WordPress/openverse/issues/791). We [discussed](https://github.com/WordPress/openverse/issues/791#issuecomment-1503047920) and [decided to wait](https://github.com/WordPress/openverse/issues/791#issuecomment-1504445287) on this feature:

> Users can unblur and reblur individual results through a simple and clear interaction on the search results page.

This means the desired flow for single results, as described in the plan, is something like this:

```mermaid
graph TB
    A(User searches) --> B(User views results w/ sensitive results)
    B --> C(User unblurs a sensitive result)
    C --> D(User can re-blur the result)  --> B
    C --> E(User visits the single result view) --> B
```

## Description

We need to add this in the search results designs; perhaps with the 👁️ button in the bottom corner of results as indicated by Francisco previously.

**Comment by dhruvkb** [comment]
Aside to the discussion, that is an impeccable diagram 👨‍🍳👌. Nice to know that GitHub supports `mermaid` natively.

**Comment by zackkrida** [comment]
Closing. Single results can be unblurred on the single result page, and will remain blurred when re-visiting the search results. I believe the current flow matches the mermaid chart here.
