### ISSUE TITLE
HTTPError: 400 Client Error consuming all the events quota for Sentry

### ISSUE THREAD

**Issue by krysal** [WordPress/openverse#2145]
## Sentry link

https://openverse.sentry.io/share/issue/dfe5cb355fb542519caced236cd4e5ec/

## Description

For some reason, Photon is failing to get some images from providers. We need to find out the root cause of this problem. When looking at this, check the Redis cache as we've been collecting more info from these events there in #2086 and https://github.com/WordPress/openverse-api/pull/1056.

## Reproduction

One of the failed URLs registered by Sentry is https://api.openverse.engineering/v1/images/91568be5-ff69-468e-93a1-44bf759177c1/thumb/, but it might work when you're trying, so this is a sporadic issue unfortunately.

**Comment by sarayourfriend** [comment]
@AetherUnbound @krysal didn't https://github.com//WordPress/openverse/blob/f54c71c4b7d4be49ea94f0501b5089171695235c/ and https://github.com//WordPress/openverse/blob/fb0d1908f8c6a418d5ae606cd9b958a5ccccd787/ solve this?

**Comment by AetherUnbound** [comment]
It did! I think we can close this.
