### ISSUE TITLE
Make analytics switchable in production

### ISSUE THREAD

**Issue by dhruvkb** [WordPress/openverse#2173]
## Description

With most of the analytics development nearing completion, we want to go live with analytics in production, which would mean changing the flags prod status from disabled to switchable.

https://github.com/WordPress/openverse/blob/21cc5ef5b2c5c113e77048935b749a8c771c6581/frontend/feat/feature-flags.json#L24

**Comment by dhruvkb** [comment]
This is blocked till all the core events are ready and the notification for the analytics has been added.

**Comment by zackkrida** [comment]
Completed in #2174. I will recommend that we make analytics enabled by default in production in #2132 for the actual "go live" of analytics.
