### ISSUE TITLE
e2e Playwright tests are broken: only 1 test runs

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse#2191]
## Description

It seems that after changes from #1920, e2e tests run only one test instead of the 155 tests from the suite.

## Reproduction

Look at the logs from #1920. They say "Running 1 test using 1 worker": https://github.com/WordPress/openverse/actions/runs/5006755962/jobs/8972488862?pr=1920

## Additional context

Almost all consequent PRs ran only 1 test. Only #2122 which was merged after it, ran the full suite. I think it's because it was still using the old settings in the CI.

**Comment by zackkrida** [comment]
I've created an issue so we can enforce not using this via lint rule: https://github.com/WordPress/openverse/issues/2195
