### ISSUE TITLE
Disalllow focused frontend tests via `no-focused-test` lint rule

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse#2195]
## Problem

A focused test (using `.only`) was accidentally introduced to the codebase in #1920. This resulted in the test suite silently only running a single test.

## Description

We can prevent this in the future with the [`no-focused-test`](https://github.com/playwright-community/eslint-plugin-playwright/blob/main/docs/rules/no-focused-test.md) rule included in various eslint plugins, like https://github.com/playwright-community/eslint-plugin-playwright and https://github.com/jest-community/eslint-plugin-jest.

**Comment by sarayourfriend** [comment]
Fixed by #2199
