### ISSUE TITLE
Get rid of API `qa` param and all associated code

### ISSUE THREAD

**Issue by dhruvkb** [WordPress/openverse#2210]
## Problem

The `qa` param has little to no utility for us. The associated indices have only 4 elements and the sample size is too small to make any meaningful conclusions.

With other work in that area such as
- the ability to test search with a different index before promotion
- search relevance sandbox
- 5000 units of sample data in dev

the utility of the QA indices is zero (or at best, close to zero).

On the contrary, it adds a code burden to keep it working, prevent 500 errors and support it at the ingestion server, API and Elasticsearch levels.

## Description

Remove the following:
- API `qa` param
- search controller handling of `qa`
- QA indices in ES
- ingestion server code that creates and populates QA indices
- creation of QA indices in `load_sample_data.sh`
- tests for all of the above

## Additional context

- This caused a 500 error on 2023-05-27 (~00:00 UTC).
- This is incompatible with #2073 
- It should not have been a public interface at all

**Comment by ashiramin** [comment]
Hi @dhruvkb I've never contributed to open source projects and would like to start with this one. I find it quite interesting. I've the contributing guidelines. Is there anything I need to do before I can start looking at this issue?

**Comment by dhruvkb** [comment]
@ashiramin since this is related to the API, it would be nice to have a copy of the API running locally. You can refer to the [API quickstart guide](https://docs.openverse.org/api/guides/quickstart.html) for instructions on how to do this.

**Comment by ashiramin** [comment]
Great I was actually reading that part of the docs. Thanks for your quick reply. I'll reach out if I have any more questions

**Comment by ashiramin** [comment]
@dhruvkb Have a PR up for review
