### ISSUE TITLE
Frontend local dev error `Cannot convert undefined or null to object`

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse#2213]
## Description

Occasionally when running and viewing the frontend locally in the browser at http://192.168.1.178:8443/, an error view and message is displayed while the terminal for the devserver process shows no issue:

<img width="389" alt="CleanShot 2023-05-29 at 15 55 15@2x" src="https://github.com/WordPress/openverse/assets/6351754/f2b7369b-6a94-47a8-af31-8e64f36dd1f5">

![CleanShot 2023-05-29 at 15 55 07@2x](https://github.com/WordPress/openverse/assets/6351754/6591c68b-e14b-4e6d-8d4f-7518ff9b1e88)

## Reproduction

1. `just frontend/run dev` locally and see if it happens. Click around the local site and see if it occurs.

## Additional context

This was previously reported by @sarayourfriend in early 2022 as an issue with vue-server-renderer:

https://github.com/nuxt/nuxt/issues/8303#issuecomment-1029081724

**Comment by sarayourfriend** [comment]
@zackkrida Shouldn't we try to reopen the issue with Nuxt? Though I doubt anything will happen with it as we're on Nuxt 2. I don't know what we can do on our end for this that would warrant an issue, is all.

**Comment by zackkrida** [comment]
I don't believe this is an issue anymore.
