### ISSUE TITLE
Storybook smoke test does not catch if individual stories are broken

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse#2219]
## Problem

See #2218 #2217 #2216 #2215 for examples of broken stories.

## Description

All of these could be prevented either by type-checking the stories (impossible due to MDX not supporting TypeScript and our previous commitment to MDX in spite of this for the sake of the description pages for stories, discussion here: https://github.com/WordPress/openverse/issues/584; also hindered by some components not being typed) or by writing a basic Playwright test for every single story (perhaps one that simply iterates through them all) to confirm there is no warning and that the story at least runs.

The latter is the only reasonable option in light of our commitment to MDX (a lot of work went into converting stories already) and that some of the components in the broken stories above aren't typed anyway (though it would work for many of our stories that do render typed components).

The solution for this is, therefore: write a Storybook playwright test to iterate through all the stories and confirm that no errors are rendered to the page. Note that storybook sometimes still renders _something_ from the story underneath and overlays the error, so it is not enough to merely confirm that there is content from the story. The test _must_ check that there is no error overlay.

**Comment by dhruvkb** [comment]
I had read that MDX v2 (https://github.com/mdx-js/mdx/issues/1041) supports TypeScript. Storybook v7 comes with MDX v2 (#2169). MDX v2 also supports IntelliSense (experimental), which should help.

```
"mdx.experimentalLanguageServer": true
```
