### ISSUE TITLE
v-popover.spec test "hideOnClickOutside -> should hide the popover if a click happens outside the popover by default" is broken

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse#2220]
## Description

Noticed in https://github.com/WordPress/openverse/pull/2199 

The test is broken. The previously used `expectClosed` assertion did nothing (fixed in the linked PR) and the fixed assertions (also in the linked PR) that try to show that the popover is closed do not work. In fact, the popover does not close in the test. In my debugging, I added a click handler to the external area element and I wasn't able to get that handler to fire. This seems to only effect this particular test case, however, as other test cases with almost identical set up had no issue with the external click not registering. I wonder if it's something related to the issue described in this review comment by @AetherUnbound: https://github.com/WordPress/openverse/pull/2141#pullrequestreview-1442655633

## Reproduction

1.  Run the test mentioned after 2199 is merged (so that the assertions are actually fixed and doing something, rather than nothing) with the test un-skipped and see that it fails.

**Comment by zackkrida** [comment]
The test in question currently fails because the wrong element is focused. Instead of the popover contents with a tabindex of `0` set, thwe wrapping element with `tabindex="-1"` is focused.

```js
Summary of all failing tests
 FAIL  test/unit/specs/components/v-popover.spec.js
  ● VPopover › accessibility › autoFocusOnShow › should focus the first tabbable element in the popover by default and not warn

    expect(element).toHaveFocus()

    Expected element with focus:
      <div tabindex="0">Code is Poetry</div>
    Received element with focus:
      <div aria-label="Test label" aria-modal="true" class="popover-content overflow-y-auto overflow-x-hidden rounded-sm border border-light-gray bg-white shadow z-popover" data-popper-escaped="" data-popper-placement="bottom-end" data-popper-reference-hidden="" role="dialog" style="--popover-height: -28px; position: absolute; left: 0px; top: 0px; margin: 0px; right: 0px; transform: translate(0px, 8px);" tabindex="-1"> <div tabindex="0">Code is Poetry</div></div>

      111 |         expectOpen()
      112 |         await nextTick()
    > 113 |         expect(getPopover()).toHaveFocus()
          |                              ^
      114 |         expect(warn).not.toHaveBeenCalled()
      115 |       })
      116 |

      at Object.<anonymous> (test/unit/specs/components/v-popover.spec.js:113:30)

```
