### ISSUE TITLE
`pnpm dev` does not copy English translations to `en.json`

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse#2272]
## Problem

Running `pnpm dev` does not copy translations from `en.json5` to the `en.json` file used by the app. This causes any new strings not to be defined, fills the console with warnings locally, and leads to a confusing experience when running the app without strings. This is especially confusing because the `dev` script does do plenty of other i18n stuff, just not copying the English translations to `en.json`.

## Description

Add copying translations to `en.json` to `dev` script.

**Comment by obulat** [comment]
Fixed by #2537
