### ISSUE TITLE
Back to search results button is gone on `main`

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse#2273]
## Description

The back to results button does not show on `main`.

## Reproduction

1.  Go to https://staging.openverse.org and search for Galah
2.  Pick the first result
3.  Notice the lack of back to results button

## Additional context

Marked high, rather than critical, because the issue isn't present in production.

@obulat @zackkrida pinging y'all to confirm whether this is intentional. I checked the recently merged frontend PRs and nothing stood out to me as necessarily including this change. We still have a playwright test for this so I assume the feature is still meant to be there: https://github.com//WordPress/openverse/blob/ea17972522d59a56dec2f08e8a2fa68230992dcc/frontend/test/playwright/e2e/search-navigation.spec.ts#L102-L112

But how does this test pass? :thinking:

**Comment by sarayourfriend** [comment]
Strangely this only appears to effect the English locale. Perhaps the button _is_ there but not visually present.

This is _not_ fixed by https://github.com/WordPress/openverse/pull/2160 (I noticed this issue while testing that PR).

**Comment by dhruvkb** [comment]
Weirdly, I cannot reproduce that locally. I have `main` checked out, did a `--hard` reset on commit 46a42f7e2 and can see the "Back to results" button.
![Cat cafe in Seoul | Openverse](https://github.com/WordPress/openverse/assets/16580576/ffb2e40f-c1b0-4c0c-a1bc-82cfac1d52e0)

**Comment by zackkrida** [comment]
I'm also not able to replicate this locally or on staging. 

<img width="731" alt="CleanShot 2023-06-01 at 08 52 29@2x" src="https://github.com/WordPress/openverse/assets/6351754/e7cc5121-3b3f-43c8-ae35-a5e74d285a8b">

Any additional context on browser and OS might be needed here, @sarayourfriend!

**Comment by sarayourfriend** [comment]
I'm no longer able to reproduce this :shrug: Closing the issue now.
