### ISSUE TITLE
Analytics event: `BACK_TO_TOP`

### ISSUE THREAD

**Issue by fcoveram** [WordPress/openverse#2276]
## Description

The UI component assumes that users need to go back to the top part of Openverse interface, and this change would help us to understand whether that is true or if any other action derivates from this search flow.

Steps:
1. Add `BACK_TO_TOP` to the `Events` type: https://github.com/WordPress/openverse/blob/839418fabb0972ec3c3ccf48c72fd64cbba03cb9/frontend/src/types/analytics.ts#L12
    - Add `query` and `page` payload for the query term and requested page depth respectively. Additionally, `scrolledPixels` derived from `document.getElementById('main-page').scrollTop` (or, preferably a Vue ref on that element instead) and similarly `maxScroll` derived from `.scrollTopMax` off the same `#main-page` element.
2. Fire the event using the `useAnalytics` composable when the back to top button is clicked. It should be added to https://github.com//WordPress/openverse/blob/HEAD/frontend/src/components/VScrollButton.vue#L47-L50

## Additional context

Screenshot of the UI component mentioned

<img src="https://github.com/WordPress/openverse/assets/895819/005a07ae-43e2-4a80-a206-392181cd5eb4" width="300" alt="Screenshot of openverse's image results. 'Back to top' is highlighted"> 

## Additional information

- [RFC](https://docs.openverse.org/projects/proposals/analytics/20221006-implementation_plan_frontend.html#events)
- [Example usage in `VHomeGallery.vue`](https://github.com/WordPress/openverse/blob/839418fabb0972ec3c3ccf48c72fd64cbba03cb9/frontend/src/components/VHomeGallery/VHomeGallery.vue#L128-L134)

**Comment by dhruvkb** [comment]
Added the "🧹 status: ticket work required" label to convert the issue into the same format as the other Analytics event PRs.

**Comment by fcoveram** [comment]
Great, more than welcome. I will refer to @sarayourfriend as I think added the technical info in the main comment.

**Comment by sarayourfriend** [comment]
Search type does not need to be stored in the payload, it can be inferred from the path (`/search` is all, `/search/image` is images, etc).

`query` and `page` would make sense, though :+1: I'll update the issue description.

**Comment by sarayourfriend** [comment]
The description is updated with the payload parameters to add and I've assigned the issue to you @nevvada. Let us know if you need any help :+1:
