### ISSUE TITLE
Change emoji for blocked issues

### ISSUE THREAD

**Issue by dhruvkb** [WordPress/openverse#229]
The current emoji for blocked issues is 🚧 `construction` which rather suggests a work in progress rather that something not being ready for work.

https://github.com/WordPress/openverse/blob/2ee1b6393ce1204566fad063070fdf07e03e96e7/automations/data/labels.yml#L46

It should be changed to something else. Possible contenders are:

| Emoji | Name | |
|-|-|-|
| 🚫 | `no_entry_sign` | |
| ⛔ | `no_entry` | &larr; preferred choice |
| ✋ | `hand` | |
| 🛑  | `stop_sign` | |
| 🙅 | `no_good` | |

Note that this is independent of the discussion to remove labels from GitHub issues.

**Comment by AetherUnbound** [comment]
I'm fine with ⛔!
