### ISSUE TITLE
Remove connection ID environment variables in favor of simply defining them

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse#2294]
## Description

We currently have a pattern of defining the connection ID for an Airflow Connection via an environment variable (with a default) in addition to the environment variable for the connection itself. This creates two new configuration values for one connection ID. Below are all of the current examples:

https://github.com/WordPress/openverse/blob/a5fb3ea5f5671085f0239641ddc1c637a6193763/catalog/dags/common/constants.py#L32-L36

https://github.com/WordPress/openverse/blob/a5fb3ea5f5671085f0239641ddc1c637a6193763/catalog/tests/dags/common/popularity/test_sql.py#L17

https://github.com/WordPress/openverse/blob/a5fb3ea5f5671085f0239641ddc1c637a6193763/catalog/tests/dags/common/loader/test_sql.py#L26

https://github.com/WordPress/openverse/blob/a5fb3ea5f5671085f0239641ddc1c637a6193763/catalog/tests/dags/common/test_sql.py#L16

These values rarely change (if ever), and do not need to be configured via environment variable.

Instead, we should define these values outright as constants and remove the environment variables from the catalog's `env.template` file.

**Comment by duwarakan** [comment]
What should be the target branch?

**Comment by zackkrida** [comment]
Hi @duwarakan `main` is the default branch for the project and a good choice for most PR targets.
