### ISSUE TITLE
"VPopover › accessibility › autoFocusOnShow › should focus the first tabbable element in the popover by default and not warn" test broken

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse#2300]
## Description

The test `VPopover › accessibility › autoFocusOnShow › should focus the first tabbable element in the popover by default and not warn` in `v-popover.spec.js` is broken.

This was caught in https://github.com/WordPress/openverse/pull/2199

The test currently passes a callback to `nextTick`. However, `nextTick` takes no arguments. The assertions present in the test are never run. The PR linked above changes this and pulls them out of `nextTick` and finds that assertions do not pass.

This may be solved by #2226 so cc @obulat who opened that PR.

**Comment by obulat** [comment]
#2226 didn't solve it, unfortunately, so it's still open

**Comment by sarayourfriend** [comment]
@dhruvkb Is there a PR to link to this or an update to share? I am asking because the priority is critical.

**Comment by sarayourfriend** [comment]
I spend a lot of time trying to fix the test and encountered the same thing. Given our usage of vue-focus-trap combined with custom handling of much of what vue-focus-trap (and the underlying focus-trap library) already handle, I'm not entirely surprised there's some wonky stuff here. If we are able to remove our manual handling of these things and rely entirely on the library, we could theoretically remove the focus management tests.

Alternatively, if these work in practice but not in JSDom, it might just be a JSDom thing and we could write a Storybook Playwright test for the same cases and remove the unit tests.

**Comment by sarayourfriend** [comment]
>  I'll get this assigned in our community meeting today given the priority.

@zackkrida Were you able to discuss this during the meeting or do we still need to find someone to work on it?

**Comment by dhruvkb** [comment]
I tried working on this for a couple of days but I couldn't fix it. So there isn't a PR yet.

**Comment by obulat** [comment]
I also tried fixing this issue but couldn't. Therefore, I think the Storybook test is the way to go here

**Comment by AetherUnbound** [comment]
@obulat, @zackkrida, or @dhruvkb, would it be possible for any of you to work on a Storybook test to address this issue this week? Or is there another approach that will reduce the immediate criticality while we tackle the larger issue?
