### ISSUE TITLE
Create a reference list for alternative project work beyond opening PRs for new work

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse#2304]
## Description

Create a page on our documentation site with a list of alternative tasks for project work beyond opening PRs for new development. This list should include items that contribute to project and team health, and help move Openverse forward. Links and/or view for the kinds of work should be provided in the documentation where relevant.

Some examples are:

- Review PRs (even and especially ones not assigned to you)
- Backlog grooming (particularly for issues marked with the "goal: fix" label)
- Investigate issues that need ticket work
- Bug bashing/dog-fooding
- Check Sentry for long-standing issues and make prioritization recommendations for the next team meeting
- Pick up an implementation plan (this would result in an open PR but takes much longer than most individual issues so wouldn’t add to the overall review burden and PR velocity)
- Research unknown components of our system and share new knowledge
- Pick up active incident investigation (needs to go hand-in-hand with improvements to incident status visibility and accessibility as discussed in other action items)

## Additional context

This is related to #2296 and should be linked to by that alert.

**Comment by sarayourfriend** [comment]
This can be implemented as an expansion of the existing list of non-code contributions in our contributing documention: https://github.com/WordPress/openverse/issues/2304
