### ISSUE TITLE
Remove `boto3` dependency and the s3 configuration from the API 

### ISSUE THREAD

**Issue by krysal** [WordPress/openverse#2305]
## Problem

We are not using Amazon buckets from the API side and for the time being, it will not be necessary.

## Description

As the title says, remove this from the Pipfiles and the code related to S3 configs, including the environment variable(s) from template files.

## Alternatives

Find a use for this package 😀

## Additional context

#2301 and older dependabot updates.

**Comment by YashGaur000** [comment]
Can you assign me issue, I would like to work on it?

**Comment by YashGaur000** [comment]
As S3.py code needs to be removed, should I delete the whole S3.py file?

**Comment by AetherUnbound** [comment]
@YashGaur000 Yes that's correct, https://github.com/WordPress/openverse/blob/main/api/conf/settings/s3.py and references to it should be removed, along with the S3 dependency in the API project.

**Comment by ngken0995** [comment]
@AetherUnbound and @krysal  https://github.com/WordPress/openverse/blob/main/api/conf/settings/s3.py and references doesn't exist in the main repo. I can remove the `boto3` dependency. Let me know if I can create a PR.

**Comment by dhruvkb** [comment]
@ngken0995 that file was removed by https://github.com/WordPress/openverse/pull/3036. Please go ahead and create the PR for deleting the dependency (and any other related usages).
