### ISSUE TITLE
Staggering of ES alias pointing may cause significant discrepancies in sensitivity marker

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse#2306]
## Description

I was looking into monitoring concurrency for #2133 when I realized that we may have a non-trivial time delay between when the alias for main document index gets changed and when the filtered index gets changed. As it stands currently, the main index alias for a media type (e.g. `image`) gets pointed from the old index to the new one and then the `create_filtered_{media}_index` DAG is triggered after that. This creates the new filtered index from the new main index, and then points the alias (e.g. `image-filtered`) to the new index.

As I understand it, we use the Elasticsearch `id` value when running a search query to determine the sensitivity based on this: 

https://github.com/WordPress/openverse/blob/91bb41c0190839edb54644ee2222fc12e32329e9/api/api/utils/search_context.py#L27-L32

If I'm understanding this correctly, this would mean that we use the presence of an Elasticsearch `id` value in the `image-filtered` index to determine sensitivity. Given that there is a time gap between when each index alias gets changed, this could mean that the `id` values returned from the new main index will map to completely different documents in the old filtered index (or documents that don't exist at all). This could return incorrect sensitivity information for those results.

I think it might be possible to make one (or both) of the following changes to mitigate this:

1. Wait to remap the main alias until after the filtered index is built & the alias for it is changed. There would still be a time when old and new exist alongside each other, but that gap could be reduced.
1. Use the `identifier` rather than the Elasticsearch `id` for comparisons when determining sensitivity. This may have a performance impact on the query since it's not the `id` value (although it might not, I'm uncertain what the effect would be).

@sarayourfriend is my understanding of the implementation of #2057 and its interaction with the refresh process correct? CC also @WordPress/openverse-api for any additional context on this.

## Fix

This issue will just address the API aspect. The fix for that is to use `identifier` rather than `id` to query the filtered index, therefore using a document identifier that is guaranteed to be stable. Even if we change how the data refresh order goes, this will be a benefit and its the easiest way to quickly fix the issue without needing to change anything in the data refresh or ingestion server, which will be more complicated.

**Comment by krysal** [comment]
Potentially related discussion: https://github.com/WordPress/openverse/discussions/1947

**Comment by sarayourfriend** [comment]
> Use the identifier rather than the Elasticsearch id for comparisons when determining sensitivity. This may have a performance impact on the query since it's not the id value (although it might not, I'm uncertain what the effect would be).

This is fine. I highly doubt it will introduce any notable performance difference. `identifier` is indexed and it will be plenty fast. The only thing to note is that because of https://github.com/WordPress/openverse/issues/2154 it must be against `identifier.keyword`, not `identifier`, or else fuzzy matching will wreak havoc on the query's results :slightly_smiling_face:

**Comment by sarayourfriend** [comment]
I did _not_ realise that `id` isn't stable across refreshes though. I understand from #1947 why we use `id` as the Postgres database ID, but I am yet again struck by how easy it is to misuse and misunderstand it. We should consider if there are ways of preventing its usage without fully understanding the context and caveats it has.

**Comment by sarayourfriend** [comment]
I've focused the stack labels to just "api" as that is the only place a change is needed for this in particular. I'll update the issue body now to reflect the necessary change to fix this. We should still think about how to document and communicate the caveats of `id`.

**Comment by sarayourfriend** [comment]
Sorry for the multiple comments. I also wanted to say that I don't think the gap is an issue either. If a query is sent to the previous filtered index, something _might_ get through, that is true. If we can minimise that time by delaying the alias switch over, that's a good change and we could do it in a separate issue. It doesn't seem like the most important problem identified in this issue, which is that the `id` isn't stable across refreshes and so there will be a potentially complete mismatch between the new origin index and the previous filtered index. @AetherUnbound do you mind if we split that into a separate issue? Notably, I think this would only require a change to the data refresh DAG. The filtered index DAG switches the indexes at the end, and if the filtered index includes more documents than the origin index, it isn't going to cause potentially sensitive content to get through. If we move the data refresh alias switch to after the filtered index creation, then we'd be okay.

**Comment by AetherUnbound** [comment]
@sarayourfriend Thanks for your work on this! I totally agree, the delay is not nearly as important as the complete mismatch, which is what I was most worried about. Having a separate issue sounds fine, especially since it's not as significant an impact.
