### ISSUE TITLE
Delay origin index alias promotion until after filtered index is created

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse#2314]
## Problem

https://github.com/WordPress/openverse/issues/2306 describes the technical issue in depth. To re-summarise, there is a gap between when the origin index is promoted and when the filtered index is finished. During this gap, the previous filtered index will still be being used for queries against the new origin index. This means that new documents in the origin index that have never been processed by the filtered index creation could get through with an incorrect sensitive text designation even if they do not have sensitive text. This is because we derive a document's text sensitivity based on its non-presence in the filtered index.

To restate: the consequence of this problem is that documents could be incorrectly designated as having sensitive text, not the other way around. To my mind, that significantly reduces the severity of this issue. If documents with sensitive text were incorrectly being left out of the sensitive text designation, then it would be a more severe issue.

## Description

To goal needs to be to minimise the gap between the origin index having new documents and the filtered index not having yet been updated to reflect the new origin index.

The best way to do this is to delay the origin index alias switch until after the filtered index is created. This will result in a world where filtered queries (the vast majority of our queries) receive up-to-date information before unfiltered queries. It also completely removes the possibility of any documents being incorrectly labelled as having sensitive text.

Move the data refresh's promote alias step to after the filtered index creation. This will require some rather complex changes as the data refresh DAG's design assumes that alias promotion can happen immediately after index creation. It will also require adding a sensor to wait for filtered index creation to finish.

This should probably be done before, with, or immediately after https://github.com/WordPress/openverse/issues/2071 (so long as that issue is implemented with _this one_ in mind) as they'll both be changing the timing of the alias promotion.

**Comment by stacimc** [comment]
Resolved by https://github.com/WordPress/openverse/pull/3303
