### ISSUE TITLE
Remove implicit `@testing-library` `get*` assertions: `v-content-report-form.spec.js`

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse#2315]
## Current Situation

See https://github.com/WordPress/openverse/discussions/2198 for description of issue.

## Suggested Improvement

Remove the `eslint` comment from the top of `v-content-report-form.spec.js` and update all tests to have explicit assertions.

Example transformations:

```js
screen.getByRole("button") // throws if not present
```

should be

```js
expect(screen.findByRole("button")).toBeInTheDocument()
```

## Benefit

See https://github.com/WordPress/openverse/discussions/2198

**Comment by ZeroPlayerRodent** [comment]
May I be assigned to this issue?

**Comment by AetherUnbound** [comment]
@ZeroPlayerRodent Done!
