### ISSUE TITLE
Remove implicit `@testing-library` `get*` assertions: `v-audio-details.spec.js`

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse#2319]
## Current Situation

See https://github.com/WordPress/openverse/discussions/2198 for description of issue.

## Suggested Improvement

Remove the `eslint` comment from the top of `v-audio-details.spec.js` and update all tests to have explicit assertions.

Example transformations:

```js
screen.getByRole("button") // throws if not present
```

should be

```js
expect(screen.findByRole("button")).toBeInTheDocument()
```

## Benefit

See https://github.com/WordPress/openverse/discussions/2198

**Comment by obulat** [comment]
This file was removed from the repository.
