### ISSUE TITLE
Update technology labels

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse#2339]
## Problem

https://github.com/WordPress/openverse/discussions/2155 identifies technology labels that need to be modified or added. 

## Description

Add the following new labels:

- pytest
- jest
- playwright
- elasticsearch
- redis
- github actions
- just

All labels should have their descriptions updated to replace "Requires familiarity with" with "Involves". "Requires familiarity with" precludes "good first issue"s being accessible introductions to the technology in question.

These labels can be updated in our label definition here: https://github.com/WordPress/openverse/blob/6363147debdda6a1deb9f4dc8addec1cf8a9102b/automations/data/labels.yml#L148-L185

**Comment by ZeroPlayerRodent** [comment]
Hello, may I be assigned this issue?

**Comment by AetherUnbound** [comment]
Sure, I've assigned you @ZeroPlayerRodent! Please let us know if you have any questions 🙂

**Comment by ZeroPlayerRodent** [comment]
Thanks!
I have one question: When adding the labels for frameworks like pytest or Jest, do I give them the wrench emoji, or do I give them the same emoji as the programming language they are made for?
