### ISSUE TITLE
Use TypeScript for Tailwind config

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse#2342]
## Problem

We are using CJS modules (with `module.exports`) for `screens` and `z-indices` because they are used by Tailwind config, which also uses CJS. Tailwind has recently added support for TS in config[^1], so we can move everything to TS.

## Description

Convert `frontend/tailwind.config.js`, `frontend/src/constants/screens.js` and `frontend/src/constants/z-indices.js` to TypeScript. There will be some changes to types (numbers might need to be wrapped in quotes). The `tsconfig` might also need to be updated.

## Alternatives

We could keep using JS with JSDoc. 

## Additional context

Nuxt 3 requires ESM, so this would be a great change to have.

[^1]: https://tailwindcss.com/blog/tailwindcss-v3-3#esm-and-type-script-support

**Comment by Devanshi-Crypto** [comment]
Hey, I have been working in typescript for a while for automation and I originally belong to the frontend field, Can I contribute in your project?

**Comment by obulat** [comment]
Sure, @Devanshi-Crypto ! I'll assign this issue to you. Feel free to ask for help if you need any.

**Comment by Devanshi-Crypto** [comment]
Hey, I have made some changes at an initial level. Can you please check and let me know .
[https://github.com/Devanshi-Crypto/openverse/commit/77bfaea9d8be02559ad18f7153fc516a2ce1ece6](url)
