### ISSUE TITLE
Consider making secondary icons official or revising them

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse#2356]
## Problem

This week I needed some icons for automations I was working on and created some "unofficial" icons that are variations on the Openverse logo:

Figma: https://www.figma.com/file/miIAs08ZsAr7JlFOGR2jLX/supporting-icons?type=design&node-id=0%3A1&t=xAJDNGB7BfQ8PAHU-1

![CleanShot 2023-06-08 at 13 27 36@2x](https://github.com/WordPress/openverse/assets/6351754/c80d5f1a-64d4-4974-8b97-83b99b110728)

@fcoveram at some point could you give feedback on these? Are they okay to use _internally_ amongst maintainers? Are they good enough for possible public usage? Particularly the Openverse bot, as it might be nice to use that for the @openverse-bot account to personalize it a bit more.

**Comment by fcoveram** [comment]
I love the bot version ❤️ We can use them publicly, definitely. I'm not fully sure about the alarm one, but it works well for what conveys. I'd like to try a new version in the future once I have more bandwidth to tackle these needs.

**Comment by zackkrida** [comment]
Cool! @fcoveram we can stick to internal maintainer locations only with the alarm icon for now.

**Comment by zackkrida** [comment]
![alarm-revised](https://github.com/WordPress/openverse/assets/6351754/97588c5f-8bb3-4ecb-
baad-81cd405aff4e)

**Comment by fcoveram** [comment]
You're right. It looks better.

Can you move the Figma file to the [Openverse folder](https://www.figma.com/files/project/31962071)? I have no access to the file and wanted to check some spacings.

**Comment by fcoveram** [comment]
Done. Here is the [new file](https://www.figma.com/file/gMEtRdHhqZvAV4Yv41Rfzf/Supporting-Icons?type=design&t=e3yhbBHYk2aQ8YAM-6).

**Comment by AetherUnbound** [comment]
We're closing this issue as all of the bots we have control over have been changed, and since this is internal to the team it doesn't necessarily belong in the `/brand` folder.
