### ISSUE TITLE
Ping the person who merged to `main` in the CI/CD failure messages

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse#2360]
## Problem

A supplement to https://github.com/WordPress/openverse/issues/1228

These messages are too easy to miss for the person who merged to main.

## Description

To make these more noticeable for the person who merged to main, ping the person who did the merge in the error message.

**Comment by zackkrida** [comment]
Some additional suggestions that would fit in the scope of this issue:

- Add the name of the commit to the top of the message
- Make it more explicit that these notifications suggest a CI/CD failure (the skip icon is fairly neutral)
- Add a note telling the person who merged how to correctly triage the CI/CD failure or deployment failure
