### ISSUE TITLE
Use a migrations management tool for upstream_db and thus for production database

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse#2364]
## Problem

If changes are made to the upstream_db schema as in #2096, you need to fully rebuild the `upstream_db` image to get them.

This also has an effect on production database management, where we are required to manually run schema change queries on production (see #2096 has a comment noting this requirement).

Neither of these are good. The first because it creates a confusing and difficult to debug local environment issue if schema changes happen (why aren't I getting this column that is obviously in the SQL file to create the schema). The second because it requires us to manually write queries that change the production schema! The first is bad but the second is downright awful and we should not continue this practice.

## Description

Use a schema migration tool like Alembic to describe the catalog database schema and apply migrations over time.

## Alternatives
We could write our own SQL migrations and apply them iteratively by hand but... Alembic is going to be a lot better at doing this, why reinvent the wheel?

## Additional context
This is marked `stack: mgmt` but it's really `stack: infra`, `stack: catalog`, and `stack: api` (basically everything) due to the crossover in local and live environment dependencies on the upstream database schema.

**Comment by AetherUnbound** [comment]
@sarayourfriend this may be a duplicate of or related to https://github.com/WordPress/openverse/issues/1836

**Comment by sarayourfriend** [comment]
It is, thank you! I'll suggest higher prioritisation on that one and close this one.
