### ISSUE TITLE
Component: Sensitive content fetch/blur sidebar toggles

### ISSUE THREAD

**Issue by dhruvkb** [WordPress/openverse#2368]
## Description

Define the component that contains two toggles, one to fetch the sensitive content from the API and the other that controls whether the sensitive content fetched should be blurred in the UI.

## API

This component need not accept props or emit events, it can be directly synced with the state held in the Pinia store.

### State

| Name | Type | Description |
|-|-|-|
| shouldFetchSensitive | boolean | whether sensitive content should be fetched from the API |
| shouldBlurSensitive | boolean | whether sensitive content should be blurred in the search results and single result page |

`shouldFetchSensitive` is synced with the feature flag store, specifically the [`fetch_sensitive` feature flag](https://github.com/WordPress/openverse/blob/de7d99e70bd56df8552608a9edc0213821068089/frontend/feat/feature-flags.json#LL36C6-L36C21).

`shouldBlurSensitive` can be stored in the `ui` store but it should not be persisted across visits, so it cannot be committed to a cookie or put into `localStorage`.

> **Note**
> The second toggle should be turned off **and** disabled if the former is off.

## Screenshot

<img width="293" alt="Screenshot 2023-06-09 at 9 13 42 AM" src="https://github.com/WordPress/openverse/assets/16580576/6c348ae3-16cd-4741-8ae0-cd695ef72ea3">

## Figma 

- **Figma:** https://www.figma.com/file/bDTfGzBit8rGRPktOR1cu4/Safe-content-browsing-flow?type=design&node-id=1140-23930&t=t4b5KNE2t2viAres-4

**Comment by wasimTQ** [comment]
@dhruvkb I'd like to contribute to this issue. I've looked through the code and I have to clarify how it should be implemented with you.

Should I use the feature flag store and manipulate the changes there? 

Or the other option should be to 
1. Add more fields `fetch_sensitive_content, blur_sensitive_content` in `filterCodesPerCategory.mature`
2. Add entries to the locales files under filter.{mature_keys}
3. Let the already available `searchStore` do all the work

Let me know if this is the ideal solution for this issue.

**Comment by dhruvkb** [comment]
@wasimTQ this issue is mainly only about implementing this specific component and interfacing it with the UI and feature flag stores. You do not need to connect this with the API, that will be handled by the search store in a separate issue.
