### ISSUE TITLE
Add Elasticsearch Airflow Provider

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse#2370]
## Description

Add the Elasticsearch Airflow provider to the catalog dependencies as described in the Implementation Plan for this work: https://docs.openverse.org/projects/proposals/search_relevancy_sandbox/20230518-implementation_plan_staging_index_rapid_iteration.html#elasticsearch-provider

## Additional context

This is part of #392

**Comment by sarayourfriend** [comment]
Do we still want to take this approach? We've introduced the ability to interact directly with the Elasticsearch REST API. Does the provider have significant benefits over directly interacting with the REST API? Just wondering if we can cut out this and https://github.com/WordPress/openverse/issues/2371 and reduce the scope of the project.

**Comment by AetherUnbound** [comment]
I think because the complexity of operations we're planning on performing in Airflow is higher than what exists currently, it makes sense to leverage the provider package to bring in a known-compatible version of the Elasticsearch python package. That will allow us to use an API that we're familiar with and use elsewhere (like the API and ingestion server) rather than having separate definitions for interacting directly with the REST API for Elasticsearch.
