### ISSUE TITLE
`pr_limit_reminders` fails on forks

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse#2393]
## Description

We should disable the `pr_limit_reminders` workflow for forks because its purpose is to remind the maintainers, not the community contributors. Currently, it fails on PRs from forks because it requires the `github_token`.

## Reproduction

See https://github.com/WordPress/openverse/actions/runs/5248359273

Priority set as high because this issue prevents community PRs from passing the CI.

**Comment by zackkrida** [comment]
@obulat do I just need to switch to `pull_request_target`? I'm trying to research how to fix this and not coming up with a clear answer.
