### ISSUE TITLE
SVG thumbnails do not work

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse#2397]
## Problem

Currently SVG thumbnails do not work as they're not supported by our thumbnail service provider Photon. This feels like poor service to our users. How could we make sure they can view SVG thumbnails?

## Description

On the frontend we fallback to the full direct image url when a thumbnail isn't available. Could we directly serve the SVGs through our /thumb endpoints? IS there another approach?

Additionally, on any search with the `extension=svg` query param set, _all_ thumbnails will fail with 415 errors.

## Alternatives

Currently < 2% of our thumbnails are 415 Unsupported Media type errors, so this does not impact many thumbnails and therefore, users.

**Comment by obulat** [comment]
Yes, @roytanck, `tiff` is another file format that is not currently handled well by the `/thumb` endpoint. We use [photon](https://developer.wordpress.com/docs/photon/) to thumbnail original images and to cache them. Unfortunately, it does not support `tiff` files, so we will need to create a separate solution. For now, as you say, we are returning "heavy and not supported by browsers" unaltered TIFF.
