### ISSUE TITLE
Add Google Analytics to Openverse site?

### ISSUE THREAD

**Issue by jdevalk** [WordPress/openverse#2403]
## Problem

Hi! We're adding Google Analytics to the entire ecosystem of WordPress.org sites and would like to add it to Openverse too if you're keen. 

## Description

We manage Google Analytics through Google tag manager. We have quite a few scripts there to make sure we don't store any personally identifiable information in GA, so we've centralized all that. You can simply add Google tag manager similarly to how that's done on WordPress.org sites, for instance [like this](https://github.com/WordPress/wordpress.org/blob/trunk/wordpress.org/public_html/wp-content/mu-plugins/pub/wporg-google-tag-manager.php) or [like this](https://github.com/WordPress/wordpress.org/blob/trunk/jobs.wordpress.net/public_html/wp-content/themes/jobswp/header.php#L17-L24). Don't forget to add the `noscript` line too, [like so](https://github.com/WordPress/wordpress.org/blob/trunk/jobs.wordpress.net/public_html/wp-content/themes/jobswp/header.php#L30).

## Alternatives

I've seen discussions around using Plausible, while that's a great product (I've done some patches to their WordPress plugin myself), we're standardizing everything else on Google Analytics and it might be easier to just follow along with that.

## Additional context

Note that if you have any cookie / privacy pages they might need updating after this change. See [this pull](https://github.com/WordPress/wordpress.org/pull/155) on wordpress.org for the changes we'll be making there.

**Comment by sarayourfriend** [comment]
We chose Plausible as a general purpose analytics solution that we could use for other services as well, not just our frontend. In the course of planning that work we intentionally decided not to use GA for privacy reasons. [One of the criteria of that project was that we would use a privacy conscious analytics option](https://docs.openverse.org/projects/proposals/analytics/20230307-backend_service.html).

@WordPress/openverse-frontend, especially @zackkrida and @dhruvkb will be best equipped to advise on how to approach this. Personally I would prefer we did _not_ switch to GA:

- [GA has a host of significant privacy problems that conflict with the values of the WordPress project, in my opinion, and if not, then at least with the values of the Openverse maintainers](https://matomo.org/blog/2022/06/google-analytics-privacy-issues/)
- [GA's scripts are significantly larger than Plausible or other alternatives](https://plausible.io/vs-google-analytics#increasing-the-page-weight-and-the-loading-time) and from a low-spec device accessibility standpoint, I firmly believe GA is a worse choice, even if it didn't have the issues with privacy.
- We cannot self-host Google Analytics, which means we do not control the service or the data, which is antithetical to WordPress's values, in my understanding of them ([according to WordPress's features list](https://wordpress.org/about/features/)).
- Plausible is fellow FOSS project and is AGPL licensed, and shares many values in that regard with WordPress, which are not true of Google Analytics. Paying them for their cloud service means we are feeding back into a diverse FOSS ecosystem of GA alternatives.

We use Plausible for custom events as well and have already worked it into our workflow. If we added GA on top of Plausible, it would hurt our users from a performance perspective and from a privacy perspective. If we switched exclusively to GA, we would need to revisit our approach to custom events and retrain maintainers on GA (who've already spent considerable time learning about Plausible). This on top of our other existing priorities for the year.

To be clear, this is just my own view of the matter. I am sharing my own person view on this. None of this is shared on behalf of the other Openverse maintainers nor should be taken to represent anyone else's view on the matter.

**Comment by zackkrida** [comment]
Our use of Plausible for over a year has met our needs well and aligns with the values of the Openverse, and broader WordPress, projects. In that time we've met various requests for analytics information about Openverse and will continue to do so.
