### ISSUE TITLE
Frontend sentry not reporting errors causing 500s

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse#2406]
## Description

The production frontend service has a regular but a very small number of 500s, less than 30 per day and often enough, none at all in a given day, typically. However, whatever errors cause these 500s are never reported in Sentry.

## Additional context

![Graph of Openverse Nuxt 500 errors daily for the last 4 weeks showing that often there are no errors but sometimes some do exist](https://github.com/WordPress/openverse/assets/24264157/49ac1d53-85b8-479a-87da-566e38ff96b3)

As you can see, we do have 500s, yet these never appear in Sentry.

It may be helpful to look through Nuxt logs around the time that 500 happens to see if anything reveals itself as far as reproduction or why Sentry might not be receiving these errors.

cc @WordPress/openverse-frontend I've marked this high because it could mean that Sentry is not working, which means our main method of observability for frontend stability isn't reliable right now.

**Comment by zackkrida** [comment]
It's not much, but these were the only errors I was able to find after the latest deployment. For some reason they didn't have timestamps which I can't seem to figure out:

`WARN  There was an error fetching media providers for audio: read ECONNRESET`

```
 ERROR  Range Not Satisfiable
  at createHttpError (/home/node/node_modules/.pnpm/send@0.18.0/node_modules/send/index.js:984:7)
  at SendStream.error (/home/node/node_modules/.pnpm/send@0.18.0/node_modules/send/index.js:270:31)
  at SendStream.send (/home/node/node_modules/.pnpm/send@0.18.0/node_modules/send/index.js:666:19)
  at onstat (/home/node/node_modules/.pnpm/send@0.18.0/node_modules/send/index.js:725:10)
  at FSReqCallback.oncomplete (node:fs:203:5)
  at FSReqCallback.callbackTrampoline (node:internal/async_hooks:130:17)
```

I also confirmed Sentry is working locally by enabling it, hardcoding the DSN, and pushing some events with `$sentry.captureException(...)`.

<img width="581" alt="CleanShot 2023-06-29 at 16 23 23@2x" src="https://github.com/WordPress/openverse/assets/6351754/e085b418-3b2d-41e5-b78a-c914bdf2c2e8">

Here's two examples, one SSR one client-side. These two were triggered with `throw new Error()` to make sure _that_ works too:

- https://openverse.sentry.io/share/issue/d30dc852709e422c87ef6dffba9862f7/
- https://openverse.sentry.io/share/issue/d30dc852709e422c87ef6dffba9862f7/


In production, I also see that the frontend tasks log `✔ Sentry reporting is enabled (client side: enabled, server side: enabled)` and have the correct environment variables in their task definitions.

Ah! But I just noticed, in prodution for some reason Sentry appears to _actually_ be disabled, despite all of those things 🤔 `window.$nuxt.$sentry.captureException` is a noop:

```js
const apiMethods = ["init", "vueRouterInstrumentation", "attachErrorHandler", "createTracingMixins", "FunctionToString", "Hub", "InboundFilters", "Scope", "addBreadcrumb", "addGlobalEventProcessor", "captureEvent", "captureException", "captureMessage", "configureScope", "createTransport", "getCurrentHub", "getHubFromCarrier", "makeMain", "setContext", "setExtra", "setExtras", "setTag", "setTags", "setUser", "startTransaction", "withScope", "BrowserClient", "makeFetchTransport", "makeXHRTransport", "defaultStackParser", "eventFromException", "eventFromMessage", "close", "flush", "forceLoad", "lastEventId", "onLoad", "showReportDialog", "wrap", "Replay", "makeBrowserOfflineTransport", "onProfilingStartRouteTransaction", "BrowserProfilingIntegration", "GlobalHandlers", "TryCatch", "Breadcrumbs", "LinkedErrors", "HttpContext", "Dedupe"]

/** @type {import('@nuxt/types').Plugin} */
export default function (ctx, inject) {
    const SentryMock = {}
    apiMethods.forEach(key=>{
        SentryMock[key] = _=>_
    }
    )

    // Inject mocked sentry to the context as $sentry (this is used in case sentry is disabled)
    inject('sentry', SentryMock)
    ctx.$sentry = SentryMock
}
```

I have to sign off, but this is quite odd. Hopefully there's something really simple we're missing.

**Comment by sarayourfriend** [comment]
If `SENTRY_DSN` isn't present at build time then webpack is going to cut it out of the build :confused:

**Comment by sarayourfriend** [comment]
The Nuxt Sentry module resolves Sentry DSN at build time. The runtime config doesn't matter _at all_. We need to change how we define the configuration to get it to work with runtime configuration: https://sentry.nuxtjs.org/sentry/runtime-config

**Comment by sarayourfriend** [comment]
Okay, I think I've got a working fix in the associated PR.
