### ISSUE TITLE
Set log rotation policy for catalog docker-compose in production

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse#2414]
## Problem

The docker-compose stack we use for the catalog in production does not have any default log rotation policy defined. Docker warns about this exact scenario[^1]:

> By default, no log-rotation is performed. As a result, log-files stored by the default json-file logging driver logging driver can cause a significant amount of disk space to be used for containers that generate much output, which can lead to disk space exhaustion.

[^1]: https://docs.docker.com/config/containers/logging/configure/

We have experienced this disk space consumption issue ourselves, see this screenshot below of disk usage over time (due almost entirely to docker logs):

![image](https://github.com/WordPress/openverse/assets/10214785/0ce25ef9-d244-4e8e-a4b8-463ec3906c0d)

_Catalog: Disk Usage (5m interval) for the 12 hours._

## Description

We should add the following (per the [docker-compose logging definition's example](https://docs.docker.com/compose/compose-file/compose-file-v3/#logging)) to the production-specific docker-compose file that we use: https://github.com/WordPress/openverse/blob/c19d10fa0105cf96a078ee9dbde0d19756e29b4c/catalog/docker-compose.yml

Specifically, we should add the following to both `scheduler` and `webserver`:

```yaml
logging:
  options:
    max-size: "100m"
    max-file: "10"
```

## Alternatives

We could do scheduled automated restarts of the stack to refresh logs, but this might disrupt running tasks.

**Comment by ZeroPlayerRodent** [comment]
May I be assigned this issue?

**Comment by sarayourfriend** [comment]
@ZeroPlayerRodent You're assigned, thanks!
