### ISSUE TITLE
Move the `VSkeletonGrid.vue` styles to the template

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse#2440]
## Description

`VSkeletonGrid.vue` uses `style` to set the Tailwind styles. 

https://github.com/WordPress/openverse/blob/04a36fcb320063aa8b42ea703c8059d7254d6990/frontend/src/components/VSkeleton/VGridSkeleton.vue#L64-L80

The nesting is used incorrectly here (`@screen md` should wrap the `masonry` class styles instead of the other way around). This causes errors when CSS is built for production (or it will cause errors after we migrate to Nuxt 3).

We should move all of the styles to the template classes instead. Here are some corresponding Tailwind classes:

`column-count: 1` -> `columns-1`
`column-gap: 1rem` -> `gap-x-4`
So, the column-related classes would be `columns-2 gap-x-4 md:columns-3 lg:columns-5`

`aspect-ratio: 1 / 1` -> `aspect-square`

## Additional context

Found this while testing Nuxt 3 migration.

**Comment by obulat** [comment]
Hi, @YashGaur000! #2636 fixed this issue, but we didn't close it. Could you please find a different issue?

**Comment by YashGaur000** [comment]
Okay, its alright but it was not nested correctly, was it?
