### ISSUE TITLE
Replace `require` with `import` for images on the homepage

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse#2465]
## Problem

We use `require` for images on the homepage. `require` will be deprecated in Nuxt 3.

## Description

We should move the `hompage_images` folder (images only, not the `json` file) to `/static` folder, and use the static URLs.

https://github.com/WordPress/openverse/blob/507d7401a774aad70b984ae7237183d510b0de30/frontend/src/components/VHomeGallery/VHomeGallery.vue#L115-L117

Change the code above to 
```
src: `/homepage_images/${imageSet.value.key}/${idx + 1}.png`
```

**Comment by tarunsamanta2k20** [comment]
I'd like to work on this.

**Comment by sehgxl** [comment]
Hey @WordPress/openverse-maintainers, I would like to work on this issue,

**Comment by obulat** [comment]
> Hey @WordPress/openverse-maintainers, I would like to work on this issue,

@sehgxl , I've added more details to the issue description.

**Comment by sehgxl** [comment]
@obulat appreciate you adding the details, working on this.
