### ISSUE TITLE
"visual-regression/v-header-internal.spec.ts:35:11 › VHeaderInternal › screen at breakpoint xs with width 340 › mobile-header-internal-modal-ltr" is flaky

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse#2473]
## Description

Failed run on `main` CI: https://github.com/WordPress/openverse/actions/runs/5340998522/jobs/9681413214

Test results artefact: [storybook_test_results.zip](https://github.com/WordPress/openverse/files/11828233/storybook_test_results.zip)

## Additional context
Marked critical as per our policy for flaky tests

**Comment by AetherUnbound** [comment]
@WordPress/openverse-frontend Is anyone able to take this on in the next few days?
