### ISSUE TITLE
OperationalError on multiple endpoints

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse#2476]
## Description

We had `OperationalErrors` occur over several endpoints this last week. These exceptions look like this:

```
OperationalError: connection is bad: Temporary failure in name resolution
  File "django/db/backends/base/base.py", line 289, in ensure_connection
    self.connect()
  File "django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "django/db/backends/base/base.py", line 270, in connect
    self.connection = self.get_new_connection(conn_params)
  File "django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "django/db/backends/postgresql/base.py", line 275, in get_new_connection
    connection = self.Database.connect(**conn_params)
  File "psycopg/connection.py", line 728, in connect
    raise ex.with_traceback(None)
```

Unlike #671 (where the database itself was unreachable), we believe this to be the result of a traffic spike which overwhelmed DNS at the time, since the database remained operational.

Endpoints affected:
- `/healthcheck/`
- `/v1/images/{identifier}/`
- `/v1/images/{identifier}/related/`
- `/v1/images/{identifier}/thumb/`

## Sentry Link

For security reasons, this is a maintainer only link: https://openverse.sentry.io/issues/4210575629/?project=6107216

## Mitigation

This could be mitigated by the process outlined in #2472

**Comment by sarayourfriend** [comment]
I've updated the incident report but it does seem like the `CONN_MAX_AGE` change linked to the linked issue has resolved this. If we have no more OperationalErrors tomorrow I'll close this issue.

**Comment by zackkrida** [comment]
All remaining OperationalErrors were in the `staging` environment, caused by the staging database restore process (cc @AetherUnbound). I am therefore going to close this and consider it resolved.
