### ISSUE TITLE
Add Free Music Archive to the "External Sources" frontend feature

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse#2486]
## Problem

The FMA is a lovely source of CC-licensed and public domain audio files. We could easily add them to our "External sources" functionality:

`https://freemusicarchive.org/search?quicksearch={term}`

**Comment by obulat** [comment]
## Solution description

"External Sources" list is built in

https://github.com/WordPress/openverse/blob/364d07ac41ab2884149220ffd9a60185c77244dc/frontend/src/utils/get-additional-sources.ts#L58C1-L67C5

Adding this code to it should fix this issue.
```
const additionalSourceBuilders: AdditionalSourceBuilder[] = [
...
  {
    name: "Free Music Archive",
    image: (search) => ({
      url: "https://freemusicarchive.org/search",
      queryParams: {
        quicksearch: search.q,
      },
    }),
  },
]
```

To test this, run `just frontend/run dev`, open an image search page and scroll down to view the "External sources" button. 

<img width="683" alt="Screenshot 2023-10-20 at 3 10 22 PM" src="https://github.com/WordPress/openverse/assets/15233243/026feb7f-e11d-4f56-b3bb-db85a8671b44">

The popup should contain "Free Music Archive", and clicking on it should open the search page on FMA with the search term from Openverse.

**Comment by alt-shreya** [comment]
I'm eager to contribute to this repo. Is this issue still available?

**Comment by AetherUnbound** [comment]
Welcome @alt-shreya! It is, I'll go ahead and assign it to you 😄 Feel free to check out our [welcome page](https://docs.openverse.org/general/contributing.html) and [quickstart guide](https://docs.openverse.org/general/quickstart.html), and let us know if you have any questions 🙂

**Comment by alt-shreya** [comment]
@AetherUnbound awesome, thank you! :sparkles: 
What would be the best way to reach out for help: the [GitHub discussions ](https://github.com/WordPress/openverse/discussions/)or the [Community page](https://make.wordpress.org/openverse/)?

**Comment by AetherUnbound** [comment]
The `#openverse` channel of the [Make WP Chat](https://make.wordpress.org/chat/) is probably the best place for general questions! If you have questions about this specific issue though, feel free to leave them here 😄
