### ISSUE TITLE
`just frontend/init` fails with cryptic error if plausible service isn't ready for requests

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse#2489]
## Description

```
$ just frontend/up
...
$ just frontend/init
env COMPOSE_PROFILES="frontend" just ../up 
env COMPOSE_PROFILES="frontend" docker-compose -f docker-compose.yml up -d
[+] Running 3/0
 ✔ Container openverse-plausible_db-1  Running                                                      0.0s 
 ✔ Container openverse-plausible_ch-1  Running                                                      0.0s 
 ✔ Container openverse-plausible-1     Running                                                      0.0s 

================================================================================
                                 Service Ports                                  
================================================================================
plausible (plausible/analytics):
-  http://0.0.0.0:50288 (→ 8000)
================================================================================
echo "🚧 TODO"
🚧 TODO
cd .. && ./setup_plausible.sh
--rpc-eval : RPC failed with reason :nodedown
error: Recipe `init` failed on line 66 with exit code 1
```

## Reproduction

1.  `just down`
2.  `just frontend/up` and right after `just frontend/init`
3. See the error above.

## Fix

Add a "wait for" recipe that waits for Plausible to be available before running `setup_plausible.sh` similar to the `docker/es/wait-for-index` recipe.

**Comment by YashGaur000** [comment]
how to run it on my machine to check for error?

**Comment by sarayourfriend** [comment]
@YashGaur000 I'm not sure what you're asking exactly. The steps to reproduce the issue are in the description. You do not need to click any links to reproduce the problem. Can you clarify your understanding of the issue and what you are trying to do?

**Comment by YashGaur000** [comment]
where to write 'just down'? in terminal of VS? i don't know how to run it and how to reproduce it. Please give some brief steps please

**Comment by sarayourfriend** [comment]
Please follow the general setup guide for working with Openverse locally: https://docs.openverse.org/general/general_setup.html

Note that Openverse does not support development directly on Windows. The linked guide recommends using WSL. Additionally, the changes required for this issue are more complex than what you are describing. As the issue describes:

> Add a "wait for" recipe that waits for Plausible to be available before running setup_plausible.sh similar to the docker/es/wait-for-index recipe.

This will require a new just recipe to wait for plausible (added to a new `docker/plausible/justfile` or to the `frontend/justfile`). The new recipe must be called before `setup_plausible.sh` is called by the frontend justfile's `init` recipe to ensure Plausible is running.

**Comment by YashGaur000** [comment]
can you assign me this issue?

**Comment by sarayourfriend** [comment]
Sure thing, you're assigned. Please ping [`@WordPress/openverse-maintainers`](https://docs.openverse.org/meta/communication_aliases.html) if you need assistance working on the issue as I'll be on holiday for the next two weeks.

**Comment by ngken0995** [comment]
Hello @sarayourfriend, Can I be assigned to this?

**Comment by ngken0995** [comment]
@sarayourfriend, Can I be assigned to this?

**Comment by AetherUnbound** [comment]
@ngken0995 I've assigned the PR to you - please do check out the previous PR related to this for some information on how to approach it: https://github.com/WordPress/openverse/pull/2705

@YashGaur000 if you're still interested in working on this let us know! We're also happy to help you find something else to work on within the project 🙂
