### ISSUE TITLE
Large SVGs can cause gunicorn workers to abort

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse#2492]
## Description

Sentry link: https://openverse.sentry.io/share/issue/4c79aa2603b3401e958c9ae7e8bf2bce/

Exceedingly large SVGs and complex SVGs, like this one:

https://api.openverse.engineering/v1/images/0274f0fc-8f55-41f7-848f-32f1712348ab/

Can cause the thumbnail endpoint to fail and kill one of our API workers. I am not sure exactly what the cause is.

**Comment by dhruvkb** [comment]
To add more context, the SVG linked above measures 33.3 MB compressed (103 MB actual) and took a full minute to render for me locally.

**Comment by sarayourfriend** [comment]
It's probably just that, the transfer of the file takes longer than the 15 second timeout. It's a good indication of an SVG that is _not_ suitable to be used as a thumbnail :open_mouth:

**Comment by AetherUnbound** [comment]
We no longer use `gunicorn` (replaced with `uvicorn` as part of the Django ASGI conversion). Closing this issue.
