### ISSUE TITLE
Baseline monitoring changes for Terraform and the unhealthy host count alarm

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse#2499]
## Description

Project thread: https://github.com/WordPress/openverse/issues/2344
Implementation plan: https://docs.openverse.org/projects/proposals/monitoring/20230606_implementation_plan_ecs_alarms.html

1. Create the monitoring modules for frontend and API staging and production and move existing alarms into these
  - Create a new `next/modules/monitoring` directory with a directory for each service/environment: `staging-frontend`, `production-frontend`, `staging-api`, etc.
  - This includes moving the UptimeRobot configuration for each service as well as the database and Redis monitors
  - Rename `service-monitors` to `service-uptime-robot` to clarify the module's purpose
  - Also create the new SNS topic for the unstable alerts' notification channel
  - This does not include moving the ECS service cloudwatch dashboard module, that should remain in the root modules
1. Create the unhealthy host count alarm for production and staging services

> **Note**
>
> The only thing that will be present in the staging monitoring modules for each service is the unhealthy host count alarm.

## Additional context

This issue will remain open until the unhealthy host count alarm is stabilised. However, once the terraform configuration changes and the new monitoring modules are present, all other alarm issues in this milestone will be unblocked.

**Comment by krysal** [comment]
Fixed in WordPress/openverse-infrastructure#558.
