### ISSUE TITLE
API thumbnails response time alarms

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse#2502]
## Description

Project thread: https://github.com/WordPress/openverse/issues/2344
Implementation plan: https://docs.openverse.org/projects/proposals/monitoring/20230606_implementation_plan_ecs_alarms.html

Create alarms in `next/modules/monitoring/production-api-thumbnails` for the following:

- Average response time anomaly
- Average response time over threshold
- p99 response time anomaly
- p99 response time over threshold

## Additional context

This issue will remain open until the alarms are stabilised.

Blocked by the baseline configuration changes in https://github.com/WordPress/openverse/issues/2499

**Comment by AetherUnbound** [comment]
@stacimc I'm going to reopen this issue until we've stabilized the alarm, per @obulat's similar note here: https://github.com/WordPress/openverse/issues/2505#issuecomment-1725017023
