### ISSUE TITLE
Documentation is not emitted on PRs if playwright tests are skipped

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse#2511]
## Description

Presently, it appears that the documentation preview does not get emitted if the playwright tests are skipped. This can be seen in PR #2330, specifically: https://github.com/WordPress/openverse/actions/runs/5418121499

If the playwright tests can be skipped, the logic should be adjusted to emit the docs nonetheless if there are documentation changes in the PR.

**Comment by dhruvkb** [comment]
Playwright tests skipped: 
- https://github.com/WordPress/openverse/actions/runs/5823248156/job/15789842621?pr=2812#step:2:1
- https://github.com/WordPress/openverse/actions/runs/5823248156/job/15789842927?pr=2812#step:2:1
- https://github.com/WordPress/openverse/actions/runs/5823248156/job/15789843256?pr=2812#step:2:1

Docs artifact built:
https://github.com/WordPress/openverse/actions/runs/5823248156/job/15789838160?pr=2812#step:5:40

Docks published:
https://github.com/WordPress/openverse/pull/2812#issuecomment-1673502197
