### ISSUE TITLE
Remove unused `composables/use-browser-detection`

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse#2535]
## Problem

`composables/use-browser-detection` is unused but still exists in our code.

## Description

Remove the `composables/use-browser-detection` file and the useless Jest mock in `v-audio-track.spec.js` against it.

**Comment by AlimurtuzaCodes** [comment]
Assign it to me I can fix this.

**Comment by AlimurtuzaCodes** [comment]
Done PR #2634 .
