### ISSUE TITLE
Watch for changes on `en.json5` and copy to `en.json` in `dev`

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse#2536]
## Problem

When running the frontend's `dev` script, if you make changes to `en.json5`, you need to run `i18n:en` to get the changes copied over to where Nuxt can see them.

## Description

We can fix this by using `run-p` to run both the dev build and `i18n:en --watch` at the same time. That way changes to `en.json` get reflected during `dev`.

## Additional context

Self-assigned because I've already implemented this in a relatively simple PR for something I'm working on locally so I'll include it there.

**Comment by zackkrida** [comment]
Nice idea!
