### ISSUE TITLE
Add a page explaining the sensitive content filtering approaches

### ISSUE THREAD

**Issue by dhruvkb** [WordPress/openverse#2550]
## Problem

The content safety wall #2462 shows [different text based on different values](https://github.com/WordPress/openverse/issues/791#issuecomment-1484245797) of the `sensitivity` field provided by the API #2549.

## Description

These differences in text can be subtle and may not immediately make clear to the user why a particular media has been flagged as sensitive. It would be helpful to have a page explaining the different factors considering when flagging a media item.

Essentially it would be mapping of keys in the `sensitivity` field in the API response to explanatory text that can be linked to from the content safety wall if the user needs more information about our process.

**Comment by sarayourfriend** [comment]
Here is my early draft of this text: https://docs.google.com/document/d/1gZ8blFT96cMyMomHuPUS-_LqK9v9GRCChG0Y9b6-EBQ/edit?usp=sharing

Please note that this is a VERY rough draft and is in no way a concrete representation of the final form of this documentation. Please share feedback here. I've added individual maintainers as editors to the document.

**Comment by dhruvkb** [comment]
@sarayourfriend should we mark this as blocked because we are awaiting input from another team for the final text?

**Comment by sarayourfriend** [comment]
Yes, good call.

**Comment by AetherUnbound** [comment]
I believe we've got confirmation on the wording and can move ahead with converting this into a page on our frontend!
