### ISSUE TITLE
Enable `playwright/expect-expect` once the plugin supports extending the assert function names

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse#2571]
## Problem

`eslint-plugin-playwright` does not have the ability to modify the list of accepted assert function names: https://github.com/playwright-community/eslint-plugin-playwright/issues/154

Because we make heavy use of reusable assertion functions, especially in visual regression tests, this particular rule is temporarily disabled (once #2312 is resolved).

## Description

After the issue in the plugin is resolved, upgrade the plugin and enable the expect-expect rule.

**Comment by gilmeir-arnac** [comment]
+1 for customized assertion function names, that's exactly what I was looking for 🙏
