### ISSUE TITLE
"e2e/search-query-server.spec.ts:94:9 › search query on SSR › url mature query is set, and can be unchecked using the Safer Browsing popup" is skipped

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse#2572]
## Problem

"e2e/search-query-server.spec.ts:94:9 › search query on SSR › url mature query is set, and can be unchecked using the Safer Browsing popup" is skipped without any explanation or associated issue that I can find. When I unskip the test it does not pass locally.

## Description

Figure out why the test does not pass. If the test is a good test to have, fix it. Otherwise, if the test is not necessary, delete it from the test suite.

## Additional context

I've marked this critical as per our flaky test guidelines but because it's already been skipped for a long time, it doesn't exactly fall into the same category. But someone did write the test for a reason, so presumably it's a good one to have. It also only fails for two breakpoints rather than all of them, so the behaviour is verifiable in _some_ conditions. Perhaps it just needs to be wrapped in a conditional based on the breakpoint being tested and excluded from the suite for certain breakpoints.

**Comment by obulat** [comment]
This test was skipped after we removed the "Safer Browsing" popup. Currently, there is no way of setting mature preferences in the UI. We could either remove the test entirely, or wait until we implement the Sensitive content blurring and update the test then.

**Comment by dhruvkb** [comment]
I'm in favour of updating the test and un-skipping it after the frontend content safety project as that would be a much clearer transition of "skipped with defunct UI" to "working with new UI". But deleting the test is also a valid option that's more consistent with our current policy of all test in our suite should be working ones.

**Comment by sarayourfriend** [comment]
Removing it under the assumption that new tests that are conscious of the specific implementation and behavioural details of the new feature will be added alongside those new features sounds best to me. If we want this specific test back for some reason, we can restore it from version control. There's no reason to keep it in the code if the test and its implementation are for a feature that doesn't exist anymore and if the new feature would require whole new tests anyway.

**Comment by obulat** [comment]
> Does playwright support a `test.todo` or similar method? That might be the best fit here

I think `fixme` is the closest to `todo`: https://playwright.dev/docs/api/class-test#test-fixme-1

**Comment by obulat** [comment]
Lowered the priority of this issue since it is not really about a flaky test.
