### ISSUE TITLE
Custom ESLint plugin to allow skipped unit tests only if there is a comment attached to the test with a GitHub issue link

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse#2573]
## Problem

`eslint-plugin-jest` and `eslint-plugin-playwright` disallow disabled tests. However, we use disabled tests as part of our flaky test workflow. In that case, we require a comment is added to the test. In these cases, we are required to add the issue comment _and_ add an `eslint-disable-next-line` pragma to silence the ESLint rule disallowing disabled tests.

## Description

It would be nice to have a smarter version of the `no-disabled-test` rule that checks whether a comment immediately precedes the skipped test with an issue comment link and only raises an error if none exists.

Once this rule exists, disable the `no-disabled-test` rules from the playwright and jest plugins.

## Additional context

I thought I had worked on something like this for another project in the past but I cannot remember where any more nor find any plugins that do this for you already. We'd have to write the rule from scratch. This is possible without much fuss now that #2482 is merged.

**Comment by chenikabukes** [comment]
Hi I'd like to work on this!

**Comment by sarayourfriend** [comment]
Thanks for the interest @chenikabukes. Do you have experience writing ESLint rules before? This task, while open to community contributors, is likely to be a significant and complex undertaking. You're welcome to work on it regardless, but just letting you know that this one will probably take a bit more independent research into ESLint rule development and the various jest and playwright test skip utilities.

I've assigned it to you in the meantime, but if you decide the issue is too much for the moment, just let me know. Happy to help you find an alternative issue to work on, if you'd like :slightly_smiling_face:

**Comment by chenikabukes** [comment]
Hi @sarayourfriend, I've worked on ESLinting this summer during my internship so should be all good, but I will let you know asap if I have any questions :)

**Comment by sarayourfriend** [comment]
Awesome! Looking forward to seeing the PR :tada:

**Comment by chenikabukes** [comment]
PR for review: https://github.com/WordPress/openverse/pull/2660

**Comment by sarayourfriend** [comment]
> while testing and running the linter I have spotted listing issues already existing in the project regarding incorrect imports in 16 files. Must I address this or make the PR including them?

Please open an issue for these. They shouldn't exist, but I suspect an environment issue. Our CI prevents merging code with linting errors.
