### ISSUE TITLE
Changes to Docker Compose should trigger a full CI + CD run

### ISSUE THREAD

**Issue by dhruvkb** [WordPress/openverse#2575]
## Description

We use filters to determine which jobs to run for each PR, this helps keep the CI + CD workflow fast and prevents unnecessary jobs from running. These filters are in the https://github.com/WordPress/openverse/blob/9a1bf60c02a92f63224cd43f2644bda2219e3b63/.github/filters.yml file.

## Problem

Since the `docker-compose.yml` file is not included in any of the filters, when changes are made to it, most jobs are skipped or bypassed. This reduces confidence in the validity of the changes.

## Reproduction

See job run https://github.com/WordPress/openverse/actions/runs/5468016976/jobs/9955141021 on PR #2568.

**Comment by YashGaur000** [comment]
Hey @dhruvkb , I would like to work on issue #2575. Can you assign me this issue?
Also, can you explain a lil about what needs to be done here, is a file named docker-compose.yml needed to be added in workflows or in filters?
Please brief me a lil.

**Comment by dhruvkb** [comment]
@YashGaur000 the `docker-compose.yml` file needs to be added in the `.github/filters.yml` file under the keys `catalog`, `api`, `ingestion_server` and `analytics` keys. This would indicate to our CI + CD workflow that any change to the Docker Compose file means that these stacks have changed and their tests need to be executed.

**Comment by YashGaur000** [comment]
fixes #2575

> ## Description
> We use filters to determine which jobs to run for each PR, this helps keep the CI + CD workflow fast and prevents unnecessary jobs from running. These filters are in the https://github.com/WordPress/openverse/blob/9a1bf60c02a92f63224cd43f2644bda2219e3b63/.github/filters.yml file.
> 
> ## Problem
> Since the `docker-compose.yml` file is not included in any of the filters, when changes are made to it, most jobs are skipped or bypassed. This reduces confidence in the validity of the changes.
> 
> ## Reproduction
> See job run https://github.com/WordPress/openverse/actions/runs/5468016976/jobs/9955141021 on PR #2568.
