### ISSUE TITLE
Cleanup tag display with long lists of tags

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse#2589]
## Problem

Some images, particularly from platforms like Flickr, have many many tags. The display of these tags is distracting, particularly on mobile:

An example: https://openverse.org/image/7e138814-e774-45fb-91ee-7b728c174616?q=Titmouse

<img src="https://github.com/WordPress/openverse/assets/6351754/a52a297b-fd43-4212-a50e-214dbba346bb" width="300" alt="Single result page screenshot">

## Description

Truncate the tags list to a fixed number of rows. We can do this hackily in CSS with `height` or some other method. Use additional styling to indicate the list is expansible.

**Comment by fcoveram** [comment]
Great finding. Thanks for the ticket ✨ 

Here is an idea that can be implemented in line with #410, and that can be found in #2113's [design file](https://www.figma.com/file/niWnCgB7K0Y4e4mgxMrnRC/Additional-search-views?type=design&node-id=22%3A13656&mode=dev) 

<img width="700" alt="Two mokcups of image details page. Tag area collapsed in the left, tag area expanded in the right" src="https://github.com/WordPress/openverse/assets/895819/83fca6ff-0397-4061-89bd-d9a696d52433">

**Comment by AetherUnbound** [comment]
This is great! As I look at those screenshots you shared, it can be a little tough initially to tell that the "Show all tags" element is something that can be interacted with. Is that consistent with the way similar elements are displayed in the rest of our app? Is there a way to make it seem a bit more like a button/interactive element? Please disregard if this fits other paradigms I'm unaware of 😄

**Comment by zackkrida** [comment]
It looks very nice! Development-wise anything we do for this issue might be deceptively challenging. We'll have to make sure it's accessible and crucially decide _what_ type of component we think this is. Perhaps an "accordian" is the closest-related pattern.

**Comment by fcoveram** [comment]
> it can be a little tough initially to tell that the "Show all tags" element is something that can be interacted with. Is that consistent with the way similar elements are displayed in the rest of our app? Is there a way to make it seem a bit more like a button/interactive element?

The button size is consistent with other buttons toggling similar actions. I tried a different style that might work well on small breakpoints, but it becomes too wide on `md` and beyond. Here is an example


<img width="2013" alt="Image details page on mobile and desktop where tag area is highlighted" src="https://github.com/WordPress/openverse/assets/895819/b14b1a38-8096-4edb-8def-f0dcc6a9a787">

### First release

As writing this comment, I think we can go with full-width for `xs / sm` and width auto for `md` and beyond.

**Comment by krysal** [comment]
I like more the version of just bold text plus the caret. The button calls more interaction but it doesn't seem so necessary for this case.

**Comment by fcoveram** [comment]
I asked for feedback on the accessibility channel and received the following [response](https://wordpress.slack.com/archives/C02RP4X03/p1692358499352209?thread_ts=1692346772.989029&cid=C02RP4X03) from `nickthegeek`:

> This is a good design pattern as long as it’s implemented accessibly. Here are a few things to remember:
> * Use a button for the toggle
> * Use aria-controls and aria-expanded on the toggle
> * Use aria-hidden on the hidden section
> * I’d personally use the aria-hidden to show/hide. ie `[aria-hidden="true"] { display: none; }`. It’s not an a11y requirement but I find devs get the toggles right when they visibly see then doing their thing
> * When the content is hidden use either display or visibility to hide the content. These do not animate on transition but you can use visibility then opacity, height, etc which do animate. The reason display and visibility are important is if a user is using a keyboard to navigate they could still access all of the tags but not see them.
