### ISSUE TITLE
Extra White-Space in responsive mode while scrolling

### ISSUE THREAD

**Issue by nayanchamp7** [WordPress/openverse#2596]
## Description
In Mobile responsive mode, there are extra whitespace after the Footer section while scrolling down. The issue is when we search for an image with a name. After the search result appear we see it.

## Reproduction

Provide detailed steps to reproduce the bug.
1. Go to https://openverse.org
2. Go to Responsive mobile device mode
3. In the search bar, search with a name, (eg: nature)
4. Go down with scrolling,
5. After the footer section, you should see an extra whitespace there.

## Screenshots

![nature-Openverse](https://github.com/WordPress/openverse/assets/43903460/f848bec4-91b3-4190-a361-861be1f7c149)

[Video Link] (https://drive.google.com/file/d/1nN7UdXsYI9kDurTxR_wMQf9Y0VIbjjVs/view?usp=sharing)

## Environment

Tested environment setup information below.

- Device: Mac
- OS: Monterey
- Browser: Chrome

**Comment by obulat** [comment]
Thank you for reporting this issue, @nayanchamp7!

**Comment by dhruvkb** [comment]
This is not limited to mobile though. It's possible to replicate the bug in Chromium on macOS.

<img width="1840" alt="image" src="https://github.com/WordPress/openverse/assets/16580576/5a93c1d2-243e-452e-9c05-d861bda406e0">

**Comment by zackkrida** [comment]
Ensuring the `body` and `html` elements are `100vh` and have vertical overflow hidden fixes this, but may have other implications. I wish we knew when this regression was introduced so we could identify what is causing it. Very puzzling.

**Comment by dhruvkb** [comment]
I was testing a hypothesis and it turns out that the space at the bottom is how much the search results would take if they weren't scrolling.
For example, if you delete a bunch of results from the DOM such that all the content would fit in the viewport without scrolling, the white space disappears.

**Comment by dhruvkb** [comment]
No solution yet but this bug is very interesting! After lots and lots of experimentation I found that this bug disappears when the footer is removed from the main cell of the grid, i.e. dropping lines 45 to 48.

https://github.com/WordPress/openverse/blob/74b90b593bbb45d61ad2e27507494d3b8dd78837/frontend/src/layouts/search-layout.vue#L45-L48
