### ISSUE TITLE
Auckland Museum

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse#2598]
### Source Site

https://www.aucklandmuseum.com/discover/collections/our-data

### Value Provided

High quality collections and data

### Licenses Provided

Not everything is openly licensed but some things are PDM or CC: https://www.aucklandmuseum.com/legal/rights-and-permissions

### Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by obulat** [comment]
Closing as duplicate of #1771. Thank you for noticing, @ngken0995!
