### ISSUE TITLE
Sync CONTRIBUTING.md across all public Openverse repositories

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse#260]
## Problem

Each Openverse repository currently has a slightly different CONTRIBUTING.md file. These can potentially be smushed into a single file that gets synced from this repository to the others similar to our other synced files.

Reported by @zackkrida 

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by obulat** [comment]
Can this now be closed, @zackkrida? I don't think it makes sense to sync now: all /openverse CONTRIBUTING have been unified. The catalog is planned to be merged in, and it already has a pretty good CONTRIBUTING doc anyways.

**Comment by dhruvkb** [comment]
@obulat  actually this isn't done. The `CONTRIBUTING.md` files are still present in the subfolders under `meta_docs/`.

I've already started the implementation of this and will have a PR up today.

**Comment by AetherUnbound** [comment]
I _think_ we can close this in favor of #2008 (and particularly now that all our public repos are in the monorepo)!
