### ISSUE TITLE
New styles in Audio control component

### ISSUE THREAD

**Issue by fcoveram** [WordPress/openverse#2602]
## Description

As part of design changes introduced in #2113, the [Audio control](https://www.figma.com/file/GIIQ4sDbaToCfFQyKMvzr8/Openverse-Design-Library?type=design&node-id=5215-31484&mode=dev) component in Design Library has new styles.

<img src="https://github.com/WordPress/openverse/assets/895819/c9a374ed-935e-4c19-bb2b-ab4783dfb926" width="650" alt="New audio control component with its variants and descriptive texts">

* `Small` size is removed due to its lack of use.
* `Tiny` is renamed as `Small`.
* `Extra large` is renamed as `Large`.
* New sizes for each variant
   * Small: 32px, `w-8` `h-8`
   * Medium: 48px, `w-12` `h-12`
   * Large: 64px, `w-16` `h-16`
* New icon sizes for each variant
   * Small: 24px, `w-6` `h-6`
   * Medium: 32px, `w-8` `h-8`
   * Large: 40px, `w-10` `h-10`
* Hover and Focus styles follow the Button style
* Default style has `2px` for border radius, although this changes depending on the component context.

## Context

The new styles are based on #415 implementation

## Figma

[Component](https://www.figma.com/file/GIIQ4sDbaToCfFQyKMvzr8/Openverse-Design-Library?type=design&node-id=5215-31484&mode=dev) in Design Library.

**Comment by obulat** [comment]
This issue is blocked because the design for single result page for Audio also needs to be updated to match the new Audio control component sizes.

**Comment by obulat** [comment]
Sorry, @fcoveram! I was wrong. Your list of what needs to be updated is right:

> What I understood from the chat we had https://github.com/obulat, is that this request creates unintended changes in the following components:
> 
>     Row (large, medium, and small)
>     Box (large, and medium)
>     Global
