### ISSUE TITLE
ESLint editor integrations fail if `@openverse/eslint-plugin` isn't built

### ISSUE THREAD

**Issue by dhruvkb** [WordPress/openverse#2616]
## Description

ESLint editor integrations will fail if `@openverse/eslint-plugin` isn't built. The plugin is built when the `eslint` script is run, but editors run ESLint on their own, not using the script, so the config will fail to parse correctly due to the Openverse plugin not having available code.

# Resolution

Add a `postinstall` script to the root package.json that builds all packages:

```json
{
  "scripts": {
    "postinstall": "pnpm --filter ./packages/* run build"
  }
}
```

## Additional context

- Reported: https://github.com/WordPress/openverse/pull/2601#issuecomment-1630714233
- Known fix: https://github.com/WordPress/openverse/pull/2601#issuecomment-1631030574

## Alternatives

An alternative to this that does not rely on pre/post scripts (which pnpm doesn't _want_ to run, but reluctantly does if you configure it to, which we only do now because of some dependencies that need it) is for us to export our own `eslint` binary from a new package `@openverse/eslint-bin` that correctly filters the list of folders, etc, that are evaluated (which editors currently do not have information about). Basically, transform the root package.json `eslint` script into _the_ ESLint binary that editors would use for our project.

This only works for editors that will use local ESLint binaries rather than globally installed ones or ones installed by the editor plugin. It's also potentially way more complex than just use a `postinstall` script, which, while not ideal, is still a standard Node project lifecycle feature.

**Comment by Dev-Arhaan** [comment]
Hey there, what is to be done in this issue to resolve it? ca n I be assigned to it?

**Comment by AetherUnbound** [comment]
It has not, I'll assign it to you!

**Comment by Dev-Arhaan** [comment]
Yeah I get it, the confusion is, should this block be added before `step 4` or `step 3`

**Comment by dhruvkb** [comment]
@Dev-Arhaan this step will be inserted between step numbers 3 (Node dependencies install) and 4 (dev server start) in the [frontend quickstart guide](https://docs.openverse.org/frontend/guides/quickstart.html) (making it the new step number 4).

**Comment by YashGaur000** [comment]
Fixes #2616 by @YashGaur000 

Added the "$ pnpm --filter='@openverse/eslint-plugin' build" command at right place in quickstart.md.
Also, added a few words which says " build it using second command " .

Please, review it ASAP, I'll be eagerly waiting from your side.

**Comment by Dev-Arhaan** [comment]
Hi there, I Added `$ pnpm --filter='@openverse/eslint-plugin' build` command at right place in quickstart.md. As stated by @dhruvkb please review it and guide me on how to do a better job at it @AetherUnbound

**Comment by Dev-Arhaan** [comment]
My pr is failing ci/cd because of label selection, can you guide me on how to add labels to my pr?

**Comment by AetherUnbound** [comment]
> My pr is failing ci/cd because of label selection, can you guide me on how to add labels to my pr?

Those fail initially until our automation kicks in - they look good now!

**Comment by zackkrida** [comment]
Since building the package takes ~300ms locally, I wonder if we should just do so as part of the dev server to prevent this issue and avoid manual action from contributors. Similarly to what we do for translations.

**Comment by dhruvkb** [comment]
The `postinstall` script was added in #2973. This ensures that our ESLint plugin is built by running the `install` (or `node-install`) recipe. 

```console
$ just install # or: just node-install
```

Additionally, the instruction to run the `install` script is documented in both the general and the specific quickstart guides so this issue can be closed.
