### ISSUE TITLE
`mature` -> `sensitive` copy changes for the frontend

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse#2623]
## Description

Change copy references of the term "mature" to "sensitive". This work is described in the implementation plan here: https://docs.openverse.org/projects/proposals/trust_and_safety/content_report_moderation/20230517-implementation_plan_mature_copy_change.html#id2

## Additional context

Part of #383

**Comment by sarayourfriend** [comment]
I'm going to roll the changes for https://github.com/WordPress/openverse/issues/2624 and this issue into the same PR. After doing the copy changes, the code changes are so small, it doesn't make sense to separate them

**Comment by dhruvkb** [comment]
Noting that this is now a pre-cursor to the rollout of #377.
