### ISSUE TITLE
Remove ESLint webpack plugin

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse#2633]
## Problem

The ESLint webpack plugin prevents you from using the application if _any_ ESLint errors exist, including ones that are quite common when debugging code (like unused variables or imports). This makes quick debugging tedious because you inevitably forget that this is the case and have to then go make an additional change (which you'll then need to also set back) to resolve the error and then wait for the app to recompile.

## Description

Remove this plugin from the Nuxt/Webpack configuration.

## Additional context

IIRC we discussed this before in the old repository but I couldn't find the issue. I don't remember what the end of that discussion was.

Does anyone _like_ this plugin? pre-commit and CI catch anything anyway, I struggle to find what the utility of this plugin is for our project :thinking:

**Comment by obulat** [comment]
> The ESLint webpack plugin prevents you from using the application if _any_ ESLint errors exist, including ones that are quite common when debugging code (like unused variables or imports). This makes quick debugging tedious because you inevitably forget that this is the case and have to then go make an additional change (which you'll then need to also set back) to resolve the error and then wait for the app to recompile.

I have wondered what the eslint module is used for several times, but hadn't looked into it. And have run into the debugging problems you describe countless times. I am 10000000 for removing it 😆 Thank you for opening the issue!
