### ISSUE TITLE
Reference frontend documentation directly rather than describing basic repository structure in Handbook

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse#264]
## Description

> The 'basic repository structure' is too basic, and probably better to reference some documentation internal to the repo instead

Originally reported by @zackkrida

This information is sure to go out of date with any restructuring as well, best to have it point to documentation that exists alongside the code so it's updated accordingly. 

Link: https://make.wordpress.org/openverse/handbook/openverse-frontend/#basic-repository-structure

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by sarayourfriend** [comment]
I've removed the page from the handbook entirely and added a reference to the docs website on the handbook welcome page.
