### ISSUE TITLE
Django request ID logging not working

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse#2656]
## Description

Example production API log:

```
[2023-07-16 05:07:33,929 - elasticsearch - 288][WARNING] [none] POST http://<redacted Elasticsearch URL>/image/_search [status:N/A request:10.012s]
```

Note the `[none]` between the log level and `POST`. The request ID should be in that space.

## Environment

Observed in production logs

## Additional context

Marked high because it makes production request lifecycle debugging impossible

**Comment by dhruvkb** [comment]
I think this is a duplicate of #2638.

**Comment by sarayourfriend** [comment]
Thanks, I should have searched!
