### ISSUE TITLE
Update "Back to results" and "Report this content" buttons

### ISSUE THREAD

**Issue by fcoveram** [WordPress/openverse#2657]
## Description

As part of the design ideas approved for #377 and #410 projects, "Back to results" and "Report this content" buttons need to update their style to catch the last changes.

### Back to results

Since the show/hide button (#2462 #2463) is `size: small`, "Back to results" needs to reflect the same size. The area where both buttons are placed also changes to match the spacing in all breakpoints.

* "Back to results" button, in all breakpoints
   * Style: Transparent, icon left
   * Size: Small
   * Color: Gray
* Buttons area
   * in `xs, sm`: left, right and bottom padding of `16px (4)`
   * in `md` and beyond: left and right padding of `32px (8)` and padding bottom of `16px (4)`

| `xs`, `sm` | `md` and beyond |
|:---|:---|
|<img width="1240" alt="Back to results area in XS breakpoint with frontend notes" src="https://github.com/WordPress/openverse/assets/895819/bc7c3841-b112-49a3-b451-30b2a546f0e8">|<img width="2097" alt="Back to results area in XL breakpoint with frontend notes" src="https://github.com/WordPress/openverse/assets/895819/1a6caff6-9c8e-4f08-a365-d43231b57be9">|

### Report content

Designs for #410 displays all buttons in `size: small`. Because of that, this button needs to have the following.

* "Report" button, in all breakpoints
   * Style: Transparent, icon right
   * Size: Small
   * Color: Gray

| `xs`, `sm` | `md` and beyond |
|:---|:---|
| <img width="994" alt="Report button in XS breakpoint with frontend notes" src="https://github.com/WordPress/openverse/assets/895819/67de5bd1-7ba7-4c93-bd28-05272bbac113"> | <img width="1175" alt="Report button in XL breakpoint with frontend notes" src="https://github.com/WordPress/openverse/assets/895819/d0db66be-ac6f-4bff-8438-431dc7e7b756"> |

## Design

Mockups for both changes can be found in #410's [design file](https://www.figma.com/file/niWnCgB7K0Y4e4mgxMrnRC/Additional-search-views?node-id=22%3A13656&mode=dev), in their respective area.

## Additional context
Projects related:
* #410 
* #377

**Comment by zackkrida** [comment]
Hi @nevvada! I can assign you to this issue. Some resources to help you:

- Our [frontend quickstart guide](https://docs.openverse.org/frontend/guides/quickstart.html)
- The single result components where these buttons live:
	- https://github.com/WordPress/openverse/blob/main/frontend/src/pages/audio/_id/index.vue
	- https://github.com/WordPress/openverse/blob/main/frontend/src/pages/image/_id/index.vue

Keep in mind, you can always connect with Openverse contributors in the #openverse channel of the [Make WordPress Chat](make.wordpress.org/chat). Thanks 😄

**Comment by nevvada** [comment]
hi @fcoveram, can you clarify something that popped up? it looks like the "Back to results" and "Report content" buttons already have styles that match the Figma. currently both buttons have the `transparent-gray` variant (giving it a dark charcoal font color) matching the designs, as well as a `label-bold` class (making them a small font size).

e.g. [this](https://github.com/WordPress/openverse/blob/ea17972522d59a56dec2f08e8a2fa68230992dcc/frontend/src/components/VBackToSearchResultsLink.vue#L7-L9) is the back to search results button and its corresponding font size:

![image](https://github.com/WordPress/openverse/assets/44593294/40a0f8c0-df5b-4752-a522-681cee4e7c62)


the button icons are also left and right respectively, matching the designs. it does however look like we'll need to still make changes to the buttons area padding, so i can open up a PR for that

**Comment by fcoveram** [comment]
Hi @nevvada 

You're correct, both buttons have `transparent-gray`, `label-bold` for text, and the icon position correctly. But they need to change their `size` values to be `small` and the padding values where they're placed also need to change.
