### ISSUE TITLE
New Metasearch button

### ISSUE THREAD

**Issue by fcoveram** [WordPress/openverse#2668]
## Description

As part of the design changes in #460, we need to add the metasearch button that triggers a popover in a modal. The component has two sizes and follows the breakpoint changes of "Load more" button.

![image](https://github.com/WordPress/openverse/assets/895819/6170bb39-a1f7-4a3f-b968-8bfce557e8a7)

## References
* [Figma component](https://www.figma.com/file/GIIQ4sDbaToCfFQyKMvzr8/Openverse-Design-Library?type=design&node-id=5327-30212&mode=dev) in Design Library.

**Comment by chenikabukes** [comment]
Hi @fcoveram I'd like to work on this! :)

**Comment by zackkrida** [comment]
Hi @chenikabukes! I'll assign you to this issue. Some resources to help you:

- Our [frontend quickstart guide](https://docs.openverse.org/frontend/guides/quickstart.html)
- The [VLoadMore Button](https://github.com/WordPress/openverse/blob/main/frontend/src/components/VLoadMore.vue) as a similar component implementation

And always, you can connect with Openverse contributors in the #openverse channel of the [Make WordPress Chat](make.wordpress.org/chat). Thanks!
