### ISSUE TITLE
Hidden header as scrolling down

### ISSUE THREAD

**Issue by fcoveram** [WordPress/openverse#2683]
## Description

Once landing in the search results, I can scroll down in the header area to hide it and reveal a white space below the footer. The bug makes openverse look like inserted as an iframe.

**Edit:** Updated in the comments below:

> I no longer see the bug in MacOS. In iOS, is now only visible on Safari.

## Reproduction

1. Go to openverse.org 
2. Search something and land on the search results
3. Scroll down within the header area
4. See the error.

### Safari on iOS
https://github.com/WordPress/openverse/assets/895819/18ce9071-a13a-4ab5-82fd-7d9545a4450f

### Safar on MacOS
https://github.com/WordPress/openverse/assets/895819/58fc5e34-92ad-4ba8-90b3-5e48bdbf6cdb

## Environment

- Device: iPhone 12 pro and Macbook pro M1 14-inch 
- OS: iOS 16.5.1 and Macos Ventura 13.4.1
- Browser:
   - in iOS: Safari and Firefox
   - in Macbook: Safari and Chrome in all breakpoints. In Firefox the bug is not visible 

## Additional context

I think it relates to #2596

**Comment by zackkrida** [comment]
Fixed as part of #2596, which is deploying to production now.

**Comment by fcoveram** [comment]
I no longer see the bug in MacOS. In iOS, is now only visible on Safari.


https://github.com/WordPress/openverse/assets/895819/f807cd4b-d534-4f36-82b3-327d108a829b

Once landing in the search results, I don't see the header and need to scroll up from the screen's far side until it shows up. Then header and results area tend to move together, notice how two scroll bars overlap each other.

**Comment by dhruvkb** [comment]
This is not reproducible on the iOS simulator, severely limiting our approaches on how to debug and resolve this.
