### ISSUE TITLE
Move data refresh complete Slack message from ingestion server to catalog

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse#2688]
## Description

Presently, the `delete_index` function in the ingestion server always sends a Slack alert denoting that a data refresh is complete:

https://github.com/WordPress/openverse/blob/6f2e34dec943400c216cc161627d93301be02563/ingestion_server/ingestion_server/indexer.py#L452

Since we now have index deletion steps in both the primary data refresh DAG and secondary filtered index creation DAG, we end up receiving this message twice (once for each DAG).

We should instead change this message so it only notifies about the index deletion. We can then modify the record count reporting step to include a note that the data refresh is complete.

## Implementation steps

First, the message linked above will need to be changed merely to 

```python
f"Index `{target}` was deleted"
```

Then, modify the `report_record_difference` function's message to include `Data refresh for {media_type} complete! :tada:` at the beginning:

https://github.com/WordPress/openverse/blob/6f2e34dec943400c216cc161627d93301be02563/catalog/dags/data_refresh/reporting.py#L20-L37

**Comment by YashGaur000** [comment]
hey @AetherUnbound Please assign me this issue, I would like to work on it.
