### ISSUE TITLE
Tall images get poorly cropped and their license icons are hidden

### ISSUE THREAD

**Issue by dhruvkb** [WordPress/openverse#2712]
## Description

If an image in the related results in the single result page is sufficiently tall, it will be cropped quite poorly and the license icons get positioned outside the bounds so as to be hidden.

## Reproduction

1. Visit this single result: https://openverse.org/image/61f31a70-5484-4233-95ab-9298e78ebee8

![Minette and Minet | Openverse](https://github.com/WordPress/openverse/assets/16580576/a5b5ede8-256b-40a5-8ec5-9e7cf6cb7510)

2. Scroll down to related images.
3. See the first thumbnail (for this single result: https://openverse.org/image/5de92826-07e8-4a42-b627-831bed30010a). The thumbnail is cropped into a small part of the original image in such a way that it is impossible to know what it actually is.

![image](https://github.com/WordPress/openverse/assets/16580576/0c866a2d-d298-4593-baff-8a1050368c4f)

4. Hover over this result. See that the license icons are not visible (as they are outside the bounds of the thumbnail box).

**Comment by obulat** [comment]
#2891 fixes the issue with the tall image's license icons being hidden:
<img width="958" alt="Screenshot 2023-09-11 at 3 02 36 PM" src="https://github.com/WordPress/openverse/assets/15233243/2366b6ce-eaf5-4835-a6d0-16a52edd3d43">

The image is, however, cropped to be contained within the tallest aspect ratio possible, and it is centered vertically. So, it's still not easy to see what this image contains. I don't think we can crop the images correctly, though, without some form of heuristics or machine learning. @dhruvkb, do you think we can consider that cropping tall images like this is enough, and close this issue?
