### ISSUE TITLE
"visual-regression/v-header-internal.spec.ts:35:11 › VHeaderInternal › screen at breakpoint xs with width 340 › mobile-header-internal-modal-ltr" is flaky again

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse#2720]
This test has been flaky before in #2473. This time it appears to be the text of the menu items causing an issue. 

Recent example runs:

- https://github.com/WordPress/openverse/actions/runs/5663119572/job/15344364179#step:4:600
- https://github.com/WordPress/openverse/actions/runs/5661274857/job/15338907435

And the diff provided:

<table>
<tr>
 <td>Actual
 <td>Diff
 <td>Expected
<tr>
<tr>
 <td> <img src="https://github.com/WordPress/openverse/assets/6351754/6c8ddf29-1ece-491b-a179-7aaae91d6b4c">
 <td> <img src="https://github.com/WordPress/openverse/assets/6351754/952e97b7-5f3d-42f0-8501-5959e2e3111b">
 <td> 
<img src="https://github.com/WordPress/openverse/assets/6351754/554b588b-41a1-43b3-98c1-5b7387f19d2d">
</table>

**Comment by obulat** [comment]
We should probably add a longer wait to make sure that the fonts finish rendering before taking the snapshot.
