### ISSUE TITLE
Audio instructions snackbar is not hidden when you navigate from All results to single result page

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse#2742]
## Reproduction

1. Go to https://openverse.org/search/?q=cat
2. Navigate to the first audio result by pressing <kbd>Tab</kbd>. The snackbar should appear.
3. Press Enter to navigate to the single result page.
4. See error: the snackbar is still visible in the corner

## Screenshots

<img width="890" alt="Screenshot 2023-07-29 at 11 55 20 AM" src="https://github.com/WordPress/openverse/assets/15233243/7782089d-f9aa-4844-ad3a-ba43c52bb8d9">

## Environment

Production site, desktop with a keyboard.

## Additional details
I noticed this bug when the Audio single result page visual regression tests failed on #2735

**Comment by zackkrida** [comment]
This also shows up on mobile, where reference to the spacebar isn't relevant
