### ISSUE TITLE
Guard against PR pings when a PR has two reviews

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse#275]
We might want to skip PRs that have two approving reviews from the PR review pings.

**Comment by sarayourfriend** [comment]
We could probably also ping `openverse-maintainers` instead of the PR author when the author is not a collaborator on the repository? It seems odd that we would ping someone to reassign reviewers if they're potentially not even familiar with the group of people working on the project yet.

**Comment by zackkrida** [comment]
Yeah in this particular instance none of the pings were very relevant https://github.com/WordPress/openverse-api/pull/788#issuecomment-1183794454

**Comment by sarayourfriend** [comment]
Done in 54aee38bc94b48143033887f0e4819648cf521a5
