### ISSUE TITLE
Omit issues with closed PRs of moving to the "In Progress" column in the project board

### ISSUE THREAD

**Issue by krysal** [WordPress/openverse#276]
## Description

Currently, the "In Progress" column of the [Openverse project board](https://github.com/orgs/WordPress/projects/3) holds some issues that aren't actually being actively worked on, and if you move them to the "To Do" or "Backlog" columns they will be moved back as they have one or more closed PRs associated that couldn't fully solve the problem.

This can already be observed in the history of the issues. Some example:
- WordPress/openverse-frontend#631
- WordPress/openverse#154

To keep this column true to its name we want to move there only issues with open PRs.

## Reproduction

This can already be observed in the history of the issue.
1. Try moving one of says issues to the "To Do" or "Backlog" column
2. Wait some minutes and see they're returned back to the "In Progress" column when the automation executes again

## Additional context

- GitHub Action workflow: [project_automation.yml](https://github.com/WordPress/openverse/blob/main/.github/workflows/project_automation.yml)
- [Python script](https://github.com/WordPress/openverse/blob/main/automations/python/issues_with_prs.py)

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by dhruvkb** [comment]
Adding more info the ticket, the code in the Python script treats all issues that have PRs associated with them as in-progress but does not check if those PRs are actually open.

https://github.com/WordPress/openverse/blob/1d9b19c53d9d63e9e52b70c14408b2f1db4383c7/automations/python/issues_with_prs.py?rgh-link-date=2022-07-15T21%3A01%3A52Z#L66-L78

The way it's written (and the lack of GitHub API support for linked issues and PRs)  means that this issue needs significant Python familiarity.

**Comment by AetherUnbound** [comment]
Per [the documentation](https://docs.github.com/en/search-github/searching-on-github/searching-issues-and-pull-requests#search-for-linked-issues-and-pull-requests), it looks like (to reiterate what Dhruv said) that we can only get whether or not there is a linked PR, not search by its state. We might need to do some work to filter out the results after the fact & remove issues for which all linked PRs are closed.

**Comment by AetherUnbound** [comment]
This seems way, _way_ less trivial than I was initially expecting 😅 the REST API doesn't provide any mechanism for getting linked pull requests, only querying for whether or not a link exists at all 🙃 It seems we might need to switch to using the [GraphQL API](https://stackoverflow.com/questions/60717142/getting-linked-issues-and-projects-associated-with-a-pull-request-form-github-ap). Perhaps instead of searching for issues with linked PRs, maybe I can go the other way around? 🤔 But that still seems like it'd run into the issue of not containing info on the linked issue. I'll look into it.

**Comment by AetherUnbound** [comment]
Per [the explorer](https://docs.github.com/en/graphql/overview/explorer), it appears that the following query works to get all open PRs with any attached closed issues _if they exist_:

```graphql
repository(owner:"WordPress", name:"openverse") {
    pullRequests(first: 100, states:OPEN, orderBy:{field:UPDATED_AT, direction:DESC}) {    
        nodes {
            number
            title
            closingIssuesReferences (first: 50) {
                edges {
                    node {
                        number
                        title
                    }
                }
            }
        }
    }
}
```

Response:

```json
{
  "data": {
    "repository": {
      "pullRequests": {
        "nodes": [
          {
            "number": 366,
            "title": "Proposal: Openverse project process ",
            "closingIssuesReferences": {
              "edges": []
            }
          },
          {
            "number": 381,
            "title": "Very early draft: WordPress Sites as Sources Plugin initial exploration",
            "closingIssuesReferences": {
              "edges": []
            }
          },
          {
            "number": 336,
            "title": "RFC: Monorepo",
            "closingIssuesReferences": {
              "edges": [
                {
                  "node": {
                    "number": 205,
                    "title": "Write an RFC for monorepo support"
                  }
                }
              ]
            }
          },
          {
            "number": 353,
            "title": "add file to eslint exclude and prettier exclude",
            "closingIssuesReferences": {
              "edges": []
            }
          }
        ]
      }
    }
  }
}
```
