### ISSUE TITLE
Test sensitive term index against user reported sensitive media

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse#2765]
This is a little experiment I've had in my notes that I am moving here to keep track of. Basically, the idea would be to pull a list of all media which has been reported as sensitive in Openverse and see what % of it is _also_ caught by the sensitive text feature. This could give us a very rough, imperfect estimate of the efficacy of the sensitive text filter at finding sensitive media.

**Comment by zackkrida** [comment]
@sarayourfriend I am considering closing this issue on the basis of its lack of usefulness. I wanted to check for your thoughts beforehand since you've thought a far deal about the sensitive indices but also things like result caching and analysis.

**Comment by sarayourfriend** [comment]
I'm fine closing it. For it to be a useful analysis I think we'd want to know which reports were for sensitive textual content, sensitive content in the work itself (image or audio), or both. It's no big surprise if our sensitive text analysis finds works that have sensitive text, so it's more useful and interesting if it's reliably matching sensitive _works_ as well, by some correlative feature of the textual content and the work (which is a fundamental but untested assumption).

It could be interesting, but I think our sensitive text approach is useful even if it only finds sensitive text, so the outcome of this analysis wouldn't necessarily influence whether we continued using this approach, at least from my perspective. It would be a lot of work though.
