### ISSUE TITLE
Unify headers across repositories

### ISSUE THREAD

**Issue by krysal** [WordPress/openverse#277]
## Description

This repository and openverse-frontend share a nice [header](https://github.com/WordPress/openverse/blob/main/README.md) with a banner image and some useful links (to the project board, the Make blog, Slack, etc.) in its main README that will be nice to standardize to the rest.

Replicate the header in READMEs of the following repositories:
- [x] [openverse-api](https://github.com/WordPress/openverse-api/) https://github.com/WordPress/openverse-api/pull/805
- [x] [openverse-catalog](https://github.com/WordPress/openverse-catalog/) https://github.com/WordPress/openverse-catalog/pull/610

**Comment by Justinjdaniel** [comment]
Can I pick this?

**Comment by sarayourfriend** [comment]
Thank you @Justinjdaniel! Closing this issue as completed.
