### ISSUE TITLE
Create a page for tag/creator/source views

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse#2774]
## Problem

We need a new page for the Additional search views projects. We should handle the following paths:
`/pages/_mediaType/tag/_tag`
`/pages/_mediaType/source/_source`
`/pages/_mediaType/source/_source/creator/_creator` (this page might not be needed as it might be handled by the source page)
## Description

To make sure that the mediaType, source and creator parameters are valid, this page should use the [validate method](https://v2.nuxt.com/docs/components-glossary/validate/) to make sure that and show an error page if necessary.
```typescript
function validate({ params, $pinia }): boolean {
  const { collection, mediaType, term } = params
  // Check that collection is one of ["tag", "creator" or "source"],
  // and mediaType is one of `supportedMediaTypes`.
  // Check that `term` is correctly escaped.
  // If the params are not valid, return `false` to show the error page.
  return isValid ? true : false
}
```
This page should also update the state (`searchType`, `searchTerm` and `searchBy` and `provider` filters) in the search store and handle fetching using mediaStore’s `fetchMedia` method in the useFetch hook.

Since it is not possible to change the path or query parameters from this page client-side, fetching can be much simpler than on the current search page (that has to watch for changes in the route and fetch if necessary).

This page should use `VCollectionHeader` and the image grid or the audio collection.

### Dependencies
Issue is blocked on the following dependencies:
- [x] #2694
- [x] #2729 
- [x] #2858

**Comment by sarayourfriend** [comment]
See https://github.com/WordPress/openverse/pull/2734#discussion_r1299592608 for a discussion about the sub-heading complexity and potential alternative formats that avoid translation issues.
