### ISSUE TITLE
K6 based API load testing script

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse#278]
## Problem

In https://github.com/WordPress/openverse/pull/257 we introduced an overly-simplistic load testing script based on `ab`. This is insufficient to adequately load the API to simulate actual production traffic.

## Description

To replace this, let's create a set of [k6 VU scripts](https://github.com/grafana/k6) to attack the staging API.

Off the top of my head, we could have VU scripts that do the following:
1. Request a random word at page_size=20 and then request all the pages and individual documents that exist for it including requesting the related results for each. Do this for all media types.
2. Same as the first entry but with page_size=500.
3. Request each individual provider using the source query param. Paginate through the provider completely until the API returns an error about deep pagination. Do this with page_size=20 and for all media types.
4. The same as the third entry but with page_size=500.

## Alternatives

We could use an alternative load testing scripting solution like Tsung or Gatling. Tsung uses XML however and do not allow programmatic execution (scripts must be defined before hand). Gatling uses JVM (Scala, Kotlin, or Java, your pick) and has a nice programmatic API, but will require a heavier docker container set up and is more complicated. It also introduced a new language to our stack that we could avoid with k6.

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by AetherUnbound** [comment]
It seems like we might want to make use of ["Scenarios"](https://k6.io/docs/using-k6/scenarios/) in k6, which would allow us to build a function for each of the 4 cases listed above and have them run simultaneously or in parallel. I haven't done much deep diving but that seems to be a good way of separating "user flows" without having everything in one big default function.

**Comment by sarayourfriend** [comment]
Cool! That's definitely what I had in mind, that they'd be separate scenarios, not just one big unwieldy function.

**Comment by zackkrida** [comment]
Krystle's PR picked up by Madison should be ready for a first review:

https://github.com/WordPress/openverse/pull/279
