### ISSUE TITLE
Update new provider docs to use correct just commands

### ISSUE THREAD

**Issue by stacimc** [WordPress/openverse#2801]
## Description

The docs for adding a new provider reference the `just` commands that were used before moving the catalog into the monorepo. The commands should now be prefaced with `catalog` (eg `just catalog/add-provider...` instead of `just add-provider...`). [Example](https://github.com/WordPress/openverse/blob/61c7abdeaed0450558859ff949846f9a1497ad13/catalog/docs/adding_a_new_provider.md?plain=1#L62)

**Comment by vinayakhegde1** [comment]
@stacimc I would like to work on this issue

**Comment by vinayakhegde1** [comment]
@obulat please do check the PR #3319
