### ISSUE TITLE
Switch local API dev server to use `gunicorn --reload` instead of Django's `runserver`

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse#2814]
## Problem

Stems from #2566 

`runserver` does not support critical features we will need after converting the app to ASGI:

1. Actually running the ASGI app in full asynchrony
2. Multiple workers (to test production configuration)

We're also making the configuration slightly more complex by moving to ASGI, relying on gunicorn and uvicorn workers.

## Description

To anticipate these complexities and make the local development environment (a) behave more like production and (b) require fewer changes when switching to full ASGI, swap out `manage.py runserver` for `gunicorn --reload`. Once we switch to ASGI in #2790, we'll either continue using gunicorn for development (with multiple workers) or can switch to `uvicorn --reload`.

`runserver` handles static file serving locally, while `gunicorn` and `uvicorn` won't know what to do. In production we rely on nginx to handle this. We could set up Nginx locally to front the API service, but to keep this simple, it's easier to conditionally add the static route handler that `runserver` uses to the API's urls configuration. See [these changes](https://github.com/WordPress/openverse/blob/980ef96e0e16fc758f78be9f2aadf595f75948f6/api/conf/urls/__init__.py#L43-L44) as an example (which require supporting changes for the `ENVIRONMENT` variable and changes to the static file configuration generally, all present in that commit).

## Additional context

Something along these lines will be necessary for ASGI conversion anyway. Doing this as a separate issue again reduces

**Comment by ashiramin** [comment]
@sarayourfriend I'd like to take a look at this. How high of a priority is it? I don't want be a blocker

**Comment by sarayourfriend** [comment]
This won't necessarily block anything for another two weeks or so. If that works for you, let me know and I'll assign it to you :slightly_smiling_face:

**Comment by ashiramin** [comment]
I just saw this :( I'll start on it soon. Please don't assign me the ticket. I'll take a stab at it and see if I can make progress by early next week. I don't want to block anyone else from picking this up.

**Comment by sarayourfriend** [comment]
No worries, sounds good, and thanks!
