### ISSUE TITLE
New popover and popover item

### ISSUE THREAD

**Issue by fcoveram** [WordPress/openverse#2839]
## Description

As part of the design changes agreed upon in #460, we need to update the styles of **Popover** and **Popover item**.

### Popover

(description from #460)

The popover follows the [Modal](https://www.figma.com/file/e4tLacmlPuZV47l7901FEs/WordPress-Design-Library?type=design&node-id=28524-24040&mode=design&t=ZV4igMACfeHQZBv2-4) implemented in Gutenberg.

* Popover is divided into three sections to make it reusable: Header, description, and content.
* Header area has the popover title and close action.
* Close button follows [Icon](https://www.figma.com/file/GIIQ4sDbaToCfFQyKMvzr8/Openverse-Design-Library?type=design&node-id=4658-12470&mode=design&t=JzKg0h3PdFx8XQ1v-4) component in `size: small`, `style: transparent`, `color: gray`.
* The container has a border radius of `4px` in all breakpoints.
* In `XS` and `SM`, the container has a padding of `16px` and a margin of `32px`.
* In MD and beyond, the container has a padding of `24px` and a `max-width` (TBD).

You can find the popover structure in the [Design Library](https://www.figma.com/file/GIIQ4sDbaToCfFQyKMvzr8/Openverse-Design-Library?type=design&node-id=5327-30390&mode=design&t=UejtvitW7rxf1Smu-4), and the Metasearch case in its respective [design file](https://www.figma.com/file/AsD7zOnUQxuLaUBiptTYAn/Metasearch-improvement?type=design&node-id=22-13656&mode=design&t=jYPJaXJ3UNeMQvis-0).

![Popover structure in small and big size](https://github.com/WordPress/openverse/assets/895819/6a9fa169-2269-4804-b9c6-b14550a8dfde)

### Popover item

In line with the improvements made in #415, this component inherits the fixed height and has three variants for different interaction cases. In #460 designs, the variant used is `Label`.

![Popover item in three variants and three interaction states](https://github.com/WordPress/openverse/assets/895819/fae83829-24d1-46cc-aad0-57306a9c094c)

You can find the Popover item component in the [Design Library](https://www.figma.com/file/GIIQ4sDbaToCfFQyKMvzr8/Openverse-Design-Library?type=design&node-id=5327-30331&mode=design&t=UejtvitW7rxf1Smu-4). You will also see a Popover header component in the same section that is not part of #460 changes and will be requested in a different ticket.

## Additional context

Since popover item is also used in [VRecentSearches](https://docs.openverse.org/storybook/?path=/story/components-vrecentsearches--default-story) component, I will create a new issue requesting its implementation.

**Comment by fcoveram** [comment]
Adding the `priority: medium` label as it's part of #460

**Comment by obulat** [comment]
@fcoveram, we have a `VItemGroup` component that is a list of `VItem`s (can be vertical or horizontal). It is used for page links and search types. Should they also use the popover item styles?

**Comment by fcoveram** [comment]
> …It is used for page links and search types…

I don't understand this part. Do you mean for the following?

| Page links | Search types |
|---|---|
| <img width="1486" alt="Openverse results, content links area" src="https://github.com/WordPress/openverse/assets/895819/0a840ffe-5f42-4c60-a95a-46cb2fc14647"> | <img width="300" alt="Openverse results. Content switcher popover visible and All content item selected" src="https://github.com/WordPress/openverse/assets/895819/f3af8e6d-b3c7-4796-9e99-cede7b013471"> |

If so, then no.

Popover item is for the recent searches popover (when you click on the search bar in search results page) and for popovers in modal. Its variants (Icon, Selection, and Label) are for content interactions that go beyond the content links and switcher popover.

**Comment by obulat** [comment]
> I don't understand this part. Do you mean for the following?
Search types - yes, and page links is for the `md` to `lg` on the content header:

<img width="198" alt="Screenshot 2023-08-23 at 12 55 25 PM" src="https://github.com/WordPress/openverse/assets/15233243/e0918c25-fe3d-4a23-b2d8-963e3a9ee00a">

**Comment by fcoveram** [comment]
Thanks for the response. Now I understand.

The content switcher popover doesn't need any change. But the content header's menu does need to be updated. I guess that is for a new PR.

I put the [site menu mockup](https://www.figma.com/file/GIIQ4sDbaToCfFQyKMvzr8/Openverse-Design-Library?type=design&node-id=5526-45152&mode=design&t=7rH9azbD2rKR9Anl-4) and the [popover in context](https://www.figma.com/file/GIIQ4sDbaToCfFQyKMvzr8/Openverse-Design-Library?type=design&node-id=5526-45706&mode=design&t=7rH9azbD2rKR9Anl-4) in the Design Library, and below a screenshot of the same element. The active state has `Label bold` style in the label, same as the current active state.

<img width="500" alt="Content header menu and popover items in different states" src="https://github.com/WordPress/openverse/assets/895819/54ffd004-f49d-4de0-96a9-fb56bc7f2b7b">

**Comment by fcoveram** [comment]
Closing this issue as both popover components were integrated successfully.
