### ISSUE TITLE
Open changelog PRs in release app workflow even if linting fails

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse#2859]
## Description

A release app workflow run recently failed on the linting step: https://github.com/WordPress/openverse/actions/runs/5934605029

This resulted in the need to manually run the rest of the workflow steps.

We can avoid this by making the linting step _optional_, opening the changelog PR even if that step fails. We can run linting manually on the changelog PR itself afterwards anyway, and it isn't critical for the deployment to be successful otherwise.

**Comment by dhruvkb** [comment]
Since the goal of the workflow is to deploy to ECS, I think that should be done first in the workflow and secondary actions like the changelog can be moved lower, so that they do not impact the core functionality.

**Comment by sarayourfriend** [comment]
That's a good point! Much easier to just switch the order of things around than try to manage different branches in GitHub actions.
