### ISSUE TITLE
Remove `django-sslserver` dependency

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse#2887]
## Problem

`django-sslserver` is installed in our Django apps, but does not appear to be used.

https://github.com/teddziuba/django-sslserver

@dhruvkb Do you remember if this is related to HTTPS testing locally? I _think_ we only need the nginx image for that, right? Just want to make sure I'm not missing something there.

It is not used in production, so even if we _do_ use it locally for something, we should make it a conditional app that isn't on in production.

## Additional context

Staff only to get input from Dhruv (and others, if necessary) to make sure we don't actually use this and I'm just not aware of it. If we do use it, then we should convert this issue to document it instead.

**Comment by dhruvkb** [comment]
I don't think the Django app needs this package for SSL. I don't remember manually installing it either. Must check Git history to know why this was added.

**Comment by sarayourfriend** [comment]
Awesome, thanks for confirming, Dhruv!
