### ISSUE TITLE
Remove `django-storages` dependency

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse#2888]
## Problem

We maintain a dependency on and conditionally configure our Django app to use `django-storages` S3 backend for FileFields. However, we don't have any FileFields.

Can we remove this depenedency? @WordPress/openverse-api

**Comment by dhruvkb** [comment]
This was used to store logos of various providers in a very old version of CC Search. These images were a part of the "Browse by Collections" feature.

![image](https://github.com/WordPress/openverse/assets/16580576/9ab95e1c-69c4-435a-aacc-eea8367ce617)

The dependency, and associated configuration should be safe to remove now. Any related buckets in S3 should be discarded as well.

**Comment by dhruvkb** [comment]
Further, this storage configuration was used by the `SourceLogo` model, added in [migration 0028](https://github.com/WordPress/openverse/blob/aa16d4f1be7607b12c428886b9890bdd947cc71c/api/api/migrations/0028_sourcelogo.py) and then removed in [migration 0051](https://github.com/WordPress/openverse/blob/aa16d4f1be7607b12c428886b9890bdd947cc71c/api/api/migrations/0051_delete_sourcelogo.py).

Hence, presently, there is no usage of `FileField` and this storage module.
