### ISSUE TITLE
Add shellcheck to all repositories

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse#289]
## Problem

We've made a few easy to avoid mistakes in shell scripts

https://github.com/WordPress/openverse-frontend/pull/1640
https://github.com/WordPress/openverse-api/pull/869

These can be avoided using shellcheck and following it's basic advice (always adding `set -e`, actual syntax checks, etc).

## Description

Add shellcheck to all repositories. Even if any of these repositories don't have shell scripts, let's add it now before we introduce a shell script and forget about this. It doesn't hurt, after all.

- [x] WordPress/openverse (https://github.com/WordPress/openverse/pull/300)
- [x] WordPress/openverse-catalog (https://github.com/WordPress/openverse-catalog/pull/718)
- [x] WordPress/openverse-api (https://github.com/WordPress/openverse-api/pull/922)
- [x] WordPress/openverse-frontend (https://github.com/WordPress/openverse-frontend/pull/1862)

## Side note
It'd be nice if we used pre-commit on all repositories instead of having the frontend repository be the odd ball using `husky`. If we used pre-commit everywhere then we could just sync the pre-commit configuration and automagically have things working for all languages across all repositories the same way. I'll open another issue to think about that for the frontend repo.

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by dhruvkb** [comment]
Since `shellcheck` has a [readymade integration for `pre-commit`](https://github.com/koalaman/shellcheck#pre-commit), I'm going to go ahead and mark this issue as good first.

**Comment by MustkimKhatik** [comment]
Hey, I would like to work on this.

**Comment by dhruvkb** [comment]
Hey @MustkimKhatik, we want to add shell-check to all 4 of our repos. The Python-based repos all use `pre-commit` for linting, which is configured using the `.pre-commit-config.yaml` file in the root of the repos.

| Repo | File |
|-|-|
| openverse | https://github.com/WordPress/openverse/blob/main/.pre-commit-config.yaml |
| openverse-catalog | https://github.com/WordPress/openverse-catalog/blob/main/.pre-commit-config.yaml |
| openverse-api | https://github.com/WordPress/openverse-api/blob/main/.pre-commit-config.yaml |

Adding it to the frontend would be more contrived but you can start with these ^ three.

**Comment by MustkimKhatik** [comment]
Alright! I would work on this three!

**Comment by MustkimKhatik** [comment]
btw this [pre-commit syntax](https://github.com/koalaman/shellcheck#pre-commit) will go as it is or there are any changes in ```args```?

**Comment by dhruvkb** [comment]
@MustkimKhatik I think we can skip the `args` field completely so that all the messages are shown.

**Comment by MustkimKhatik** [comment]
> @MustkimKhatik I think we can skip the `args` field completely so that all the messages are shown.

Alright we will do that

**Comment by MustkimKhatik** [comment]
Hey @dhruvkb, For frontend workaround is same? because there is no ```.pre-commit-config.yaml``` file so where we adding ShellCheck?

**Comment by sarayourfriend** [comment]
@MustkimKhatik We'd have to add it as an additional workflow job in the CI/CD for the frontend repository. This could be done with this action, for example: https://github.com/marketplace/actions/shellcheck

Alternatively, Dhruv has been working on getting pre-commit into the frontend repository in this PR: https://github.com/WordPress/openverse-frontend/pull/1862 Maybe helping on that PR would be a good way to go about this as well. Getting pre-commit in the frontend would help unify our linting across all repositories.

**Comment by MustkimKhatik** [comment]
Okay @sarayourfriend, maybe adding ShellCheck directly into pre-commit will be more convenient instead of additional workflow job. I would definitely look for it.

**Comment by dhruvkb** [comment]
Closing this as all our active repos are now using pre-commit with a _nearly_ identical config that includes ShellCheck.
