### ISSUE TITLE
Remove `python3-openid` dependency from API

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse#2896]
## Problem

[`python3-openid`](https://pypi.org/project/python3-openid/) is an API dependency, but is unused.

Note: @WordPress/openverse-api can someone else confirm that I'm looking at the OAuth implementation in the API correctly and that openid is indeed unused? I've searched for `openid` in the codebase and can find no references. This is the only usage I can see in the dependency's documentation, but I could be missing something. Is this connected to another dependency, somehow?

## Description

Remove the dependency from `api/Pipfile` and run `pipenv install` inside `api` directory.

Confirm tests pass by running the following from repository root:

```
$ just dc build web
$ just api/test
```

**Comment by obulat** [comment]
This dependency was added in https://github.com/cc-archive/cccatalog/pull/512 when a single requirements file was split into dev and prod, probably using freeze. It also hasn't been updated since 2020. So, seems safe to remove.
