### ISSUE TITLE
Prevent workflows from eating up GitHub openverse-bot user's API requests

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse#290]
## Problem

We have a lot of workflows that run on every push and some on every issue and PR that opens. Several of these could be limited to run in series or cancel in progress runs.

## Description

Use the `concurrency` setting for workflows to manage runs that overlap: https://docs.github.com/en/actions/using-jobs/using-concurrency

Note that not all workflows will need the same configuration so do take care to investigate each one and ensure you understand when and why it runs to be able to develop the correct group name for them.

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by dhruvkb** [comment]
After #1668, we have a good concurrency configuration for the workflows and I have not seen any rate-limiting affecting our workflows.
