### ISSUE TITLE
GH Pages deployments failing

### ISSUE THREAD

**Issue by dhruvkb** [WordPress/openverse#2900]
## Description

Consider these two workflow runs

- https://github.com/WordPress/openverse/actions/runs/5971194440/job/16209593998#step:2:566
- https://github.com/WordPress/openverse/actions/runs/5978165187/job/16219691937#step:2:564

Both fail with the following error message:

```
/usr/bin/git submodule sync --recursive
/usr/bin/git -c protocol.version=2 submodule update --init --force --depth=1 --recursive
Error: fatal: No url found for submodule path 'automation-checkout' in .gitmodules
Error: The process '/usr/bin/git' failed with exit code 128
```

This error has caused a number of GitHub Pages deployments to fail recently, with our documentation and PR previews not updating as expected.

**Comment by AetherUnbound** [comment]
I wonder if this also has to do with the recent application of our branch rules in https://github.com/WordPress/openverse-infrastructure/pull/591

**Comment by sarayourfriend** [comment]
The error is documented in the action's issue tracker: https://github.com/actions/checkout/issues/1358

What is `automation-checkout`? We don't have any git submodules, do we? I don't think this is related to the branch protection issues. It could be, it I'd first start with trying to figure out why the action things we have submodules that need checking out.
