### ISSUE TITLE
Explore splitting CI into multiple workflow files

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse#291]
## Problem

In the API and Frontend repositories we stuff all our CI into a single workflow. This helps with some things, like being able to share Docker builds, but hurts other things, like not being able to use the `paths` option to selectively run steps only when necessary.

For example: it's a waste of time and resources to run unit and e2e tests on the frontend with nothing in the `src` directory or the CI configuration for those tests has changed. Same with the API unit tests, it doesn't make sense to run the ingestion tests if the API was updated nor the API tests if only the ingestion server is updated. It doesn't make sense to run either if only documentation has been updated.

## Description

Explore the possibility of splitting CI into multiple workflow files so that we can use the paths option to selectively run certain CI steps only when relevant.

We could also try something like this: https://github.com/orgs/community/discussions/25669

Because we have required checks that need to pass on PRs, we might have to use that strategy to cause the checks to automatically pass instead of running. Splitting into multiple files may not even be possible with required checks, I'm not sure.

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by dhruvkb** [comment]
The CI + CD workflow is very selective now and only runs the necessary steps based on the changed files.
