### ISSUE TITLE
Linting is failing on false-positives for executable files from dev container

### ISSUE THREAD

**Issue by rwidom** [WordPress/openverse#2922]
## Description

I haven't been able to commit requested changes on https://github.com/WordPress/openverse/pull/2782, because pre-commit is failing on lots of files that I haven't touched.

## Reproduction

1. Use VS Code, and start up Docker Desktop for mac, but do not start any of the docker services or enter a virtualenv (may need to start VS Code before Docker Desktop and choose to edit the dev container json locally, and then start Docker Desktop).
2. get into branch `fix-1484/europeana-image-dimensions`, run `just lint` and `just catalog/test`, and observe that everything (including "check that executables have shebangs") passes
3. try to commit and see
```
> git -c user.useConfigOnly=true commit --quiet --allow-empty-message --file -
`pre-commit` not found.  Did you forget to activate your virtualenv?
```

4. Choose "Reopen in dev container" to start the virtual environment. (observe a new command prompt in terminal: `vscode ➜ /workspaces/openverse (fix-1484/europeana-image-dimensions) $ `, and confirm that you're in the same branch)
5. Try `just lint`. 
6. See a ton of messages fly by with the following pattern of error message:
```
[definitely not executable filename, e.g. .md, .sql, .json] marked executable but has no (or invalid) shebang!
  If it isn't supposed to be executable, try: `chmod -x ingestion_server/test/mock_schemas/api_matureimage.sql`
  If on Windows, you may also need to: `git add --chmod=-x ingestion_server/test/mock_schemas/api_matureimage.sql`
  If it is supposed to be executable, double-check its shebang.
```

## Screenshots

Linting fine when Docker is on and not in the dev container (but can't commit):
![image](https://github.com/WordPress/openverse/assets/2520575/768bcad6-6181-49c6-8679-6256d7e1357c)

Linting fails from the dev container (so can't commit):
![image](https://github.com/WordPress/openverse/assets/2520575/a1c34d95-4752-483b-b0d6-44ab28b5a9c8)

Here are some additional notes.

### Create a new branch with cherry-picked commits from the original

The difference seems to be less about the branch, and more about whether or not linting is happening within the dev container. Here is a screenshot from `main`, running `just lint` within the dev container, with the same kind of errors:

![image](https://github.com/WordPress/openverse/assets/2520575/9a0cc87f-dba2-49a1-8606-e18ae0711e05)

That said, I did do some cherry picking which was smooth sailing with Docker down / outside of the dev container.

<details>
<summary>Cherry-picked commits added to a new branch from main</summary>

```
commit 73a4d1b662db3d7a1175e21ea3093ee3be1a0a11
Author: rwidom <xxx>
Date:   Tue Aug 22 19:34:07 2023 -0400

    add tests for one dimension but not both
    
    (cherry picked from commit daa0c484fc4190488da9f8605bea8c5e1de9146b)

commit 349e64ed25a4e2b4d5fc7b1290c95485bca01b44
Author: rwidom <xxx>
Date:   Tue Aug 22 19:29:10 2023 -0400

    extract expected result constants
    
    (cherry picked from commit 2a20b7103436e3f8ff2b659d705775e148d2e174)

commit b60ec2ec2cab0756b52765e6dcbaceb2c2afab8a
Author: rwidom <xxx>
Date:   Tue Aug 22 19:14:38 2023 -0400

    reduce nesting
    
    (cherry picked from commit 9b75639b649d1014250b0b0e9f2883b88559c3a7)

commit b39520845ed1956204e46199632c07f84c045037
Author: rwidom <xxx>
Date:   Tue Aug 15 18:42:05 2023 -0400

    handle shorter filetype strings
    
    (cherry picked from commit 99293b004b851d86e4796bcd6d2a7821eca2d4fc)

commit f9a05029ccb49ef9db0c9a852b24776c5c424f1d
Author: rwidom <xxx>
Date:   Tue Aug 15 18:13:17 2023 -0400

    handle more falsey item responses
    
    (cherry picked from commit 0c6c083443e151bf6618380570c7d51f127ec39a)

commit 4df666a0f3320c7984a744444e2a81e992e7f6b4
Author: rwidom <xxx>
Date:   Fri Aug 11 04:56:38 2023 -0400

    add filetype and filesize
    
    (cherry picked from commit 9d983bcc380036d4ce8597ad2879e4a641638587)

commit 2ae7443794a6914e7f81596effe3b9205081867c
Author: rwidom <xxx>
Date:   Thu Aug 10 07:46:52 2023 -0400

    dimensions after 1st resource, use default delay
    
    (cherry picked from commit ec40e8cfffa10768c3738066c75027b30916e222)

commit e4b8c74efc56699bfb8e3d1604146b56f487a164
Author: rwidom <xxx>
Date:   Wed Aug 9 19:36:30 2023 -0400

    separate function to get item data
    
    (cherry picked from commit b1b46960976eb31f34ddc7f25a898b83d619c96a)

commit 9554beef178794743e0372113b01f1268ef16596
Author: rwidom <xxx>
Date:   Mon Aug 7 18:35:18 2023 -0400

    mock record api calls to enable test image list
    
    (cherry picked from commit 2bba58151cf5d2ad9177fac3936c9e3e29bcfbd1)

commit 73f68f5cb412d8cbb90c5a8489ecbc6dd789735a
Author: rwidom <xxx>
Date:   Mon Aug 7 17:16:54 2023 -0400

    make sure the dimension tests actually run
    
    (cherry picked from commit 10130652a2051b56173aebfcd80d10a444ec81cf)

commit 97d30e67ff09c0d0dd75213842223f443f3fd56c
Author: rwidom <xxx>
Date:   Sat Aug 5 14:24:02 2023 -0400

    add individual item data pull to get dimensions
    
    (cherry picked from commit 8c9a9dbebeff671fdc4dc48e54c0a790950a7a17)

commit 2b7acbc22751fda59dd89cef6bc13fbccc1031e7
Author: rwidom <xxx>
Date:   Sat Aug 5 14:22:49 2023 -0400

    adding test resources
    
    (cherry picked from commit 8420d7fe2b9a4c99741be68605338c7cf95d1434)
```
</details>

### Double-check the executable status of the file on mac

Here's an example of one of the files failing linting:

```
documentation/api/reference/search_algorithm.md: marked executable but has no (or invalid) shebang!
  If it isn't supposed to be executable, try: `chmod -x documentation/api/reference/search_algorithm.md`
  If on Windows, you may also need to: `git add --chmod=-x documentation/api/reference/search_algorithm.md`
  If it is supposed to be executable, double-check its shebang.
```

I followed the instructions above, but I don't think it matters, because *my mac* never thought that those files were executables, and apparently the first level virtual environment doesn't either. See the differences below when I use `ls -al`.

```
vscode ➜ /workspaces/openverse (fix-1484/europeana-image-dimensions-cherry-picked) $ ls -al documentation/api/reference/search_algorithm.md
-rw-r--r-- 1 vscode vscode 12594 Aug 26 15:52 documentation/api/reference/search_algorithm.md
vscode ➜ /workspaces/openverse (fix-1484/europeana-image-dimensions-cherry-picked) $ chmod -x documentation/api/reference/search_algorithm.md
vscode ➜ /workspaces/openverse (fix-1484/europeana-image-dimensions-cherry-picked) $ ls -al documentation/api/reference/search_algorithm.md
-rw-r--r-- 1 vscode vscode 12594 Aug 26 15:52 documentation/api/reference/search_algorithm.md
vscode ➜ /workspaces/openverse (fix-1484/europeana-image-dimensions-cherry-picked) $ ls -al .devcontainer/post_create.sh
-rwxr-xr-x 1 vscode vscode 615 Aug 26 15:52 .devcontainer/post_create.sh
```

### Theory on why this is happening

Based on [this docker issue](https://github.com/docker-library/postgres/issues/1108), it looks like there may be something about *how* we make files available to the docker image we use for linting (bind/ongoing updates rather than copied at startup?) that is causing linting to see those files as executables, even though they aren't in the local system.

If that's right (big if!) possible solutions (none of which I like):
- Make linting run in its own thing that doesn't have bound files that restarts (i.e. reloads changes) every time we lint?
- Add a script to run `chmod -x` on everything that doesn't end in `.sh` in whatever the right environment is before linting?

But there are also [a million dev container settings](https://code.visualstudio.com/docs/devcontainers/containers) that I know nothing about and could be causing this issue.

## Environment

- Device: Mac laptop
- OS: macOS 11.7.4
- VS Code (Version: 1.81.1, Commit: 6c3e3dba23e8fadc360aed75ce363ba185c49794)
- Docker Desktop (Version: 4.21.1 (114176), Engine: 24.0.2, Compose: v2.19.1)

**Comment by dhruvkb** [comment]
@rwidom are you using Docker on macOS? If so it is a known issue docker/for-mac#5029.

**Comment by rwidom** [comment]
Thanks so much @dhruvkb ! It looks like I can't use VirtioFS with my macOS version. :/

**Comment by dhruvkb** [comment]
I triaged the issue as a DX fix, but I'm not sure we can do anything besides wait for Docker to fix it upstream? You could try alternatives to Docker Desktop (like [OrbStack](https://orbstack.dev/) or [Colima](https://github.com/abiosoft/colima)) but I'm not entirely sure they will fix the issue as they all use Docker Engine under the hood.

@rwidom in the meantime I would recommend linting separately (which works, as you have mentioned) and then committing/pushing with the `--no-verify` flag to skip the lint step.

**Comment by rwidom** [comment]
OK, I'll use `--no-verify` for the immediate issue, but maybe I'll also just poke around to see if I can come up with a more integrated solution for the dev container. I don't think it's *only* docker, it seems like it's something about the dev container + docker interaction, right? OK if we leave this open for a minute @dhruvkb ? (cc @sarayourfriend , @AetherUnbound )

**Comment by dhruvkb** [comment]
@rwidom thank you for working around this, and for searching for solutions. It's totally fine to keep this open, we want to support devcontainers as a viable option for new contributors to skip setting up the entire toolchain so ironing out these problems is important to us.

**Comment by rwidom** [comment]
Big thanks for the meeting! I think that we left with these recommendations, but please confirm @sarayourfriend, @AetherUnbound and/or @stacimc:

- The dev container is intended for use in github code spaces (tested and supported there), and it does not work locally e.g. in VS Code, so don't use it there.
- We can put that in the set up document (my set up is working much better now with pre-commit installed correctly, which would have happened if I had used `just install` outside of the dev container)
- Maybe `post_create.sh` can check to see if it's running in github code spaces, and throw an error / reminder about not using dev container locally

Yes?

**Comment by sarayourfriend** [comment]
That's my understanding. I've opened an issue to add that documentation. Closing this one as resolved now that we know the underlying issue. Thanks for working through this with us, @rwidom :pray:
