### ISSUE TITLE
Remove manual `credits` section from release notes template

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse#295]
GitHub now automatically shows a `contributors` section at the bottom of release notes, with a photo of each contributor. Right above this we show a generated list of contributors. Our list has some problems: it shows multiple dependabot entries, and the Openverse bot.

We may want to consider removing our section in favor of GitHub's. One question I have is that GitHub's section may only appear in the GitHub UI, while ours is in the actual text of the release. Is there a benefit to having it in the text that we'll lose?

**Comment by dhruvkb** [comment]
I'm not aware of any use of the text outside the context of the GitHub UI so I agree that the credits section can be dropped.

**Comment by dhruvkb** [comment]
We've removed the credits sections from the release notes.
