### ISSUE TITLE
Extract the pgcli version for the Dockerfile from the api Pipfile

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse#2959]
## Problem

Currently, the `pgcli` version in the Dockerfile is hard-coded. Neither Renovate nor Dependabot update it, and it is very difficult to remember that it also needs updating.

https://github.com/WordPress/openverse/blob/a52ef07a1732180c3e31b84eb4e9444a1e8f54f8/docker/upstream_db/Dockerfile#L5

## Description

We should try to extract the `pgcli` version from the `api/Pipfile`:
https://github.com/WordPress/openverse/blob/a52ef07a1732180c3e31b84eb4e9444a1e8f54f8/api/Pipfile#L16

**Comment by dhruvkb** [comment]
That would create a strange coupling between the `upstream_db` and the `api` packages especially because the package change would only be applied when the `Dockerfile` is built into an image.

It would be more convenient to pin a major (and optionally minor) version, making known safe patch improvements automatically work when images are built.

**Comment by AetherUnbound** [comment]
Could we perhaps define the pgcli version in a requirements.txt file, extract it like we do [with the catalog version into a Docker argument](https://github.com/WordPress/openverse/blob/09879490d0f8d0177dd2877e4aead4cc9a24f201/catalog/Dockerfile#L3-L6), then add that file to the list of files that dependabot checks for updates? That would make sure that we get regular updates on pgcli without coupling it to any other project.

**Comment by dhruvkb** [comment]
@AetherUnbound that also seems like a good solution 👍. We will also have to include that file in the `.github/filters.yml` file to each project it affects so that new Docker images are pushed to GHCR when the file changes.
