### ISSUE TITLE
Should we have an 'effort' label?

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse#296]
## Problem

Currently, some `low` priority issues might take only 1-2 minutes, and could be worth doing from time to time, but are easy to lose track of due to their low priority.

## Description

A label indicating the effort, complexity, or time estimate for an issue might incentivize people to take on low-priority, low-effort issues more regularly.

**Comment by dhruvkb** [comment]
I think the effort labels would be a valuable addition, although we might need to be deliberate about properly separating good first issues from low effort ones. Surely there can be an overlap but not all good first issues are low effort.

**Comment by ramadanomar** [comment]
I think difficulty would be a more appropriate term considering it's an open source project where people of all backgrounds, experience and expertise would contribute. This could potentially tackle the issue @dhruvkb stated, as 'effort' is subjective. What is a low effort task for me isn't necessarily a low effort for other people and vice versa

**Comment by dhruvkb** [comment]
@ramadanomar in that case, isn't difficulty also subjective? What's difficult for someone might by easy for someone else.

**Comment by zackkrida** [comment]
I prefer `effort` because it's subjective, but is a time-based subjectivity, not one based on 'expertise' like difficulty is. 

Both are _quite_ subjective however!

**Comment by krysal** [comment]
I am not against adding it, just not making it mandatory.

**Comment by AetherUnbound** [comment]
I also like the idea of a non-mandatory `effort` label 🙂 It would definitely be helpful for those moments when I would like a "quick win" PR that I know I could knock out easily! And for those cases as folks have mentioned where an issue might be a "good first issue", but not a particularly "low effort" one (e.g. @rwidom with the iNaturalist work 😄)

**Comment by obulat** [comment]
It would be interesting to try out the approach of tackling several "low effort" PRs per week. What I'm afraid of is oftentimes I start working on an issue thinking it's a "low effort" one and end up spending too much time on it :) If we add this label, it would be nice to add it somewhere in our team expectations doc to try to tackle these regularly.

**Comment by sarayourfriend** [comment]
Closing this issue in favour of https://github.com/WordPress/openverse/discussions/2816 as a full discussion with poll.
