### ISSUE TITLE
ESLint plugin package is broken on `main`

### ISSUE THREAD

**Issue by dhruvkb** [WordPress/openverse#2965]
## Description

The ESLint plugin package is broken on `main` with unit tests failing. This breakage was likely introduced in PR #2908, similar to #2957.

## Reproduction

1. Check out repo.
2. Run unit tests for `@openverse/eslint-plugin`.

Alternatively, see [this CI + CD failure](https://github.com/WordPress/openverse/actions/runs/6055992747/job/16435584020#step:4:58).

**Comment by dhruvkb** [comment]
Tagged priority as high because this causes frontend changes to fail pre-push Git hooks and forcing the need to push with `--no-verify`.

**Comment by sarayourfriend** [comment]
I have half a fix locally. I'll open a revert PR in case folks are able to get that merged in before I can fix it forward.

**Comment by dhruvkb** [comment]
I don't know if we need to revert, so far it's only been a minor inconvenience when pushing. I'll let others chime in here if their experience has not been pleasant.
