### ISSUE TITLE
Warning from @nuxtjs/i18n about locales without ISO code

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse#2986]
## Description

Nuxt i18n expects every locale to have the ISO code to add it to the `html` element and to create the alternate links for SEO purposes, and issues a warning when it's not available: `WARN [@nuxtjs/i18n] Locale ISO code is required to generate alternate link`.

## Reproduction

1. Run `just frontend/run dev`.
2. Open the app at `localhost:8443`.
3. See the warning in the console.

## Additional context

We should probably just filter out all the locales without the ISO code.
The list of locales we get from the WordPress GlotPress repository is very comprehensive. Some locales don't even have their own ISO codes. The locales without ISO codes probably do not have many strings translated (I suspect they are completely untranslated).

**Comment by dhruvkb** [comment]
None of the languages without an ISO code have any translations:

<img width="763" alt="image" src="https://github.com/WordPress/openverse/assets/16580576/37dd027e-7ca4-4fca-84ea-3df34bb9a26d">

While these are legitimate languages (I personally recognise Bhojpuri as a language spoken by ~52 million people), it would not be a loss to drop them from the application as they are currently unusable anyway.

Would it be acceptable to use their `code` field (usually 3 chars) as a sort of pseudo-ISO? None of them use a code that's an ISO for a different language.

**Comment by krysal** [comment]
Before shipping this, I noticed the "Emoji" language in the selector. It was funny, I was wondering who was speaking or reading only with emojis 😄
