### ISSUE TITLE
Add access request logging to Nuxt

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse#2993]
## Problem

We have no server request access logging set up for Nuxt, which makes investigating frontend incidents very difficult.

## Description

Add access request logging using a middleware. This one-log-per-request middleware should match what Django provides out of the box: timestamps, request path etc.

## Additional context

This is a hot-fix before we implement a full-fledged Nuxt server logging solution.

**Comment by sarayourfriend** [comment]
A potentially low-effort approach to this would be adding Nginx as a reverse proxy to the frontend and copying the request log configuration we use in the API: https://github.com/WordPress/openverse/blob/b2e9989a8574ba1c5b36e1ea509683f632008a39/api/nginx.conf.template#L10-L24

This would probably be easier than adding a new Nuxt module or writing one ourselves, especially if we want to minimise the amount of special configuration needed to parse the log lines: https://github.com/WordPress/openverse-infrastructure/blob/b2e9989a8574ba1c5b36e1ea509683f632008a39/next/modules/concrete/api/main.tf#L210-L214. It may even be possible to copy the API's nginx configuration entirely, with few changes other than to remove location definitions that do not apply to the Nuxt service. We would, however, need to add a new nginx target to `frontend/Dockerfile` and publish the image to GHCR. Then the ECS configuration can also be copied from the API, with changes to adapt the relevant aspects to the frontend.

JSON logs are automatically parsed by Logs Insights, and we have plenty of examples of querying Nginx logs from the API when we've debugged API incidents.

If there's a trivial or simple way to just add a Nuxt module to accomplish this that is easy to configure request logging (with timing) for, then Nginx could be more effort. However, getting request timing is critical to the usefulness of the logs from a debugging perspective, so if that is not included in the Nuxt logging module and is hard to add for some reason, then Nginx would be better.
