### ISSUE TITLE
Handle Plausible outages

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse#2996]
## Problem

When Plausible server was out on August 28th, we received reports of many 5xx responses from Nuxt. This was misleading because there was no degradation of Openverse frontend for the user (the analytics requests are not blocking and don't break anything in the UI if they fail).

## Description

We should re-write the response header in case Plausible returns 503. Here's is the example of rewriting for 504 errors:

https://github.com/WordPress/openverse/blob/6408b4234241046816c8e68a2bb73226a0c6821d/frontend/nuxt.config.ts#L337-L344

In case the error message contains "service unavailable", we should add the error message to the message that is logged to the console. I think we don't event need to check if it's prod or dev environment, as we might want to see the message logged everywhere.

```
if (err.message.toLowerCase().includes("service unavailable")) { 
       res.writeHead(424, { "Content-Type": "text/plain" }) 
       res.end(`Plausible unavailable: ${e.message}`) 
     } 
```

Note: I am not sure about the shape of the `err` object here. In Cloudflare, I can only see the "Edge status code" and "Origin status code", both equal to "503 Service Unavailable"

**Comment by dhruvkb** [comment]
We already have an error handler set up in the Plausible proxy that checks for `ECONNREFUSED`.

https://github.com/WordPress/openverse/blob/6408b4234241046816c8e68a2bb73226a0c6821d/frontend/nuxt.config.ts#L338-L343

It can be extended to handle other errors.
