### ISSUE TITLE
Remove requests for reviews from closed PRs

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse#30]
The requests for reviews are added automatically now.
When a PR is closed, the requests for review are not removed, and it's impossible to remove them manually.

![FFB72DFE-8148-43D3-A678-ECB81E7F42C5_1_105_c](https://user-images.githubusercontent.com/15233243/121479789-0f7c0300-c9d3-11eb-9e29-aa35653e4381.jpeg)

I'm not sure what that means for the reviewer who was requested. It would still be nice to remove requests automatically.

**Comment by zackkrida** [comment]
> I'm not sure what that means for the reviewer who was requested.

I don't think there are any negative consequences, actually. 

> The requests for reviews are added automatically now.

When this _wasn't happening_, would you remove yourself from the 'Reviewers' section of PRs after they were closed?

I think we might be able to close this, unless there is a negative consequence I am missing.

**Comment by AetherUnbound** [comment]
I believe that GitHub will now remove the group automatically after someone from it reviews the PR. Example: https://github.com/WordPress/openverse/pull/198

That PR initially had the `WordPress/openverse-developers` group as a reviewer, but once Dhruv and Sara reviewed it, they did so _on behalf of_ the group. It's no longer present in the reviewer section, so I think this can be closed :slightly_smiling_face: 
![image](https://user-images.githubusercontent.com/10214785/159990628-ed3ae35f-38d1-44c7-95cc-8a76740a116e.png)
