### ISSUE TITLE
Undefined mediaResults when switching quickly between filters with license_type applied

### ISSUE THREAD

**Issue by stacimc** [WordPress/openverse#3027]
## Description

Error: `Cannot read properties of undefined (reading 'reduce')` in [transformResults](https://github.com/WordPress/openverse/blob/9e63905a97868a1f1f40fa778588ff4d72ff687e/frontend/src/data/media-service.ts#L38), on the main search results page.

While I was not able to reproduce this, it looks like the events are consistently happening when navigating from a search with `license_type=commercial,modification` filters applied, to the same search with a specific media-type filter. E.g.:

`/search/?q=cat&license_type=commercial,modification` -> `/search/image/?q=cat&license_type=commercial,modification`

In each case I checked, it appears that the search should have returned media results.

## Sentry Link

https://openverse.sentry.io/share/issue/eb40f50b906643398ebfa974a59901ed/

**Comment by obulat** [comment]
The underlying API issue for this is #3058.

As a frontend hot-fix, similar to #3016, we can add an `undefined`/`null` check in the `transform` method. So, replace

https://github.com/WordPress/openverse/blob/9e63905a97868a1f1f40fa778588ff4d72ff687e/frontend/src/data/media-service.ts#L35C5-L35C43

```
const mediaResults = <T[]>data.results ?? []
```

**Comment by ngken0995** [comment]
Hello @obulat, I'd like to work on this issue. May I be assigned to it?

I have went through the [quick-start](https://docs.openverse.org/frontend/guides/quickstart.html) guide for frontend. I'm able to pass all the test from running `just frontend/run test:unit`I'm trying to run `just frontend/run test:playwright` and it gives me this `error: FATAL  EACCES: permission denied, mkdir '/frontend/node_modules/.cache/nuxt'` What is the best way to run test for playwright and storybook? Thank you.

**Comment by ngken0995** [comment]
Hello @stacimc,

I'd like to work on this issue. May I be assigned to it? Please read the comment above. I couldn't run some of the test. Should I proceed and create a hot-fix from @obulat suggestion?

**Comment by dhruvkb** [comment]
@ngken0995 you can work on this issue and submit the PR to let CI run the Playwright tests for you. I don't know what exactly could be be causing Playwright to not run locally so maybe deleting the `.cache` and trying could help?

**Comment by ngken0995** [comment]
@dhruvkb I couldn't find the `.cache` folder and decided to submit a PR and let CI run the Playwright test which passed.
