### ISSUE TITLE
Replace deprecated `body` in the ES requests

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse#3043]
## Description

The `get_sources` function in the `search_controller` uses the deprecated `body` parameter:

https://github.com/WordPress/openverse/blob/517a16e407abad1801702b1dceabf1b0598f853b/api/api/controllers/search_controller.py#L555-L571
 
Deprecation warning in the CI (when running the API tests).
```
  /api/api/controllers/search_controller.py:682: DeprecationWarning: The 'body' parameter is deprecated and will be removed in a future version. Instead use individual parameters.
    results = settings.ES.search(index=index, body=agg_body, request_cache=True)
```
This can be replaced with the following code:
```python3
        aggs = {
                "unique_sources": {
                    "terms": {
                        "field": "source.keyword",
                        "size": size,
                        "order": {"_key": "desc"},
                    }
                }
        }
        try:
            results = settings.ES.search(index=index, aggs=aggs, request_cache=True)
```

## Additional context

We recently updated ES version from 7 to 8, and started seeing the deprecation warnings in CI

**Comment by ngken0995** [comment]
Hello @obulat and @WordPress/openverse-maintainers,

I'm trying to have my first contribution on open source project and this issue look suitable for me. Can you assign me to this issue? How can I run an API tests?

**Comment by krysal** [comment]
Hi @ngken0995, you can find the instructions for the API tests in the [docs site](https://docs.openverse.org/api/guides/test.html).

**Comment by ngken0995** [comment]
Hello @krysal,

Thank you for providing the docs site. It was super helpful. I can't join the slack channel because I'm not authorized. I'm trying to run `just api/up`.

rHere is the result:
`env COMPOSE_PROFILES="api" just ../up
env COMPOSE_PROFILES="api" docker-compose -f docker-compose.yml up -d
env: ‘docker-compose’: No such file or directory
error: Recipe `dc` failed on line 141 with exit code 127
env COMPOSE_PROFILES="api" docker-compose -f docker-compose.yml up -d
env: ‘docker-compose’: No such file or directory
error: Recipe `dc` failed on line 141 with exit code 127
env COMPOSE_PROFILES="api" docker-compose -f docker-compose.yml up -d
env: ‘docker-compose’: No such file or directory
error: Recipe `dc` failed on line 141 with exit code 127
`
I'm kinda stuck trying to resolve the error. Please advise.

**Comment by krysal** [comment]
@ngken0995 Could try running `just env` before `just api/up`? That must complete your files.

Also, you should be able to join Slack, it's free to access for anyone, you just need a WordPress.org account first. Check [this page](https://make.wordpress.org/chat/).

**Comment by ngken0995** [comment]
Hello @krysal, I was able to run `just api/up`, `just api/init` and `just api/test`. I made the changes suggested above and still getting the same error when I run `just api/ test`. Do I need to change any test data?

**Comment by ngken0995** [comment]
@krysal, I have joined the slack channel with a WordPress.org account.

This is the result after I made the changes and ran `just api/test` below:

`test/test_auth.py: 7 warnings
test/test_dead_link_filter.py: 4 warnings
test/unit/controllers/test_search_controller.py: 125 warnings
  /venv/lib/python3.11/site-packages/elasticsearch_dsl/search.py:712: DeprecationWarning: Passing transport options in the API method is deprecated. Use 'Elasticsearch.options()' instead.
    es.search(index=self._index, body=self.to_dict(), **self._params).body,

test/test_auth.py: 14 warnings
test/test_dead_link_filter.py: 7 warnings
test/unit/controllers/test_search_controller.py: 237 warnings
test/unit/utils/test_search_context.py: 4 warnings
test/unit/views/test_media_views.py: 6 warnings
  /venv/lib/python3.11/site-packages/elasticsearch_dsl/search.py:712: DeprecationWarning: The 'body' parameter is deprecated and will be removed in a future version. Instead use individual parameters.
    es.search(index=self._index, body=self.to_dict(), **self._params).body,

test/unit/models/test_media_report.py::test_deindexing_creates_deleted_image_instance[image_media_type_config]
test/unit/models/test_media_report.py::test_deindexing_creates_deleted_image_instance[image_media_type_config]
test/unit/models/test_media_report.py::test_deindexing_creates_deleted_image_instance[audio_media_type_config]
test/unit/models/test_media_report.py::test_deindexing_creates_deleted_image_instance[audio_media_type_config]
  /venv/lib/python3.11/site-packages/django/db/models/fields/related_lookups.py:52: RemovedInDjango50Warning: Passing unsaved model instances to related filters is deprecated.
    warnings.warn(

../venv/lib/python3.11/site-packages/_pytest/cacheprovider.py:451
  /venv/lib/python3.11/site-packages/_pytest/cacheprovider.py:451: PytestCacheWarning: could not create cache path /api/.pytest_cache/v/cache/nodeids: [Errno 13] Permission denied: '/api/.pytest_cache'
    config.cache.set("cache/nodeids", sorted(self.cached_nodeids))

../venv/lib/python3.11/site-packages/_pytest/stepwise.py:56
  /venv/lib/python3.11/site-packages/_pytest/stepwise.py:56: PytestCacheWarning: could not create cache path /api/.pytest_cache/v/cache/stepwise: [Errno 13] Permission denied: '/api/.pytest_cache'
    session.config.cache.set(STEPWISE_CACHE_DIR, [])

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html

Results (165.04s (0:02:45)):
     559 passed
       4 skipped
`

**Comment by obulat** [comment]
@ngken0995, It looks like all of the tests passed. There are some warnings about the deprecations, but they don't affect the `162 passed` tests.

**Comment by ngken0995** [comment]
@obulat This is good to hear! I have created a PR.
