### ISSUE TITLE
Define a `robots.txt` for the API

### ISSUE THREAD

**Issue by dhruvkb** [WordPress/openverse#3060]
## Problem

A not insignificant amount of bot traffic on the API is from web crawlers by search engines, like Yandex for example.

## Description

The API should have a `robots.txt` file to discourage crawlers.

**Comment by MysteryManav** [comment]
@dhruvkb can you assign this to me under hacktoberfest ? Also please provide the data that is to be put in the robots.txt

**Comment by dhruvkb** [comment]
@MysteryManav we need to serve a text file at the root `robots.txt` URL of the API. You can refer to this [helpful tutorial](https://adamj.eu/tech/2020/02/10/robots-txt/#with-a-template) on how to do that.

This `robots.txt` file should contain a list of URLs that search engines and other crawlers are not allowed to index. This would be a list of our API endpoints so the contents of the file will look a bit like this.

```txt
# Block API endpoints
User-agent: *
Disallow: /v1/images/
Disallow: /v1/audio/
Disallow: /v1/auth/
```

Also cc @obulat because of experience with `robots.txt` on the frontend.
