### ISSUE TITLE
Update `_AIRFLOW_DB_UPGRADE` to `_AIRFLOW_DB_MIGRATE`

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse#3077]
## Description

The `_AIRFLOW_DB_UPGRADE` environment variable was recently deprecated: https://airflow.apache.org/docs/apache-airflow/stable/release_notes.html#the-db-init-db-upgrade-commands-and-database-load-default-connections-configuration-options-are-deprecated-33136

We will need to update this in the docker-compose file to `_AIRFLOW_DB_MIGRATE`:

https://github.com/WordPress/openverse/blob/0a5f1a4beaa27cfd5dd4d1baa10209b76f830924/docker-compose.yml#L115

## Reproduction

1. Run `just catalog/test-session`
2. Observe the following log line in the start up output:

```
WARNING: Environment variable '_AIRFLOW_DB_UPGRADE' is deprecated please use '_AIRFLOW_DB_MIGRATE' instead
```

**Comment by 23198** [comment]
@AetherUnbound  could you please assign this to me ? Thanks, Also, I created a PR for this, could you please help me in understanding how to add Labels to this PR, I am unable to do so, no info in the contributing.md as well

**Comment by AetherUnbound** [comment]
@23198 The PR template we have has some automation around it to add the labels from linked issues. It looks like you're set now with that PR 🙂
