### ISSUE TITLE
Add toggleable 'redirection' mode that 301s the entire WordPress Theme

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse#308]
## Problem

As part of our iframe removal efforts, the Openverse WordPress theme located at https://github.com/WordPress/wordpress.org/tree/trunk/wordpress.org/public_html/wp-content/themes/pub/wporg-openverse needs to be updated to redirect the entire site to our new domain, openverse.wordpress.net.

## Description

We need to add a way for the theme to 301 redirect entirely to a new URL. This is expected to be openverse.wordpress.net. It might be nice to put this redirect mode behind a customizer setting, as we did for the iFrame url already in the theme.

The redirects need to account for internationalization and query params need to be preserved. Some examples:

1. `https://ru.wordpress.org/openverse` should redirect to `openverse.wordpress.net/ru`
2. `https://wordpress.org/openverse/search/?q=dog` should redirect to `https://openverse.wordpress.net/search/?q=dog

## Alternatives

There is no alternative.

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by krysal** [comment]
Solved in WordPress/wordpress.org#98.
