### ISSUE TITLE
Add visual regression tests for the sensitive content explanation page

### ISSUE THREAD

**Issue by dhruvkb** [WordPress/openverse#3081]
## Problem

PR #3074 (fixing #2550) adds a page explaining our content safety approach. This page does not have visual regression tests because the translation for this page is nuanced and Google Translate would not be sufficient for this.

## Description

We will wait for this page to be translated, and then use the official translations to add the VR tests for this page.

**Comment by dhruvkb** [comment]
This issue is blocked on the rollout of this page and subsequently on completion of official translations of this page into AR, ES and RU.

**Comment by obulat** [comment]
@dhruvkb, I used google translate to add the `ar` locale to tests, and I think we _can_ use machine translated strings for testing.

**Comment by dhruvkb** [comment]
Since the page has some sensitive text, I wanted to use the proper translations even in testing because I don't think Google Translate can capture the nuance of the wordings. We discussed this internally and the consensus was to wait for the page to be translated before adding VR tests.
