### ISSUE TITLE
Unable to select a new image from the home page after clicking one and returning using browser-back

### ISSUE THREAD

**Issue by paras-2407** [WordPress/openverse#3106]
## Description
The bug in the website is that on the home page of the website, there are 9 randomly generated pictures and when we click on any one of them, it opens the whole page related to that image but when we go back and again click another image it again shows the details of the previously opened image or we can say of the first image opened.

## Screenshots
Here is the screen recording of the bug.
[](https://bit.ly/3PGOwQX)

## Additional context
1. Deletion of the section is not required as it is quite good thinking to add such a section the case is just that if improved it will be a great experience for the users.

**Comment by AetherUnbound** [comment]
Thank you @paras-2407 for submitting this issue! I've confirmed that I'm observing it in production myself as well.

**Comment by dhruvkb** [comment]
Adding more context that the link in the address bar is updated correctly, only the contents of the page are incorrect. Refreshing the page shows the accurate information.

**Comment by paras-2407** [comment]
Hello, I want to actively contribute to this website so, please assign me this PR under Hacktoberfest label or Hactoberfest-accepted label.

**Comment by AetherUnbound** [comment]
Thanks for offering @paras-2407! I've assigned you, do you need any other information for addressing this issue?

**Comment by paras-2407** [comment]
Thank you @AetherUnbound for assigning me this issue.

**Comment by paras-2407** [comment]
It would be greatfull if you add the label Hacktoberfest-accepted too. As it is not getting counted through hacktoberfest label

**Comment by AetherUnbound** [comment]
@paras-2407 According to the [maintainer documentation](https://hacktoberfest.com/participation/#maintainers) for Hacktoberfest, the label on the issue should be sufficient. The `hacktoberfest-accepted` label should be used for PRs that are submitted for issues; this issue does not have an associated PR yet.

**Comment by paras-2407** [comment]
@AetherUnbound my issue is not getting counted in hacktoberfest challenge, so please recheck.

**Comment by dhruvkb** [comment]
@paras-2407 issues are not counted in Hacktoberfest, only PRs are counted.

**Comment by dhruvkb** [comment]
Upon further investigation the back action is broken across single result pages. To reproduce,

1. Click on any image from the homepage gallery. Note some attributes about the image like the title, appearance and artist.
3. Click some related image from the bottom. Note some attributes about this image too.
4. Click another related image from the bottom. Note some attributes about this image too.
5. Now successively click the browser's back button. You will not see the previous images but rather the final image thrice and then be taken to the homepage (meaning that while the browser cycled back, the `mediaItem` in single result store was not updated).
