### ISSUE TITLE
Prevent PRs from being merged if they have the "awaiting triage" label

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse#311]
## Description

Presently we have automation around [labeling PRs using attached issues](https://github.com/WordPress/openverse/blob/7ea4b0b3a6bd930788f0222d3f2f7c2cdd183c74/automations/python/label_pr.py) and [required labels](https://github.com/WordPress/openverse/blob/main/.github/workflows/pr_label_check.yml)

However, the former cannot always add labels in certain cases (if there's no linked issue, for example) and the latter allows the `🚦 status: awaiting triage` label. This means that we can open _and merge_ PRs which go entirely unlabeled. This can cause issues with our release notes, since they're sectioned by label ([see the first 2 lines in this set of release notes as an example](https://github.com/WordPress/openverse-api/releases/tag/v2.5.11)).

We should either add a new step which requires that the `🚦 status: awaiting triage` label _not_ be present prior to merging, or remove them as acceptable options for the PR label check workflow.

I would personally prefer the latter option!

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by justbaileym** [comment]
I'd like to implement this!
