### ISSUE TITLE
Add new Flickr subprovider: Internet Archive Book Images

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse#3121]
## Description

We got the following message from a recent run of the [Flickr subprovider audit DAG](https://docs.openverse.org/catalog/reference/DAGs.html#flickr-audit-sub-provider-workflow):

```
Consider adding the following sub-providers for Flickr:
Internet Archive Book Images: 126377022@N07 (4767558 cc-licensed images)
```

We'll want to add this as a new subprovider here:

https://github.com/WordPress/openverse/blob/5b9db79b3098a53646553b44437496fbb3e16db6/catalog/dags/common/loader/provider_details.py#L47-L64

I believe that we'll also need to create a new provider reference for this in the API's Admin UI in order for the results to show up, once the subprovider is added.

**Comment by SudhanshuJoshi09** [comment]
Hey @AetherUnbound, I would like to work on this. Can I get started ?

**Comment by AetherUnbound** [comment]
@SudhanshuJoshi09 please go ahead! I'll assign it to you 🙂
