### ISSUE TITLE
Duplicated API access logs

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse#3126]
## Description

Every request on the API is logged twice [in the nginx container], in a different format:

```
xxx.xx.xx.xx - - [03/Oct/2023:03:59:10 +0000] "GET /healthcheck/ HTTP/1.1" 200 19 "-" "ELB-HealthChecker/2.0" "-" | container_id | nginx

2023-10-03T03:59:10.414Z | {"time_local":"03/Oct/2023:03:59:10 +0000","remote_addr":"xxx.xx.xx.xx","remote_user":"","request":"GET /healthcheck/ HTTP/1.1","status": "200","host_header": "xxx.xx.xx.xx","body_bytes_sent":19,"request_time":"0.013","http_referrer":"","http_user_agent":"agent","upstream_response_time":0.012,"http_x_forwarded_for":""} | container_id | nginx
```

## Additional context

In the `django` container logs, we also have two very similar logs for one request. The main difference I see between them is the lack of `request id` in one of them, so I'm not sure if it's possible to combine them:

```
<timestamp> | [2023-10-03 15:15:09,480 - gunicorn.access - 363][INFO] 127.0.0.1 - - [03/Oct/2023:15:15:09 +0000] "GET /v1/audio/2ecd1fbf-8122-47e8-84db-50c8ce19c04a/ HTTP/1.0" 200 1682 "-" "Openverse/0.1 (https://openverse.org; openverse@wordpress.org)" | task_id | django

<timestamp> | [2023-10-03 15:15:09,479 - log_request_id.middleware - 55][INFO] <task_id> method=GET path=/v1/audio/2ecd1fbf-8122-47e8-84db-50c8ce19c04a/ status=200
```

**Comment by Chinmay-Bakhale** [comment]
@obulat Could you please add a label of "good first issue"?

**Comment by obulat** [comment]
@Chinmay-Bakhale, we label issues with "good first issue" if they have a clear and relatively simple fix that takes less than 4 hours[^1]. This issue needs more investigation to figure out how to fix it, that's why I didn't add the label.

If you think you know how to fix it, @Chinmay-Bakhale, please add a comment describing your solution, and I will assign it to you. Otherwise, feel free to find another ["good first issue"](https://github.com/WordPress/openverse/issues?q=is:issue+is:open+label:%22good+first+issue%22) or ["help-wanted"](https://github.com/WordPress/openverse/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22) issue :)

[^1]: [Good first issues documentation](https://docs.openverse.org/meta/github_contribution_practices.html#good-first-issues)
