### ISSUE TITLE
Add timing information to ES queries

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse#3139]
## Problem

We do not have much insight on the Elasticsearch end into how much time requests are taking, which requests are being handled, or any significant level of logging.

## Description

We should record at least the `es_took` pieces of queries made to Elasticsearch on the API side so we can gather more accurate query timing information.

## Alternatives

We could (and perhaps should) also add Elasticsearch timing information to the API logs, on a separate level from ES verbose logging (see https://github.com/WordPress/openverse-infrastructure/issues/629).

## Additional context

This is part of an effort to uncover what is causing recent elevated API response times.

**Comment by sarayourfriend** [comment]
Olga and I discussed this during the team meeting and weren't able to come up with what the goal is behind this issue. Specifically, Olga mentioned that it would be helpful if we thought that particular queries were causing the response time issues, but that isn't our current hypothesis (which is garbage collection issues). For that reason, deprioritising this in favour of focusing on continued efforts to get more monitoring information out of ES for the garbage collection (https://github.com/WordPress/openverse-infrastructure/pull/662) will get us closer to getting help from people who know ES better than we do.

**Comment by obulat** [comment]
We have discussed this issue at the monthly priorities meeting.

To implement this issue, we would need to detect the start time before sending the query to ES, and then after the ES responds, we should log the time it took for ES (the ES response `took`) and the time it took for Django request to go through.
