### ISSUE TITLE
Remove pinned glibc update once docker images are updated

### ISSUE THREAD

**Issue by stacimc** [WordPress/openverse#3157]
## Current Situation

#3154 adds explicit pinned updates to glibc in the Dockerfiles for the catalog airflow webserver, upstream_db, ingestion_server, and api to fix a security vulnerability not fixed in the python and airflow docker images.

## Suggested Improvement

Once the images are updated and the glibc version is verified, we can clean up the temporary updates in the docker files.

**Comment by AetherUnbound** [comment]
Sufficient time has passed that we should now check if the updated images have this library updated. If not, we can re-add the blocked label.

**Comment by dhruvkb** [comment]
I think this confirms that the `python:3.11-slim` image now has the same `glibc` version as we have pinned.

<img width="974" alt="image" src="https://github.com/WordPress/openverse/assets/16580576/1ebf7513-b52a-4169-900e-da15db6dcbb2">

We can safely revert #3154.
