### ISSUE TITLE
Sync `.pre-commit-config.yaml` from this repo

### ISSUE THREAD

**Issue by dhruvkb** [WordPress/openverse#316]
## Problem

All our repos now use pre-commit for linting but they are all still using their own `.pre-commit-config.yaml` files with slightly different hooks and configurations.

## Description

Centralising the `.pre-commit-config.yaml` file (and related files like ESLint and Prettier configs) will help us to ensure a consistent code style across all our repos and make it easier to keep them in sync as styles evolve.

## Additional context

We already sync a number of other files (notably GitHub actions) from this repo to all the others so there is a precedent for doing this. 

## References
You can see the current sync code at https://github.com/WordPress/openverse/blob/7c2e6c3724482413688a96ed955440c57d8f61c3/.github/sync.yml.

**Comment by AetherUnbound** [comment]
My only concern with this is that we have a number of non-trivial differences between various pre-commit configs, and some configs which are repo-specific. It would be cool if we could use the same mechanism as the `docker-compose.override.yml` to define a base pre-commit config that the repo can add onto or adapt 😮

**Comment by dhruvkb** [comment]
Related to #317.

**Comment by dhruvkb** [comment]
@AetherUnbound I've opened a PR for the sync action to support Jinja-style templates. Although not 100% what you suggested [here](https://github.com/WordPress/openverse/issues/316#issuecomment-1275182463), but it'll open a whole slew of possibilities for us to sync even more content centrally!

**Comment by AetherUnbound** [comment]
Wow! That's incredible 🤩
