### ISSUE TITLE
National Gallery of Art (United States)

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse#3167]
### Source API Endpoint / Documentation

https://github.com/NationalGalleryOfArt/opendata

### Provider description

Browseable search of open access images from NGA: https://www.nga.gov/collection-search-result.html?sortOrder=DEFAULT&artobj_downloadable=Image_download_available&pageNumber=1&lastFacet=artobj_downloadable

The National Gallery of Art has an open access data collection (see link above) from which Openverse should be able to ingest tens of thousands of openly licensed images.

### Licenses Provided

Public domain/CC0

### Provider API Technical info

The repository linked above has several pages of documentation, it's best to start here: https://github.com/NationalGalleryOfArt/opendata/blob/main/documentation/Data%20Dictionary.txt

Note that the dataset is CC0, not necessarily the images/media linked to. We would need to confirm the rights' statement for each work, it doesn't appear to be included in the dataaset itself. This could require scraping the NGA's landing page for each work.

### Checklist to complete before beginning development

- [X] Verify there is a way to retrieve the entire relevant portion of the provider's collection in a systematic way via their API.
- [ ] Verify the API provides license info (license type and version; license URL provides both, and is preferred)
- [X] Verify the API provides stable direct links to individual works.
- [X] Verify the API provides a stable landing page URL to individual works.
- [X] Note other info the API provides, such as thumbnails, dimensions, attribution info (required if non-CC0 licenses will be kept), title, description, other meta data, tags, etc.
- [X] Attach example responses to API queries that have the relevant info.

### Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by ngken0995** [comment]
@sarayourfriend Can I work on this?

**Comment by sarayourfriend** [comment]
Sure! There's a fair bit of complexity with needing to crawl the individual works pages, so let us know if you need help. Check out the existing provider script DAGs for examples. iNaturalist is a good example of loading data from a data dump, there are significant performance considerations to keep in mind that the iNaturalist DAG handles well. However, this is also a _much_ smaller dataset, so it might not be as important for NGA.

Just send a ping to @WordPress/openverse-catalog if you run into help or want to chat about anything. Folks are also responsive in the Openverse channel of Make WordPress Slack: https://make.wordpress.org/chat/

**Comment by ngken0995** [comment]
@sarayourfriend Can I use javascript package puppeteer to crawl the individual works pages?

**Comment by sarayourfriend** [comment]
@ngken0995 I'm so sorry about this, but I've just realised that we already have the NGA's open access images in Openverse, by way of Wikimedia Commons: https://openverse.org/image/f1a2f23d-1e3d-4759-8933-962cb0bbd0bb?q=c.%201520,%20NGA%201609

However, as you can see, there are significant issues with how we've parsed the data from those works, so I will open a separate issue for working on correcting those and adding the NGA as a "source" (essentially a sub-provider). If you're still keen to work on NGA, I can ping you on that issue (I'll have to create it later, due to a personal time crunch today).

That means this issue is invalid. However, for posterity, to respond to your question, we don't have any support for using Puppeteer in the DAGs. [Beautiful Soup](https://beautiful-soup-4.readthedocs.io/en/latest/) would be preferred when possible. Beautiful Soup should work fine for situations where we don't need the downloaded page to execute JavaScript.

Let me know if you'd like me to ping you on the other issue, and apologies for the confusion here.

**Comment by ngken0995** [comment]
@sarayourfriend it will be great to look at those new issues. I hope I’ll be to resolve parsing issue. Please ping me once they are created.
