### ISSUE TITLE
Replace elasticsearch RequestError with BadRequestError

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse#3169]
## Description

`api/controllers/search_controller` imports an exception (`RequestError`) that does not exist:

https://github.com/WordPress/openverse/blob/3bb5bff6d0cf9cd381405c1e0392bb06a1f51783/api/api/controllers/search_controller.py#L12

Replace `RequestError` with `BadRequestError`:
~~`from elasticsearch.exceptions import NotFoundError, RequestError`~~
`from elasticsearch.exceptions import NotFoundError, BadRequestError`

## Additional context

[2 years ago](https://github.com/elastic/elasticsearch-py/commit/6462574ba44a87075a37a9e810ed8675f9511e76), the code update in Elasticsearch was updated and `RequestError` was replaced with `BadRequestError`.

**Comment by CodeAnk2829** [comment]
Hey @obulat, I want to work on this issue. Could you please assign me this issue?
