### ISSUE TITLE
Remove the `pretty-format-json` hook from this and other repositories

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse#317]
## Description

This repository has https://github.com/pre-commit/pre-commit-hooks#pretty-format-json hook while other repositories probably do not. The requirements for linting `json` files thus differs between repositories. This difference causes extra sync requests when the `json` files from this repositories have different format than the `json` files in other repositories (and no other changes).

This PR was failing CI:
https://github.com/WordPress/openverse-frontend/pull/1917
I've fixed linting errors, and then merged them in. After that, a new sync PR was opened with identical changes but different formatting:
https://github.com/WordPress/openverse-frontend/pull/1920

This issue is marked as `high` priority because not fixing it causes a drift between repository configs.

**Comment by dhruvkb** [comment]
WordPress/openverse-frontend#1960 is in perpetual freeze because of this.
