### ISSUE TITLE
Add logging & tallying for deep pagination

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse#3189]
## Description

We currently don't have much insight into how many iteration our dead link filtering must go through in order to serve requests. We believe that deeper pagination (e.g. iterating over lots and lots of dead links) may be causing our recent increased API response times. We would like to add some logging and tallying into the dead link filtering iterations to know how deep we have to go for certain requests. There's a few steps  we could handle this:

- Logging a query that requires iterating more than `n` times (5? 10?) through the dead page logic, with the query parameters
- Tallying the above, along with a date * time window (e.g. have "number of requests that paginated more than 5 pages in a 5 minute window" as a tally we can observe, this might also require tallying _all_ requests in said 5 minute window that hit the search endpoint, so we can get a ratio of dead link iteration to regular requests)

It would also be ideal if we could set up a sample dashboard or Log Insights query for binning the number of requests which go more than `n` pages deep per 5 minutes from the logs, that way we could observe it over time.

**Comment by gibrown** [comment]
I have definitely seen this happen in the past. Based on the API docs it looks like the limit is a max of 400 items (20 pages and 20 items per page). That is probably good, but if you allow thousands it can be a problem. ES also has a global setting that lets you limit the number of items deep you can go: https://www.elastic.co/guide/en/elasticsearch/reference/8.9/index-modules.html#index-max-result-window

**Comment by dhruvkb** [comment]
Keeping this open till we have this in our Log Insights dashboard.

**Comment by dhruvkb** [comment]
Closing this as the parent project of reducing API response times is already considered resolved.
