### ISSUE TITLE
Refactor and improve `VTag` component

### ISSUE THREAD

**Issue by dhruvkb** [WordPress/openverse#3190]
## Description

The `VTag` component added in #3137 can be improved further in the following ways:

- forward all props to the inner `VButton` (and potentially also events from the inner `VButton`?).
- use a slot for the content instead of a prop. This can unlock future UI additions/improvements such as icons to indicate ML-generated tags etc.
- add accessible labels to the links to clearly indicate that the link is a tag.

## Additional context

This issue was based on a review comment: https://github.com/WordPress/openverse/pull/3137#pullrequestreview-1675188420

**Comment by Pqformeln** [comment]
Hi,

We are a group of 5 students at KTH whom would like to solve this issue as part of a course in Software Engineering!

@pqformeln @FelixSjogren @Stagge @isadorawinter @BDidace

**Comment by dhruvkb** [comment]
@Pqformeln thanks for offering to contribute, and welcome to Openverse. Would you like to solve this one issue collectively or would you like to work on five separate issues?

**Comment by Pqformeln** [comment]
Thanks, collectively!

**Comment by dhruvkb** [comment]
@Pqformeln in that case I would recommend the following approach:

- Fork the `WordPress/openverse` repository to one of your accounts, let's say `Pqformeln/openverse`.
- Invite everyone else as collaborators on this fork.
- Create a new branch on your fork, let's say `vtag_improvements`.
- Now all the collaborators can push commits to this branch and collaborate on the work. You have to take care to not overwrite each others' work so best to plan how to split up the work beforehand.
- Create a PR from the `vtag_improvements` branch on the fork to the `main` branch on `WordPress/openverse`.

Alternatively, we can split out the work in this issue beforehand and each of the interested parties can work independently and make separate PRs.

**Comment by zackkrida** [comment]
@dhruvkb I'm going to assign you to this PR in a mentor/reviewer capacity, and so it doesn't show up as unassigned in our project tracking.
