### ISSUE TITLE
Avoid API failure when requests URL params aren't fully encoded

### ISSUE THREAD

**Issue by krysal** [WordPress/openverse#3199]
## Description

Django fails to decode these requests and returns 500 errors.

```
ValueError
Invalid hex encoding in query string
```

## Reproduction

1. Request to the API the https://api.openverse.engineering/v1/images/  endpoint with the query param `q=Canada holds 57%25 of the global export market`
2. Observe the response: `Not Found. The requested resource was not found on this server`
3. Then remove the `25` of the param and request the URL again
4. See the error.

## Environment

- Device: Mac
- OS: MacOS v10.15
- Browser: Firefox v119.0
- Other info: more details in Sentry link (below).

## Additional context

[Information from Sentry](https://openverse.sentry.io/share/issue/3df6e5d4a65e4c3fbaa807f4537e84c1/).

**Comment by dhruvkb** [comment]
Query params have to be [URL-encoded](https://en.wikipedia.org/wiki/Query_string#URL_encoding). This is something that we should document and expect from the users of the API and deviations from this should raise errors. The more important code-change here is to raise 400 Bad Request errors in these cases and not 500, that needs to be fixed.

**Comment by krysal** [comment]
That sound perfectly reasonable @dhruvkb. Thanks for further explaining the issue and solutions.

**Comment by AetherUnbound** [comment]
We're seeing that this now raises a `SuspiciousOperation` error within the Oauth backend per this Sentry issue: https://openverse.sentry.io/share/issue/eb602c45bcb34dc8947e660d793eea2e/

**Comment by krysal** [comment]
Closing as this hasn't seen activity in a long time.

**Comment by AetherUnbound** [comment]
Reopening as this occurred again recently (example URL: http://api.openverse.org/v1/images/?q=73%25%20of%20Arkansans%20think%20that%20crime%20is%20on%20the%20rise%20in%20their%20state, which unencoded reads as `73% of Arkansans think that crime is on the rise in their state`). Sentry link: https://openverse.sentry.io/share/issue/6031f339cffe4045b0e6198e251bf2d3/

**Comment by AetherUnbound** [comment]
Some related issues I've found:
- https://github.com/jazzband/django-oauth-toolkit/issues/954
- https://github.com/oauthlib/oauthlib/issues/662

It seems that the former resulted in https://github.com/jazzband/django-oauth-toolkit/pull/963 which fixed cases of this for `oauth2_provider/backends.py`: 
https://github.com/jazzband/django-oauth-toolkit/blob/102c85141ec44549e17080c676292e79e5eb46cc/oauth2_provider/backends.py#L18-L27

But not for the `rest_framework` extension:

https://github.com/jazzband/django-oauth-toolkit/blob/102c85141ec44549e17080c676292e79e5eb46cc/oauth2_provider/contrib/rest_framework/authentication.py#L21-L31

I'll make an upstream issue and try to solve this with an attempted fix as well.

**Comment by AetherUnbound** [comment]
Hoping this can be addressed by: https://github.com/jazzband/django-oauth-toolkit/pull/1444

**Comment by zackkrida** [comment]
@WordPress/openverse-api this should be available due to the upstream fix contributed by @AetherUnbound to the latest 3.0.x releases of django-auth-toolkit: https://github.com/jazzband/django-oauth-toolkit/releases.
