### ISSUE TITLE
[Meta] Make sure CI integration tests run on Dependabot PRs

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse#32]
Some automated testing run on dependabot PRs would cut down on manual work to validate small dependency version bumps.

Subissues:

- [x] Openverse catalog
- [x] WordPress/openverse-api#122
- [x] Openverse frontend

**Comment by zackkrida** [comment]
There's only linting on the catalog, but that should be sufficient for now.

**Comment by krysal** [comment]
The Catalog repo [runs the automated tests](https://github.com/WordPress/openverse-catalog/blob/main/.github/workflows/push_pull_request_test.yml) too. For example: [some tests results](https://github.com/WordPress/openverse-catalog/pull/114/checks?check_run_id=3207069570).
