### ISSUE TITLE
Test issue for verifying the subscribe-to-label action works

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse#320]
## Description

Test issue to trigger subscribe-to-label action.

## Reproduction

1. 
2. 
3. 
4. See error.

## Environment

 - Device: 
 - OS: 
 - Browser: 
 - Version: 
 - Other info: 

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by AetherUnbound** [comment]
Gah, unexpected hiccup - it looks like the `github-actions` bot account can't use the @ groups 😞

**Comment by AetherUnbound** [comment]
We're currently using `secrets.GITHUB_TOKEN`, I think if we use `secrets.ACCESS_TOKEN` that will use the @openverse-bot account which should have the right permissions to mention people 😮 @dhruvkb what do you think?

https://github.com/WordPress/openverse/blob/358da3d039b6ae9b55475b674cb31040834173ef/.github/workflows/subscribe_to_label.yml#L14

**Comment by dhruvkb** [comment]
Yeah @AetherUnbound, switching to `ACCESS_TOKEN` should fix it. @openverse-bot is a regular user so it can tag anyone.
