### ISSUE TITLE
Add a documentation page describing the different parts of our stack

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse#3201]
## Description

We have some information regarding the different aspects of our stack in the top level README.md: https://github.com/WordPress/openverse#openverse

It would be useful to have a documentation page on our docs site that goes further in-depth about the various pieces of our stack, with references to the related documentation and code for each entity (e.g. API, ingestion server, catalog, frontend).

**Comment by AetherUnbound** [comment]
Hi @zealshah29! I think it would be ideal to have the following for each section of the stack listed in the link above:
- Link to the folder for the service on GitHub
- Link to the documentation for the service on docs.openverse.org
- Primary language(s) for the project
- List of all of the tools/technologies/frameworks the services uses
    - Links to each of the above's documentation would be ideal as well

For example for the API, we'd have (respectively):
- _summary of the service_
- [Code](https://github.com/WordPress/openverse/tree/main/api)
- [Documentation](https://docs.openverse.org/api/index.html)
- Language: Python
- Tools & Frameworks: 
    - [Django REST framework](https://www.django-rest-framework.org/)

Having a list like for each part of the stack would be excellent!

**Comment by zealshah29** [comment]
Okay, got it! So shall I create a new page in the documentation folder? or shall I create a subfolder for the same within the documentation folder?
