### ISSUE TITLE
Add shim READMEs to service subfolders pointing to the documentation site

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse#3205]
## Description

We've moved most of our documentation to the documentation site (`documentation/` and docs.openverse.org), however we've historically had README.md files at the following top level folders:

- `catalog`: https://docs.openverse.org/catalog/index.html
- `api`: https://docs.openverse.org/api/index.html
- `ingestion_server`: https://docs.openverse.org/ingestion_server/index.html
- `frontend`: https://docs.openverse.org/frontend/index.html

We should add a shim README which points to the documentation page for each service (also linked above).

## Additional context

Related to #3204

**Comment by AlajeBash** [comment]
Hi i will like to contribute to this issue please assign me. Thanks

**Comment by dhruvkb** [comment]
Sure @AlajeBash, please take this up, thanks!
