### ISSUE TITLE
Do not produce reingestion workflow documentation if it matches regular workflow documentation

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse#3207]
## Description

Presently, our [DAG documentation generation](https://github.com/WordPress/openverse/blob/efbe123d9c860dab1c46878b04b320acb5fbb28d/catalog/utilities/dag_doc_gen/dag_doc_generation.py) script will generate documentation for all DAGs that define a `doc_md` on the DAG:

https://github.com/WordPress/openverse/blob/efbe123d9c860dab1c46878b04b320acb5fbb28d/catalog/utilities/dag_doc_gen/dag_doc_generation.py#L122

For some DAGs (namely reingestion workflows, where we reuse the same DAG machinery over different windows), this produces the exact same documentation multiple times. This is unnecessarily redundant, here's an example from Flickr:

- https://docs.openverse.org/catalog/reference/DAGs.html#flickr-workflow
- https://docs.openverse.org/catalog/reference/DAGs.html#flickr-reingestion-workflow

We should record the DAG doc text while iterating over the DAGs and skip producing documentation for any DAGs that have already matched a previous example exactly.

The easiest way to do this might be to record the doc markdown in a mapping from `doc markdown: dag ID`, then check for the doc markdown's presence in that mapping before producing the string. This is complicated by the fact that we want the original workflow (not the reingestion one) to be the DAG which receives the documentation, not the reingestion workflow.

We could also instead add some logic when coming across DAGs with `reingestion` in the DAG ID to find and check the original DAG and see if the docstrings match. If they don't match, then continue with processing as normal, otherwise skip.

**Comment by devansh83** [comment]
Hello, just to clarify, what you are suggesting is we create a map where the keys are the docstrings and the value is the DAG ID. We then search if the new docstring matches with any of the keys and if it doesn't we add it. As for reingestions, we add a condition where basically if the DAG ID contains reingestion, the key corresponding to the original DAG ID is compared to the docstring and if there is any change then the key is updated. 
If this is the case, I would like to work on this issue and it would be a great help if you could tell me how do I get the different DAG ID's and their corresponding docstrings.

Thanks.

**Comment by mattfergoda** [comment]
Please assign this one to me 😊
