### ISSUE TITLE
Remove references to using cURL in the API documentation

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse#3208]
## Description

We note "You can refer to the cURL request samples for examples on how to consume this endpoint." in every endpoint's description. This is redundant and unnecessary, we can likely remove this string entirely:

https://github.com/WordPress/openverse/blob/098925afa90b26881b4b4d3e2baffa69049692c0/api/api/docs/base_docs.py#L8-L11

**Comment by bermr** [comment]
Hi, just made a PR: https://github.com/WordPress/openverse/pull/3209 :)
