### ISSUE TITLE
`name` incorrectly used instead of `property` for OpenGraph tags

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse#3211]
## Description

OpenGraph tags for title, description, and image all incorrectly use a `name` instead of `property` attribute.

`<meta name="og:title" content="A super cool bird">` should be `<meta property="og:title" content="A super cool bird">`

To fix this, update the `createDetailPageMeta` function to use `property` instead of `name`: https://github.com/WordPress/openverse/blob/aa3a7f5b37f5baf590967b950aade0c18299e3cf/frontend/src/utils/og.ts

## Additional context

OpenGraph Protocol definition: https://ogp.me/#metadata

**Comment by dhruvkb** [comment]
I might be wrong but I remember reading that OpenGraph has a provision to fallback to the `name` attribute if a `property` attribute is not found. I'll try to see if I can find that documentation again.
