### ISSUE TITLE
Upgrade Ruff (and other pre-commit hooks)

### ISSUE THREAD

**Issue by dhruvkb** [WordPress/openverse#3212]
## Problem

Ruff recently [released `v0.1.0`](https://astral.sh/blog/ruff-v0.1.0). This reminds me that we do not currently have a way to automatically update our pre-commit hooks like we have Dependabot for Python and Node.js packages, and Renovate for GitHub Actions.

## Description

Update our pre-commit hooks. A potential further improvement would be to find, recommend and/or implement some action that can automatically update the hooks periodically (like Dependabot does at the start of each month).

## Additional context

pre-commit, our linting and hooks framework of choice, has [built-in support for updating hooks](https://pre-commit.com/#pre-commit-autoupdate) using the `autoupdate` subcommand.

**Comment by dhruvkb** [comment]
Yes @agnes-sharan it is open. I'll assign it to you.

**Comment by sarayourfriend** [comment]
This was resolved by #3312.
