### ISSUE TITLE
Replace upper case licenses with lower case ones in catalog database

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse#3222]
## Problem

The catalog has two variants for CC0 and PDM licenses: upper case and lower case ones. 
```
select license, count(license) as amount from image group by license;
+--------------+-----------+
| license      | amount    |
|--------------+-----------|
| cc0          | 21040903  |
| CC0          | 207167    |
| pdm          | 14088617  |
| PDM          | 348539    |
+--------------+-----------+
```
While this does not affect search in the API (because we lower-case the licenses when indexing them into Elasticsearch), we still should standardize the licenses in the catalog.

## Description

Run the `batched_update` DAG in Airflow with the following queries:
1. CC0
- `select_query`: `WHERE license='CC0'`
- `update_query` `SET license='cc0'`
2. PDM
- `select_query`: `WHERE license='PDM'`
- `update_query`: `SET license='pdm'`

## Alternatives

We could run the update query in `psql`, especially considering the number of affected items (less than 600 000), but it's better for catalog performance to use the `batched_update` DAG.

**Comment by obulat** [comment]
> Upstream Batched Update | prod
APP  [8:13 AM]
Updated 207,167 records for query: CC0_sync

The `batched_update` DAG for CC0 finished in 61 minutes

**Comment by obulat** [comment]
> Upstream Batched Update | prod
APP 
Updated 348,539 records for query: PDM_sync

The `batched_update` DAG for PDM finished in 71 minutes.

**Comment by AetherUnbound** [comment]
@obulat we also have some marked as `publicdomain`, should we do another batched update for those as well to change them to `pdm`? There are only 231 records.

**Comment by obulat** [comment]
> @obulat we also have some marked as `publicdomain`, should we do another batched update for those as well to change them to `pdm`? There are only 231 records.

Those are a different license than pdm: a combination of PDM and CC0 that's been retired. More on them here: https://creativecommons.org/retiredlicenses/
