### ISSUE TITLE
Remove `just` output from CI job

### ISSUE THREAD

**Issue by dhruvkb** [WordPress/openverse#3223]
## Description

The CI job runs `just` without any arguments and prints a beautiful, albeit redundant, list of all available recipes. This should be removed.

## Reproduction

See [this log](https://github.com/WordPress/openverse/actions/runs/6570432186/job/17847941436).

**Comment by ngken0995** [comment]
@dhruvkb I believe the [install recipe parameter is empty](https://github.com/WordPress/openverse/blob/0d95b6213472be1a737e2bf3bee211c582457b78/.github/workflows/ci_cd.yml#L368) then a run `just` prints a list of all available recipes. There is a
[condition](https://github.com/WordPress/openverse/blob/0d95b6213472be1a737e2bf3bee211c582457b78/.github/actions/setup-env/action.yml#L68) to turn off the install deps off by stating it as `false`. Can I work on this?

**Comment by bermr** [comment]
Sorry @ngken0995, didn't see your comment. I did something like what you said.
