### ISSUE TITLE
Duplication in API logging

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse#3237]
## Problem

In the django container logs, we also have two very similar logs for one request. The main difference I see between them is the lack of request id in one of them, so I'm not sure if it's possible to combine them:

<timestamp> | [2023-10-03 15:15:09,480 - gunicorn.access - 363][INFO] 127.0.0.1 - - [03/Oct/2023:15:15:09 +0000] "GET /v1/audio/2ecd1fbf-8122-47e8-84db-50c8ce19c04a/ HTTP/1.0" 200 1682 "-" "Openverse/0.1 (https://openverse.org; openverse@wordpress.org)" | task_id | django

<timestamp> | [2023-10-03 15:15:09,479 - log_request_id.middleware - 55][INFO] <task_id> method=GET path=/v1/audio/2ecd1fbf-8122-47e8-84db-50c8ce19c04a/ status=200

We should probably silence the gunicorn access log because it logs the same information as the log_request_id.middleware, but it doesn't have access to the request id. 

> **Note**
>
> This issue was written when we still used Gunicorn. We use uvicorn now. The description is up-to-date for our current stack.

## Description

Disable uvicorn's access logging by setting `no_access_log=True` in `api/run.py` in the call to start uvicorn.

**Comment by sarayourfriend** [comment]
This was solved in production by setting the log level higher than INFO. We've dropped it back down to info, so to solve this, we need some small configuration changes. Namely, we just need to disable uvicorn's request logging: https://www.uvicorn.org/settings/#logging

I'll update the issue description with instructions.
