### ISSUE TITLE
Remove `this` from `VGridSkeleton` props `default` 

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse#3268]
## Problem

`VGridSkeleton` uses `this` in the props' `default` function. This causes a build error in Vue 3.
https://github.com/WordPress/openverse/blob/964c5cca996ad0073318a01f4637df64956cd7e1/frontend/src/components/VSkeleton/VGridSkeleton.vue#L45-L52

## Description

The setting of the default element count should be moved to the `setup` function:

```
const elementCount = computed(() => {
  if (props.numElems) return props.numElems
   if (props.isForTab === "all") return 20
   if (props.isForTab === "image") return 30
   return 8
})
```

The `numElems` would need to be replaced with `elementCount` in the `template`, too.

**Comment by Ashhar-24** [comment]
Hey, I'm interested to work on this issue. 
Could you please guide me how to solve this issue, as I'm a beginner in Open Source :D
Thanks

**Comment by obulat** [comment]
> Hey, I'm interested to work on this issue. 
> Could you please guide me how to solve this issue, as I'm a beginner in Open Source :D
> Thanks

Sure, @Ashhar-24 !

You can set up the app locally using this guide: https://docs.openverse.org/frontend/guides/quickstart.html

Then you will need to change the `VGridSkeleton.vue` file as describe in the issue. Don't forget to create a branch on your fork of the Openverse repository for your changes,  don't open a PR from your `main` branch.

**Comment by Ashhar-24** [comment]
Ok thanks @obulat .

**Comment by Ashhar-24** [comment]
@obulat Kindly review my latest PR request `3341` and suggest changes if required.
