### ISSUE TITLE
"Week in Openverse" posts are broken

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse#327]
## Description

The 'a week in Openverse' posts on https://make.wordpress.org/openverse are broken. It looks like the last one was in March:

https://make.wordpress.org/openverse/tag/week-in-openverse/

We should fix these! I actually do not recall how or where the script for them was working. CC @dhruvkb, the original author.

**Comment by AetherUnbound** [comment]
I believe the script lives in this repo! https://github.com/WordPress/openverse/blob/main/automations/js/src/last_week_tonight.js

**Comment by AetherUnbound** [comment]
Indeed it looks like the actions have been failing for a little bit: https://github.com/WordPress/openverse/actions/workflows/weekly_updates.yml

Looks like an `npm` issue? https://github.com/WordPress/openverse/actions/runs/3357677596/jobs/5563664104
