### ISSUE TITLE
Removing the "Implementation" section from our issue templates

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse#329]
## Assigned reviewers

- [x] @dhruvkb
- [ ] @zackkrida

## Description

All of our issue templates have an "Implementation" section with the following:

> ## Implementation
> 
> - [ ] 🙋 I would be interested in implementing this feature.

I believe the intent behind this was to give an option to community members who submit issues to request that they implement said issues. However, most of our issues are submitted by maintainers and we have a different process for prioritization & backlog pruning. Additionally, folks can always request to work on an issue they submit within the body of the ticket. I have not (per my memory) seen this field used by a community member when submitting an issue, and in fact [this flag was only used once by issue authors who were not submitted by maintainers](https://github.com/WordPress/openverse-catalog/issues/661) ([as far as my search revealed](https://github.com/WordPress/openverse-catalog/search?q=is%3Aissue+in%3Abody+%22%5Bx%5D+%F0%9F%99%8B%22+-author%3Aobulat+-author%3AAetherUnbound+-author%3Akrysal+-author%3Astacimc+-author%3Asarayourfriend+-author%3Azackkrida+-author%3Adhruvkb&type=issues)). Lastly, while this field is a checkbox it is not editable by community members for tickets maintainers have submitted, so it is functionally redundant with the issues "Assigned" property.

All that said, would anyone object to removing this section from all of our issue templates?

**Comment by dhruvkb** [comment]
It makes sense to remove it. It's only use was for community contributors who open issues to indicate that they would also like to be the one to fix it. That way the person triaging could assign it to them after determining the validity of the issue.

A simple `<!-- If you would like to work on this, please comment below separately. -->` could be enough to replace that checkbox.

**Comment by zackkrida** [comment]
I support this change and the suggested approach 👍

**Comment by tahmid-ul** [comment]
I would like to work on this issue. 

Before sending a PR I do have a question. Should I remove the entire Implementation section including the heading or just the checkbox? 

I have found this section in two templates - Bug Report and Feature Request. I guess the section should be removed from both templates?

**Comment by dhruvkb** [comment]
@tahmid-ul we want to remove the entire section, with the heading included and replace it with the comment: `<!-- If you would like to work on this, please comment below separately. -->`

The section should be removed from all templates where it occurs.
