### ISSUE TITLE
Related endpoint returns 500 if the main item is not found in ES index

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse#3349]
## Problem

For the related endpoint, we first search for the item in ES index to get its title, tags and creator.

https://github.com/WordPress/openverse/blob/5e55faa84e3fdfb3f7ac5ad9de041bb0056eacf6/api/api/controllers/elasticsearch/related.py#L30

When the `identifier` part of the URL matches the UUID regex, but there's no media item with such an `identifier`, this request doesn't return anything, so this request returns 500 ("Could not find items"). It should return 404 instead, using `raise APIException("Not found.", 404)`

## Description

If the ES request does not return the item, we should return a 404 error.

**Comment by ngken0995** [comment]
@obulat This might be related to #3520. Here is a comment @dhruvkb wrote. [link](https://github.com/WordPress/openverse/blob/ddec27d7f8f5548b548b568c22a6f955536f1510/api/api/controllers/elasticsearch/related.py#L30C6-L30C6)

**Comment by obulat** [comment]
You're right, @ngken0995. Thank you for catching this.
Fixed by #3552.
