### ISSUE TITLE
Endless loading while running dev

### ISSUE THREAD

**Issue by fcoveram** [WordPress/openverse#3379]
## Description

During the last PR reviews, I've been struggling to load pages while running dev with `just frontend/run dev`. Sometimes the page loads correctly; many times it loads just part of the interface, and others, it keeps loading without any timeout. I keep refreshing the page and luckily see everything, but even when rerunning dev and/or deleting the branch, the problem is still there.

This is making the review process harder and other folks might have faced the same issue.

## Reproduction

Here is a screen recording of my process.

https://github.com/WordPress/openverse/assets/895819/ed322526-fbcb-4872-a72d-7b3cd4baa53a

## Environment

- Device: Macbook M1 Pro 14'' 2021
- OS: Sonoma 14.1.1
- Browser: Chrome (119.0.6045.159) and Firefox (119.0.1)

**Comment by sarayourfriend** [comment]
@fcoveram have you run into this recently? Nuxt 3 should have improved things overall with running the frontend, including some additional messages in the console that would help us understand what went wrong when it wouldn't load. If you haven't seen it recently, do you mind if we close the issue?

**Comment by fcoveram** [comment]
Not anymore. It has been fixed ✨
