### ISSUE TITLE
Redis 7.x upgrade

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse#3382]
| Start Date | ETA        | Project Lead | Actual Ship Date |
| ---------- | ---------- | ------------ | ---------------- |
| 2023-11-21 | YYYY-MM-DD | TBD          | TBD              |

## Description

Our Redis clusters are currently two versions behind, and need to be upgraded to the latest version since 5.x is EOL.

## Documents

- [ ] Implementation Plan(s)

## Issues

- [x] https://github.com/WordPress/openverse/issues/3385
- [x] https://github.com/WordPress/openverse-infrastructure/issues/611

## Prior Art

- The [Elasticsearch 8 upgrade](https://github.com/WordPress/openverse-infrastructure/issues/553)

**Comment by dhruvkb** [comment]
Redis has been upgraded to v7.1 in both staging and production. This is the latest version available through AWS Elasticache.

The approach we took was to make the API capable of working (even if the performance is a bit degraded) when Redis is inaccessible (https://github.com/WordPress/openverse/pull/3505) and then upgraded Redis using the AWS management console UI. We monitored user endpoints through a k6 script (https://github.com/WordPress/openverse/pull/3575). For most of the migration, Redis stayed available for reads and writes and the switchover did not cause any spikes in 5xx errors. Then the infrastructure resource was updated to match the values of the actual Elasticache instance (https://github.com/WordPress/openverse-infrastructure/pull/739).
