### ISSUE TITLE
Make API resilient to a Redis outage

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse#3385]
## Description

Presently, our API relies heavily on Redis and expects it to be highly available. This can be seen by performing the following:

1. `just a` (start the API)
2. `docker stop openenverse-cache-1`
3. Visit http://localhost:50270/v1/images/?q=cat

This high dependence on Redis makes it difficult for us to make changes to the cache, e.g. version upgrades like #3382.

We will need to build some resiliency into the API in every instance where one of the caches is used:

https://github.com/WordPress/openverse/blob/38642838852151a38951e1641726588bb273a670/api/conf/settings/databases.py#L47-L59

In cases where we can continue without the cache (even at the detriment to performance), we should continue execution. If cache is absolutely required for a certain operation, we might issue an HTTP 424 for the request (though perhaps a 500 would make more sense?).

## Additional context

This is part of the larger effort around upgrading Redis, see #3382

**Comment by sarayourfriend** [comment]
> we might issue an HTTP 424 for the request (though perhaps a 500 would make more sense?).

I think 424 is the right option if we can handle it _somehow_. I think 5xx generally means "something unexpected went wrong and we don't know why"?
