### ISSUE TITLE
Add ESLint rules to mandate braces around `if`-`else` and `switch`-`case`

### ISSUE THREAD

**Issue by dhruvkb** [WordPress/openverse#3386]
## Problem

Currently it's possible to write one-line `if`-`else` statements without braces. It's also possible to write `case` blocks inside `switch` without braces.

## Description

The lack of braces is easier to read initially but makes it possible to make errors when adding more statements to these constructs or updating code in the future.

Mandating braces with ESLint (with the possibility to autofix can prevent these problems.

## Additional context

This scope for improvement to our ESLint config was raised in the review for #3375.

**Comment by bhavik001** [comment]
Hello @dhruvkb !
Can you assign me this issue I am interested in working on it!

**Comment by bhavik001** [comment]
Hey @dhruvkb !
Can you please review the new update that I have added? And let me know if I have to make any changes then.

**Comment by bhavik001** [comment]
Hey @dhruvkb  I will gonna create new pull request.

**Comment by bhavik001** [comment]
Hey @dhruvkb ! can you check my pull request. And Let me know if I have to update anything.

**Comment by bhavik001** [comment]
Hey @dhruvkb !
Can you please review the code that I have added in packages\eslint-plugin\src\rules\analytics-configuration.ts

**Comment by dhruvkb** [comment]
Hey @bhavik001 I've reviewed the PR and suggested some changes. It's really great and proceeding in the right direction but it still needs some additional work. Let's continue this discussion regarding the PR there.

**Comment by bhavik001** [comment]
Hey 
Let me know if everything is good or if I have to make any changes. Also can you merge the code after reviewing?
