### ISSUE TITLE
Use the `batched_update` DAG with stored CSVs to update Catalog URLs

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse#3415]
## Problem

We have generated some CSVs with `identifier` and another column that we need to use to update the Catalog media table, but we don't have a way to efficiently run the media table updates.

## Description

The batched update DAG is reusable DAG which can be used to perform an arbitrary batched update on a Catalog media table, while handling deadlocking and timeout concerns.
During the cleanup process in data refresh, we generate the CSVs that contain the item `identifier` and the cleaned up version of another column (`title`, `url`, `foreign_landing_url`, `creator_url` and ~`tags`~). We need a DAG that is similar to the batched update DAG, but can use a CSV table for selecting the items that need to be updated.

It is important that this work does not _delete_ any tags. The tag column, while present in the CSVs, should _not_ be used.

## Additional context

The CSV files are saved in the docker container of the ingestion server when we run data refresh.

**Comment by zackkrida** [comment]
This was [discussed](https://make.wordpress.org/openverse/2024/05/20/openverse-monthly-priorities-meeting-2024-06-05/#comment-282) in today's priorities meeting. We decided to move forward with this PR but _only_ apply updates to URLs. We do not want to delete any data (tags in this case). 

The accuracy threshold filtering of existing will now be preserved and iterated on as part of the [Removal of the ingestion server](https://github.com/WordPress/openverse/issues/3925#top) [#3925](https://core.trac.wordpress.org/ticket/3925) project.
