### ISSUE TITLE
Handle exceptions from ingestion server's calls to Elasticsearch

### ISSUE THREAD

**Issue by dhruvkb** [WordPress/openverse#3437]
## Description

Handle exceptions from ingestion server's calls to Elasticsearch.

## Example

The following calls to Elasticsearch to create a new index can raise an exception, if that index already exists.

```
BadRequestError(400, 'resource_already_exists_exception', 'index [image-init-filtered/-jGDxWxbQS-_SdarNzk34g] already exists')
```

https://github.com/WordPress/openverse/blob/46b6b931f5f9fcf01bc53f47e8e6b944a40f8720/ingestion_server/ingestion_server/indexer.py#L302-L305

https://github.com/WordPress/openverse/blob/46b6b931f5f9fcf01bc53f47e8e6b944a40f8720/ingestion_server/ingestion_server/indexer.py#L499-L502

This exception is not handled in the code. It should be captured and should mark the appropriate task as 'succeeded' in this particular case because the task is idempotent and the index has been created.

## Additional context

This exception was captured by Sentry.

**Comment by AetherUnbound** [comment]
After looking into this, it looks like all of the events related to this error are in the `local` environment. Additionally, I feel like that piece of the code _should_ fail the way it's currently set up to do in production; the attempted recreation of an existing index, while idempotent at that particular step, would likely mean a failure elsewhere in our process. It'd be best for execution to stop here in that case I think! 

I'm going to close this issue for now.
