### ISSUE TITLE
Replace unmaintained `sugarshin/required-labels-action` GH action

### ISSUE THREAD

**Issue by krysal** [WordPress/openverse#344]
## Problem
We're getting warnings from workflows using this action, see for example https://github.com/WordPress/openverse-catalog/actions/runs/3653606401

No further support seems to be forthcoming since the [last update was on February 2020](https://github.com/sugarshin/required-labels-action/releases). So we would need to replace it sooner or later.

## Description

Change to use [agilepathway/label-checker](https://github.com/agilepathway/label-checker) or any other updated action.

**Comment by sharmadhiraj86** [comment]
Hi I would like to solve the issue .Can you let me know how and where I should make the changes.

**Comment by dhruvkb** [comment]
Sure @sharmadhiraj86, you can work on it. You will need to update the `pr_label_check.yml` workflow @ https://github.com/WordPress/openverse/blob/0a513611e57074dd6546633dfad930bb43d006e3/.github/workflows/pr_label_check.yml to use the new action mentioned in the issue.
