### ISSUE TITLE
Categorise weekly updates by stack

### ISSUE THREAD

**Issue by dhruvkb** [WordPress/openverse#3445]
## Problem

The current [weekly update posts](https://make.wordpress.org/openverse/tag/week-in-openverse/) created by the [`last_week_tonight.mjs` script](https://github.com/WordPress/openverse/blob/main/automations/js/src/last_week_tonight.mjs) puts every change from every PR and every closed issue into one big changelog. That's not very good and it makes the changes hard to understand.

## Description

Earlier, when we did not have a monorepo, the changelog used to be very neatly organised. We can achieve the same again, using the "stack" labels that were introduced during monorepo-ification.

## Additional changelog

- [Current Make post example](https://make.wordpress.org/openverse/?p=1260)
- [Pre-monorepo Make post example](https://make.wordpress.org/openverse/?p=937)

**Comment by danielbmasud** [comment]
Hey I wanted to mention here that I'm working on this in tandem with [#3448](https://github.com/WordPress/openverse/issues/3448)

**Comment by dhruvkb** [comment]
Awesome @danielbmasud! In that case, I'll assign this to you as well.

**Comment by zackkrida** [comment]
Hi @danielbmasud, I've unassigned you from this issue. If you would like to work on it again in the future please let us know. Thanks!

**Comment by AetherUnbound** [comment]
Saving these links as they're helpful in understanding the shape of data returned and what to do with it:
- https://docs.github.com/en/rest/search/search?apiVersion=2022-11-28#search-issues-and-pull-requests
- https://octokit.github.io/rest.js/v20#search
