### ISSUE TITLE
Add a check on startup to ensure application is not using default key in live environments

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse#3456]
## Description

In #3422, we altered the Django secret key to use a more obvious shim value. @dhruvkb suggested:

> We can also update settings.py to raise an error if it's unchanged.

To be specific, we should check to ensure that the value is not `example_key` in any `ENVIRONMENT` that's not `local` or `development`, and raise an appropriate error if it is.

**Comment by sarayourfriend** [comment]
This would be the exception to raise for an issue of this nature: https://docs.djangoproject.com/en/4.2/ref/exceptions/#improperlyconfigured

**Comment by firatbezir** [comment]
Can i give it a shot?

**Comment by sarayourfriend** [comment]
I've assiged it to you @firatbezir, go for it :slightly_smiling_face:

**Comment by obulat** [comment]
> To be specific, we should check to ensure that the value is not `example_key` in any `ENVIRONMENT` that's not `local` or `development`, and raise an appropriate error if it is.

How do you get the `example_key` for all environments in Django settings?

**Comment by sarayourfriend** [comment]
I _think_ Madison meant `example_key` as a literal string, like `"example_key" != actual_value`? Can you confirm @AetherUnbound?

**Comment by AetherUnbound** [comment]
That's correct!
