### ISSUE TITLE
Replace cURL to Slack with `slackapi/slack-github-action`

### ISSUE THREAD

**Issue by dhruvkb** [WordPress/openverse#3461]
## Problem

The following workflows make Slack API calls using a cURL request.

- https://github.com/WordPress/openverse/blob/c312886d98bc74f5a67caef4cdf2eaf046c0c313/.github/workflows/discussion_ping.yml#L23-L27
- https://github.com/WordPress/openverse/blob/c312886d98bc74f5a67caef4cdf2eaf046c0c313/.github/workflows/pr_limit_reminders.yml#L38-L47
- https://github.com/WordPress/openverse/blob/c312886d98bc74f5a67caef4cdf2eaf046c0c313/.github/workflows/pr_ping.yml#L31-L35
- https://github.com/WordPress/openverse/blob/c312886d98bc74f5a67caef4cdf2eaf046c0c313/.github/workflows/pr_ping.yml#L40-L44

## Description

A better approach is to use the (official?) [Slack API action `slackapi/slack-github-action@v1.23.0`](https://github.com/slackapi/slack-github-action) by means of [technique 3 i.e. incoming webhooks](https://github.com/slackapi/slack-github-action#technique-3-slack-incoming-webhook). These workflows can be coverted to that actions making them more maintainable because cURL and Bash (and especially together) can be notoriously hard to understand and make changes to.

**Comment by The5cheduler** [comment]
I would like to contribute to this!
Please assign it to me.

**Comment by The5cheduler** [comment]
Hey, I think current version of slackapi/slack-github-action is 1.24.0. I have used that in current change, please let me know if it need ot me 1.23.0 for any particular reason.
