### ISSUE TITLE
PRs that both have changes requested and are drafted should be in the drafted column of the PR board

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse#3467]
## Description

It appears that if a PR both has changes requested _and_ is drafted, it shows up in the "changes requested" column of the PR board. The maintainer team usually uses drafting a PR as knowing that it requires further changes or additional work, any drafted PR should go into the drafted column regardless of how many reviews it has (or what the state of those reviews are).

## Screenshots

![Screenshot 2023-12-05_13-20-06](https://github.com/WordPress/openverse/assets/10214785/f908a144-494d-44e4-88f6-b35169c48efc)

**Comment by dhruvkb** [comment]
This is how the workflow is currently defined.

- If a PR is converted to draft it will be moved to the Draft column. This is regardless of the number of reviews and their type.
- However, if a PR that's drafted gets reviewed, it will be moved to the appropriate column as per the type of the review and count of reviews.

The issue in the screenshot seems to be match the second case.

The way to fix this would be to check `pr.isDraft` in this code branch and not invoke `syncReviews()` if the PR is a draft.
https://github.com/WordPress/openverse/blob/b004dc620897d832fefa01c97a4fe16206adc713/automations/js/src/project_automation/prs.mjs#L62-L64

```diff
  if (eventName === 'pull_request_review') {
-   await syncReviews(pr, prBoard, prCard)
+   if (pr.isDraft) {
+     await prBoard.moveCard(prCard.id, prBoard.columns.Draft)
+   } else {
+     await syncReviews(pr, prBoard, prCard)
+   }
  } else {
```

**Comment by The5cheduler** [comment]
I would love contribute to this project!
Please assign it to me.
