### ISSUE TITLE
Add a "notes" field to `ContentProvider`

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse#3470]
## Description

Reading through #3393, I realized that we don't have a mechanism for easily tracking _why_ we made certain changes to content providers (e.g., why `Flora-On` content is currently hidden). I think adding a `notes` field to the `ContenProvider` table might be an easy way for maintainers to add notes about what actions were taken on a provider and when, to help us remember down the line.

## Alternatives

An audit trail with reasons might be possible, but seems like it may be more work than what's necessary in this case.

**Comment by dhruvkb** [comment]
Not opposed to it, but I am not sure if that's something that should be in the database for the model or better recorded in our discussion/knowledge areas like Slack, P2s, docs, GitHub issues and PR descriptions. 

I get that we have are so many of them and they are so disjointed, which makes finding anything across all of them is a terrible experience, but I still feel weird about storing notes and explanations in the DB rows.

Again not opposed to it, just slightly uncomfortable.

**Comment by dhruvkb** [comment]
Wait, there already is one!

https://github.com/WordPress/openverse/blob/8b0ec498e12d73a0fc3499a5a8f5753911b2fe9c/api/api/models/models.py#L30

**Comment by AetherUnbound** [comment]
Wait, why isn't it available on the Admin UI then @dhruvkb? 😮 
![image](https://github.com/WordPress/openverse/assets/10214785/1e32d166-01f1-45d5-a907-583e0cdab2ca)

**Comment by AetherUnbound** [comment]
Ah, presumably because of this exclusion:

https://github.com/WordPress/openverse/blob/098925afa90b26881b4b4d3e2baffa69049692c0/api/api/admin/__init__.py#L85

Do you think we could remove that exclusion? It seems weird to me _not_ to have that available on the Admin UI 🤔

**Comment by AetherUnbound** [comment]
Apparently this was added here 😅 

https://github.com/WordPress/openverse-api/commit/d6f4d399bd4012a6b3dd81ac891720d743266466

I think we could just remove this and re-expose the notes field, what do you think @dhruvkb?
