### ISSUE TITLE
Set up staging ingestion server connection in Airflow

### ISSUE THREAD

**Issue by stacimc** [WordPress/openverse#3492]
## Problem

#3232 created a DAG for creating staging ES indices, which works by connecting to the staging ingestion server. In order to use the DAG we need to set up an Airflow connection to the staging ingestion server.

## Description

First we should add an official DNS name to the staging data refresh server. Then we'll add the connection to Airflow using an Airflow variable `AIRFLOW_CONN_STAGING_DATA_REFRESH`.

**Comment by AetherUnbound** [comment]
This connection has been added!
![image](https://github.com/WordPress/openverse/assets/10214785/8827598a-5597-4d48-aea2-90548e4bedf9)
