### ISSUE TITLE
Link to source on creator view

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse#3496]
## Description

It might be nice to link the source on the creator view, given that we have that information and are displaying it anyway.

**Example**:

1. Visit https://staging.openverse.org/preferences and enable `additional_search_views`
2. Visit https://staging.openverse.org/image/source/smithsonian_air_and_space_museum/creator/Unknown/
3. The source name should be clicked on too

## Alternatives

Not sure if this is necessary or ideal, but just something I thought while navigating through the pages.

## Additional context

Related to #410

**Comment by krysal** [comment]
This is a more interesting case, actually. I'll assume the creator is not really named "Unknow," but we don't know who the creator is. How is this case being handled? Do we show all the unknown creator's works under that source?

CC @obulat @sarayourfriend

**Comment by sarayourfriend** [comment]
@krysal I've opened https://github.com/WordPress/openverse/discussions/3508 to avoid pulling the discussion here off of the issue Madison originally opened, which might need its own conversation here.

**Comment by obulat** [comment]
@fcoveram, could you update the creator view design with the source link, if you agree with this feature?

**Comment by fcoveram** [comment]
Here is an idea already applied in the mockups

![Mockup of creator view. Header area and link to source are highlighted](https://github.com/WordPress/openverse/assets/895819/a16b07d5-7fd7-4d39-99b0-8e498f9bfd01)

I had to hack the frame element in Figma as wrapping a link component in two lines is not possible, but the visual outcome is the main point in the design.
