### ISSUE TITLE
"Back to Results" button doesn't work when Report content modal is open

### ISSUE THREAD

**Issue by stacimc** [WordPress/openverse#3513]
## Reproduction

1. Make a search in Openverse, for any search term (example 'swan')
2. Click on any individual result to go to the single result page (example http://localhost:8443/image/0e3f0106-2cc0-4450-9424-a7b8738d2352?q=swan)
3. Click the `Report this content` button to open the Report Content modal
4. Go back to the top of the page and click the "Back to Results" button, without closing the modal
5. Observe that the button does not work

## Screenshots

<img width="1165" alt="Screenshot 2023-12-11 at 1 48 23 PM" src="https://github.com/WordPress/openverse/assets/63313398/ef7188aa-58b0-4c46-926e-e659a5fa8855">

**Comment by obulat** [comment]
Fixed in #4701
