### ISSUE TITLE
Add Openverse cookie information to WP.org cookie policy

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse#352]
## Problem

As Openverse is covered by WP.org's privacy policy, we should request an update to the text content on https://wordpress.org/about/privacy/cookies/ to include details about the cookies used in wordpress.org/openverse.

Someone will need to identify the cookie(s) in Openverse and provide the information used by the tables on the WP.org page:

Cookie | Duration | Purpose | Logged-in Users Only?
-- | -- | -- | --

**Comment by obulat** [comment]
Openverse is using a separate domain, openverse.org, so this is not necessary anymore
