### ISSUE TITLE
Add an `aspect: data` label?

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse#3574]
## Description

We've had a few issue recently (#3573, #3499, #3530, #3393, etc.) that seem to be more related to our _data_ than our _code_. I think we might be served by having an additional `aspect` label for data related work. Potentially `📚 aspect: data`!

If folks are generally positive about this, we'll need to add this new label to the `labels.yml` definition file: https://github.com/WordPress/openverse/blob/6da2118ade7acff7035abb0df42e17578e8ecab3/automations/data/labels.yml#L115

**Comment by firatbezir** [comment]
Can i pick this up?
