### ISSUE TITLE
Modal popover for report and license definition

### ISSUE THREAD

**Issue by fcoveram** [WordPress/openverse#3582]
## Problem
As reported in #569, reporting content is currently made from a popover that looks broken on small screens. Based on the recent Design Library updates, we can improve this, and also the license definition popover, by reusing the component merged in #2860

### Issues related

- Report of a broken popover in #569
- The basis for a future suggested in #645
- Modal specs in #2860

### Search results page

Since the license description element is toggled from the drawer in small screens, I have two ideas that I would like your thoughts on.

#### v1. Replace drawer with the license

In this first version, once you click on the license’s question icon, the drawer disappears and is replaced by the license popover. You can see how the results grid is visible behind the modal layer.

<img width="2740" alt="Drawer  v1" src="https://github.com/WordPress/openverse/assets/895819/64ba8298-40d5-46b8-aab6-659d3b4efbbe">

#### v2. Push the drawer behind modal opaque layer 

The second idea is to push the drawer behind the modal layer to avoid losing the context of where users displayed the info from. See how the drawer remains behind the dark layer.

I am more drawn to this version as contexts in modals play a key role.

<img width="2740" alt="Drawer  v2" src="https://github.com/WordPress/openverse/assets/895819/342d9fe2-5bff-4b69-a9e5-e7b9006e5d33">

#### From `LG` and beyond

On bigger screens, the license description popover is displayed as in the current flow.

<img width="2890" alt="Results with modal popover" src="https://github.com/WordPress/openverse/assets/895819/f4d631f0-8be3-466c-affb-8f1fdfb224f1">

### Single result page

In the single result page, the popover shows up as in the current flow.

<img width="2740" alt="Single result page with modal popover" src="https://github.com/WordPress/openverse/assets/895819/9b861979-2c15-4b4b-a558-48db7d66d475">

## Popovers

As described in #2860, the following specs are still valid:

- Popover is centered, full width, and has a max value of 400px.
- On `xs` , horizontal margins `24px`

However, I noticed that we did not consider a scrollable popover for those cases where its height overflows the device screen. For that case, I tried the following:

<img width="500" alt="Scrollable popover behavior" src="https://github.com/WordPress/openverse/assets/895819/3079d0b4-9437-4c9a-b55c-c6d326ee3d28">

The spacings mirror the ones applied to the current component, but instead of wrapping the content with a single element, the popover's header is separated to keep it sticky when scrolling down. Below a screenshot of dev mode.

<img width="400" alt="Popover with notes in header" src="https://github.com/WordPress/openverse/assets/895819/184bf9d1-cb69-4ec3-a0c2-dcac6602dd60">

## Mockups

Figma file: [Modal popover for report and license definition](https://www.figma.com/file/chRWINXqyRzYRPZOJOJHuD/Modal-popover-for-report-and-license-definition?type=design&node-id=22-13656&mode=dev)

**Comment by sarayourfriend** [comment]
FWIW I agree that the additional context in v2 makes a lot of sense to me. As a bonus, it would also reduce the number of visual changes happening on the screen as you click into each license popover and back to the filters.

**Comment by fcoveram** [comment]
The mockups for v2 (Push the drawer behind the modal opaque layer) were updated with the latest changes and are ready for dev.

**Comment by zackkrida** [comment]
This looks great, thank you @fcoveram

**Comment by obulat** [comment]
Blocked by the code freeze during Nuxt 3 migration.
