### ISSUE TITLE
Update Catalog of Life data source url for iNaturalist DAG

### ISSUE THREAD

**Issue by rwidom** [WordPress/openverse#3631]
## Description

iNaturalist uses the [Catalog of Life](https://www.catalogueoflife.org/) dataset to include common names in image metadata. However, [the dataset URL is currently hard-coded and broken](https://github.com/WordPress/openverse/blob/f4320b91c53cffed8e68ac368d63abae4f56d7f6/catalog/dags/providers/provider_api_scripts/inaturalist.py#L220). The API at that URL returns [Error 404: "ColDP archive for dataset 9840 not found"](https://api.checklistbank.org/dataset/9840/export.zip?format=ColDP).

## Reproduction

Click the links above, and confirm results.

## Additional context

Let's reach out to the folks at Catalog of Life for advice and/or try to parse and use the download URL posted on [this page](https://www.catalogueoflife.org/data/download).

**Comment by rwidom** [comment]
@krysal, I just reached out to support@catalogueoflife.org for a more sustainable solution, but do you think I should just manually update the url for now?

**Comment by krysal** [comment]
@rwidom If you had identified an alternative working solution I believe is worth trying it while we await the iNaturalist response.

I set the priority thinking the reactivation of the DAG was blocked by this issue. Is this the case? If not then we can lower it to medium.
