### ISSUE TITLE
Establish preliminary Django admin access control for content moderator users

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse#3633]
## Description

See the following for implementation description and rationale: https://docs.openverse.org/projects/proposals/trust_and_safety/content_report_moderation/20231208-implementation_plan_django_admin_moderator_access.html#preliminary-access-control

**Comment by AetherUnbound** [comment]
The code change for this was pushed in #3899, and I've added the `Content Moderator` group with the following permissions:

![image](https://github.com/WordPress/openverse/assets/10214785/9fa92f62-f3b3-4777-a62f-258e05f311f4)

I'm not sure if `view` on the media tables themselves need to be added - but we can always add that down the line.
