### ISSUE TITLE
Create new content report Django admin table view

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse#3635]
## Description

We will scrap the existing reports view in the Django Admin UI. Instead of showing a list of reports, we’ll show a list of reported media, sorted by the total number of pending reports, and then by the age of the oldest pending report. This will have the effect of sorting re-reported works to the top of the list, under the assumption that a work with multiple pending reports is probably higher priority, because a decision to report it was taken multiple times. By default, we will only show works with “pending” reports (reports where `decision_id = NULL`). This creates a queue to work through progressively, from top to bottom. Remove any manual sorting options for now. We can add those back if we get feedback that moderators want them, but for now they just clutter and confuse the interface, and make the foundational feature more complex.

Said another way:
- Create a new view based on the media object default model view but sort media by pending report count and the oldest report’s age
- Exclude media items that have no reports
- Filter to only show media with pending reports by default, but allow showing all reported media

## Context

See the following for implementation description and rationale: https://docs.openverse.org/projects/proposals/trust_and_safety/content_report_moderation/20231208-implementation_plan_django_admin_moderator_access.html#id2

**Comment by AetherUnbound** [comment]
Based on the necessary presence of the `decision_id = NULL` check, this is actually blocked by #3636

**Comment by dhruvkb** [comment]
#3636 has been resolved by #3989. This is now unblocked.
