### ISSUE TITLE
Create `ModerationDecision` table

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse#3636]
## Description

The plan for this has been modified slightly from the [description in the IP](https://docs.openverse.org/projects/proposals/trust_and_safety/content_report_moderation/20231208-implementation_plan_django_admin_moderator_access.html#id3) based on the subsequent [Bulk actions IP](https://docs.openverse.org/projects/proposals/trust_and_safety/content_report_moderation/20240122-implementation_plan_bulk_moderation_actions.html), so the full description (including updates) is written out below. Where it differs from the IP I have bolded the text so it is easier to see.

- Create the new ModerationDecision model with the following columns:
  - id: basic auto-incrementing id
  - created_on: the date the moderation decision was created, in other words, the date the decision was made
    - Provided by OpenLedgerModel
   - moderator_id: a foreign key relationship with moderator who made the decision
   - media_identifiers: a **many-to-many** relationship to the media the decision is related to, implemented by a join table.
     - Because deindexing media removes them from the API database, the identifiers needs to be non-constrained, so not a foreign key, just an indexed non-unique UUID column using the [`db_constrained` argument](https://docs.djangoproject.com/en/5.0/ref/models/fields/#django.db.models.ManyToManyField.db_constraint)
   - explanation: moderator notes explaining the decision; optional
   - action: slug column of the action taken
     - **`marked_sensitive`** (marked a work as sensitive)
     - `deindexed_copyright` (deindexed the work from Openverse search due to copyright)
     - `deindexed_sensitive` (deindexed the work from Openverse search due to sensitivity)
     - `rejected_reports` (the reviewed reports were rejected)
     - **`deduplicated_reports`** (the reviewed reports were marked as duplicates, in other words, re-reports that did not result in deindexing but were also accurate, for example, re-reports of a sensitive work that add information regarding sensitivity but do not require deindexing)
     - **`reversed_deindex`** (undo a previous deindexing decision)
     - **`reversed_mark_sensitive`** (undo a previous decision marking the record sensitive)
- Create an AbstractModerationDecision for each media type
- Add new nullable `decision_id` column to the Report models
- Remove all logic from the Report models’ `save` methods

Blocks https://github.com/WordPress/openverse/issues/3638, https://github.com/WordPress/openverse/issues/3641, https://github.com/WordPress/openverse/issues/3840, and https://github.com/WordPress/openverse/issues/3844

**Comment by dhruvkb** [comment]
This is blocked on #3719 which enables plural media identifiers and adds additional actions for the decision model.

**Comment by sarayourfriend** [comment]
Thank you, Staci!
