### ISSUE TITLE
Augment media admin view with moderation information

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse#3637]
## Description

See the following for implementation description and rationale. **This issue covers only the point 1 in the linked section.** https://docs.openverse.org/projects/proposals/trust_and_safety/content_report_moderation/20231208-implementation_plan_django_admin_moderator_access.html#id4

Blocks https://github.com/WordPress/openverse/issues/3638

**Comment by dhruvkb** [comment]
This would be blocked on #3636 as moderation decisions cannot be added to the admin view till the decision models have been created and the associated migrations have been applied.
