### ISSUE TITLE
Drop `status` column from content report tables

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse#3642]
## Description

See the following for implementation description and rationale: https://docs.openverse.org/projects/proposals/trust_and_safety/content_report_moderation/20231208-implementation_plan_django_admin_moderator_access.html#backfill-moderationdecision-and-drop-report-status

Blocked by ~#3641~ #4530 and the **re-run of the `backfillmoderationdecision` command**.

**Comment by dhruvkb** [comment]
This is not directly related to this project but I wanted to suggest inheriting from `OpenLedgerModel` in the report models (currently they do not, and instead use a custom field for `created_at`) which would introduce a migration so it's possible to run both migrations simultaneously to reduce the downtime on that table.

**Comment by sarayourfriend** [comment]
Good call! Unifying the date columns is a great idea, especially given how small the tables are at the moment. Would it require following the zero downtime migration policy? If so, we should create the issues for each part of the process, maybe as follow-up tasks to the project rather than part of it.

**Comment by AetherUnbound** [comment]
This is still blocked by https://github.com/WordPress/openverse/pull/4530, but can be tackled after that is run!

**Comment by krysal** [comment]
The backfill was run between Tuesday and Wednesday so this is unblocked.
