### ISSUE TITLE
[Nuxt 3] Re-add Storybook and Storybook tests

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse#3664]
## Problem

The Nuxt 3 migration branch removed Storybook. It needs to be added back.

## Description

The official Nuxt 3 module for Storybook is not updated to use the latest versions of Nuxt/Storybook. While it seems to mainly work, the SVG icons failed to load. There was also a problem with the Storybook lacking `theming` package.

**Comment by dhruvkb** [comment]
Closing for now as we've decided to attempt the Nuxt 3 migration again in a few months once the ecosystem is more mature.
