### ISSUE TITLE
[Nuxt 3] Re-add Prometheus module

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse#3665]
## Problem

The Nuxt 3 branch removed Prometheus module. It needs to be added back.

## Description

We should research if there are official modules for Prometheus. If not, the new implementation should use the Nitro layer to add Prometheus.

**Comment by dhruvkb** [comment]
Closing for now as we've decided to attempt the Nuxt 3 migration again in a few months once the ecosystem is more mature.
