### ISSUE TITLE
Integrate 'alex' to ensure our Markdown docs are considerate

### ISSUE THREAD

**Issue by dhruvkb** [WordPress/openverse#368]
## Problem

We have a lot of Markdown documents. Our linting process catches syntax errors but we don't have a system in place to catch insensitive or inconsiderate writing.

## Description

Alex (https://alexjs.com/) could help with that. It catches writing that can be insenstive or inconsiderate, and offers alternatives.

**Comment by sarayourfriend** [comment]
This can be implemented with a new documentation site CI job that utilises the GitHub action: https://github.com/marketplace/actions/alex-recommends

**Comment by sarayourfriend** [comment]
We won't use Alex due to issues discussed in #3065 as well as further discussions in the sensitive terms repository around Vale.
