### ISSUE TITLE
Prevent workflows specific to this repo and its management from running on forks

### ISSUE THREAD

**Issue by dhruvkb** [WordPress/openverse#3693]
## Description

We have a number of workflows for managing the `WordPress/openverse` and `WordPress/openverse-infrastructure` repositories that only make sense to run on this repo. These workflows should not run on forks. 

We can conditionally abort the workflow (by passing it, so that forks are not overrun with workflow failures) by comparing [`github.repository`](https://docs.github.com/en/actions/learn-github-actions/contexts#github-context) with the allowlisted names of the main/original/upstream repos.

## Reproduction

This issue was raised by contributor @firatbezir in a discussion #3686.

## Additional context

A good way to identify these workflows is to find workflows that run on a schedule. Most management workflows that shouldn't run on forks (like label/meta-files sync and reminders) run on a fixed schedule.

Contributors affected by this issue can completely disable GitHub Actions on their repo. This will not affect their ability to submit PRs as all necessary workflows for a PR to be merged will be run on the upstream repo once a PR is created.

<img width="1818" alt="Screenshot 2024-01-23 at 12 50 32 PM" src="https://github.com/WordPress/openverse/assets/16580576/96500b58-9169-47b7-85c1-b23679714ebd">

**Comment by AetherUnbound** [comment]
I think we could use `github.repository_owner == 'WordPress'` to cover all cases for this!
