### ISSUE TITLE
Browser Extension

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse#37]
We should continue to support the CC Search browser extension, as many folks find it quite useful. 

- [x] Reach out to (Mayank @makkoncept)
- [x] Design the new extension page (@panchovm): [mockups][ext-page-mockups]
- [x] https://github.com/WordPress/openverse-frontend/issues/87
- [x] Clone the [archived browser extension](https://github.com/creativecommons/ccsearch-browser-extension/) repo
	- [x] #39
	- [x] WordPress/openverse-browser-extension#1
	- [ ] WordPress/openverse-browser-extension#2

[ext-page-mockups]: https://www.figma.com/file/BlUTIXRHLOq5mRITpDpi3E/Transitional-styles?node-id=114%3A2594&viewport=74%2C344%2C0.09312169253826141

**Comment by panchovm** [comment]
The mockup update is detailed on [this ticket](https://github.com/WordPress/openverse-frontend/issues/88).

**Comment by zackkrida** [comment]
We also need to reach out to the original extension author @makkoncept regarding the original extension in the browser extension stores, and how we can potentially take over the publishing.
