### ISSUE TITLE
Add access token and throttled application models to Django admin

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse#3711]
## Problem

When investigating traffic patterns and addressing malicious API usage, it can be useful to use the Django Admin web UI to check the status of an access token and/or client application.

## Description

We should add the `oauth_provider.models.AccessToken` and `api.models.oauth.ThrottledApplication` tables to the Django Admin UI so that these records can be easily accessed and searched against from the web UI.

https://github.com/WordPress/openverse/blob/098925afa90b26881b4b4d3e2baffa69049692c0/api/api/models/oauth.py#L27

Those models will need their own views added to `admin.__init__`:

https://github.com/WordPress/openverse/blob/5e5a2aa376048391a8455ae3063b4f3e7afe0d0d/api/api/admin/__init__.py

While I initially thought this would be good as read-only, we might even want to enable editing of certain fields so that access can be revoked by maintainers using the Admin UI as well.

**Comment by bjornthiberg** [comment]
Hi, 

We are a group of 5 students at KTH. As a part of a Software Engineering course we are to solve an issue for an open-source project. Ok if we take this one? :) @WordPress/openverse-maintainers

/ @bjornthiberg @samshahriari @torenylen @Oozna @Samkth123

**Comment by AetherUnbound** [comment]
Hi @bjornthiberg and others! We'd love to have y'all help contribute to the project 😄 I'll go ahead and assign it to you. Please check out our [welcome](https://docs.openverse.org/general/contributing.html) and [quickstart](https://docs.openverse.org/general/quickstart.html) documentation pages, and if you have any questions about this issue feel free to leave them here!
