### ISSUE TITLE
`visual-regression/v-header-internal.spec.ts:36:11 › VHeaderInternal › screen at breakpoint xs with width 340 › mobile-header-internal-modal-ltr` is flaky

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse#3714]
## Description

`visual-regression/v-header-internal.spec.ts:36:11 › VHeaderInternal › screen at breakpoint xs with width 340 › mobile-header-internal-modal-ltr` is flaky.

It fails in this run: https://github.com/WordPress/openverse/actions/runs/7699638405/job/20981848020

And passes in this run: https://github.com/WordPress/openverse/actions/runs/7699638405/job/20983730568

**Comment by sarayourfriend** [comment]
I had this fail again in another PR and remembered to grab the test results artefact.

It looks like the same font rendering issue that @obulat fixed in the other playwright tests. I bet https://github.com/WordPress/openverse/issues/3713 is too?

[storybook_test_results.zip](https://github.com/WordPress/openverse/files/14105698/storybook_test_results.zip)

**Comment by obulat** [comment]
Yes, @sarayourfriend, this does look like a font rendering issue. We should probably add a wait to this test.

**Comment by sarayourfriend** [comment]
How does that work, Olga? Is there an example to go off of?
