### ISSUE TITLE
Remove references to the browser extension

### ISSUE THREAD

**Issue by dhruvkb** [WordPress/openverse#374]
## Description

Since the extension is not maintained, and we are archiving the repo, we should remove all references to the extension repo from the codebase to prevent workflows and automations from failing.

## Occurrences

- [ ] `README.md` https://github.com/WordPress/openverse/blob/6b9ce3a3a75e01e7d776b751cf8e1d871704a430/README.md?plain=1#L29
- [ ] `automations/data/github.yml` https://github.com/WordPress/openverse/blob/6b9ce3a3a75e01e7d776b751cf8e1d871704a430/automations/data/github.yml#L7
- [ ] `.github/sync.yml` https://github.com/WordPress/openverse/blob/6b9ce3a3a75e01e7d776b751cf8e1d871704a430/.github/sync.yml#L11

**Comment by GreenCreep** [comment]
How do I add the right labels to my pull request? (PR label checks fail)

Sorry, this is my first time fiddling on Github...

**Comment by dhruvkb** [comment]
@GreenCreep the labels should be added automatically on the PR. For some reason they weren't applied so I've added them manually.
