### ISSUE TITLE
Image type used for thumbnails is sometimes incorrectly extracted from the content type

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse#3750]
## Reproduction

1. Go to https://api.openverse.engineering/v1/images/cf168b67-00be-4e4c-8985-ccf388afecd5/thumb
2. You should get a 415 error, the media type is not supported, with the following detail: 
```
{"detail":"Unsupported media type \"Image extension png;charset=UTF-8 is not supported by the thumbnail proxy.\" in request."}
```
The image is a png, but extracting it from the head request is done incorrectly, and instead of `png` we get  `png;charset=UTF-8`

## Additional context

https://github.com/WordPress/openverse/blob/8a939a4bc76a45473757f6704fad60ce7831dffb/api/api/utils/image_proxy/extension.py#L77-L83

Adding a `.split(";")[0]` could probably fix this.

**Comment by thegreendrinker** [comment]
Darien is working on this!
