### ISSUE TITLE
About page has outdated links for codebase and the GitHub project board

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse#3757]
## Problem

https://openverse.org/about page has links to the pre-monorepo codebase and the old GitHub project board.

<img width="500" alt="Screenshot 2024-02-06 at 10 31 39 AM" src="https://github.com/WordPress/openverse/assets/15233243/3ac83622-9938-4046-a761-edbb7615e414">

### Current text

All of our code is open source ([Openverse frontend](https://github.com/wordpress/openverse-frontend/), [Openverse API](https://github.com/wordpress/openverse-api/), [Openverse Catalog](https://github.com/wordpress/openverse-catalog/)) and we [welcome community contribution](https://make.wordpress.org/openverse/). You can see what [we’re currently working on](https://github.com/orgs/WordPress/projects/3).

### Text to add

All of our code is open source and can be accessed at the [Openverse GitHub repository](https://github.com/wordpress/openverse). We [welcome community contribution](https://docs.openverse.org/general/contributing.html). You can see what [we’re currently working on](https://github.com/orgs/WordPress/projects/75).

## Additional context

Repository links are given here:
https://github.com/WordPress/openverse/blob/906a85470296e58175850458903a6553180b0d05/frontend/src/pages/about.vue#L24-L38

The corresponding i18n string:
https://github.com/WordPress/openverse/blob/906a85470296e58175850458903a6553180b0d05/frontend/src/locales/scripts/en.json5#L85-L88

**Comment by enteragoodusername** [comment]
I would like to do this! Can I be assigned to this issue?

**Comment by obulat** [comment]
Sure, @enteragoodusername! I've assigned the issue to you.
