### ISSUE TITLE
Pin version of `audiowaveform` image in API `Dockerfile`

### ISSUE THREAD

**Issue by dhruvkb** [WordPress/openverse#3782]
## Problem

The current API Dockerfile uses the `latest` tag of the `audiowaveform` image.

https://github.com/WordPress/openverse/blob/e98f7e90f260dfe2e7d2c13d4bf07731130df5c0/api/Dockerfile#L10

## Description

As @realies has pointed out in #2412, now the workflow tags the images with a version, when a new version of `bbc/audiowaveform` is published with a Git tag.

That line can now be updated as follows.

```diff
- FROM docker.io/realies/audiowaveform:latest AS awf
+ FROM docker.io/realies/audiowaveform:1.10.1 AS awf
```

**Comment by zablon-oigo** [comment]
Hello, I'm interested in addressing this issue. Could you please assign it to me? I believe I can handle it effectively. 
Thank you!
