### ISSUE TITLE
Unable to visit creator page if creator name has `/` in it

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse#3791]
## Description

In the new creator view, if a creator has a `/` in it, the part after the `/` is interpreted as a path and 404s.

## Reproduction

1. Run the frontend locally
2. Make sure you have `additional_search_views` enabled in `/preferences`
3. Visit http://localhost:8443/audio/source/wikimedia_audio/
4. Click on any of the results with `/` in them
5. See 404

## Screenshots

![image](https://github.com/WordPress/openverse/assets/10214785/860e8416-24da-489a-9db2-5ef3756b91a3)

## Additional context

Related to #410

**Comment by zackkrida** [comment]
Fixed by #3866
