### ISSUE TITLE
Logging EC2 memory metrics (via Cloudwatch)

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse#382]
| Start Date        | ETA | Project Lead | Actual Ship Date |
| ---------- | ---------- | ------------ | ---------------- |
| 2023-02-20 | 2023-02-24 | @sarayourfriend           | TBD              |

## Description

Install the Cloudwatch agent for memory metrics.
Openverse is (in the beginning of 2023) moving away from EC2 with the exception of the Elasticsearch Cluster, Ingestion server and Catalog. Currently, we don’t have memory metrics for EC2 instances.

## Documents

This is a project that does not require project documentation.

**Comment by AetherUnbound** [comment]
This was shipped with https://github.com/WordPress/openverse-infrastructure/pull/357 but shouldn't be considered success until https://github.com/WordPress/openverse-infrastructure/issues/380 is complete.
