### ISSUE TITLE
Seek alternatives to `banyan/auto-label`

### ISSUE THREAD

**Issue by dhruvkb** [WordPress/openverse#3823]
## Description

We use https://github.com/banyan/auto-label for labelling PRs with migrations. This is a problem because the action has not been updated in years and has [not updated from Node v12 to Node v16](https://github.com/banyan/auto-label/issues/44) (when v12 was deprecated) and likely will not be updated from Node v16 (as that's scheduled for deprecation too).

## Solution

The only solution is to stop using this action and look for actively-maintained alternatives. It is also possible to do what the action does using custom code similar to #3815, in which case the action will no longer be needed.

## Additional context

To be fair, when GitHub deprecates a Node version, it does not break the workflow but rather forces the action to work on the next supported Node version and this action works properly on Node v16, and hopefully, will continue to work on Node v20.

**Comment by GauranshMathur** [comment]
Hi,

I am interested in contributing and would like to be assigned to this issue. As this is my first time contributing on this project. I would like some help on some more details about the solution that you are looking for.

**Comment by AetherUnbound** [comment]
Hey @GauranshMathur! Thanks for you interest in this issue. As mentioned in the PR description, we're looking for alternative GitHub Actions to https://github.com/banyan/auto-label which retains the same functionality in our workflows but is more actively maintained. Here's an example where this workflow is used:

https://github.com/WordPress/openverse/blob/68ffb8d4a3b4a2336d25a08972285678f446ec90/.github/workflows/migration_safety_warning.yml#L45-L47

And what it's configuration file looks like:

https://github.com/WordPress/openverse/blob/5bfab8b184bf7636d1541e0ddd21313252d9dee1/.github/auto-label.json

Essentially, we want a GitHub Action that, when called, will apply labels to a PR based on file name patterns. You can do research into this on your own and come up with an alternative action we could use.

As an alternative approach, it may also be possible to add a new set of conditions to our [CI/CD's `get-changes` job](https://docs.openverse.org/meta/ci_cd/jobs/preparation.html#get-changes), which uses [this `filters.yml`](https://github.com/WordPress/openverse/blob/7912d0f8bc32cd5b6279c21f36b14e491a88d199/.github/filters.yml) to accomplish something similar. The [`add-stack-label` job](https://docs.openverse.org/meta/ci_cd/jobs/preparation.html#add-stack-label) is a good example of how the output from `get-changes` is used to apply labels:

https://github.com/WordPress/openverse/blob/9b1aa7762f37646b2c6b4a1dc5c8feb493f5bb4d/.github/workflows/ci_cd.yml#L142-L184

Let me know if you have any other questions, or if you feel up to tackling this work and we can assign the issue to you!

> **Note**:
> For other maintainers, it looks like we had [`auto-label` configuration for project-related files](https://github.com/WordPress/openverse/blob/5bfab8b184bf7636d1541e0ddd21313252d9dee1/.github/auto-label.json#L4-L5) which is no longer hooked up to any GHA workflow. We'll want to make sure whatever approach is taken here also fixes that, too.

**Comment by GauranshMathur** [comment]
I feel up to the task, i would take some time to understand the code base and open a pr once i have a good enough solution. I

And i will msg here if i need any help as well! Thanks!

**Comment by GauranshMathur** [comment]
No worries, yeap. its better i focus on other first good issues due to the complexity. Glad my code may of be some help
