### ISSUE TITLE
Provider DAG stability 

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse#385]
| ETA        | Start Date | Project Lead | Actual Ship Date |
| ---------- | ---------- | ------------ | ---------------- |
| 2023-03-31 | 2023-01-01 | @AetherUnbound           | 2023-04-03              |

## Description

This project fixes all the issues that prevent provider API script DAGs from running successfully.

## Documents

This project does not require documentation.

## Issues

The issues from this project are tracked by the [Catalog Provider DAG stability milestone](https://github.com/WordPress/openverse-catalog/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22Provider+DAG+stability%22)

**Comment by AetherUnbound** [comment]
The milestone was officially closed yesterday, and this project can now be considered complete!
