### ISSUE TITLE
Switch to Docker Compose v2

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse#3876]
## Problem

Docker recommends users use `docker compose` instead of `docker-compose` as of July 2023, when version 1 of the compose api stopped being supported. 

> Important
> 
> Docker's documentation refers to and describes Compose V2 functionality.
> 
> Effective July 2023, Compose V1 stopped receiving updates and is no longer in new Docker Desktop releases. Compose V2 has replaced it and is now integrated into all current Docker Desktop versions. For more information, see [Migrate to Compose V2](https://docs.docker.com/compose/migrate).
>
> -- https://docs.docker.com/compose/

Most fresh installs of Docker no longer include the `docker-compose` alias. 

## Description

Update all of our justfiles and build steps to use `docker compose` instead of `docker-compose`. 
As a bonus, this would allow for predictability in service container names, which use a `-` instead of `_` separator in Compose V2[^1].

## Alternatives

Keep using old software :cry: 

[^1]: https://docs.docker.com/compose/migrate/#service-container-names

**Comment by sarayourfriend** [comment]
Duplicate issue https://github.com/WordPress/openverse/issues/3973 has some additional information that could be helpful for completing this and cleaning up our code (e.g., massively reduce the complexity of `just ps` script)

**Comment by obulat** [comment]
I updated the priority to critical because the CI is intermittently failing due to `docker-compose` not being available in GitHub CI runners.

**Comment by AetherUnbound** [comment]
Resolved by #4017

**Comment by sarayourfriend** [comment]
@AetherUnbound can you clarify what work that is? The basic part is done, separate issues could be helpful to break down further tasks.

**Comment by AetherUnbound** [comment]
Specifically this piece from @obulat's PR description:

> This PR only replaces `docker-compose` in `justfile`s and documentation with `docker compose`.
> It does not simplify the `docker ps` script.
> @zackkrida mentions the replacement of underscores with dashes for container names in the issue: should this be done manually? Would it also affect production? 

If this piece is not considered important then we can close the issue.

**Comment by sarayourfriend** [comment]
I think they are important, but should be separate issues. We're not using compose v1 anymore, so at the very least the title of the issue and the main portion of it is complete. The others are far less important "nice to have" clean ups, right?

**Comment by dhruvkb** [comment]
> As a bonus, this would allow for predictability in service container names, which use a `-` instead of `_` separator in Compose V2[^1]

To be honest, this makes service names "more" confusing, not "less", because the project-service separator is now the same as our separator used within the service name.

[^1]: https://docs.docker.com/compose/migrate/#service-container-names

**Comment by sarayourfriend** [comment]
> To be honest, this makes service names "more" confusing, not "less", because the project-service separator is now the same as our separator used within the service name.

+1, I was going to comment that on the eventual issue, if we made a new one :)

**Comment by AetherUnbound** [comment]
I think, in that case, we can probably close this issue! Any objections?

**Comment by dhruvkb** [comment]
I think that would be good @AetherUnbound as it would help to clarify the exact changes remaining to be made and if scoped sufficiently small, it could even be a good first issue for introducing contributors to our Docker development stack.

**Comment by sarayourfriend** [comment]
Here are follow up issues. Closing this one in favour of them.

https://github.com/WordPress/openverse/issues/4045
https://github.com/WordPress/openverse/issues/4046

I did not create an issue for changing the service separator, it won't be relevant after the `just ps` script change and seems likely to be more of a headache than any potential benefits that I could think of (I really can't think of any specific ones). If anyone else has a strong feeling and especially justification for it, please write an issue for it.
