### ISSUE TITLE
Add docs for including machine-generated Arabic translations in e2e tests

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse#3877]
## Problem

We currently have an undocumented practice: Whenever we add new text to Openverse requiring translation, which is included in Visual regression tests whose snapshots are updated, we hardcode manual Arabic translations to the https://github.com/WordPress/openverse/blob/main/frontend/test/locales/ar.json file. This allows us to _approximate_ how RTL and Arabic support looks in the actual site.

You can see this process in action on [this PR](https://github.com/WordPress/openverse/pull/3852/files#r1507831474).

## Description

Add docs explaining how this works, and instructing folks to go to translate.google.com to get a machine translation, to https://docs.openverse.org/frontend/guides/translate.html.

**Comment by obulat** [comment]
#3725 has added a script for getting the Arabic translation automatically, and also added documentation for it: https://docs.openverse.org/frontend/reference/i18n.html#test-locales
