### ISSUE TITLE
API ECS Migration

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse#388]
| ETA        | Start Date | Project Lead | Actual Ship Date |
| ---------- | ---------- | ------------ | ---------------- |
| 2023-02-28 | 2023-01-01 | @sarayourfriend           | TBD              |

## Description

Project to move API deployment to ECS.

## Documents

No documentation in this issue is necessary because the planning has already been done and the project is in progress.

**Comment by sarayourfriend** [comment]
This was completed last week with the switch over from EC2 to ECS. After a week of using the ECS deployment, things look fine. We will schedule a date to decommission the EC2 deployment entirely.
