### ISSUE TITLE
PR Project Automation is failing

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse#391]
## Description

It looks like the "PR Project Automation" workflow is failing: https://github.com/WordPress/openverse/actions/workflows/pr_project_automation.yml

This workflow is supposed to archive columns automatically after the weekly development chat.

## Reproduction

Most recent run as of the creation of this issue: https://github.com/WordPress/openverse/actions/runs/4115406067

## Additional context

We also make note in the [Weekly Dev Chat Facilitation Guide](https://make.wordpress.org/openverse/handbook/development-weekly-chat-facilitation-guide/) that folks should archive these columns. We could remove that line once this is functional again since it will now be done automatically. @dhruvkb do you recall a reason why we shouldn't _also_ archive the "Done" column of project 3 automatically too?

**Comment by dhruvkb** [comment]
@AetherUnbound I think the only reason we did not implement it in our issues board is because of the satisfaction associated with archiving the closed issues. It should be very straightforward to automate that as well if that's preferable to the team.
