### ISSUE TITLE
Add SEO properties to the collection pages

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse#3917]
These changes depend on the code changes from #3886

## Problem

The collection pages do not have the SEO-related properties.

## Description

The `collection.vue` pages added in #3886 need to have the SEO and Open Graph properties:
- title
- description
- thumbnail

The Implementation plan does not give the final texts we should use for the title and description. These texts should be accessible and i18n-friendly. For instance, if the text uses the tag name in a sentence ("Cat images"), it will not be possible to translate it in some languages grammatically because the tag name ("cat" here) will need to be in a specific form, and we cannot deduct the case automatically. In Russian, for instance, "cat" is "кот", but in the "Cat images" sentence, it could be translated as "Картинки с кот**ом**"

## Additional context

Section on SEO in the Additional search views Implementation plan: https://docs.openverse.org/projects/proposals/additional_search_views/20230719-implementation_plan_additional_search_views.html#seo

**Comment by zackkrida** [comment]
@WordPress/openverse-frontend we can use this issue to discuss the specific language to be used. I would propose very simple initial titles (with the automatic " | Openverse" suffix on each:

- `{tag} {mediaType} | Openverse`: "Dog images", "Field-recording audio tracks"
- `{creatorName} | Openverse`: "zackkrida", "sarayourfriend" [Deliberately non-specific in the future event of multi-media type creators]
- `{provider} {mediaType} | Openverse`: "Flickr images", "ccMixter audio tracks"

**Comment by sarayourfriend** [comment]
Those look good to me.

**Comment by obulat** [comment]
> * `{tag} {mediaType} | Openverse`: "Dog images", "Field-recording audio tracks"
> 
> * `{creatorName} | Openverse`: "zackkrida", "sarayourfriend" [Deliberately non-specific in the future event of multi-media type creators]
> 
> * `{provider} {mediaType} | Openverse`: "Flickr images", "ccMixter audio tracks"

As discussed previously, I [asked](https://wordpress.slack.com/archives/C02RP50LK/p1711438077531719) about these titles in the #polyglots channel of Make Wordpress Slack channel.

**Comment by obulat** [comment]
Based on the replies in Slack channel, I think we should use these titles and add notes to translators in the comments on the dynamic nature of the `tag`, asking to adjust the sentence if necessary. We could include an example translated Spanish sentence: `{mediaType} etiquetadas como {tag} | Openverse`
