### ISSUE TITLE
Usage Analytics

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse#394]
| ETA        | Start Date | Project Lead | Actual Ship Date |
| ---------- | ---------- | ------------ | ---------------- |
| 2023-04-31 | 2023-03-01 | @dhruvkb           | TBD              |

## Description

Openverse contributors have very little insight into the behaviors and interests of our users. We do not have any means of observing if they actually use the features we build in the intended manner or at all.

This project will gather this information through analytics, specifically logging events performed by users.

The implementation plan for the first part of the project, the frontend event collection, is ready, and is planned to be implemented by the end of April.
The second part of the project, the analytics backend, still needs planning. 

## Documents

- [x] [Frontend Event Collection Implementation Plan](https://github.com/WordPress/openverse/blob/383f0a6e15f28a385fac3de03f67762fc3eb8d94/rfcs/20221006-frontend_event_tracking.md)
- [x] #804 

## Issues

- [x] #843
- [x] #844
- [x] #2173

### Events

_Events required for rollout:_

- [x] #1069
- [x] #1068 - #2120
- [x] #1078 - #2247
- [x] #1080 - #1180
- [x] #1081 - #1147
- [x] #1082 - #1181

---

_Events to be added gradually:_

- [x] #1070 - #2423
- [x] #1071 - #1151
- [x] #1072 - #2454
- [x] #1073 - Closed without PR
- [x] #1074 - #2449
- [x] #1075 - #2450
- [x] #1076 - #1158
- [x] #1077 - #2398
- [x] #1079 - #2373
- [x] #1083 - #2424
- [x] #1084 - #2247
- [x] #1085 - #2247
- [x] #1086 - #1156
- [x] #1087 - #1118
- [x] #1088 - #2405

## Prior Art

- https://github.com/WordPress/openverse/issues/754

**Comment by dhruvkb** [comment]
# Update 2023-03-08

- The RFC for using Plausible and the PR that sets up Plausible for local development is present in the PR #804.
- Some groundwork for the analytics feature flag and preferences is in PR #843.

These two are collectively blocking #844, which actually sets up analytics in Nuxt.

**Comment by dhruvkb** [comment]
# Update 2023-03-30

Discussions for the optimal self-hosted Plausible setup are underway.

Meanwhile, since the development environment has a fully functional Plausible setup, issues have been created for recording individual events under the Analytics milestone. With the supporting architecture (composable and utilities) built previously, these issues are smaller, making them suitable for outside contributions.

**Comment by zackkrida** [comment]
@dhruvkb small update: we can go ahead with the cloud-hosted Plausible for now. When we launch analytics we can use a 30 day trial and move on to the full paid account.

**Comment by dhruvkb** [comment]
# Update 2023-04-11

## Done

- Sorted events by priority. 
  - Split into the minimum viable set for a rollout.

## Next

- Make a trial Plausible cloud account.
  - Add creds to the secret store. 
  - Write a P2 post about this Plausible account's creation.
  - Set up payment information.
- Configure Plausible endpoint env vars inside the infra repo.

## Blockers

None.

**Comment by zackkrida** [comment]
## Update 2023-05-03

The analytics events required for launch have been assigned and are under active development. I've started a discussion with the goal of resolving our open design issues for the analytics opt-out in the frontend user interface:

https://github.com/WordPress/openverse/issues/2013

**Comment by zackkrida** [comment]
Hi, @obulat if you are able I think it may make sense to focus on getting #1078 ready for review prior to other PRs, so we can make analytics live with the required events listed here.

**Comment by dhruvkb** [comment]
Thanks @openverse-bot!

**Update:** We have added analytics calls for all the core event types listed above, and we also have the opt-out interface ready. We should be all set to go live.

**Comment by dhruvkb** [comment]
**Update:** Analytics are already live on Openverse. We can gradually add the remaining analytics event and close the project as done after that.

**Comment by dhruvkb** [comment]
Not much to update here since all analytics events have associated PRs. This project will be concluded and closed when those PRs are undrafted, reviewed, approved and merged.

**Comment by zackkrida** [comment]
The final analytics event from the implementation plan was merged and deployed; this project can be considered a success!
