### ISSUE TITLE
Implement and surface list-based deferred metrics

### ISSUE THREAD

**Issue by dhruvkb** [WordPress/openverse#3946]
## Description

Implement pseudo-models (`managed = False`) for creators, providers and media and custom filters for the Django admin. Create the Django admin UI to present the following leaderboards for each media type.

- most reported creators
- most reported sources
- most reported media items

## Additional context

- [Implementation plan (with code samples)](https://docs.openverse.org/projects/proposals/trust_and_safety/content_report_moderation/20240122-implementation_plan_moderation_metrics.html#lists)

**Comment by dhruvkb** [comment]
The surfacing of the metrics depends on the Django admin views (https://github.com/WordPress/openverse/milestone/22) to be ready.

**Comment by sarayourfriend** [comment]
Reprioritised as per https://github.com/WordPress/openverse/issues/383#issuecomment-2151103330

**Comment by sarayourfriend** [comment]
Closing as won't do as per https://github.com/WordPress/openverse/issues/383#issuecomment-2153354643
