### ISSUE TITLE
Dark Mode Design Proposal

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse#3959]
_Written by @fcoveram_

## Problem

As part of the #3592 project we need a finalized design proposal which provides:

- The mapping of dark mode color values to the existing color tokens
- The position of new UI elements

---

## Color system

The current color system of Openverse has worked great conveying the relationship between content hierarchy and brand identity. The unique look of the homepage stands out with its vibrant color compared to other search services, and the use of pink complements the overall design without becoming distracting during the search experience.

However, adding a dark theme to the site presents a substantial challenge in keeping that balance untouched and reach a look-and-feel that feels familiar.

Here I am introducing a proposal for Openverse in dark theme and their main characteristics.

### Neutrality

My first explorations began with reusing the current dark charcoal shades to test how the UI feels. After making some mockups, I immediately noticed the overall pink tone caused by this scale as it comes from lightness variants of Pink.

![current palette hsl](https://github.com/WordPress/openverse/assets/895819/91757cc1-ae6c-473b-8b3f-133e9111e81f)

The pink tones in the background competed with the search result and the details page, adding a distracting tone that does not exist in the current theme. Because of that, I decided to neutralize those shades to be entirely gray and remove any hue nuances in the UI.

![first iteration  dark pink](https://github.com/WordPress/openverse/assets/895819/5e5a85d6-90bb-44b2-97c1-78ab6ed5028a)

### Lightness

In parallel, I aimed to keep the gray shades simple and use one scale for both light and dark themes. I used [Huetone](https://huetone.ardov.me/?palette=N4IgdghgtgpiBcIDyAHGYBuMBOBnOANCABYCuMuCA2qJLAiAObYQCeIRAxgPYA23eaiADEAMwDsEiRxEwAJvPkzhc0atXLOAVm3blEAJyHDygwCZz55eLk2bygGzinT5Vofv3ygCzjfv5QBmB2Dg5TNAiIjlAAY5OLiQAF0AXwJaaDhEFABLMABrGR5%2BQXgqEVFOUW9RCGVRAxhJQPqDOTMYTmUYWrk5A26AIxtOAA5uuUC5TgBGZXizUYgWomEIORnRUa1TGZmIcTnV8QMZjzk3GBmzbyORQJgYzjM61ZnBmNuY5LSM%2BkRWDBePwAO5FPgCShlCqiBpybz1GA9CDfVZqR6BBGrGA6byLTTiA4zLEidYGGJ7UziQkzcTKUZnMxPRzaPYrERaGDeClmHzLGLM1aBQIzeI7N6jGKSuapdLgTIMPKibjgkpQ8piLSiByiQiyRpVUTzGw9QbKQZmTg1dnCUZLSS81YOO0KC6rbyjcQPN0iCxaDrjN6cQKcdrKGZaQKEwMiOIvUaO2MQGbacWxpnmcayv5ZEAgiDYMB5RiqyFCMQ9UZ9eqcTpW%2BrrQYQRNibxNrRm1YKIyBVEibQJymrCAQHUzPu20RaFETk7eFEtjxTGIt7wwMwLIJaUUr8PiGLkmW-eX-EC4UicWu4ShcCGlDU9SqdeY9LRyGPCTiNQazUx9Ubko4ozBtuPiBBAzw2mYDQOBS4RaOInACuGMDOshbziO46EiOOeLYcIUqWvhK7XMh2YnrmODYAIpb3jCU5IvUupVp2FShg4wb1B23gGHS2IGKMqGsSo2qTEaqzPB2G76Fo3gOGYdy2pMDIfuICYfOJIiwe8nw%2BOOoi7m8jzct8qRJEQAAu3BgBQQh3Im7IkmmDgyHxIAxgMRDjjIQ4gNcPktKkQA) to generate shades based on LCH color mode. This mode sets color values based on the human perceptive lightness rather than computing red-green-blue values, as sRGB does.

This scale sets the baseline for hierarchies in backgrounds, surfaces, and texts. Now that gray is a separate color with shades, yellow and pink also have their scale.

![brand color scales](https://github.com/WordPress/openverse/assets/895819/fab0c8d0-5531-4357-8ea6-3ba8ef89fa1c)

![polygon levels](https://github.com/WordPress/openverse/assets/895819/b8711c21-5742-412c-b60d-ddff77c330ff)

![openverse ui levels](https://github.com/WordPress/openverse/assets/895819/feae74bc-2dc3-4ea2-8832-2d7041eb49f3)

![Zoom in UI parts](https://github.com/WordPress/openverse/assets/895819/cba9cdb2-cc6d-42fd-9eac-a1c419a6e586)

### Brand

Given that keeping the brand identity is among the requirements, the tests began by “turning off” the lightness of pink and yellow while keeping their accent and complementary roles, respectively. However, and because of the nature of each color, the inversion felt forced and the UI ended up with a muddy yellow and a saturated neon.

![first iterations brand colors](https://github.com/WordPress/openverse/assets/895819/7d79cd19-6e08-4526-9623-762e6c4282fc)

Shifting the role of yellow and pink was sufficient to reach the brand’s familiar tone. Among the tweaks applied, both tones moved slightly toward the surface lightness to make them more visible. In that same vein, brand colors in the audio wave also tap into brand shades to make the UI richer.

![Light and dark colors](https://github.com/WordPress/openverse/assets/895819/1f4fbdd4-b655-4491-9b1b-e0e62ee51f1b)

![Final mockups](https://github.com/WordPress/openverse/assets/895819/b589229a-9d0f-402e-9c22-00000d4d9a16)

![Audio wave details](https://github.com/WordPress/openverse/assets/895819/a3a948a9-5325-4e0a-80cd-0229a643bfd1)

## Design Library

Creating variables in the design library helped streamline the application of the new color system in pages and components. The "Colors" collection gathers all colors with a more straightforward name and sets the baseline for their use.

To apply color in the UI, the "Alias" collection assigns meaning to each color through a name format that describes how the color is used in both light and dark themes. So, for instance, a surface placed above the background should use the color `bg-surface` , whereas for an interactive element where the background color changes once the pointer goes over, the color used should be `bg-fill-primary-hover` 

Describing the meaning of each color in the library would make the mockup creation and the library maintenance easier. Acknowledging that this benefits Figma users, I would like your suggestions on how to sync better design and frontend documentation.

![figma variables](https://github.com/WordPress/openverse/assets/895819/119baa8b-cb52-42f3-bcb0-ba5c5900150e)

![designing in figma](https://github.com/WordPress/openverse/assets/895819/bd62204d-cf92-4411-aa29-aae2f8e8d4fb)

## Designs

Together, these three pillars consolidate the new color system for both light and dark themes. Please take a look at the design page that gathers the main sections and components in both versions, and let me know what you think.

![Mockups  homepage](https://github.com/WordPress/openverse/assets/895819/0aaf14aa-e8b1-4d3b-82fa-af2a3bc94697)

![Mockups  all content results](https://github.com/WordPress/openverse/assets/895819/3e6a4ed4-b4fe-45d5-83aa-5533e8c978af)

![Mockups  audio results](https://github.com/WordPress/openverse/assets/895819/5005ea6c-2887-44ba-89f4-27ce9c1103bd)

![Mockups  image srp](https://github.com/WordPress/openverse/assets/895819/20a9ecdc-4e1c-44c9-a1ef-9770d9abe806)

![Mockups  audio srp](https://github.com/WordPress/openverse/assets/895819/7b8059e4-9114-4cf0-9c66-94d3b2afee20)

----

## Pending tasks

As part of the requirements pointed out in the project proposal, the following is pending from my side:

- [ ] Add the design of the onboarding process introducing the feature
- [ ] Add the design for switching theme
- [ ] Share the documentation for transiting to the new color system

## Mockups

Figma file: [Dark mode](https://www.figma.com/file/OP3r0AJWo1k7U3K2hgRwwK/Dark-mode?type=design&node-id=22-13656&mode=dev)

**Comment by zackkrida** [comment]
@WordPress/openverse-frontend Please provide Francisco some feedback on these designs this week; thank you!

**Comment by sarayourfriend** [comment]
These look great to me, Francisco. I don't have any questions. The explanation of layers and names for different colours is _awesome_ and will make working with these colours in the actual code more pleasant. Having names based on _usage_ is always easier to remember, I think, thank references to the specific colours, which are easier to mix up what they're for. Extra kudos there, from me :slightly_smiling_face: 

For syncing the colours, I don't know what Figma has built in, but it looks like there is [at least a community plugin to export variables](https://www.figma.com/community/plugin/1256972111705530093/export-import-variables). If it's possible to extract a JSON file of the variables, then it's really easy for us to add those directly to our Tailwind configuration, it may even just be a matter of copy/paste depending on how the variables are organised in the JSON. Even if it isn't JSON, a file that defines each variable name the colour code it represents in a structured format would make it easy for a maintainer to update the variables without too much hassle. That's only possible once (/if, depending on how the implementation plan approaches things) we've made the requisite changes to the application to use the new names.

Into the future, if Figma has a web API for it, even better! We could one day write a GitHub workflow that someone could just press a button (basically) and have a PR generated with the new variables on their behalf. We have a suite of tests that take screenshots of almost every part of the application, and once we have that configured for dark mode, we'll have a decent level of confidence that any changes to colours will be reflected in the snapshots and be easy to review and confirm.

**Comment by jasmussen** [comment]
Looks great!

**Comment by fcoveram** [comment]
> …it looks like there is [at least a community plugin to export variables](https://www.figma.com/community/plugin/1256972111705530093/export-import-variables). If it's possible to extract a JSON file of the variables, then it's really easy for us to add those directly to our Tailwind configuration, it may even just be a matter of copy/paste depending on how the variables are organised in the JSON…

Nice! I will take a look. If you @obulat have time to check as well, I would appreciate how the exported file meets your frontend needs.

**Comment by obulat** [comment]
> > …it looks like there is [at least a community plugin to export variables](https://www.figma.com/community/plugin/1256972111705530093/export-import-variables). If it's possible to extract a JSON file of the variables, then it's really easy for us to add those directly to our Tailwind configuration, it may even just be a matter of copy/paste depending on how the variables are organised in the JSON…
> 
> Nice! I will take a look. If you @obulat have time to check as well, I would appreciate how the exported file meets your frontend needs.

I tried copying the Dark theme to my Figma drafts and running this plugin there but it exported 0 variables. I'm not sure how it works.

**Comment by fcoveram** [comment]
Variables are already part of the design library. There are other old collections in the library so just check the “Colors” and “Alias” ones.

**Comment by zackkrida** [comment]
@fcoveram all of this feedback is quite positive, I think we are ready to move on to the pending tasks :tada:. I will finish the implementation plan this week.

**Comment by fcoveram** [comment]
Yes! I plan to begin the pending work this week.

**Comment by krysal** [comment]
I see the design has already been approved, but I wanted to echo how well inverting the colors works for the Dark mode. Love it!

**Comment by fcoveram** [comment]
Given that all feedback is positive. I will close this issue and create new ones for the remaining design tasks.

**Comment by dhruvkb** [comment]
While this issue has been closed, I wanted to note this point for @fcoveram's consideration.

The homepage with the pink background looks great on its own but when considering with respect to the other screens and surfaces in the app, which all have black/grey backgrounds, the pink background feels out of place and too bright.

For example, in this screenshot of a message sharing some implemented dark mode mockups, the homepage is the one that is the brightest and the background is taking up more attention.

<img width="965" alt="Screenshot 2024-08-01 at 7 38 08 PM" src="https://github.com/user-attachments/assets/6c66ae3e-a5ed-4064-825b-0cbfe6acbc12">

Personally I feel that the background of the homepage should be made darker.

**Comment by fcoveram** [comment]
I applied the same lightness as in its light version (in yellow) to achieve consistency between both themes. I agree it feels brighter, but I would go with that version and use Openverse in dark mode for a few days to see how it feels before making conclusions.

The new theme might feel strange at first, but the change could blend easily into our personal experiences in the daily use.

If then we all agree about the brightness, we can definitely make an exception to lower the shade.

**Comment by obulat** [comment]
> I applied the same lightness as in its light version (in yellow) to achieve consistency between both themes. I agree it feels brighter, but I would go with that version and use Openverse in dark mode for a few days to see how it feels before making conclusions.

I also feel that the homepage is too bright, and it loses some of the advantages of the dark mode. I didn't want to share a simple "I don't like it" comment, so I researched some color advice on the dark themes. I've found an idea of using lower saturation, so I tried applying it. In this screenshot below, the header is 40% saturation, the main content - 50%, the footer is the current 70%. I think 40% looks too dull, but 50% looks easier on the eyes than the current color. What do you think, @fcoveram?

<img width="847" alt="Screenshot 2024-08-19 at 2 46 47 PM" src="https://github.com/user-attachments/assets/e657492f-ef71-45b1-952e-aefbaced1c0d">


I do agree on getting more people to use the dark theme (in staging) for a longer period of time and collecting their opinions.

**Comment by fcoveram** [comment]
Lightness and saturation are two different attributes of colors. The former refers to how close from from white or black color is; and the latter to how much saturation the color has.

Despite this difference, I understand your point and I'm open to revisit the decision.

> In this screenshot below, the header is 40% saturation, the main content - 50%, the footer is the current 70%. I think 40% looks too dull, but 50% looks easier on the eyes than the current color.

How did you set the saturation? Ideally, we should keep within the pink shades defined in #4268. For the dark theme, the pink defined as `complementary` is `pink-9` (`#911A71`), so we can try `pink-10` instead.
