### ISSUE TITLE
Update references to audio works to use "audio track(s)"

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse#3972]
## Problem

In https://github.com/WordPress/openverse/pull/3941 we established a convention of referring to audio works/results as "audio tracks" rather than just "audio". While "audio" is indeed a singular and plural noun, it has a strange feeling as a noun. Using the phrase "audio tracks" reads better.

## Description

Update existing references to audio works to use the new convention "audio track(s)".

## Additional information
All of the English text in Openverse is contained in `en.json5`:

https://github.com/WordPress/openverse/blob/aa9ea4bcfe40683923c98ca43b23f6ff22a06a2f/frontend/src/locales/scripts/en.json5

To fix this issue, you would need to find occurrences of "audio" that refers to "audio tracks", and replace it with "audio track". 
Here, we would replace `audio` with `audio track`:
`{hero: { description: "An extensive library of free stock photos, images, and audio, available for free use." } }`
But here, replacement is not needed:
`"This audio format is not supported by your browser."`

**Comment by Collins-Webdev** [comment]
Hello @sarayourfriend ,
I made a pull request about it [here](https://github.com/WordPress/openverse/pull/4037). 

Please review the changes and let me know if there are any further adjustments needed. Thank you for considering my contribution.

**Comment by obulat** [comment]
Fixed in #4037
