### ISSUE TITLE
Recreate application diagram in Draw.io

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse#40]
We should recreate the [architecture diagram](https://github.com/WordPress/openverse-api/#system-architecture) of the project in **Figma**, so we can edit it more easily as future changes are made to the API and catalog.

**Comment by dhruvkb** [comment]
Maybe a tool like [Draw.io](https://app.diagrams.net/) is more suitable for this task?
- Saves to Google Drive
- Has blocks and templates for a lot of cases (like process blocks for flowcharts and AWS service blocks for infra diagrams)

**Comment by zackkrida** [comment]
Yeah I'm fine with that or another dedicated uml diagram tool. I was referring to @panchovm out of laziness haha

**Comment by panchovm** [comment]
Agree with @dhruvkb. Draw.io does not need paid accounts if we need future changes. I will do it and share it with you all.

**Comment by zackkrida** [comment]
@rbadillap may have other ideas or approaches for generating this diagram!

**Comment by rbadillap** [comment]
[Lucid](https://lucid.app/documents#/dashboard) (a.k.a Lucidchart) is a tool that offers integrations with GitHub, AWS, Slack, and more. This tool's main focus is to provide the most features related to architecture as possible, it's collaborative and can be exported as PDF, PNG, and SVG.

The integration with AWS also enables a feature to inspect the current resources installed.

**Comment by dhruvkb** [comment]
Lucid's AWS inspection seems like a great feature but I'm "drawn" to Draw.io because [it's FOSS](https://www.diagrams.net/about) whereas Lucid needs a paid subscription. Draw.io has the ability to Git track diagrams.

**Comment by sarayourfriend** [comment]
Was this solved by https://github.com/WordPress/openverse-api/pull/771 by any chance?

**Comment by zackkrida** [comment]
Indeed it was, using Draw.io. I'll close this!
