### ISSUE TITLE
Update docker-compose files to use the latest version

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse#4020]
## Problem

Some `docker-compose` files that specify version use a rather old "2.4" one.

## Description

Update the `version` to the latest and thoroughly audit for any problems.
Some maintainers have previously had issues with the resource limits when using version 3.x.

## Alternatives

Keep using the old versions 

## Additional context

This was raised during migration from Docker Compose V1 to V2 (#4017)

**Comment by sarayourfriend** [comment]
Closed by https://github.com/WordPress/openverse/pull/4200
