### ISSUE TITLE
Write TSDoc to document frontend fields

### ISSUE THREAD

**Issue by dhruvkb** [WordPress/openverse#4025]
## Description

For fields with complications, or edge cases, or noteworthy details, write descriptions in the frontend interfaces that can be parsed by the documentation generation script from #4023.

Also document what the frontend expects from the API, what it wrangles and generates automatically.

## Instructions

A quick primer about the media documentation pipeline for the frontend: the `just` recipe `frontend/generate-docs` calls `pnpm` script `doc:media-props` which runs `frontend/scripts/document-media.js`. This JS script parses `frontend/types/media.ts` and writes a Markdown file that's served by the docs.

So to do this, you'll need to follow these steps.

- Start the docs server `just s`, let it run in the background.
- Edit the sole file `frontend/types/media.ts`.
  - Add documentation comments `/** */` for properties of the interfaces `Media`, `ImageDetail` and `AudioDetail`.
  - You can write Markdown, you can use TSDoc features like `@see`.
  - You can also see refer to pre-written docstrings (e.g. `id` and `title`) as examples.
- Run `just frontend/generate-docs media-props false`.
- Check the running docs @ `/meta/media_properties/frontend.html` to see your updates on the page.

**Comment by zackkrida** [comment]
@WordPress/openverse-frontend I am not confident what this work entails. Is there more information anywhere? To start, what files is it meant to touch? I see the work done in frontend/src/types/media.ts but am not sure how everything connects.

**Comment by dhruvkb** [comment]
@zackkrida I've updated the PR description to add section "Instructions" that provides more info on what need to be changed and how the changes can be seen locally.
