### ISSUE TITLE
Simplify `just ps` script using compose v2's `docker compose ps` JSON output

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse#4045]
## Current Situation

The Python script that `just ps` uses was written to be compatible with Docker compose v1. That meant it could not take advantage of compose v2's JSON output from `docker compose ps`, which added some complexity to the script.

https://github.com/WordPress/openverse/blob/bdb8f0ad1dd0b2ae504f708b4105fdadc10e8988/utilities/ps.py

This issue is open to community contributors. In order to complete this issue, you should have an intermediate understanding of Python, and basic familiarity with Docker compose. You must also have the entire Openverse docker compose stack running, for which you should follow https://docs.openverse.org/general/general_setup.html and the setup guides for each of the API, frontend, catalog, and ingestion server. You will need this to test the output of `just ps`. Please include sample output of the modified script in the PR description.

## Suggested Improvement

Now that [we've moved to compose v2](https://github.com/WordPress/openverse/issues/3876), we should clean up this script, simplifying it and deleting code that parsed the complex table output. Check out https://github.com/WordPress/openverse/pull/1160 where we originally introduced the script for background on its current implementation. 

This function in particular should be much simpler using `--format json` output.

https://github.com/WordPress/openverse/blob/bdb8f0ad1dd0b2ae504f708b4105fdadc10e8988/utilities/ps.py#L66-L92

Use `just dc ps --format json` instead of `docker ps` (no compose). That will also eliminate the need to filter services using the network name heuristic.

## Benefit

Remove unnecessary code, simplify the `just ps` script. The best code is no code.

**Comment by zaharoian** [comment]
I'm interested in this issue!

**Comment by sarayourfriend** [comment]
Go for it, @zaharoian, and thanks!
