### ISSUE TITLE
Use `.venv` for catalog virtualenv

### ISSUE THREAD

**Issue by dhruvkb** [WordPress/openverse#4109]
## Problem

The catalog virtualenv is currently placed in `venv/` in the catalog directory. This is a bit non-standard and the conventional name of the virtualenv directory is `.venv/`.

## Description

The catalog should be updated to create and use a virtualenv in the `.venv/` directory.

## Additional context

All major package managers adhere to this convention.

- [Poetry](https://python-poetry.org/docs/configuration/#virtualenvsin-project)
- [Rye](https://rye-up.com/guide/faq/#can-i-relocate-virtualenvs)
- [PDM](https://pdm-project.org/latest/usage/venv/#the-location-of-virtualenvs)

**Comment by thegreendrinker** [comment]
I would like to take on this issue! My goal would be to get it done this week.

**Comment by dhruvkb** [comment]
Sure @thegreendrinker, please take it up!

**Comment by dhruvkb** [comment]
Here are the places where will need to make changes.

1. The `justfile` the catalog automatically creates the virtualenv at `venv/`. https://github.com/WordPress/openverse/blob/b55d6d521ee71b717f73ccf225b1de3bf35e5df9/catalog/justfile#L37

   ```diff
   - bash -c "python$CATALOG_PY_VERSION -m venv venv/"
   + bash -c "python$CATALOG_PY_VERSION -m venv .venv/"
   ```

3. The [catalog quickstart](https://docs.openverse.org/catalog/guides/quickstart.html#setup) in the docs suggests creating a virtualenv at `venv/` using `python3 -m venv`. This should instead point to the `just` recipe so that it's automatically addressed by point no. 1 above. https://github.com/WordPress/openverse/blob/b55d6d521ee71b717f73ccf225b1de3bf35e5df9/documentation/catalog/guides/quickstart.md?plain=1#L55-L56

   ```diff
   - python3 -m venv venv 
   - source venv/bin/activate 
   + just venv
   + source .venv/bin/activate
   ```
