### ISSUE TITLE
Clearly document all media properties

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse#412]
| Start Date | Project Lead | Actual Ship Date |
| ---------- | ------------ | ---------------- |
| 2023-03-01 | @dhruvkb         | TBD              |

## Description

All the details we collect and store for each media type should be clearly documented, and should be consistent across the stack (Catalog, API and Frontend).

Due to historic reasons during the development of the project, not all properties that are deemed required are available in the data. As a pre-requisite to making the data more consistent, we need to document all the media properties and whether they are available (should be available in the future) in the database or are added by the API/ingestion server/elasticsearch/frontend. 

Also, we need to document whether the properties are nullable, and what their constraints are. Although we have the database constraints, some of them are not reliable.

## Documents

- [x] #855 

## Implementation Plans

- [x] #1995
- [x] #1996

## Prior Art

- Excellent table for `image` fields by @rwidom : https://docs.google.com/spreadsheets/d/1gaVsvFnsYby2iwzRm0Ta9IPhvNixCpQdHByGLo1r_pg/edit?usp=sharing ("image table ddl" tab)
- Related analysis was attempted in the Data normalization issue https://github.com/WordPress/openverse/issues/244

**Comment by obulat** [comment]
## Update 2023-04-26



The [project proposal](https://github.com/WordPress/openverse/pull/1153) has been finalized, and the PR with the Catalog implementation plan (#1904) opened.
The migration to `drf-spectacular` that creates OpenAPI 3 spec in the API is also the foundation work for the API and frontend parts of this project.


### Blockers



None.

**Comment by dhruvkb** [comment]
This project has been shipped, efforts are underway to describe the properties manually across catalog, API and frontend.

**Comment by zackkrida** [comment]
I've begun work on https://github.com/WordPress/openverse/issues/4025 and should have a PR out in the next 1-2 days.

**Comment by dhruvkb** [comment]
#4366 is the final PR which will close #2187 and also this project.
