### ISSUE TITLE
Create a "dev dependencies check" script for identifying what a contributor may need

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse#4137]
## Description

This came out of a discussion between maintainers about Sprints/Contributor Day events where new contributors could use some tooling to determine quickly what dependencies they'd need. This could be similar to [`calypso-doctor`](https://github.com/Automattic/wp-calypso/tree/35b12eebe9b836cf83ce841d1ff2e9259fa6271c/packages/calypso-doctor) (although perhaps not as involved) in that it would check for various dependencies and fail for ones that are missing.

As `just` is an uncommon requirement for a project but happens to be necessary for everything we run on the command line, perhaps the tool could also auto-install `just` (by downloading a binary and putting it in the user's `PATH`) if requested.

This should probably be written in bash, or at least a language (like pure python) that doesn't require any dependencies in order to run on a POSIX machine.

The dependencies to check for (in my mind and from [this doc](https://docs.openverse.org/general/general_setup.html)) are:
0. `git`
1. `just`
2. `docker`
3. `python` (for `pre-commit`)
4. `pnpm` (for linting and the frontend)

**Comment by sarayourfriend** [comment]
> putting it in the user's PATH

Where would you propose that be? A single, safe, and writable destination for `PATH` is not determinable, certainly not easily, and certainly not with reliability. `~/.local/bin` is a convention, but there are others too (e.g., `~/Applications`). We could add some path in the Openverse monorepo directory to user's path, and modify their bashrc/zshrc/etc..., but that's pretty gross! I hate it when scripts touch these files without asking me. And whether they're even reliably available on some systems is a question in itself.

Everyone should install just using the tools available to them from their operating system or typical dependency management solution. Use a script from the Openverse project to download it, also kind of makes us responsible for keeping it up to date, or providing some method for doing so. We're not really in the business of managing system dependencies, as far as I know. Unless we're also going to check the `just` version for contributors and offer to update for them (what a load of complexity :woozy_face:) I don't think there is a good approach here. At most, I think we should link to https://github.com/casey/just?tab=readme-ov-file#installation; and suggest https://github.com/casey/just?tab=readme-ov-file#pre-built-binaries for users that run into problems using standard solutions.

Anything more is a responsibility I don't think this project is equipped to take on, and so complicated that it would inevitably incur a maintenance burden (of course regular maintainers aren't the ones using installation scripts like this most often, so we wouldn't see when they break or stop working).
