### ISSUE TITLE
Core user interface improvements

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse#415]
| Start Date | ETA        | Project Lead | Actual Ship Date |
| ---------- | ---------- | ------------ | ---------------- |
| 2023-03-01 | 2023-04-30 | @fcoveram           | TBD              |

## Description

Update the visual style of `VButton` component in both [Design Library](https://www.figma.com/file/GIIQ4sDbaToCfFQyKMvzr8/Openverse-Design-Library?t=GdHMIoc3UuqazIW0-7) and [Storybook](https://wordpress.github.io/openverse/storybook) components to set a consistent baseline for all UI components.

~~Blocked by #386.~~

## Documents

- [x] Project Proposal: #912  
- [x] Design Proposal as implementation plan: #860

## Issues

- [x] #466
- [x] #1017
- [x] #1019
- [x] #1020
- [x] #1187

**Comment by panchovm** [comment]
# Update 2023-03-08
* Design proposal was shared in #860 
* Work on the implementation plan has not started yet. I will ping folks asking for help as it requires technical expertise.

**Comment by panchovm** [comment]
# Update 2023-03-21
* Suggestions and corrections to the Project Proposal document (#912)
* Questions on the Figma design file shared in the design ticket (#860)

7 days until finishing the Project Proposal and it's not fully clear if an Implementation plan is required or not.

**Comment by panchovm** [comment]
# Update 2023-04-12
Last week I was AFK, so this update considers all days from the last update post.

* Two design iterations were made and shared in #860 based on #1049 reviews.
* Design Library was updated with the last changes shared in #860 
* Issues section in this ticket's first message was updated by @obulat to list the implementation tickets.

**Comment by panchovm** [comment]
# Update 2023-04-17

The update work on components continues. No significant news to notify has come up.

**Comment by panchovm** [comment]
# Update 2023-04-24

The code work continues without significant news to report.

**Comment by fcoveram** [comment]
# Update 2023-05-08
* Clean up process continues on #1187

**Comment by fcoveram** [comment]
All issues related to the project implementation are done, do we need something else @obulat before moving us to the [delivery stage](https://docs.openverse.org/projects/planning.html#delivery-status-shipped)?

**Comment by zackkrida** [comment]
The [two success criteria](https://docs.openverse.org/projects/proposals/core_user_interface_improvement/20230314-project_proposal_core_ui_improvement.html#success) are met:


> - `VButton` code component follows the design documentation specs.
> - Design Library documents the `VButton`-based components following Storybook
  documentation.
