### ISSUE TITLE
Dark mode feature introduction flow

### ISSUE THREAD

**Issue by fcoveram** [WordPress/openverse#4157]
Designs for Dark mode project (#3592)

## Description
In order to have users updated with the latest improvements on the search, I have the following idea.

![Feature introduction modal in homepage](https://github.com/WordPress/openverse/assets/895819/c881ba86-4d96-4de9-a552-c61970e7bf0b)

The "what's new" message is displayed in a modal with a blurred background that shows an image or gif, text content introducing the feature, and one action to enable/explore the feature and one to close the overlay dialog.

For the dark mode feature, all texts are pending and need comms revision, and the visual placed above text content will show how the feature works in production (discussed in #4155).

Here is a prototype that simulates all interactions expected.

https://github.com/WordPress/openverse/assets/895819/28f784f6-58f0-4cd6-a978-1f81317292e2

## Mockups

Figma file: [Dark mode](https://www.figma.com/file/OP3r0AJWo1k7U3K2hgRwwK/Dark-mode?type=design&node-id=1899-46617&mode=design)

**Comment by jasmussen** [comment]
Beautiful work as always. As I think we discussed in a chat, there are a few ways to do this:

1. Roll this out with system set by default, don't inform anyone
2. The same but with a modal
3. The same but with a notice
4. Above options, but defaulting to "light"

Of those, 1 appeals to me because it's very simple. I also have a slight aversion to welcome modals that get in my way, though I like that you've positioned this as a "What's new" modal: _ooh new goodies!_ 

Whether it's a notice or a modal, I'm happy to defer to you and everyone else, both can work fine. The notice gets less in the way, though, so the main question to answer is: is dark mode a substantial enough feature to warrant the modal instead of the notice? My instinct: _probably_.

**Comment by stacimc** [comment]
I've added `priority: medium` as I believe that's the given priority for the project, but please feel free to update.

**Comment by AetherUnbound** [comment]
I like the idea of the modal and how you've presented it here! I worry though about how we might be able to actually manage showing the modal only once on an implementation level. Currently I feel like I have to dismiss our existing analytics banner quite frequently when using the search; it would be unpleasant to have to dismiss the modal multiple times across different devices or even multiple times on the same device depending on how we save session state information. 

I do think rolling dark mode out with system as default would be a good alternative to this though! It doesn't solve the more general feature introduction flow though.

**Comment by zackkrida** [comment]
I also think this looks _fantastic_, but think it ultimately might be too intrusive. The main use case I'm concerned with is first-time Openverse users and the added barrier of making a search.

The majority of our traffic is on desktop and our homepage is fixed-height, so the control will immediately be visible to users. 

I _do_ think that defaulting to system would work well to fix this issue. Any user who is sufficiently tech-savvy enough to enable dark mode on their system or browser will 1. probably appreciate Openverse's dark mode, and 2. if they do not like it, should be able to find the footer control to disable it.

**Comment by sarayourfriend** [comment]
Agreed on the intrusiveness of it. Is there an option where we somehow highlight the toggle itself, maybe with a tooltip indicating the feature is new?

If we do _anything_ for this, I'd like also to have a timeline defined for when we would deprecate the feature. It should not live indefinitely.

**Comment by fcoveram** [comment]
I have another less intrusive idea I can go back to, and also try something as minimal as possible.

First-time users is definitely a concern, but I also think it's good to consider a system for introducing features no matter the expertise level. This tech-savvy feature is simple in terms of steps required, but the additional search views involve more screens and we didn't consider an introduction stage when outlining the project.

**Comment by fcoveram** [comment]
Coming back here after a few days to share a new version. Before diving into details, here is a recording of a prototype.

https://github.com/WordPress/openverse/assets/895819/45c5d085-de55-4db3-88c5-b90de1b79a98

The idea main idea behind this proposal is showing a whats-new message in the home page while stand out the theme switcher until the user clicks on it. The homepage's banner is a link that takes you to the [latest release page](https://github.com/WordPress/openverse/releases/tag/api-2024.05.01.13.59.00) on Github where more details are added.

The glowing button meets the WCAG requirements, and for the motion reduction settings, we can set the border in dark (text-primary color) and change its width from 1.5px to 3px without the transition effect.

We can reuse this pattern in upcoming features that impact the UX more significantly. In cases where the feature is a set of views or flows that are not afford through a single UI's component, we can safely skip the glowing button and rely on the release page. There we can include recordings and mockups describing what changed and how users can use it. I'm thinking this scenario specifically for the #410 project where we missed this introductory stage.

For a more real interaction, you can check [this prototype](https://www.figma.com/proto/OP3r0AJWo1k7U3K2hgRwwK/Dark-mode?page-id=1899%3A46617&type=design&node-id=2054-10762&viewport=-6710%2C-3393%2C0.29&t=sDDXMwwgA2NF5uN2-9&scaling=min-zoom&starting-point-node-id=2054%3A10762&show-proto-sidebar=1).

**Comment by AetherUnbound** [comment]
This is... _so cool_. I love it, I think it's an excellent approach for showcasing new features without being too intrusive. Amazing!! 🤩

**Comment by sarayourfriend** [comment]
That's great! It's definitely less intrusive on desktop, and looks like a pattern we can use moving forward. Nice work, Francisco!

I am keen to see how it comes across on mobile, and whether it's less intrusive than a banner. On a small phone screen the homepage is pretty tight.

![Screenshot_20240507-223143](https://github.com/WordPress/openverse/assets/24264157/aaf7f77a-ffd5-44ac-9937-9ff01cae8059)

**Comment by fcoveram** [comment]
The dark notification message _intends_ to be intrusive. For that reason is that I suggested not overusing it in other scenarios and instead finding more in-context manners of announcing changes.

However, that screen @sarayourfriend definitely looks overloaded. I was thinking of adding the announcement banner on both desktop and mobile. But I agree there is room for improvement in having a cleaner layout.

**Comment by sarayourfriend** [comment]
> However, that screen @sarayourfriend definitely looks overloaded. I was thinking of adding the announcement banner on both desktop and mobile. But I agree there is room for improvement in having a cleaner layout.

Looking at the screenshot again, I wonder if for mobile we could put the language and colour scheme selector on the same row, so that each are only half the page? Some longer language names might not fit, but very few are that long. Because the screen is so much smaller on mobile, with the highlight effect, the colour scheme button would be pretty noticeable (it isn't far from the main content so that you could miss it, like it is on desktop).

**Comment by fcoveram** [comment]
> I wonder if for mobile we could put the language and colour scheme selector on the same row, so that each are only half the page?

Yes. The change requested in #4155 includes the footer in this way. Here is a screenshot from the dark mode file where footer variants are added.

![All variants of Footer internal and content](https://github.com/WordPress/openverse/assets/895819/2da34c8d-c008-42b0-b055-28efef8d772f)

**Comment by fcoveram** [comment]
I created the mockups for the smallest breakpoint, and here is the outcome.

![Feature introduction on XS breakpoint](https://github.com/WordPress/openverse/assets/895819/dd97e574-536e-4641-bc9b-5815f51ae88e)

The mockups has the following changes:
* Announcement banner has a shorter version of the main text.
* `h1` has a smaller font-size for a cleaner layout.

While revisiting the current homepage, I noticed other minor text styles we could correct in the PR. In addition to that, I also think we could include `text-wrap: balance` in `h1` to have a harmonious white space on the text's right side. 

The assets are ready in the [Mockups](https://www.figma.com/design/OP3r0AJWo1k7U3K2hgRwwK/Dark-mode?node-id=22-13656) page.

**Comment by fcoveram** [comment]
Replacing the `design: in discussion` label with `design: ready`

**Comment by sarayourfriend** [comment]
@zackkrida Does this need an implementation plan ticket or will it be a one-off issue? It looks like there could be individual components related to this, but I'm not sure if they're separate PRs, necessarily.

We probably need to fix the problem @AetherUnbound identified in this thread, which I reproduced in this comment as well: https://github.com/WordPress/openverse/issues/4157#issuecomment-2071112897

My concern is whether whatever we use to indicate _this visitor already knows about this feature_ would cause the experience to differ?

Although, I'm wondering if this is potentially related to the change we made in Cloudflare regarding session cookies and cache bypass :thinking:

**Comment by zackkrida** [comment]
@sarayourfriend I believe the issue @AetherUnbound identified is updated as of the session cookies and cache bypass changes we made. As of this issue: https://github.com/WordPress/openverse/issues/4308, user color mode selection will be stored in the existing UI cookie which is already being used to bypass the page cache. 

I think we should dismiss this "dark mode feature notification" effect when:

- The user clicks "See more" in the homepage announcement pill-banner-thing
- The user clicks on or taps the theme switcher at all

I will amend the existing implementation plan to include this feature introduction and add it to the task list. I'll also include the other changes I've made to the IP when drafting the issues, like those mentioned in #4308.

**Comment by fcoveram** [comment]
We could include a third case: if user doesn't click on the banner or the switcher, both elements disappear after 2 weeks. What do you think? Both elements are not intrusive and that time span sounds reasonable to me.

**Comment by zackkrida** [comment]
@fcoveram that is potentially a bit more complex to implement but is probably a good idea. 

Interestingly, I've also had a thought. We really only want to introduce a feature to _existing_ users, right? For new users, they are unfamiliar with all of Openverse's functionality. So we also might want to: 

- only show the feature introduction to users with existing Openverse cookies
- only show the feature introduction for a fixed period of time (2-3 weeks)

**Comment by dhruvkb** [comment]
> We really only want to introduce a feature to existing users, right?

Does this mean the default theme for existing users will be "light" and not "system"? If I use dark mode on my computer and visit Openverse, having visited before, I would expect the light-themed site I know but it will be dark-themed (because of "system").

We also shouldn't make "light" the default for everyone though because for new users, it is a more pleasant experience to be served in their preferred OS level color theme.

**Comment by zackkrida** [comment]
@dhruvkb The discussion on this issue predates the decision to use "system" as the default. But I am not understanding what you are asking.

> If I use dark mode on my computer and visit Openverse, having visited before, I would expect the light-themed site I know but it will be dark-themed (because of "system").

Which would be explained by the feature introduction, correct?

**Comment by dhruvkb** [comment]
But also there is no need to introduce the feature anymore, the site is dark so I have been made aware that there is now dark mode.

**Comment by zackkrida** [comment]
Oh I follow you now :laughing: That's fair, and I suppose it's a matter of what level of awareness and announcement is sufficient. @fcoveram what do you think? Is the feature introduction still necessary if we are defaulting to "system" by default?

**Comment by fcoveram** [comment]
> @fcoveram what do you think? Is the feature introduction still necessary if we are defaulting to "system" by default?

When you say the feature introduction, you mean the message on the homepage plus the glowing button?

Regardless of the response, I'm still convinced that adding a visual sign in the UI indicating new features sets an appealing manner of product progress.

As in other examples I've previously mentioned, we didn't include an indicator for landing on source, creator, and tag views. The feature awareness relies on users' ability to discover in the UI what's new. For other upcoming features, let's say filtering by color, users will need to discover it.

**Comment by fcoveram** [comment]
My core point with the above is whether we want to introduce features through the UI. If the answer is no, then we will continue communicating the product changes through the existing channels (a post on Make and/or WordPress social media).

**Comment by zackkrida** [comment]
> Regardless of the response, I'm still convinced that adding a visual sign in the UI indicating new features sets an appealing manner of product progress.

I agree, and this is the information I was looking for. Thank you!

**Comment by sarayourfriend** [comment]
Commenting to add a big +1 to what you've said @fcoveram that Zack quoted. We should absolutely highlight improvements and new features in ways that will be evident to users who may not even be aware that Openverse has a Make blog or social media.
