### ISSUE TITLE
Move JS packages to `packages/js` to match automations layout

### ISSUE THREAD

**Issue by dhruvkb** [WordPress/openverse#4165]
## Description

The `packages/` directory contains our JavaScript packages (currently `eslint-plugin`). This plugin should be moved into `packages/js/` to distinguish it from, and align it with, the Python packages directory named `packages/python`.

The directory should be renamed and references to it (e.g. in `pnpm-workspace.yaml` and `filters.yml`) should be updated to reflect the new name.

<img width="154" alt="Screenshot 2024-04-19 at 9 19 15 AM" src="https://github.com/WordPress/openverse/assets/16580576/b2d6f4eb-53d7-465b-b5fe-cd340c05687b">

## Alternatives

The idea of a `py-packages` and `js-packages` in the root (formerly this issue's goal) is not popular and so has been rejected.

**Comment by dhruvkb** [comment]
Cool, noted. I initially didn't think that anyone would vote for the nested option. But now that you have, I think we should block #4107 till this is decided?

**Comment by AetherUnbound** [comment]
Ah good call, agreed!

**Comment by dhruvkb** [comment]
I'm removing the discussion label, updating the issue title and description and linking PR #4174.
