### ISSUE TITLE
Polite Crawler

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse#417]
| Start Date | Project Lead | Actual Ship Date |
| ---------- | ------------ | ---------------- |
| 2023-04-28 | @obulat | TBD              |

## Description

To improve the search relevancy and the search experience, we need more data about the media files. To get it, we need to politely crawl the providers to download the file and save its properties (height, width), and check if it is dead. 

## Documents

- [ ] Project Proposal
- [ ] Implementation Plan

## Prior Art

- How to politely crawl and analyze half a billion images by Alden Page [^1]
- https://github.com/cc-archive/image-crawler
- https://github.com/WordPress/openverse/issues/1765
- https://github.com/WordPress/openverse/issues/1790

[^1]: [How to politely crawl and analyze half a billion images](https://alden.page/blog/how-to-politely-crawl-and-analyze-half-a-billion-images/)

**Comment by AetherUnbound** [comment]
This project was not completed in 2023 and we are closing it in favor of prioritizing other work. Closing this issue.
