### ISSUE TITLE
Delete the `archive` directory

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse#4187]
## Current Situation

Context in this PR: https://github.com/WordPress/openverse/pull/4073#issuecomment-2071388892

## Suggested Improvement

Delete the `archive` directory.

## Benefit

We don't need the code and the jars in particular are relatively huge files.

## Additional context

@AetherUnbound and @WordPress/openverse-catalog generally, I had actually confused this archive directory with the `retired` DAGs. Many of those are also no longer relevant, right? Are there any of those we can delete? Several times when I've worked in the catalog and done a search of the codebase, I've had to wade through false positives from the retired DAGs, especially the commoncrawl code, which also has a lot of non-idiomatic code (bad examples for future code): https://github.com/WordPress/openverse/blob/697f62f01a32cb7fcf2f4a7627650a113cba40da/catalog/dags/retired/commoncrawl/sync_commoncrawl_workflow.py#L54-L59

That's not part of this issue, but I realised I got the two confused when I asked in the linked-context PR, and wanted to make sure to also ask about those retired DAGs, and whether any of that code could also be deleted. I don't totally follow why git history isn't sufficient to record the retired DAGs, but we could also create a directory of retired DAGs with links to the last commit they existed in, each time we remove them, if the problem is having ease of reference to the old code. At the very least, documenting the specific benefits for keeping unused code, especially code that doesn't match our expectations of how Airflow DAGs should be written, would be really helpful (if nothing at least as a reminder for myself each time I come across this question :sweat_smile:).

**Comment by sarayourfriend** [comment]
Going to go ahead and open a PR for this because it will take only a few seconds anyway.

**Comment by AetherUnbound** [comment]
Regarding your question about the `retired` folder in this issue, I think we can remove it as well at this point! You're right, git history should be sufficient enough for us if we need to look back (thus far, we have not needed to).

**Comment by sarayourfriend** [comment]
Great, issue is here: https://github.com/WordPress/openverse/issues/4240. I've asked some follow up clarification questions for the catalog folks there.
