### ISSUE TITLE
Remove untranslated and/or low translation locales from the locale chooser

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse#4196]
## Problem

In our locale dropdown which allows users to choose a translated version of Openverse, we show all  available languages, regardless of whether or not these languages have any translations.

For users, this means they may choose their language from the dropdown and see the site fully in English, with a notice that we are seeking translation contributions. This is not an ideal user experience. 

Ideally, we either:

- Only show languages with _some_ translations, regardless of the % completion of traslation **Edit: Let's start this way, by removing any language with 0% translation.**
- Choose a "minimum % completed" to show a language 

For maintainers, the number of translated pages we generate is also likely related to vue-router performance problems which are blocking the #411 project.

## Description

We should either remove untranslated locales and or remove untranslated locales and filter translated locales down by a particular % translated in:

https://github.com/WordPress/openverse/blob/7c6298a537a9c21e0c90850dd93f59f542ac7dd6/frontend/src/locales/scripts/get-validated-locales.js#L59

**Comment by sarayourfriend** [comment]
@zackkrida I can't remember from our discussion what we decided either way, but should we create an issue to follow up on this and bring a new call-to-action for contributing translations to Openverse? When we looked at the interactions with the current link, they were really low, so it's probably a good idea to consider different ways to encourage and make folks aware of the opportunity to contribute translations for languages that are not currently in the app. @obulat for example suggested using the accept header to see when a user's system is configured to request pages in a language for which we don't have translations, as an indication for when to show _some_ call to action for helping with translations.

Mostly asking: was that something we agreed we should do? And if so should we get an issue for it. Or, is there a way to fold this into or after something like #3559 where we'll potentially have better tools for calls to action?

**Comment by zackkrida** [comment]
I think initially, let's hide any language with 0% translation.

As for a call to action for translations @sarayourfriend, we should definitely do that. It might be most elegant to do it in conjunction with @obulat's `accept header` recommendation, because it would allow us to show users a targeted banner for their language. It would take a bit of work to store a list of untranslated locales in the app state in order to know which languages to show the banner for, but it's definitely worth considering.

I'll create an issue and edit this message with a link to it.
