### ISSUE TITLE
Augmenting catalog data with non-ingestion sources

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse#420]
| Start Date | Project Lead | Actual Ship Date |
| ---------- | ------------ | ---------------- |
| TBD        | TBD          | TBD              |

## Description

Getting content safety/reports back to the catalog
Any external validation we do on content safety
Dead link ETL
The project relates to all of the above, so setting up a mechanism for this is a prerequisite for any of those processes
This might require a “deleted” table in the catalog to reference which media we’ve removed for various reasons

Possible dependents: 
- Data normalization
- Dead link ETL

### Prerequisites
- #416

## Documents

- [ ] Project Proposal
- [ ] Implementation Plan

**Comment by AetherUnbound** [comment]
This project was not completed in 2023 but will be incorporated into a new project idea for 2024. Closing this issue.
