### ISSUE TITLE
Replace the sample string in a secret with a more obviously safe value

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse#4217]
## Description

The local Plausible setup we use a (probably default) `SECRET_KEY_BASE`. This is not a problem because we don't use this key in production, but to prevent false security flagging, we should replace the value with a safe-looking one.

## Solution
Replace the current value `MN00EYOjQegVd5Z2NkMoSk3o1cklN/37YINtjYtM3yxsoXUhRNnvgWu3pgnEibKR126HmlGeHu7KHpPaYj/Awg==` with  "local_secret_key_base":

https://github.com/WordPress/openverse/blob/b55d6d521ee71b717f73ccf225b1de3bf35e5df9/docker/plausible/env.docker#L2

**Comment by madewithkode** [comment]
Hi @obulat  I'd like to take on this

**Comment by obulat** [comment]
Sure, @madewithkode, I've assigned the issue to you.
