### ISSUE TITLE
Explore frontend performance measurement

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse#423]
| Start Date |  Project Lead | Actual Ship Date |
| ---------- |  ------------ | ---------------- |
| 2023-07-01 |  TBD          | TBD              |

## Description

On the frontend, we can improve the UX by improving performance. First, we would need to analyze the current state and find the bottlenecks that affect the performance the most. We would probably need to reduce JS bundle size.

For this project, we can reach out to external contributors who could do an audit for us.

## Documents

- [ ] Project Proposal
- [ ] Implementation Plan

## Prior Art

- https://github.com/WordPress/openverse/issues/646
- https://github.com/WordPress/openverse/issues/626
- https://github.com/WordPress/openverse/issues/490

**Comment by AetherUnbound** [comment]
This project was not completed in 2023 and we are closing it in favor of prioritizing other work. Closing this issue.
