### ISSUE TITLE
Improved search syntax experience

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse#424]
| Start Date | ETA        | Project Lead | Actual Ship Date |
| ---------- | ---------- | ------------ | ---------------- |
| 2023-07-01 | 2023-07-30 | TBD          | TBD              |

## Description

This is a project for adding a better search syntax experience (filtering by specific properties) to the search bar.

## Documents

- [ ] Project Proposal
- [ ] Implementation Plan

**Comment by AetherUnbound** [comment]
This project was not completed in 2023 and we are closing it in favor of prioritizing other work. Closing this issue.
