### ISSUE TITLE
Remove retired DAGs

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse#4240]
## Current Situation

We have a handful of "retired" DAGs in the catalog codebase. Some of the older ones especially have non-idiomatic code, and would serve as bad examples of how to write new catalog code.

## Suggested Improvement

Delete the [retired DAGs directory](https://github.com/WordPress/openverse/tree/main/catalog/dags/retired) and remove references to it.

## Benefit

No bad code examples, less code, etc.

## Additional context

Previous discussion here: https://github.com/WordPress/openverse/issues/4187#issuecomment-2087489663

**Comment by AetherUnbound** [comment]
Having looked over each of them, I believe the entire folder can be removed.

**Comment by saldanhad** [comment]
Hi @sarayourfriend,

I'd like to take on this issue. Could you assign it to me.
