### ISSUE TITLE
Frontend keyboard shortcuts

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse#425]
| Start Date | ETA        | Project Lead | Actual Ship Date |
| ---------- | ---------- | ------------ | ---------------- |
| 2023-08-01 | 2023-08-31 | @panchovm           | TBD              |

## Description

This is a project to add keyboard shortcuts to the frontend search experience.

## Documents

- [ ] Project Proposal
- [ ] Implementation Plan

**Comment by AetherUnbound** [comment]
This project was not completed in 2023 and we are closing it in favor of prioritizing other work. Closing this issue.
