### ISSUE TITLE
Machine Image Labeling pipeline

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse#426]
| Start Date | ETA        | Project Lead | Actual Ship Date |
| ---------- | ---------- | ------------ | ---------------- |
| 2023-08-01 | 2023-08-31 | TBD          | TBD              |

## Description

This is a project for scoping out what it would take to add machine labels: the API to use, how much of the dataset to apply this to, and the pipeline for sending data to the API.

### Possible dependencies
Backpropagation and polite crawler

### Related project
#422 

## Documents

- [ ] Project Proposal
- [ ] Implementation Plan

**Comment by AetherUnbound** [comment]
This project was not completed in 2023 and we are closing it in favor of prioritizing other work. Closing this issue.
