### ISSUE TITLE
Duplicate image detection

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse#427]
| Start Date | Project Lead | Actual Ship Date |
| ---------- | ------------ | ---------------- |
| 2023-08-01 | TBD          | TBD              |

## Description

We need to prevent duplicate images from being added to Openverse. This is useful both for content safety (to prevent already reported media from being added, even with different metadata) and for search result relevancy (having duplicate media in the results makes the experience worse).

We also have existing duplicates we would need to address. In the future, we will need to come up with a more robust solution for determining the ‘canonical’ piece of media in the case of duplicates. A possible heuristic for this is to use a preference for the media from "authoritative" sources like museums over social media sources.

### Prerequisites
- Perceptual hashing and/or literal hashing with tolerances
- https://github.com/WordPress/openverse/issues/417

## Documents

- [ ] Project Proposal
- [ ] Implementation Plan

**Comment by AetherUnbound** [comment]
This project was not completed in 2023 and we are closing it in favor of prioritizing other work. Closing this issue.
