### ISSUE TITLE
Max field length for catalog and API is inconsistent

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse#4279]
## Description

We set the max length for varchar fields in the catalog and the API. However, these values are inconsistent. This can cause an error during data refresh, when a field value in the catalog is longer than the catalog max.

For instance, max length for `title` is 5000 in the catalog, and 2000 in the API.

https://github.com/WordPress/openverse/blob/3da4ab6189d8eba5e5bcc2195c249e08b7adc648/catalog/dags/common/storage/columns.py#L686

https://github.com/WordPress/openverse/blob/3da4ab6189d8eba5e5bcc2195c249e08b7adc648/api/api/models/mixins.py#L66-L71

## Fields

| Name               | Catalog max length | API max length |
| ------------------ | ------------------ | -------------- |
| filetype           | 5                  | 80             |
| foreign_identifier | 3000               | 1000           |
| thumbnail          | 3000               | 1000           |
| title              | 5000               | 2000           |
| url                | 3000               | 1000           |

## Additional context

The issue was first noted when running a data refresh on Wikimedia data, read more in a [comment](https://github.com/WordPress/openverse/pull/4260#issuecomment-2096622447).

Set the priority to high because the latest Wikimedia data has caused a data refresh error locally.

**Comment by AetherUnbound** [comment]
I could have sworn there was some mechanism for automatic truncation in the data refresh, but sure enough I've tried this by adding a title that was 5000 characters to our local sample data, and the `just api/init` command fails:

```
ingestion_server-1  | [2024-05-07 16:52:20,290 - root - 316][INFO] Running copy-data query: 
ingestion_server-1  | 
ingestion_server-1  | DROP TABLE IF EXISTS "temp_import_image";
ingestion_server-1  | CREATE TABLE "temp_import_image" (LIKE "image" INCLUDING DEFAULTS
ingestion_server-1  |     INCLUDING CONSTRAINTS);
ingestion_server-1  | 
ingestion_server-1  | ALTER TABLE "temp_import_image" ADD COLUMN IF NOT EXISTS
ingestion_server-1  |     id serial;
ingestion_server-1  | CREATE TEMP SEQUENCE IF NOT EXISTS id_temp_seq;
ingestion_server-1  | ALTER TABLE "temp_import_image" ALTER COLUMN
ingestion_server-1  |     id SET DEFAULT nextval('id_temp_seq'::regclass);
ingestion_server-1  | 
ingestion_server-1  | ALTER TABLE "temp_import_image" ADD COLUMN IF NOT EXISTS
ingestion_server-1  |     standardized_popularity double precision;
ingestion_server-1  | ALTER TABLE "temp_import_image" ALTER COLUMN
ingestion_server-1  |     view_count SET DEFAULT 0;
ingestion_server-1  | 
ingestion_server-1  | INSERT INTO "temp_import_image" ("tags","creator_url","source","provider","meta_data","filesize","category","foreign_identifier","created_on","foreign_landing_url","license","url","title","last_synced_with_source","license_version","removed_from_source","filetype","width","updated_on","identifier","thumbnail","watermarked","creator","height")
ingestion_server-1  |     SELECT "tags","creator_url","source","provider","meta_data","filesize","category","foreign_identifier","created_on","foreign_landing_url","license","url","title","last_synced_with_source","license_version","removed_from_source","filetype","width","updated_on","identifier","thumbnail","watermarked","creator","height" from "upstream_schema"."image" AS u
ingestion_server-1  |     WHERE NOT EXISTS(
ingestion_server-1  |         SELECT FROM "api_deletedimage" WHERE identifier = u.identifier
ingestion_server-1  |     )
ingestion_server-1  | 
ingestion_server-1  | ORDER BY identifier
ingestion_server-1  | LIMIT 100000;
ingestion_server-1  | ALTER TABLE "temp_import_image" ADD PRIMARY KEY (id);
ingestion_server-1  | DROP SERVER upstream CASCADE;
ingestion_server-1  | 
ingestion_server-1  | [2024-05-07 16:52:20,356 - gunicorn.access - 363][INFO] 192.168.64.1 - - [07/May/2024:16:52:20 +0000] "POST /task HTTP/1.1" 202 169 "-" "curl/7.81.0"
ingestion_server-1  | [2024-05-07 16:52:20,489 - ingestion_server.slack - 266][ERROR] :x_red: Error processing task `INGEST_UPSTREAM` for `image` (`psycopg2.errors.StringDataRightTruncation`): 
ingestion_server-1  | ```
ingestion_server-1  | value too long for type character varying(2000)
ingestion_server-1  | 
ingestion_server-1  | ```
ingestion_server-1  | [2024-05-07 16:52:20,537 - root - 186][ERROR] value too long for type character varying(2000)
ingestion_server-1  | Traceback (most recent call last):
ingestion_server-1  |   File "/ingestion_server/ingestion_server/tasks.py", line 183, in fn_with_sentry
ingestion_server-1  |     result = fn(*args, **kwargs)
ingestion_server-1  |              ^^^^^^^^^^^^^^^^^^^
ingestion_server-1  |   File "/ingestion_server/ingestion_server/tasks.py", line 261, in perform_task
ingestion_server-1  |     func()  # Run the task function if it is defined
ingestion_server-1  |     ^^^^^^
ingestion_server-1  |   File "/ingestion_server/ingestion_server/tasks.py", line 246, in ingest_upstream
ingestion_server-1  |     refresh_api_table(model, model, progress)
ingestion_server-1  |   File "/ingestion_server/ingestion_server/ingest.py", line 317, in refresh_api_table
ingestion_server-1  |     downstream_cur.execute(copy_data)
ingestion_server-1  | psycopg2.errors.StringDataRightTruncation: value too long for type character varying(2000)
```

**Comment by obulat** [comment]
> I could have sworn there was some mechanism for automatic truncation in the data refresh, but sure enough I've tried this by adding a title that was 5000 characters to our local sample data, and the `just api/init` command fails:

I know of the mechanism for automatic truncation when cleaning and saving the data in the catalog, in the `Column` classes, but I've never seen it in the data refresh.
I had the exact same error when testing #4260.

**Comment by AetherUnbound** [comment]
A few maintainers discussed this issue synchronously, and proposed changing the above fields (and a few others) to `TEXT` rather than a very long `VARCHAR`. The [Postgres documentation](https://www.postgresql.org/docs/current/datatype-character.html) states:

> For many purposes, character varying acts as though it were a [domain](https://www.postgresql.org/docs/current/domains.html) over text.
> ...
> There is no performance difference among these three types, apart from increased storage space when using the blank-padded type, and a few extra CPU cycles to check the length when storing into a length-constrained column. While character(n) has performance advantages in some other database systems, there is no such advantage in PostgreSQL; in fact character(n) is usually the slowest of the three because of its additional storage costs. In most situations text or character varying should be used instead.

This means that, on the storage level, `text` and `varchar` are functionally equivalent. Thus we can do away with the limits on both databases entirely for these columns, using `ALTER` statements that take seconds (rather than a huge data migration). We tested this on the staging database with great success:

```sql
deploy@localhost:openledger> ALTER TABLE audio ALTER COLUMN title TYPE TEXT USING title :: TEXT; 
You're about to run a destructive command.
Do you want to proceed? [y/N]: y
Your call!
ALTER TABLE
Time: 0.080s
deploy@localhost:openledger> ALTER TABLE audio ALTER COLUMN foreign_identifier TYPE TEXT USING foreign_identifier :: TE
 XT;
 ALTER TABLE audio ALTER COLUMN foreign_landing_url TYPE TEXT USING foreign_landing_url :: TEXT;
 ALTER TABLE audio ALTER COLUMN creator             TYPE TEXT USING creator :: TEXT;
 ALTER TABLE audio ALTER COLUMN creator_url         TYPE TEXT USING creator_url :: TEXT;
 ALTER TABLE audio ALTER COLUMN url                 TYPE TEXT USING url :: TEXT;
 ALTER TABLE audio ALTER COLUMN thumbnail TYPE TEXT USING thumbnail :: TEXT;
 ALTER TABLE audio ALTER COLUMN audio_set_foreign_identifier TYPE TEXT USING audio_set_foreign_identifier :: TEXT;
 
You're about to run a destructive command.
Do you want to proceed? [y/N]: y
Your call!
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
Time: 0.523s
```

The above successfully changed the longer columns into the `text` data type without issue! So, baring any objections from @WordPress/openverse-maintainers, we can move forward with the following:

* Pause the data refresh
* Open a PR for the API with a Django migration for the columns
* Deploy migration to production on Monday next week
* Re-enable the data refresh
* Open a PR to reflect the changes in the catalog, and manually make the changes in the upstream DB

**Comment by sarayourfriend** [comment]
Now that the API does not have a field length limit, I think we should close this issue. The problem here is solved, it can never be the case now that the catalog has something that is _too long_ for the API.

Converting the catalog's columns to text is captured in a separate issue, but isn't necessary for resolving this particular issue: 

https://github.com/WordPress/openverse/issues/4312

Please reopen this if my assessment of this problem is incorrect and it still stands.
