### ISSUE TITLE
Dead link ETL

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse#428]
| Start Date | ETA        | Project Lead | Actual Ship Date |
| ---------- | ---------- | ------------ | ---------------- |
| 2023-08-01 | 2023-09-30 | TBD          | TBD              |

## Documents

- [ ] Project Proposal
- [ ] Implementation Plan

**Comment by AetherUnbound** [comment]
This project was not completed in 2023 but will be incorporated into a new project idea for 2024. Closing this issue.
