### ISSUE TITLE
Setup and add initial Dark Mode visual regression test screenshots

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse#4305]
> This issue is part of the Dark Mode project: #3592. Please see the [implementation plan](https://docs.openverse.org/projects/proposals/dark_mode/20240325-implementation_plan_dark_mode.html) for additional detail and context. 

> [!IMPORTANT]  
> This issue is blocked until #4303 and #4304 are completed.  

## Description

Once the dark mode palette is added and can be forced via feature flag, update our visual regression tests to create new dark mode snapshots. Existing screenshots should be renamed to <snapshot_name>_light and the new dark mode screenshots should be named <snapshot_name>_dark.

For setting dark mode in the tests, update `frontend/test/playwright/utils/breakpoints.ts` so that each breakpoint produces and expects a dark mode screenshot to pass as well as the existing light mode screenshot. Emulating dark mode can be easily handled via [Playwright's emulation controls](https://playwright.dev/docs/emulation#color-scheme-and-media).

This will produce a large file diff. When this PR lands @fcoveram  and @WordPress/openverse-frontend  should review the full dark mode appearance for correctness and sufficient color contrast (see the [“Accessibility”](https://docs.openverse.org/projects/proposals/dark_mode/20240325-implementation_plan_dark_mode.html#accessibility) section for more details).

**Comment by zackkrida** [comment]
@obulat and I discussed this a bit an actually came up with a seemingly much simpler approach:

- Add a new step to CI "Run Dark Mode Playwright tests (playwright_vr)", that runs the test suite but with global configuration that enables dark mode, like:

```yaml
         - name: playwright_vr
            script: "ENABLE_DARK_MODE=true test:playwright visual-regression -u"
```

Then, we change the snapshot directory to one for dark mode screenshots using the https://playwright.dev/docs/api/class-testproject#test-project-snapshot-path-template config based on the presence of ENABLE_DARK_MODE

Finally, we setup the dark mode config with something like this:

export default defineConfig({
  use: {
    colorScheme: ENABLE_DARK_MODE !== "true" ? 'light' : 'dark',
  },
});

**Comment by sarayourfriend** [comment]
@zackkrida just to make sure, but these visual regression tests are separate from tests that would confirm behaviour of the system's reported preference, and toggles, in each of the available combinations, right? I see we have unit tests for the `use-dark-mode` composable, I'm getting at more integration-level tests that e2e would be good for to confirm that `use-dark-mode` is actually operating on the page. In other words, that the result is used correctly to render a particular colour scheme.

One aspect that isn't covered by the proposed configuration, for example, is the "no-preference" option supported by `use.colorScheme`: https://playwright.dev/docs/api/class-testoptions#test-options-color-scheme

**Comment by zackkrida** [comment]
@sarayourfriend yes, separate. These tests are solely for verifying the correct visual appearance of components and pages in each color mode (so currently light and dark but in the future our high-contrast variants, as well).

That said, we don't have an existing issue for an e2e test as you've described. Would you mind creating one and adding it to the [second dark mode milestone](https://github.com/WordPress/openverse/milestone/32)?

**Comment by zackkrida** [comment]
@obulat, @sarayourfriend and I chatted about this a bit and I'm thinking it'll actually be best to take a different approach. I'll take some time to describe the approach here tomorrow!

**Comment by sarayourfriend** [comment]
> That said, we don't have an existing issue for an e2e test as you've described. Would you mind creating one and adding it to the [second dark mode milestone](https://github.com/WordPress/openverse/milestone/32)?

I will do this today, it's needed regardless of the visual regression testing approach you end up describing :+1:
