### ISSUE TITLE
Convert longer media `varchar` fields to `text` in the catalog database

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse#4312]
## Description

Related #4279, see that issue for the rationale.

Alter the `audio` and `image` tables in the catalog to convert the following fields from `character varying` to `text` in the underlying database:

- `foreign_identifier`
- `foreign_landing_url`
- `url`
- `thumbnail`
- `creator`
- `creator_url`
- `title`
- `audio_set_foreign_identifier` (audio only)

This will require crafting the migration steps for the catalog database by hand and applying them, then altering the SQL DDL for the tables to reflect this difference. The alters should look like this:

```sql
ALTER TABLE audio ALTER COLUMN title TYPE TEXT USING title :: TEXT;
```

Postgres uses the same underlying storage methods for both these types, so the conversion from one to the other should be extremely fast.

> **Note**
> This is blocked by #4311, as the target columns need to be expanded first before the source ones can, otherwise the data refresh will fail.

**Comment by sarayourfriend** [comment]
@WordPress/openverse-catalog is anyone able to write the migration for this?

**Comment by AetherUnbound** [comment]
I'll pick this up later this week if no one gets to it before me.
