### ISSUE TITLE
Add ability to revoke access to specific Openverse API registered client applications

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse#4321]
## Problem

Our main tool to fight ToS violations at the moment is to employ Cloudflare rules targeting particular request/response headers. This works well, but isn't necessarily intuitive, and we can do more in this regard. We have no way built into Django admin to revoke access to a client application.

## Description

~Add a new throttle scope "revoked" that simply disallows access. Either raise a 401 in the throttle itself, or probably better, augment `conf.oauth2_extensions.OAuth2Authentication` to check the scope and raise DRF's unauthorised exception when the throttle scope is "revoked".~

We'll be adding a new boolean `revoked` to the throttled application instead. See context in this comment: https://github.com/WordPress/openverse/pull/4334#issuecomment-2113303369

## Alternatives

A workaround is to set the throttled application back to unverified. The registrant would not receive a new email to re-verify, so this effectively revokes access, as unverified applications receive 401s as well. However, this is only a workaround, and is indirect (there's no way to make this clear in Django admin, nowhere near as clear as an explicit throttle scope). As such, it is not a satisfactory long-term solution.

**Comment by madewithkode** [comment]
Hi @sarayourfriend, I'd like to take on this. 
I'd try to open a draft PR as early as possible and I'd appreciate as much guidance as I can  get as I don't have it all figured out.

**Comment by sarayourfriend** [comment]
Sure thing @madewithkode. You've seen it is high priority, so we'll be working on a quick turnaround for reviews and requested changes. You're welcome to work on it, but I'll ask you to be extra proactive in communicating any potential delays so we can hand off if needed. You've been a proactive communicator in the past, so I think it should be fine, just wanted to clarify expectations on this particular issue.

For implementation, to add a new throttle scope, create a new class `RevokedOAuth2IdRateThrottle`. It should be essentially a copy/paste of the `Exempt` throttle class, but with exempt replaced with "revoked" in the rate limit model set and scope string.

Here's the code of the exempt throttle class: https://github.com/WordPress/openverse/blob/c92d484cd0f356cb71e8fd7fc15d4a45d6523d0f/api/api/utils/throttle.py#L186-L188

You'll also need to add a "revoked" entry to the `RATE_LIMIT_MODELS` attribute on `ThrottledApplication`:

https://github.com/WordPress/openverse/blob/098925afa90b26881b4b4d3e2baffa69049692c0/api/api/models/oauth.py#L30-L36

Django admin is already configured for the rate_limit_model field to be configurable by admins, so there's no need to make changes to Django admin for this issue.

Finally, in `OAuth2Authentication`, you'll need to add an additional condition to raise `rest_framework.exceptions.PermissionDenied` when `request.auth.application.rate_limit_model == "revoked"`. You'll need to check if `request.auth` and `request.auth.application` exist too or use a combination of calls to `getattr`.

That's the implementation work, I think. Last part is to add and update `test_auth` to account for the revoked throttle class:

https://github.com/WordPress/openverse/blob/575f529a1aed2c01efce6abd3684a4cd98dc375f/api/test/integration/test_auth.py#L135

This is a significant issue with a few different moving parts, and the unit tests will probably almost certainly require adjustments to existing tests (at the very least to exclude the "revoked" throttle class from tests that expect authentication to pass), as well as brand new tests. `test_auth` is a bit of a gnarly module, so please reach out early if you run into difficulties with that. The tests are almost certain to be the most complex and tedious part of this issue.
