### ISSUE TITLE
Reenable Science Museum provider in Django admin

### ISSUE THREAD

**Issue by stacimc** [WordPress/openverse#4350]
## Problem

Once an image data refresh has been run successfully, later than May 16 2024 (time of issue creation), we will be able to reenable the Science Museum provider in Django admin to begin serving results in the API.

Update for clarity: #4261 tracks the relevant issue. After some provider API updates for Science Museum we noticed many of our URLs for that provider were invalid, and had to merge code to fix them in the DAG, run a backfill, and finally run a data refresh.

**Comment by stacimc** [comment]
I am assigning this issue to myself to make sure I don't forget about it, but if the image data refresh succeeds before I can get around to this any maintainer should feel free to grab this.

**Comment by stacimc** [comment]
Update: the initial run of the Science Museum DAG after merging code to validate the URLs encountered unrelated Gateway Time-out errors on the provider side, preventing ingestion from completing the backfill for all records. We needed to do a `skip_ingestion_errors` run to complete the backfill, but this was delayed by repeated issues with a catalog deploy. We finally got a `skip_ingestion_errors` run of Science Musem with the url validation to complete on 2024-06-18.

The image data refresh which is _currently_ running at the time of this comment will update those records in the API. Once that completes, we can finally re-enable the provider.

**Comment by stacimc** [comment]
I ran `select count(*) from image where provider='sciencemuseum' and url ilike '%/images/%'` in the production API and verified that there are 0 Science Museum records with the incorrect URL formatting. I also spot checked a few image URLs just to make sure they were valid and all worked 👍

**Comment by krysal** [comment]
The Science Museum has been re-enabled; you can check it out at https://api.openverse.org/v1/images/stats/.
