### ISSUE TITLE
Alert

### ISSUE THREAD

**Issue by Marco1553** [WordPress/openverse#4354]
## Airflow log link

> **Note**: _Airflow is currently only accessible to maintainers & those given
> access. If you would like access to Airflow, please reach out to a member of
> @WordPress/openverse-maintainers_.

**Comment by Marco1553** [comment]
What

**Comment by dhruvkb** [comment]
@Marco1553 this issue was closed because you had not filled out the issue template. We will gladly reopen the issue if you fill out the issue template with the actual bug report or feature request.
