### ISSUE TITLE
Create a document for how to start the catalog stack and run a DAG for testing

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse#4356]
## Description

It would be useful to have a document we could point new contributors to that describes how to run the catalog stack, navigate to Airflow, and start a DAG. This could include a few suggestions of DAGs to run (i.e. DAGs which do not require API keys), like the ones for SMK or Finnish Museums. It should include screenshots and the instructions should not require knowledge of Airflow in order to execute.

This comment can be used as a basis for the document: https://github.com/WordPress/openverse/pull/4216#discussion_r1584615766

**Comment by madewithkode** [comment]
Hi @AetherUnbound I'd like to take on this. It's funny that I'd have to ask a similar question on how to make changes to the documentation 😅
Is there like a doc you can point me too or perhaps an overview of the steps required.

**Comment by AetherUnbound** [comment]
Ha, great question! Our documentation-documentation is available here: https://docs.openverse.org/meta/documentation/index.html#documentation. The [quick start](https://docs.openverse.org/meta/documentation/quickstart.html) should be particularly useful! That said, we don't have a document specific to _creating a new documentation page_. If you're up for tackling that as part of this work, that'd be extremely helpful! No pressure though 😄 The process will look like this:

1. Create a markdown file at a place within the `documentation/` hierarchy that makes the most sense.
2. Make sure that the file is present in the closest `index.md` file (usually alongside the file itself). For instance, a new file `dag_testing.md` in `documentation/catalog/guides/` would need an entry in `documentation/catalog/guides/index.md` with the name of the document (so this example would add `dag_testing` here: https://github.com/WordPress/openverse/blob/a1440025f5a60ac1dbbb4d3d3bb152faffe4964f/documentation/catalog/guides/index.md#L9).
3. Write the document using [MyST flavored Markdown](https://mystmd.org/guide).
4. Run `just lint` to make sure the document is formatted. 
5. Run `just documentation/live` locally (following the quick start guide) and navigate to the new page to make sure it looks okay!

That should be it, feel free to ask here or in Slack if you have any other questions about that process!

**Comment by madewithkode** [comment]
Thanks for the rundown! This should be enough to get started.
