### ISSUE TITLE
Write a page describing the machine-generated tags for the frontend

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse#4379]
## Problem

As part of the "Incorporate Rekognition Data" project, we need to add a page documenting the machine-generated tags.

## Description

[Description of the page in the Implementation Project](https://docs.openverse.org/projects/proposals/rekognition_data/20240510-implementation_plan_machine_generated_tags_frontend.html#add-about-tags-description-page)
We should add a page to explain the users the difference between where the Openverse tags come from, the difference between the source and generated tags, and a short description of the machine-generated tag providers. This page should be linked from the Generated tags section. This page will not be added to the header navigation.

**Comment by zackkrida** [comment]
Closed by #4442
