### ISSUE TITLE
Capture thumbnails during Europeana ingestion

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse#4403]
## Description

We've been advised by the folks who maintain the Europeana API that it would be advisable to use the thumbnails they've already generated rather than trying to generate our own! Given that we have a _few_ issues with generating Europeana thumbnails (#3970, #3783, #3480), it would definitely be ideal to use the values they provide instead.

The thumbnails are available in the `edmPreview` field within the returned data, here's an example with our sample data: 

https://github.com/WordPress/openverse/blob/aedc9c16ce5ed11709e2b6f0b42bad77ea1eb19b/catalog/tests/dags/providers/provider_api_scripts/resources/europeana/europeana_example.json#L93-L95

It looks like there could be a list of thumbnails, we should probably just retrieve the first one from the list.

In order to accomplish this, we'll need to modify the [Europeana provider ingestion script](https://github.com/WordPress/openverse/blob/7f4fb7c91363747505d72a63dc7509617d16acfc/catalog/dags/providers/provider_api_scripts/europeana.py). We should add a new function to the `EuropeanaRecordBuilder` class to retrieve this value. A good example to use would be [`_get_filesize`](https://github.com/WordPress/openverse/blob/7f4fb7c91363747505d72a63dc7509617d16acfc/catalog/dags/providers/provider_api_scripts/europeana.py#L156-L157). We'll then need to capture this information in `get_record_data`, by adding it to the dictionary with the `"thumbnail_url"` key here:

https://github.com/WordPress/openverse/blob/7f4fb7c91363747505d72a63dc7509617d16acfc/catalog/dags/providers/provider_api_scripts/europeana.py#L73

We'll also need to add tests for this function and update any other Europeana tests that might be affected. An example test for `_get_filesize` can be [found here](https://github.com/WordPress/openverse/blob/33f9f7c54c2a27593716ce429b2b4b42f8df6e22/catalog/tests/dags/providers/provider_api_scripts/test_europeana.py#L299-L308).

**Comment by madewithkode** [comment]
I'd love to take on this @AetherUnbound
