### ISSUE TITLE
Do not add "project" issues to the Backlog

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse#445]
## Problem

Currently, all new issues are added to the [Backlog on the Openverse GitHub board](https://github.com/orgs/WordPress/projects/3#column-14087268).  We have a special board for the Projects (issues with the "project" label), so it's better not to add them to the Backlog.

## Description

Update https://github.com/WordPress/openverse/blob/cc93d225869932fd683a33014b96da8eb831ff6e/.github/workflows/new_issues.yml#L22 with the correct label `🧭 project: thread`

**Comment by dhruvkb** [comment]
I believe the change required will be pretty small (like an extra `if` condition) so I marked it as a good first issue.

**Comment by obulat** [comment]
I couldn't find anything about selecting the issues with a specific label in the action we are using, @dhruvkb. There is a GitHub action that can add an issue with specific labels (with `and`, `or` or `not` between the labels) to a specific project column, but it only works with the new projects: https://github.com/actions/add-to-project

I think we should migrate Openverse project to the "new project' so that the UX is the same as in the Openverse Project board, and the newer actions are available to us.

**Comment by sarayourfriend** [comment]
This issue is still valid but the change should be very simple now, I believe it's just to update the line below with the correct label `🧭 project: thread`:

https://github.com/WordPress/openverse/blob/cc93d225869932fd683a33014b96da8eb831ff6e/.github/workflows/new_issues.yml#L22

**Comment by ngken0995** [comment]
Hello @sarayourfriend, Can i work on this?

**Comment by dhruvkb** [comment]
Should we also exclude "🧭 project: proposal" and "🧭 project: implementation plan" labels?
