### ISSUE TITLE
Determine if all tags in the catalog database have an associated provider

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse#4454]
## Problem

We recently encountered an issue with the API's Admin UI where the provider was not given for a tag: #4439

## Description

While this issue was explicitly referenced as occurring locally, it's expected that the `tags` column should have both the `name` and `provider` keys specified for each entry: https://docs.openverse.org/meta/media_properties/catalog.html#id24

We'll need to fix the data in the [`sample_image.csv` file](https://github.com/WordPress/openverse/blob/8e6b88442bdf84aa3c54492159e6298e9e8fa54a/sample_data/sample_image.csv), and also ensure that the data in production contains this field. If an update needs to be made to the production catalog data, we'll use a batched update for it and assume the `provider` for the tag is the same as the provider for the record.

Once this is checked, we could potentially revert #4440 since the assumption will be confirmed (although it may still be a good idea to have it around).

**Comment by AetherUnbound** [comment]
I ran the following query to try and gather more information about this (note that the `?` operator [checks for the existence of a key](https://www.postgresql.org/docs/current/functions-json.html)):

```sql
openledger=> select count(*), provider from image
openledger->  where exists (
openledger(>      select 1 from jsonb_array_elements(image.tags) as t where not t ? 'provider'
openledger(>  )
openledger->  group by 2;

 count  | provider
--------+----------
 184535 | flickr
(1 row)

Time: 3500796.006 ms (58:20.796)
```

I think the next step would be running a batched update for this to correct those values, but I wanted to see what was causing them:

```sql
deploy@localhost:openledger> select identifier, provider, tags from image
 where exists (
     select 1 from jsonb_array_elements(image.tags) as t where not t ? 'provider'
 )
 limit 1
+--------------------------------------+----------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| identifier                           | provider | tags                                                                                                                                                                                                                                                                                                                                                                                                                  |
|--------------------------------------+----------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| fc52c811-d446-4157-b575-752144ed7bc2 | flickr   | [{}, {"name": "ancientrome", "provider": "flickr"}, {"name": "capitolinemuseums", "provider": "flickr"}, {"name": "italia", "provider": "flickr"}, {"name": "italy", "provider": "flickr"}, {"name": "museicapitolini", "provider": "flickr"}, {"name": "roma", "provider": "flickr"}, {"name": "rome", "provider": "flickr"}, {"name": "sculpture", "provider": "flickr"}, {"name": "statue", "provider": "flickr"}] |
+--------------------------------------+----------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
```

Note the empty tag `{}` in the tags list. I'm going to try and see next if that's the _only_ cause of the issue in production data.

**Comment by AetherUnbound** [comment]
It looks like the empty tag arrays are indeed the cause of the issue in the catalog! 

```sql
openledger=> select count(*), provider from image
openledger->  where exists (
openledger(>      select 1 from jsonb_array_elements(image.tags) as t where not t ? 'provider' and t != '{}'::jsonb
openledger(>  )
openledger->  group by 2;
 count | provider
-------+----------
(0 rows)
```

Note that it looks like these are filtered out as part of the [cleanup step during the data refresh](https://github.com/WordPress/openverse/blob/9eb5edeb70de05aa0b68f167b8f915e03131ede6/ingestion_server/ingestion_server/cleanup.py#L134-L135), so they would never actually make it to the API. That said though, I think it makes sense to clean this data up anyway within the catalog. I'll craft a batched update config for it.

**Comment by AetherUnbound** [comment]
I believe this should work as the input for a batched update:

```json
{
    "query_id": "remove_empty_tags_objects",
    "table_name": "image",
    "select_query": "WHERE provider = 'flickr' AND EXISTS (SELECT 1 FROM jsonb_array_elements(image.tags) AS t WHERE t = '{}'::jsonb)",
    "update_query": "SET updated_on = now(), tags = (SELECT jsonb_agg(t1) FROM jsonb_array_elements(image.tags) as t1 WHERE t1 != '{}'::jsonb)",
    "batch_size": 10000,
    "update_timeout": 3600,
    "resume_update": false,
    "dry_run": true
}
```

If that looks okay, then I'll kick that off and also open a PR to fix this in the source data.

**Comment by stacimc** [comment]
This looks good to me! Excellent investigation. Plan sounds great as well 🚢

**Comment by AetherUnbound** [comment]
This is blocked while we troubleshoot access rules for Airflow's UI.

**Comment by AetherUnbound** [comment]
This was run successfully using a batched update!

> Updated 184,535 records for query: `remove_empty_tags_objects`
