### ISSUE TITLE
Link to the catalog quickstart guide from the central quickstart page

### ISSUE THREAD

**Issue by dhruvkb** [WordPress/openverse#4479]
## Description

The [central quickstart page](https://docs.openverse.org/general/quickstart.html) does not link to the [catalog quickstart guide](https://docs.openverse.org/catalog/guides/quickstart.html). That should be fixed by adding the link.

The changes need to be made to this file here:

https://github.com/WordPress/openverse/blob/0094a1d0495578692d76aa243d894aad8d9a16a0/documentation/general/quickstart.md?plain=1#L16-L19

## Additional context

This issue was identified at contributor day.

**Comment by szymon-polaczy** [comment]
I'd like to work on this
