### ISSUE TITLE
Update references to our developer tools to have the `./ov` prefix

### ISSUE THREAD

**Issue by dhruvkb** [WordPress/openverse#4482]
## Description

In our documentation we refer to our developer tools like `just`, `pdm` and `pnpm` in several places. The ideal approach now is to invoke these tools with either `./ov` prefix or inside the `./ov bash` shell.

This new approach needs to be updated in the documentation.

## Additional context

This issue was identified at contributor day.

**Comment by szymon-polaczy** [comment]
I'd like to work on this
