### ISSUE TITLE
Prevent race condition with "Draft release" and "Release app" workflows

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse#4505]
## Description

Apparently there is a race condition between these two, discovered by @stacimc last week when trying to deploy the catalog. Basically, if they run at the same time, it seems that "Draft release" may re-mark a release as draft even after it's been published (and triggered "Release app"). This caused a lot of confusion and it must be prevented. We can at least prevent concurrency between the two, I think that would fix the race condition, at least for when Release app ran just before Draft release.

I don't know whether the other way around would still have an issue, though. I think not, because draft release keeps the same drafted release ID? Anyway, we don't know what the race condition looks like in that direction, so we can at least prevent the one we do know about.

To implement the fix, use the same concurrency key for the two workflows. This will mostly be a big change to release app, which will now not be able to handle multiple apps at once. That's fine, really. Let them queue. We never need to move _that_ fast.

**Comment by dhruvkb** [comment]
I know we've closed this issue but I have to note a potential problem with this.

> That's fine, really. Let them queue.

Actually GitHub will not queue all workflows. In workflows with the same concurrency key, any new workflow run will cancel all queued but not currently running workflows and queue itself to run next ([explanation](https://github.com/orgs/community/discussions/12835)). 

We should ensure that maintainers do not release multiple apps as these workflow with the same concurrency keys will cancel each other.
