### ISSUE TITLE
Create a dataclass for indexer worker TaskStatus

### ISSUE THREAD

**Issue by stacimc** [WordPress/openverse#4534]
## Current Situation

#4330 added the new catalog indexer worker. For each triggered task, the indexer worker API maintains a [dictionary](https://github.com/WordPress/openverse/blob/417ba9c8f1562564691895e6e8c2c7e567f5a975/indexer_worker/indexer_worker/tasks.py#L49) of data related to the task's status.

## Suggested Improvement

 It would be better to define a `dataclass` or named tuple for this information, which would also allow us to have meaningful typing around the [`tasks` dictionary](https://github.com/WordPress/openverse/blob/417ba9c8f1562564691895e6e8c2c7e567f5a975/indexer_worker/indexer_worker/tasks.py#L21).

**Comment by akshay-km** [comment]
Is this issue still open? I would like to work on it. Can u assign it to me ?

**Comment by akshay-km** [comment]
@WordPress/openverse-maintainers Hi , I would like to work on this issue. Can you please assign this to me ? Thanks

**Comment by akshay-km** [comment]
@WordPress/openverse-maintainers  Hi , I would like to work on this issue. Can you please assign this to me ? Thanks

**Comment by akshay-km** [comment]
Hi , @krysal @stacimc  . I have created a PR , for this issue.  #4601 . If any corrections are needed, pls let me know
