### ISSUE TITLE
Add an analytics event showing how many results a search yields

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse#4561]
## Problem

Currently, we have the analytics data on what terms the users search for, but not on how many results they get for this search.
Adding this event would help us answer questions like "What are the popular searches that receive no results, or fewer than 1 page of results?"

## Description

Add a `GET_SEARCH_RESULTS` (name is under discussion) event near the existing `SUBMIT_SEARCH` event.
https://github.com/WordPress/openverse/blob/3e76e4ba3e258330697e55a58ade9f0f51238b1d/frontend/src/types/analytics.ts#L49-L62

I think the best place to send this event would be the store before we return `mediaCount`, if page is 1 (so, it fires once per a search term, and does not fire when you click on Load more):
https://github.com/WordPress/openverse/blob/3e76e4ba3e258330697e55a58ade9f0f51238b1d/frontend/src/stores/media/index.ts#L506

**Comment by spran180** [comment]
Hi, I would like to work on this issue. Can you please assign this to me? Thanks!

**Comment by obulat** [comment]
Hi @spran180, thank you for your interest! We are currently in a code-freeze in the Nuxt part of this repository because we are migrating to Nuxt 3. If you're interested, I'll assign the issue to you as soon as the code freeze is lifted.

**Comment by spran180** [comment]
Yes I'm interested @obulat. Once migration is completed you can assign it to me.

**Comment by obulat** [comment]
> Hello @obulat 👋
> 
> I am a student at Technical Universoty in Slovakia studying Informatics, and I have experience with web software development, particularly in Python backend technologies. I am eager to contribute to this project and would love to work on this issue.
> 
> Would it be possible to assign it to me? I'm confident that I can provide a solution and am available to start immediately. Please let me know if you need any further details from my side.
> 
> Looking forward to your response as soon as possible.

Sure, @Danil49 ! Please go ahead. If you have any questions, don't hesitate to ask them here.
