### ISSUE TITLE
Improve display of sensitive images on search result views

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse#4563]
## Problem

Sensitive images show up as a blurred gradient in the search results grid. When hovered, they show the CC licenses hover "tooltip" behind the sensitive blur.

![image](https://github.com/WordPress/openverse/assets/6351754/a3cb7d28-bb1d-497b-a528-73970539578b)

These blurred results may not clearly indicate that they are sensitive results enough. An example I've shared previously is cases where someone might be searching for gradient backgrounds:

![image](https://github.com/WordPress/openverse/assets/6351754/a00863d0-4c0c-4e0e-9970-b4151a410746)

However, even in cases where users are searching for results that do _not_ look like blurred gradients, I think we should still consider adding additional visual indication for sensitive results. 

Google, for example, uses an eye icon over the result itself:

![image](https://github.com/WordPress/openverse/assets/6351754/16443a2b-6195-461d-abbc-e7c62f8ba8c0)

## Description

Add the existing eye icon for show/hiding images to unblurred sensitive results on the search view. Fix the license hover to show _above_ the blur. 

## Additional context

CC @fcoveram for design ideas and suggestions.

**Comment by fcoveram** [comment]
Your suggestion makes total sense.

Do we have the capacity to implement it once we land on a solution? IIRC, we decided somewhere to pause frontend implementations. Also asking this to revisit my backlog and priorities.

**Comment by zackkrida** [comment]
> Do we have the capacity to implement it once we land on a solution?

In general, I think we can always have designs prepared even if we aren't ready to build the frontend code. Particularly for a fairly small feature like this, it might even be possible for a community contributor to work on.

**Comment by sarayourfriend** [comment]
If we want to find a community contributor, @madewithkode knew someone who was interested in getting involved contributing to Openverse design work, IIRC.

**Comment by madewithkode** [comment]
Sure @sarayourfriend! I can point them to this if @fcoveram needs an extra hand.

**Comment by fcoveram** [comment]
> In general, I think we can always have designs prepared even if we aren't ready to build the frontend code.

Absolutely. My point was primarily about _when_ to have the mockup given that there are currently about [9 tickets](https://github.com/WordPress/openverse/labels/design%3A%20ready) open and labeled with design ready that can be started to be implemented and I don't have the bandwidth to take this in about a week.

I'm currently addressing other requests, but by the end of the next week I can share a proposal. The design certainly doesn't involve many changes, but it might require a revision by all of us.

**Comment by sarayourfriend** [comment]
@fcoveram can you confirm that you do not need a community contributor to look at this? Want to respect your time and the effort it takes to usher designs through. If it's a small change, this could be a good entry point for someone else to start being able to contribute directly to new designs, but I can also understand that it might be a lot of work to onboard someone if you're already busy with work.

**Comment by fcoveram** [comment]
Any design contribution is always welcome. It's not strictly _needed_, but more hands are indeed helpful.

The change is small so it's a good entry point for sharing design ideas. The onboarding should not be hard task if the individual is familiar with Figma and Design Libraries. Openverse Design Library has all components and most pages to assemble a visual idea and share it here.

**Comment by fcoveram** [comment]
Here is an idea for this in light and dark mode

https://github.com/user-attachments/assets/a8dec64e-05d4-465c-9669-985797db960d

![Resting and hover state of image component in blurred](https://github.com/user-attachments/assets/708bc874-8a49-4e5e-b486-d34bc95c0681)

While designing the mockups, I noticed the eye icon doesn't provide much info for users that have not open the safe browsing settings, so I replaced the CC icons with a label describing the eye meaning during hover. It felt strange showing the license restriction of a content that you can not see.

What do you think of this?

**Comment by zackkrida** [comment]
> I replaced the CC icons with a label describing the eye meaning during hover. It felt strange showing the license restriction of a content that you can not see.

Excellent :+1: I think that is perfect.

Can you clarify something about light and dark mode @fcoveram? Is there a subtle color overlay (white in light mode, black in dark mode) over the blurred images to guarantee sufficient contrast with the eye icon? That is what it looks like, and I think it's a great idea.

**Comment by fcoveram** [comment]
> Is there a subtle color overlay (white in light mode, black in dark mode) over the blurred images to guarantee sufficient contrast with the eye icon?

Yes.

To reach a similar surface contrast feeling between light and dark, I added a blurred layer over the image with a background color called `bg-blur`. The alias and respective colors were added in the Design Library's variables as it goes

## Colors
* `white-88`: `#FFFFFF` at 88%
* `black-72`: `#000000` at 72%

## Alias
```
# Light theme
:root {
	bg-blur: var(white-88);
}

# Dark theme
:root {
	bg-blur: var(black-72);
}
```

**Comment by fcoveram** [comment]
[Here are all mockups](https://www.figma.com/design/StypVqPKOAqqELmOv0FmxM/Sensitive-image-on-search-results?node-id=22-13656&m=dev) marked as ready for dev.

I modified all components involving images by including the blurred layer for the sensitive content. I will create the issues requesting those changes.

**Comment by fcoveram** [comment]
The following issues were created requesting updates in some components:
* #4777
* #4778 
* #4779
