### ISSUE TITLE
Improve homepage text spacing

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse#457]
## Problem

Homepage texts have unbalanced line-height values.

## Description

@panchovm is working on making the text styles consistent, which should fix most text inconsistencies.

**Comment by fcoveram** [comment]
A solution to this was addressed in the designs of #4157 as the proposal involves tweaks in the homepage. I will replace the `design: needed` label with `design: ready`

**Comment by obulat** [comment]
Fixed by #4922
