### ISSUE TITLE
Renovate's pnpm is not updating pnpmfileChecksum

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse#4586]
## Description

Reported by @obulat.

Starting in Dependabot PRs which update JavaScript dependencies strip the `pnpmfileChecksum` key from our `pnpm-lock.yaml` file.

Here is an [example](https://github.com/WordPress/openverse/pull/4578/commits/0a96fa925348704c8539a633b46566587ed7d309) you van view (expand the diff for the `pnpm-lock.yaml` file to view).

It may be because Renovate is not using a late-enough PNPM version, which could be fixable in the GitHub action using this argument: https://github.com/renovatebot/github-action/blob/main/README.md#docker-cmd-file

Use that to run a new script that ensures the correct version of pnpm is used.

## Additional Information

- pnpm added `pnpmfileChecksum` in pnpm v9: https://github.com/pnpm/pnpm/releases/tag/v9.0.0
- pnpm v9 was added to [renovate on April 29](https://github.com/renovatebot/renovate/releases/tag/37.327.3) in 37.327.3

**Comment by zackkrida** [comment]
I looked at some of our renovatebot runs and it is using pnpm 9:

https://github.com/WordPress/openverse/actions/runs/9737120285/job/26868743673

Something more subtle is happening here, with how pnpm updates dependencies and rewrites lockfiles. 

I wonder if we can simply turn off the checksum?

**Comment by sarayourfriend** [comment]
Fixed by `ignoreScripts`, it seems! See https://github.com/WordPress/openverse/pull/4596/commits/329c461fbd96475d10934687a87f6f72193e1ab7 and https://github.com/WordPress/openverse/pull/4578/commits/4b524d88e70fb83745979533d445cd2641620c23

**Comment by sarayourfriend** [comment]
@WordPress/openverse-frontend if y'all notice Renovate acting up again, not doing the right thing, please open an issue right away so we can fix it!
