### ISSUE TITLE
Update external sources modal styles

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse#460]
## Problem

The external sources section needs to be more consistent with the rest of the text styles.

### Wide desktop
<img width="1077" alt="Screenshot 2023-02-03 at 9 10 20 AM" src="https://user-images.githubusercontent.com/15233243/216525733-b9b69400-db1a-4f48-ad01-77993ea00181.png">

### Mobile
<img width="372" alt="Screenshot 2023-02-03 at 9 12 32 AM" src="https://user-images.githubusercontent.com/15233243/216525992-df3da3af-93e8-413f-b5d0-38228dea98f9.png">

## Additional context
First reported by @panchovm

**Comment by fcoveram** [comment]
Here is an idea.

## `XL` breakpoint

https://github.com/WordPress/openverse/assets/895819/870c56d5-7b10-48ef-92b0-512431ac036e

## `XS` breakpoint

https://github.com/WordPress/openverse/assets/895819/4055b256-0765-43e2-850d-37cef79fb8eb

---

The button triggers a popover in a modal in all breakpoints. The design spans the following changes:

### Metasearch button
* It has the same height as the [Load more](https://www.figma.com/file/GIIQ4sDbaToCfFQyKMvzr8/Openverse-Design-Library?type=design&node-id=5173-16609&mode=design&t=JzKg0h3PdFx8XQ1v-4) in all breakpoints
* It follows the [Button](https://www.figma.com/file/GIIQ4sDbaToCfFQyKMvzr8/Openverse-Design-Library?type=design&node-id=4577-11868&mode=design&t=JzKg0h3PdFx8XQ1v-4) style with `border: gray` and `type: icon right`.

### Popover in modal
Overall, the popover follows the [Modal](https://www.figma.com/file/e4tLacmlPuZV47l7901FEs/WordPress-Design-Library?type=design&node-id=28524-24040&mode=design&t=ZV4igMACfeHQZBv2-4) implemented in Gutenberg.

* The popover is divided into three sections to make it reusable: Header, description, and content.
   * Header area has the popover title and close action.
   * Close button follows [Icon](https://www.figma.com/file/GIIQ4sDbaToCfFQyKMvzr8/Openverse-Design-Library?type=design&node-id=4658-12470&mode=design&t=JzKg0h3PdFx8XQ1v-4) component in `size: small`, `style: transparent`, `color: gray`.
* The container has a border-radius of `4px` in all breakpoints.
* In `XS` and `SM`, the container has a padding of `16px` and a margin of `32px`.
* In `MD` and beyond, the container has a padding of `24px` and a `max-width` value to be defined.
* Sources are [Popover item](https://www.figma.com/file/GIIQ4sDbaToCfFQyKMvzr8/Openverse-Design-Library?type=design&node-id=1343-3416&mode=design&t=JzKg0h3PdFx8XQ1v-4) elements with new styles. If we go with this design, the component update request should be a new ticket.

What do you think of this idea?

**Comment by zackkrida** [comment]
@fcoveram love the new idea. Having it be a button reinforces the idea that load more and this button are both ways of finding new media

**Comment by fcoveram** [comment]
If we decide to go with the design introduced above, we should also address #533

**Comment by sarayourfriend** [comment]
The new approach also looks great to me :+1:. A significant improvement over the popover menu.

**Comment by fcoveram** [comment]
Design file is ready for its development

**Figma file:** [Metasearch improvement](https://www.figma.com/file/AsD7zOnUQxuLaUBiptTYAn/Metasearch-improvement?type=design&node-id=22-13656&mode=dev).

---

The specs described [here](https://github.com/WordPress/openverse/issues/460#issuecomment-1636043869) remain true, except for the following change in small popover:
* **Breakpoint:** `XS` only.
* **Margin:** Margin of `24px` from screen device.

### Question
* Do we need to create the Metasearch button as a component? I already [made it](https://www.figma.com/file/GIIQ4sDbaToCfFQyKMvzr8/Openverse-Design-Library?type=design&node-id=5327-30330&mode=dev) for Figma, but not sure about its code version

**Comment by fcoveram** [comment]
Why was this ticket closed? The new metasearch button is part of the change and has yet to be implemented.

**Comment by fcoveram** [comment]
The improvement looks great in staging. Closing this ticket as the implementation is done. Great work ✨
