### ISSUE TITLE
Add a message to inform the user about more filters when one media type is chosen

### ISSUE THREAD

**Issue by dhruvkb** [WordPress/openverse#461]
## Problem

The list of features in the mixed media results page is very small and there is no indication that more filters are available when you select only one media type.

## Description

Add a message in the filters panel (something along the lines of "more filters are available if you select a certain media type") so that people can know that there are more filters and also how to access them.

## Additional context

This will need design input and also the i18n-ified message text.

**Comment by obulat** [comment]
@dhruvkb, this issue seems to be the same as #509. This was opened earlier, but 509 seems to have more detail (it has a possible design image :) ). Can we close one of these issues?

**Comment by dhruvkb** [comment]
Sure @obulat, let's only have the one with more details.

**Comment by zackkrida** [comment]
Closing in favor of #509
