### ISSUE TITLE
Remove environment name from Airflow Alerts message username

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse#4613]
## Problem

Airflow alerts include the environment "production" in the username in Slack:
![image](https://github.com/user-attachments/assets/3c12d5e8-a4a2-4cea-a0ce-64cba74d2806)

The message above is about the _staging_ ES cluster. But the username of the message makes it easy to get confused and think it's for the production cluster.

## Description

We have a single channel for alerts from the live Airflow instance. Any alerts going to that channel must be from the live instance and must never be from another source (outside of specific testing scenarios where this is communicated extremely clearly). The channel is exclusively for important alerts that need to be triaged.

In other words, the contract of that channel is such that the alerts are only from the live instance. This does not need to be clarified in every message from the live instance. Therefore, we can remove the "environment" name from the message username.

To fix this, remove the `environment` note from the username here: 

https://github.com/WordPress/openverse/blob/d500b7764c411f7d228ae12c57dce519c8709610/catalog/dags/common/slack.py#L339-L346

If we want to make sure locally created messages can under no circumstances be confused for real ones, even if they are somehow mistakenly sent to the live channel, we can modify the message body to indicate this when `ENVIRONMENT == "local"` or something... but I don't think this is expressly necessary.

**Comment by zackkrida** [comment]
For these messages as well, maybe we should pass the service name as the title so the full title would be something like "Airflow Alert | Elasticsearch Staging Cluster"

**Comment by sarayourfriend** [comment]
Nice! Good idea to lead with the environment name, even: "Staging ES cluster"/"Production ES cluster". Along with abbreviating ES in the title, it helps the environment not get lost or glossed over, which is really the important thing here.

**Comment by AetherUnbound** [comment]
For these kinds of alerts, we can also change the icon used for the alert itself in Slack, perhaps for even further distinction!
