### ISSUE TITLE
Inadequate space between media and search box when 'Back to results' link is absent

### ISSUE THREAD

**Issue by dhruvkb** [WordPress/openverse#462]
## Description

When the 'Back to results' link is missing, the media gets very close to the search bar at the top.

## Reproduction

1. Search for something.
2. Choose a result.
3. See the space between result top and search bar.
4. Refresh the page so that the 'Back to results' link goes away.
5. See the now-much-smaller space between the result top and search bar.

## Screenshots

| With back link | Without back link |
|-|-|
| ![image](https://user-images.githubusercontent.com/16580576/216292010-a734e1a8-bcff-43b5-95b3-76ee91dfa2f0.png) | ![image](https://user-images.githubusercontent.com/16580576/216291487-180aee0a-de94-4224-8075-f0858ba73371.png) |
| ![image](https://user-images.githubusercontent.com/16580576/216292291-da76a077-b906-4fa3-997f-b686799da518.png) | ![image](https://user-images.githubusercontent.com/16580576/216290984-594da8bf-4a0e-4c7a-b248-88a8fe3ae30c.png) |

**Comment by obulat** [comment]
The designs were changed, and we no longer have a search bar on the single result page.
