### ISSUE TITLE
Fix issues with ES node replacement documentation

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse#4620]
The [ES node replacement doc](https://docs.openverse.org/meta/maintenance/elasticsearch_cluster.html#node-replacements) has a few issues I need to fix:

- `<env>` is used in multiple contexts which accept different values (`staging` in some places, `dev` in others, for example)
- Inconsistency with usage of `j tf` versus `terraform` in places. I think we should stick to using plain `terraform` while CD-ed into the correct directory, and note such in the instructions.
- Step 8 forgets to include the `-<env>-` section of the elasticsearch module name(s), which could confuse someone implementing the plan.
- **Critical** Step 3 brushes over the terraform plan/apply step, despite this step needing to be a targeted apply in our old terraform state. Applying a non-target state change here could be disaster.
- Nit: incorrect "ElasticSearch" capitalization in places

**Comment by krysal** [comment]
Resolved in #5212.
