### ISSUE TITLE
Normalise `verbose_name` and `verbose_name_plural` for audio models

### ISSUE THREAD

**Issue by dhruvkb** [WordPress/openverse#4655]
## Description

Audio models have either none, or incorrect `verbose_name_plural` values. Additionally they all lack `verbose_name`.

| Model | Current `verbose_name_plural` | Expected `verbose_name_plural` | Expected `verbose_name` |
|-|-|-|-|
| Audio | None | "audio tracks" | "audio track" |
| SensitiveAudio | "Sensitive audio" | "sensitive audio tracks" | "sensitive audio track" | 
| DeletedAudio | "Deleted audio" | "deleted audio tracks" | "deleted audio track" |

Note the lowercasing of the first letter in `verbose_name_plural` and the use of "track(s)" to differentiate singular and plural values.

This change will lead to a new no-op migration.

## Additional context

These textual changes actually make a significant difference in the experience of moderation as the Django admin uses these values heavily to build menus and pages.

**Comment by Yadavanurag13** [comment]
```
class Meta:
        verbose_name = "Deleted audio"
        verbose_name_plural = "Deleted audios"


class Meta:
        db_table = "api_matureaudio"
        verbose_name = "Sensitive audio"
        verbose_name_plural = "Sensitive audios"
```
@dhruvkb is this the expected solution?

**Comment by dhruvkb** [comment]
No @Yadavanurag1. The solution would be to specify the value in the expected columns for `verbose_name` and `verbose_name_plural`.

**Comment by dryruffian** [comment]
Hi @dhruvkb,

```python

class Audio(AudioFileMixin, AbstractMedia):

    class Meta(AbstractMedia.Meta):
        db_table = "audio"
        verbose_name = "audio track"
        verbose_name_plural = "audio tracks"

```

is this the expected solution and I will also do it for classes `SensitiveAudio` and `DeletedAudio`, if its can you please assign this issue to me.
