### ISSUE TITLE
iNaturalist appears last in the alphabetically-sorted sources table 

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse#469]
## Description

The sorting for Sources page is case-sensitive, so `iNaturalist` comes last because it starts with a lower-case letter.

## Reproduction

1. Go to https://staging.openverse.org/sources

2. View the image sources table
3. You should see that iNaturalist is last when the table is sorted by the source name.

## Screenshots
<img width="1037" alt="Screenshot 2023-02-01 at 11 11 47 AM" src="https://user-images.githubusercontent.com/15233243/215987392-52957ab0-5015-42e8-97eb-8db8399b3ee1.png">

## Additional context

The sources in the filters are listed in a correct, case-insensitive, order.

**Comment by Chirag57** [comment]
#3026

**Comment by Chirag57** [comment]
#3026
