### ISSUE TITLE
Nuxt 3 frontend is using build-time environment variables (`import.meta.env`) for runtime variables

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse#4703]
## Description

@zackkrida found that Plausible was originally an issue, and in investigation Zack and I realised that we are using build-time variables for things that must be runtime:

https://github.com/WordPress/openverse/blob/d423c4b5e4c566585739e4adb82ecc3c92944aaa/frontend/nuxt.config.ts#L198

https://github.com/WordPress/openverse/blob/d423c4b5e4c566585739e4adb82ecc3c92944aaa/frontend/nuxt.config.ts#L67

`import.meta.env` is build time: https://nuxt.com/docs/api/advanced/import-meta#builder-properties

These (and probably other variables) must be runtime.

This issue is critical because we are missing a huge number of Sentry alerts due to alarms being configured for production, but `deploymentEnv` being set to LOCAL in the live environments due to the build-time variable usage.

**Comment by zackkrida** [comment]
cc @obulat (since you're active in GitHub at the moment and might see this)
