### ISSUE TITLE
Sphinx/MYsT dev build is very slow

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse#4726]
## Current Situation

The various Sphinx extensions we use combined with the very large number of files (particularly the changelogs) results in a huge overhead for starting up the Sphinx dev site (`ov just documentation/live`).

## Suggested Improvement

It would be nice to find a workaround for this so that most cases of building the dev site could be faster, with optional configuration available to enable a "full" build.

One approach could be to just ignore the changelog directory by default, changelogs account for close to 50% of the files in the documentation site, noticeable during the "Write output" step of the build.

I've tried disabling some extensions locally, like the two custom extensions we have (link issues and link usernames), but doing so does not noticeably speed up the build.

Ignoring the changelogs could be accomplished by conditionally adding them to the `exclude_patterns` list in `documentation/conf.py` based on an environment variable. Something like this could be a good start:

```python
import os

CI = os.getenv("CI") is not None
INCLUDE_CHANGELOGS = bool(os.getenv("INCLUDE_CHANGELOGS", CI))

_default_exclude_patterns = ["_build", "Thumbs.db", ".DS_Store", ".venv", "README.md"]
exclude_patterns = _default_exclude_patterns + ([] if INCLUDE_CHANGELOGS else ["changelogs"])
```

Ideally we'd discover the source of the slowness and see whether there are official workarounds. We destroy the build cache in the `documentaiton/live` recipe. Perhaps this isn't always necessary, and we could be more judicious about when we do it, rather than doing it _every_ time.

## Benefit

Reduce the overhead of most documentation live site builds, speeding up work on documentation, encouraging proper local review of changes, make the documentation more pleasant to work with.

**Comment by kb-0311** [comment]
@sarayourfriend Could something like this be used here? I would say, let's by default exclude the changelogs unless explicitly instructed to include them.

````python
import os

exclude_patterns  = ["_build", "Thumbs.db", ".DS_Store", ".venv", "README.md"]

INCLUDE_CHANGELOGS= os.getenv("INCLUDE_CHANGELOGS")

if to_include_changelogs:
    exclude_patterns.append("changelogs")

````

something like this,maybe?

**Comment by sarayourfriend** [comment]
Sure, that fits within the approach I shared in the issue description. It would be useful to default (or maybe just _force_) the inclusion of changelogs in CI: `os.getenv("CI") or os.getenv("INCLUDE_CHANGELOGS")`.

If you'd like to implement that, please feel free, just let me know and I'll assign the issue to you :slightly_smiling_face: 

One thing to keep in mind, if changelogs are excluded, then references to them from other documents won't resolve and Sphinx will complain about this. I can't remember if it will crash the live preview site, it might be conditional on the specific circumstances. Which is just to say: there might be slightly more nuance than telling Sphinx to ignore the changelogs: it might also be necessary to mock the changelogs as a location in that case so other references don't break and cause Sphinx live preview to behave strangely.

**Comment by kb-0311** [comment]
Yeah, please do assign the issue to me. 

> It would be useful to default (or maybe just force) the inclusion of changelogs in CI: os.getenv("CI") or os.getenv("INCLUDE_CHANGELOGS").

So the intended behaviour is to keep the change logs unless explicitly specified not to, right?

>it might also be necessary to mock the changelogs as a location in that case so other references don't break and cause Sphinx live preview to behave strangely.

so kind of like redirecting the references to the changelogs in existing documentation to a placeholder 404 page or something like that maybe?
