### ISSUE TITLE
Text cutoff in responsive

### ISSUE THREAD

**Issue by Himshekhar07** [WordPress/openverse#474]
## Description
On this page https://wordpress.org/openverse/, the text cutoff at the responsive below 375px.

## Reproduction

1. Open https://wordpress.org/openverse/
2. Responsive at 375px x 437px
3. See the text "Explore more than" at top of the hero banner.

## Screenshots

https://share.cleanshot.com/9fG1lHgXjwzLfwLlpZ8H

## Environment

- Device: Laptop
- OS: iOS
- Browser: Chrome
- Version: 108.0.5359.124

**Comment by zackkrida** [comment]
Fixed.
