### ISSUE TITLE
Improve recent searches privacy notice

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse#4741]
## Problem

The current recent searches privacy notice is confusing and overly technical:

> Openverse does not store your recent searches, this information is kept locally in your browser

It's unclear what is meant by "Openverse" (many users will not know the difference between the Openverse API and servers and the Openverse website running in their browser), and "local" with respect to a client/server relationship is technical jargon.

The phrasing also complicates the message by alluding to an assumption (that the recent searches are shared with Openverse's servers) but not saying it explicitly. This can be resolved by simplifying the message altogether, which will also shorten it.

On mobile screens the text in English wraps to two lines. On smaller mobile screens or for larger screens in languages with longer strings, the keyboard will cover the second line after some recent results appear.

![Screenshot_20240812-065110](https://github.com/user-attachments/assets/c4b957ad-d2e1-49e1-a07a-5250efe0e84f)

## Description

Update the text to read:

> Recent searches are saved on your computer and never shared

Update the text in `en.json5`. It may also be necessary to update Playwright snapshots for this change: <https://docs.openverse.org/frontend/guides/test.html#updating-snapshots>

Run the following to do so:

```shell
ov just frontend/run test:playwright visual-regression -u
```

## Additional context

Marked with accessibility and interface to emphasise the issue with the existing terminology being inaccessible to non-technical users.

**Comment by zackkrida** [comment]
The proposed language is definitely an improvement :+1:

**Comment by fcoveram** [comment]
The text suggested is concise and clear. Thanks @sarayourfriend
