### ISSUE TITLE
Storybook configuration is split between Nuxt config and Storybook directory

### ISSUE THREAD

**Issue by dhruvkb** [WordPress/openverse#475]
## Description

Currently the Storybook configuration is partly defined in the Nuxt config monolith `nuxt.config.ts` and partly in the Storybook directory `.storybook/`. This can lead to conflicting configurations and unnecessarily complicates the layout.

All the configuration should be in one place.

## Additional context

I'm not entirely decided on what the better place is between the two although I am leaning towards `nuxt.config.ts`.

**Comment by dhruvkb** [comment]
Related to #596.

**Comment by obulat** [comment]
Closing this issue as Storybook is not currently set up, and the setup will change once the module is ready.
