### ISSUE TITLE
`airflow_log_cleanup_workflow` module docs are invalid markdown

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse#4750]
## Description

The following two lines produce invalid markdown due to the angle brackets used to surround the type annotations:

https://github.com/WordPress/openverse/blob/97dba8e4e53c888cf854dd940272489bc146399d/catalog/dags/maintenance/airflow_log_cleanup_workflow.py#L19-L20

This causes an issue for e.g., prettier parsing the DAG docs file:

```
documentation/_serve/catalog/reference/DAGs.html
[error] documentation/_serve/catalog/reference/DAGs.html: SyntaxError: Unexpected closing tag "p". It may happen when the tag has already been closed by another tag. For more info see https://www.w3.org/TR/html5/syntax.html#closing-elements-that-have-implied-end-tags (1292:40)
[error]   1290 | <p><code class="docutils literal notranslate"><span class="pre">--conf</span></code> options:</p>
[error]   1291 | <ul class="simple">
[error] > 1292 | <li><p>maxLogAgeInDays:<INT> - Optional</p></li>
[error]        |                                        ^^^^
[error]   1293 | <li><p>enableDelete:<BOOLEAN> - Optional</p></li>
[error]   1294 | </ul>
[error]   1295 | </section>
```

Changing these to use some other syntax to annotate the type would solve this. The angle bracket syntax isn't used anywhere else, and the types do not correspond to JSON types, which is the input format, nor exactly match Python type names, so I'm not sure if this is following some specific but unfamiliar to me syntax for annotation.

## Fix

We can fix this by changing these to use parenthesis.

**Comment by AetherUnbound** [comment]
The file referenced looks like it's the _produced_ HTML for our documentation site, which is in `documentation/_serve` 🤔 I'm not sure that's something prettier should be running on in most cases (particularly `ov just lint`)...either way, easy enough fix.

**Comment by sarayourfriend** [comment]
> The file referenced looks like it's the produced HTML for our documentation site, which is in documentation/_serve

Oh, true, I hadn't noticed that. Probably worth an issue for that one! It might have been the way I was running prettier at the time, though, I haven't seen this error come up when running it again.

On the other hand, we probably _should_ validate the HTML output, if this kind of thing is possible, provided we want the HTML output to be valid :sweat_smile:

I'm guessing if we did need angle brackets we'd actually need to transform them (at which step I'm not sure) into HTML escape sequences, like you would when wanting to render angle brackets in HTML anyway.
