### ISSUE TITLE
Improvement over image component

### ISSUE THREAD

**Issue by fcoveram** [WordPress/openverse#4777]
As per the [design](https://github.com/WordPress/openverse/issues/4563#issuecomment-2243368772) introduced in #4563 for an enhanced version of browsing results with sensitive images, the image component requires some changes.

## Description

[Both versions](https://www.figma.com/design/GIIQ4sDbaToCfFQyKMvzr8/Openverse-Design-Library?node-id=4050-9020&m=dev) of the component documented in the Design Library have the following changes:

### Image large
* Blur layer over image has the `bg-blur` variable
* In hover and focus, the component shows the text "Sensitive content" inside. Center and bottom aligned

![image large variant in Figma with specs](https://github.com/user-attachments/assets/869b4736-bb92-47e8-8546-254f773b682d)

### Image small
* Blur layer over image has the `bg-blur` variable
* The text "Sensitive content" replaces the CC license icons
* In resting state, the label has the `text-secondary` variable applied
* In hover and focus states, the label has the `text` variable applied

![image small variant in Figma with specs](https://github.com/user-attachments/assets/7fcce05a-bb27-40bf-bdcd-f3ba870bbfdd)

The alias mentioned above go as (copied from [this comment](https://github.com/WordPress/openverse/issues/4563#issuecomment-2244785363)): 

#### Colors
* `white-88`: `#FFFFFF` at 88%
* `black-72`: `#000000` at 72%

#### Alias

```
# Light theme

:root {
	bg-blur: var(white-88);
}

# Dark theme

:root {
	bg-blur: var(black-72);
}
````

## Additional context

The tokens applied are according to #3592 project

**Comment by dhruvkb** [comment]
In the process of implementing this I have observed that the text "Sensitive content" does not look very good for tall images. For example, see image number 5 in the second row here.

<img width="1840" alt="image" src="https://github.com/user-attachments/assets/7533fecf-c853-4f8b-be6d-9f2b07cd4eb4">

@fcoveram what would you recommend as the course of action in that case?

**Comment by fcoveram** [comment]
That looks good to me
