### ISSUE TITLE
Improvement over audio component

### ISSUE THREAD

**Issue by fcoveram** [WordPress/openverse#4778]
As per the [design](https://github.com/WordPress/openverse/issues/4563#issuecomment-2243368772) introduced in [#4563](https://github.com/WordPress/openverse/issues/4563) for an enhanced version of browsing results with sensitive images, the audio component requires some changes.

## Description

The three variants of the component documented in the Design Library need to allow hiding the image beneath a blur layer that has the `bg-blur` variable applied. There are no changes over current interactions.

Screenshots from the [design file](https://www.figma.com/design/StypVqPKOAqqELmOv0FmxM/Sensitive-image-on-search-results?node-id=22-13656&m=dev) made for #4563 

| `XL` breakpoint | `XS` breakpoint |
|:---|:---|
| ![Mockup of audio results on desktop. One track has the image cover blurred](https://github.com/user-attachments/assets/cdd4adf3-f594-4e90-8e4d-87cb25a6152f) | ![Mockup of audio results on mobile. One track has the image cover blurred](https://github.com/user-attachments/assets/5b2568d5-1dd4-484b-bae5-2892e8e25822)|

## Additional context

The tokens applied are according to #3592 project

**Comment by obulat** [comment]
## Implementation

If `shouldBlur` is `true`, the `VAudioThumbnail` in `VRowLayout` component:

https://github.com/WordPress/openverse/blob/975c543a221a19169c7bde5f31ea7a8eafb1f977/frontend/src/components/VAudioTrack/layouts/VRowLayout.vue#L11

should be replaced with a `div` with `bg-blur` class and a `VIcon` with `eye-open` as the name. Sample use of `VIcon`:

https://github.com/WordPress/openverse/blob/975c543a221a19169c7bde5f31ea7a8eafb1f977/frontend/src/components/VSafetyWall/VSafetyWall.vue#L56
