### ISSUE TITLE
Improvement over global player component

### ISSUE THREAD

**Issue by fcoveram** [WordPress/openverse#4779]
As per the [design](https://github.com/WordPress/openverse/issues/4563#issuecomment-2243368772) introduced in #4563 for an enhanced version of browsing results with sensitive images, the global player comoponent requires one change.

## Description

Audio cover image needs to allow be hidden beneath a blurred layer that has the `bg-blur` variable applied. There are no changes over current interactions.

<img alt="Mockup of audio results on mobile. Global player is active with a blurred image cover" src=https://github.com/user-attachments/assets/454f6d96-f8a4-4f8d-bb58-c30974127826 width=320>

## Additional context

The tokens applied are according to #3592 project

**Comment by obulat** [comment]
## Implementation

https://github.com/WordPress/openverse/blob/975c543a221a19169c7bde5f31ea7a8eafb1f977/frontend/src/components/VAudioTrack/layouts/VGlobalLayout.vue#L6

Here, if `shouldBlur` is true, the `VAudioThumbnail` should be replaced with a simple div with `bg-blur` and `VIcon` named "eye-open", as here: https://github.com/WordPress/openverse/blob/975c543a221a19169c7bde5f31ea7a8eafb1f977/frontend/src/components/VSafetyWall/VSafetyWall.vue#L56

The snapshots for visual regression tests will need to be updated, [here are the instructions for updating the snapshots using the GitHub CI](https://docs.openverse.org/frontend/reference/testing_guidelines.html#debugging)
