### ISSUE TITLE
"Testing Nuxt 3" text hidden on frontpage

### ISSUE THREAD

**Issue by d3jawu** [WordPress/openverse#4811]
## Description

The text "Testing Nuxt 3" is present on the frontpage. It's not immediately visible, but can shows up when copy-pasting text (see reproduction).

## Reproduction

1. Highlight the two blocks of header text on the frontpage:
<img width="598" alt="image" src="https://github.com/user-attachments/assets/e7e42475-43e7-4426-a3a7-1efc586afcb7">

2. Paste into a text editor:
<img width="862" alt="image" src="https://github.com/user-attachments/assets/6194b503-2d61-40c6-a116-72e01da5b742">

## Screenshots

The tag containing the text is also visible in the markup.

<img width="1210" alt="image" src="https://github.com/user-attachments/assets/7459a32d-8209-499d-b28f-0e5381d5cd37">

## Environment

- Device: MacBook Pro; Android phone (repro'd on both)
- OS: MacOS Sonoma 14.6.1, Android 14
- Browser: Firefox, Firefox Mobile

**Comment by obulat** [comment]
Thank you for catching and reporting this, @d3jawu !

**Comment by d3jawu** [comment]
I've found the corresponding element in a template, it seems to be related to i18n:

<img width="633" alt="image" src="https://github.com/user-attachments/assets/80b38e2b-69a9-4090-b57d-c340b2d2d7f6">

**Comment by obulat** [comment]
Yes, we've added it in when testing the Nuxt 3 deployment (when migrating from Nuxt 2). The lines 88-90 should be removed.
