### ISSUE TITLE
Add 90% ES CPU alarms to the list of those disabled for the data refresh

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse#4826]
## Description

Presently, we disable the Elasticsearch 50% CPU alarm during the course of the data refresh process. Since #4683, the data refresh has also been tripping the Elasticsearch 90% CPU alarm as well. We should add this to the list of alarms which get disabled. Specifically:

https://github.com/WordPress/openverse/blob/d500b7764c411f7d228ae12c57dce519c8709610/catalog/dags/common/cloudwatch.py#L73-L72

We should add another `enable_alarm_actions` call for `ES Prod CPU utilization above 90%`.

**Comment by coson-lu** [comment]
@WordPress/openverse-maintainers
Is the fix for this issue just adding

`cw_wrapper.enable_alarm_actions("ES Production CPU utilization above 90%", enable)`

after

`cw_wrapper.enable_alarm_actions("ES Production CPU utilization above 50%", enable)`?

**Comment by AetherUnbound** [comment]
Hey @coson-lu! That's correct.

**Comment by coson-lu** [comment]
@WordPress/openverse-maintainers
I can work on this issue.
