### ISSUE TITLE
Add Flickr source for Katmai National Park and new homepage images set

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse#4856]
## Problem

Katmai National Park uploads PDM images of bears, notably during the famous [Fat Bear Week](https://www.nps.gov/katm/learn/fat-bear-week.htm).

https://www.flickr.com/photos/katmainps/

## Description

These are high quality photos of bears, plus also something that a lot of people are aware of and might look for. I don't think we could legally make explicit reference to fat bear week, but adding Katmai as a source, would be fun... and we could add a homepage image carousel of bears from Katmai during/around Fat Bear Week (again, without explicit mention of fat bear week).

- [x] [Add Katmai NPS as source to Flickr ingestion](https://github.com/WordPress/openverse/pull/4971)
- [x] Backfill Katmai NPS as source for works we've already ingested (batched update kicked off)
- [x] Add Katmai NPS as source to production API (needs to be manually done in Django Admin)
- [ ] Add the Katmai homepage image set (includes identifying the images to use, partially complete)

**Comment by sarayourfriend** [comment]
We were missing some really great images from Katmai due to the original licence being all-rights-reserved. That caused them to be skipped when we ingested the relevant time period.

To at least have last year's fat bear week photos available, I manually reingested Katmai NPS from September 1 to December 1, 2023, using these query parameters in the flickr workflow:

```json
{
        "max_upload_date": 1701349200,
        "min_upload_date": 1690812000,
        "user_id": "99350217@N03"
}
```

That ingested 122 PDM images from last year's Fat Bear Week and the surrounding months.

Afterwards, I initiated a batched update to backfill Katmai NPS as the `source` for images from that Flickr creator. That is still runnnig and will probably take at least 90 minutes (based on the time other smaller batched updates have taken recently).

In the meantime, I've gone ahead and found a handful of images from Katmai NPS that we already have in Openverse, that might be good candidates for the homepage images. We need 12 total.

- Bear tracks, with human hands for size comparison: https://openverse.org/image/670130cc-e761-41e4-9436-1488f7254d57
- Cute photo of a fox: https://openverse.org/image/85f309a9-e844-4616-9e30-d5a9bab74bf6
- 2022 Fat Bear Week champion: https://openverse.org/image/9f117d7c-2f26-4ab3-ae82-42ceae94b7af
- NPS employees monitoring wolves: https://openverse.org/image/770f9136-0861-4ac7-83a8-9417c76935b6
- Another cute fox, this time peaking from behind a rock: https://openverse.org/image/cc4a9a03-7d81-4ee9-97ad-544eac11b33d

There are a _lot_ of really good images from last year that we should have available after this coming week's data refresh is complete. For example, these are all from October 2023:

- Holly eating clay: https://www.flickr.com/photos/katmainps/53230450000/
- Bear scratching an itch: https://www.flickr.com/photos/katmainps/53290888528/
- Extremely floofy subadult bear on a hike: https://www.flickr.com/photos/katmainps/53291014449/
- A very fat bear in front of a seaplane: https://www.flickr.com/photos/katmainps/53230325929/
- A bear with a fish in its mouth: https://www.flickr.com/photos/katmainps/53291110915/
- Ground squirrel: https://www.flickr.com/photos/katmainps/53290889118/
- Two cubs cuddling: https://www.flickr.com/photos/katmainps/53291013489/

**Comment by krysal** [comment]
Given a shift in priorities and the fact that the week of the event has already passed, we consider this ticket done. Thanks for driving this effort, @sarayourfriend. It'd be fun to get to try it next year!
