### ISSUE TITLE
Consider an animated loading state for slow thumbnails

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse#491]
## Problem

If a thumbnail response is particularly slow, perhaps we could show a clearer loading state instead of a static gray background.

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by panchovm** [comment]
So we don't need a design for this and instead implement the skeleton.

**Comment by zackkrida** [comment]
This can be closed. We've implemented a loading skeleton UI (still some accessibility questions with those, but it's implemented nontheless) and we have made fixes t large thumbnails we had in the past. The vast majority of our thumbs load quickly now.
