### ISSUE TITLE
Tweaks to VSafetyWall component to support dark mode

### ISSUE THREAD

**Issue by fcoveram** [WordPress/openverse#4910]
## Problem

After introducing the mockups for dark mode (#3592), I noticed that the [VSafetyWall](https://docs.openverse.org/storybook/iframe.html?globals=backgrounds.value:!hex(0d0d0d)&id=components-vsafetywall--default) component was not included in the designs.

### Related issues
* Component introduced in #791

## Proposal

The change is straightforward and simplifies the background with gradient and texture made for light mode to have a single `bg` color.

![VSafetyWall component on mobile and desktop in light version](https://github.com/user-attachments/assets/dc6b8673-18b1-43a8-a176-fa8af0ab89b5)

Its dark version behaves the same as in the dark mode designs where `bg` changes to a different shade. Here is the outcome.

![VSafetyWall component on mobile and desktop in dark version](https://github.com/user-attachments/assets/78ff7e3a-efe8-4693-9a85-588d0de0c1f7)

Although the gradient with texture reaches a more appealing white page, the darker version demands unnecessary visual tweaks.

What do you think of this change?

## Mockups
Figma file: [Dark Mode. i2 page](https://www.figma.com/design/OP3r0AJWo1k7U3K2hgRwwK/Dark-mode?node-id=2276-38118&m=dev)

**Comment by zackkrida** [comment]
@fcoveram looks great :+1:

**Comment by fcoveram** [comment]
Awesome. I added [the mockups](https://www.figma.com/design/GIIQ4sDbaToCfFQyKMvzr8/Openverse-Design-Library?node-id=7002-39382&m=dev) in the "Views" page in the Design Library.

![Safety wall mockup in different breakpoints](https://github.com/user-attachments/assets/e7aa0d75-29f1-4892-9d33-e3f461734de3)

There are a few frontend notes that are not part of the dark mode support and can be addressed in the future as follow-up improvements.
