### ISSUE TITLE
Use k6 release assets to build `ov` images

### ISSUE THREAD

**Issue by dhruvkb** [WordPress/openverse#4934]
## Description

The k6 RPM only provides packages for the `x86_64` architecture. Till the `aarch` version is not added to the RPM (grafana/k6#2136), we should use the assets from their [GitHub Releases](https://github.com/grafana/k6/releases) to get the platform specific build.

## Additional context

This was brought up in issue #4931, and hot-fixed by #4932 to use Rosetta emulation. This is a more elegant solution that avoids emulation. The most ideal would however be for k6 to start providing `aarch` builds in their RPM.

**Comment by obulat** [comment]
I think most contributors will never use k6. Maybe building it should be optional?
