### ISSUE TITLE
Button to return to top not working in search page

### ISSUE THREAD

**Issue by d3jawu** [WordPress/openverse#4948]
## Description
In the search results page, clicking the "return to top" button at the bottom-right of the page does not work.

## Reproduction
1. Run a search.
2. Click the `^` button at the bottom-right of the page.
3. The page does not scroll back to the top.

## Screenshots
<img width="802" alt="Screenshot 2024-09-17 at 1 53 28 PM" src="https://github.com/user-attachments/assets/805eb026-c9b7-414d-9902-89aa766ba8df">

## Environment
- Device: 15in M2 Macbook Air
- OS: MacOS Sonoma 14.6.1
- Browser: Firefox 130

## Additional context
The button still works on other pages, such the page for an individual piece of content, or the [Sources](https://openverse.org/sources) page.

**Comment by obulat** [comment]
Thank you for reporting, @d3jawu !
