### ISSUE TITLE
Change "exact match boost" implementation to use a `match_phrase` query in `should`

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse#4960]
## Problem

We currently use an additional simple query string entry into the boolean filter for search to boost exact phrasal matches on the title of a work:

https://github.com/WordPress/openverse/blob/50e401f17b9290cd373bdced98babd457700b990/api/api/controllers/search_controller.py#L305-L312

## Description

We can bypass simple query string altogether for this, saving some parsing cycles in Elasticsearch, and making our intention much clearer in code (and in the generated query), by using [`match_phrase`](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-match-query-phrase.html) directly. This also obviates the need to mock out the simple-query-string syntax for phrasal matches.

**Comment by dryruffian** [comment]
Hi @sarayourfriend,
Hope You are doing well, is this the solution you are looking for 
```python
exact_match_boost = Q(
    "match_phrase",
    title={
        "query": query,
        "boost": 10000
    }
)
```
if yes can you assignee me this issue.

**Comment by sarayourfriend** [comment]
That looks right, yep! I've assigned the issue to you, thanks!
