### ISSUE TITLE
Add Sutori to the "Made with Openverse" page

### ISSUE THREAD

**Issue by dhruvkb** [WordPress/openverse#4972]
## Problem

Sutori is a collaborative instruction and presentation tool for the classroom. Sutori integrates with Openverse to provide access direct access to our vast catalog images from their media uploader tool.

## Description

Add Sutori to the "[Made with Openverse](https://docs.openverse.org/api/reference/made_with_ov.html)" page. The source code for this webpage is at https://github.com/WordPress/openverse/blob/9525973401e86c664571fb040d1ec86a7a837ae1/documentation/api/reference/made_with_ov.md.

You can include the following links:

- [Homepage](https://www.sutori.com/)
- [Changelog announcing the integration](https://headwayapp.co/sutori-updates/millions-of-free-educational-resources-299145)

**Comment by dryruffian** [comment]
Hi @dhruvkb,
Hope you are well, I am aditya i am new to he open source world I think this issue will be great for clearing my basics so can you assign this issue to me

**Comment by dryruffian** [comment]
Hi @dhruvkb,
Thank you for assigning me this issue,
I've added Sutori to the "Made with Openverse" page. Sutori is an educational tool that integrates Openverse images in their media uploader.

Changes:
- New section for Sutori in `made_with_ov.md`
- Brief description and integration details
- Links to homepage and integration announcement

Please review and let me know if any changes are needed. Thanks!
