### ISSUE TITLE
Add search result index to the `SELECT_SEARCH_RESULT` event

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse#5005]
## Problem

We don't currently track the page of API results that a selected search result is chosen from. 

## Description

Indirectly track the page of a search result by including its index in the analytics event payload. Perhaps we should call this something like "resultPageIndex" or simply "index" depending on what @WordPress/openverse-frontend thinks.

**Comment by TusharNaugain** [comment]
@zackkrida To track the page of a selected search result include its index in the analytics event payload as resultPageIndex or index.
