### ISSUE TITLE
Update text area colors in dark mode

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse#5026]
## Description

The Content Report form text area color in dark mode should be updated.

## Reproduction
Go to a [single result page](https://staging.openverse.org/image/a3565050-50dc-4a57-8986-dc6bc3d8af48?q=dog), click on Report content button and select "Other" as the reason. You should see the text area that has white background.

## Screenshots

![Image](https://github.com/user-attachments/assets/6f823062-103b-471d-afa3-f89fd59ef286)

## Additional context

First [reported](https://github.com/WordPress/openverse/discussions/4783#discussioncomment-10398044) by @zackkrida 

@fcoveram, I extracted this sub-issue from #4911, but I don't know what the correct color in dark mode should be. Are there any designs for it?

**Comment by fcoveram** [comment]
I can't see the image attached above, so I don't know exactly which components are involved. Regardless, all elements in the Design Library's Components page already have the light and dark mode themes applied.

Here is how it looks like in dev mode.

https://github.com/user-attachments/assets/44b53738-cc15-4197-a2a9-61d51abfb659

**Comment by obulat** [comment]
Thank you for showing your workflow in the Playground, Francisco!

I fixed the linked image, and will fix the text area soon
