### ISSUE TITLE
Prevent layout shift when the theme switcher is rendered

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse#5085]
## Problem

Currently, when the theme switcher is rendered, it shifts the footer layout. This was done to avoid client-server mismatch and subsequent re-rendering.

## Description

A better solution would be to render a "unknown" value on the server, and then, in `onMounted`, set the correct value in the theme switcher. This way, there will be no layout shifting and no client-server mismatch.

**Comment by dhruvkb** [comment]
Another issue is that the "System" option also includes the actual applied theme in the option name, which causes hydration issues on clients whose default system theme is dark.

![Image](https://github.com/user-attachments/assets/b22e371b-6e15-48da-9e75-eb386c55f8af)
