### ISSUE TITLE
Update the color of `text-secondary`

### ISSUE THREAD

**Issue by fcoveram** [WordPress/openverse#5151]
## Problem

During the last monthly call (Nov 6th), we talked about the color feeling of `text-secondary` in content-heavy pages in light theme and how the lighter shade feels too soft for reading, as part of #5148 

We decided to make the `text-secondary` color darker in light theme while keeping the lighter version in dark theme.

## Description

Change `text-secondary` from `gray-9` to `gray-12` in light theme. The outcome uses the same gray shade in both `text` and `text-secondary`.

The Figma's Design Library variables were updated with this change.

![Screenshot of Figma variables of Openverse Design Library](https://github.com/user-attachments/assets/f8482d1a-355d-44e8-a601-6bd65e3019a7)

**Comment by dhruvkb** [comment]
@fcoveram this change would make the secondary text as dark as the primary in the light theme. Is that intentional? I thought we would be picking something darker but not as much as the primary.

**Comment by fcoveram** [comment]
It is intentional but open to change. 

I can try `gray-10` and `gray-11` in my browser inspector, and perhaps you both @obulat and @dhruvkb do the same and share your preferences here. What do you think?

**Comment by dhruvkb** [comment]
I tried your suggestion @fcoveram and to be honest, I did not observe major differences in contrast between `gray-11` and `gray-12`, (and `gray-10` felt a bit lighter and harder to read) so I'm inclined to accept your suggestion and use `gray-12`.

**Comment by fcoveram** [comment]
I tried both colors and `gray-12` keeps feeling better than lighter versions.

**Comment by obulat** [comment]
I agree, @fcoveram, `gray-12` feels more readable than the lighter colors.

**Comment by fcoveram** [comment]
Let's go with `gray-12` then. We can always change it in the future if needed.
