### ISSUE TITLE
`DataCloneError` raised on search in Safari

### ISSUE THREAD

**Issue by stacimc** [WordPress/openverse#521]
## Sentry link

https://sentry.io/share/issue/1e4d506348ab4ec79ab36a11d8d55a0f/

## Description

`DataCloneError: The object can not be cloned` is being raised by `postMessage` after a small number of searches. There are only 7 events in the last four months, all on Safari or Mobile Safari.

I'm unable to reproduce this using any of the searches in Sentry. The exception is raised _after_ a successful API response.

## Reproduction

Unable to reproduce.

**Comment by krysal** [comment]
I couldn't find this issue in Sentry and we don't have more reports about it so I'm closing it.
