### ISSUE TITLE
Scrollbar displayed even when element is not overflowing

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse#5282]
## Description

Setting overflow to `scroll` instead of auto makes Windows browsers display the scrollbar even if the content is not scrollable (browsers on MacOS hide it)

## Reproduction

1. Open the website on a Windows computer
2. See scrollbars on the homepage and on external sources modal.

## Screenshots

![Image](https://github.com/user-attachments/assets/50b70a15-9709-43dd-a9c6-49239323c98a)

## Environment

- OS: Windows

## Additional context

To fix the issue, the following lines need to change:

1.

https://github.com/WordPress/openverse/blob/b0ac47d52ca9ee8e6350c7eaf9672e6f54f7c78d/frontend/src/layouts/default.vue#L17

Replace `overflow-y-scroll` with `overflow-y-auto`.

2. 

https://github.com/WordPress/openverse/blob/b0ac47d52ca9ee8e6350c7eaf9672e6f54f7c78d/frontend/src/components/VModal/VModalContent.vue#L229-L230

Replace `scroll` with `auto`

**Comment by Anuj012004** [comment]
Hi, I’d like to work on this issue. Is it okay if I take this up?
Please let me know if there are any guidelines or additional details.

**Comment by dhruvkb** [comment]
Yes @Anuj012004! Please go ahead, I'll assign this to you.

**Comment by CoDinAIy** [comment]
Hello, has this issue been resolved yet? I am able to make a PR immediately if you approve.

Thanks

**Comment by dhruvkb** [comment]
@CoDinAIy thanks for your interest in this issue, and I appreciate you stepping back to give @Anuj012004 the chance to complete the task they've requested. You can look at the list of [good first issues](https://github.com/WordPress/openverse/issues?q=is:issue+is:open+sort:updated-desc+label:%22good+first+issue%22) to see if there are any other issues that you can help with.

**Comment by CoDinAIy** [comment]
Hi @dhruvkb I shall take a look tomorrow, thank you.
