### ISSUE TITLE
Amend repo 'acknowledgements' section

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse#53]
## Description

The acknowledgements section at the end of the sub-repo READMEs (example: https://github.com/WordPress/openverse-frontend/#acknowledgments) should be alphabetized and have the following names added:

- Jane Park (@janetpkr)
- Liza Daly (@lizadaly)
- Ryan Merkley (@ryanmerkley)

It is also likely preferable to switch to full names instead `@githubhandle`s.

Can you think of anyone else, @kgodey?

## Related PRs

- WordPress/openverse-frontend#210
- WordPress/openverse-api#207
- WordPress/openverse-catalog#172

**Comment by kgodey** [comment]
@sebworks and @pa-w were members of the CC Search team at CC before I joined CC and should also be credited.

**Comment by zackkrida** [comment]
Thank you!
