### ISSUE TITLE
Focus style animation inconsistent across the site

### ISSUE THREAD

**Issue by fcoveram** [WordPress/openverse#535]
## Description
The focus style animation when browsing with a keyboard changes from animated to static. I do not why and exactly where this occurs but it affects consistency and feels odd. 

## Reproduction
1. Search for anything.
2. Click on the search bar in the header while being in search results.
3. Browse with your keyboard, forward and backward.
4. See transition between focus styles between elements.

## Screenshots
<img src="https://user-images.githubusercontent.com/895819/180867940-cbbe36f6-7123-4ffe-b679-726e680be2ce.gif" width="650">

## Resolution
- [ ] 🙋 I would be interested in resolving this bug.

**Comment by obulat** [comment]
I think this issue has been fixed in the Core UI improvements project. Is there anything left here, @fcoveram ?

**Comment by fcoveram** [comment]
Nothing is left. It works excellent ✨ Closing this issue
