### ISSUE TITLE
Add proper logging to frontend

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse#536]
## Problem

Currently, we loosely use the `~/utils/console.ts` to sometimes log things, though not always in the most informational way. We also do not include useful debug information like a request ID, timestamps or standard formatting.

## Description

Using `winston`, `bunyan` or some other popular NodeJS logging library, enable JSON formatted logs with request IDs and try to clean up the existing logging a bit as well.

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by krysal** [comment]
Raising the priority, since the activation of the P99 response time alarm for Nuxt depends on this.

**Comment by sarayourfriend** [comment]
I have a working Nginx image locally. I'm playing around briefly with getting static file serving also working, but it's not a requirement for this, so if I can't get it working properly in the next hour I'll just put up the basic PR for Nginx that proxies everything to Nuxt.

This gives us per-request logging of key information matching the same logs for the API service, meaning we can reuse queries between the two, and avoids adding any new dependencies or complexity to the frontend to handle logging, which we don't necessarily need to unblock the other issue.
