### ISSUE TITLE
Different components in storybook and the staging site (audio box)

### ISSUE THREAD

**Issue by fcoveram** [WordPress/openverse#538]
## Description
While reviewing the components in storybook, I noticed a different version of the audio box small and the search bar on the staging site. I did not check all components but it might happen with other components too

## Reproduction
1. Open the [small version of the audio box](https://wordpress.github.io/openverse-frontend/?path=/story/components-audio-track--box-small).
2. Open the [all content results](https://search-staging.openverse.engineering/search/?q=cats) of the staging site on a small device.
3. Notice the difference by interacting with the component

## Screenshots
|Storybook|Staging site|
|:---|:---|
|<img src="https://user-images.githubusercontent.com/895819/178338616-74df60b7-e07e-40f2-a6e7-d1727e8d71f4.gif" width="170">|<img src="https://user-images.githubusercontent.com/895819/178339188-f8b71af5-3c43-41d0-b69a-0e1dc697775c.gif" width="170">|

## Resolution
- [ ] 🙋 I would be interested in resolving this bug.

**Comment by obulat** [comment]
The issue was solved, @fcoveram 🎉
