### ISSUE TITLE
Image results grid improvement

### ISSUE THREAD

**Issue by fcoveram** [WordPress/openverse#547]
## Problem
The current image result view does not display the CC-license icons on `sm` breakpoint. The last mockup shared showed the icons below each image in a 2 columns grid, but there is an ongoing proposal for supporting 3d model content that needs to be taken into account.

### Issues related
* Problem detected: WordPress/openverse#563
* 3d model support proposal: WordPress/openverse#558
* WordPress/openverse#561 

### Mobile
https://user-images.githubusercontent.com/895819/172160157-e260adfb-9c50-4d92-aee5-757fff81b26f.mp4

### Desktop
https://user-images.githubusercontent.com/895819/172160850-0b90336b-a6d8-4502-9c29-d3814126c3cd.mp4

## Description
On mobile, the layout displays images on a single column grid where each image has its cc-license icons below. The image component has three states: resting, hover, and focus. The video attached above shows the first and third ones, and the style changes are the focus ring and a color shift in the icons area from `dark-charcoal-70` to `dark-charcoal`.

Since WordPress/openverse#558 proposal suggests new hover styles, the image component inherits the cc-icons area change. On the other hand and time ago, I had the idea of reviewing the row height of the current grid as it looks good on big screens but tight on laptop sizes. See the image below of the current layout.

<img width="1440" alt="CleanShot 2022-06-06 at 13 11 17@2x" src="https://user-images.githubusercontent.com/895819/172160555-19175787-a567-469a-9495-40aefea2d492.png">

I was playing with different heights, and I like how `200px` for the row height looks like. It will show three full rows, acknowledging its relativity due to device sizes, and considering that the WordPress header will be removed, the page will look clean and highlights more the content results.

See the image below and please share your thoughts.

<img width="1440" alt="Image results (Macbook pro 13)" src="https://user-images.githubusercontent.com/895819/172160688-79bb9c56-927a-4adb-a227-e7b4b0191068.png">

## Design file
Figma: [Image results grid improvement](https://www.figma.com/file/bfe7wowCpMxsle7vHBAVMe/Image-results-grid-improvement?node-id=0%3A1)

**Comment by zackkrida** [comment]
We've updated this issue to high priority and added it to our todo column. @fcoveram will review and prepare the assets to make sure it is ready for work.

**Comment by fcoveram** [comment]
The design file needs to be revisited to pull in Design Library's last changes. Once done, I will come back to notify it's ready to its implementation.

**Comment by fcoveram** [comment]
# New design

Since this ticket was created from no longer existing needs, the new design attached below has new components and layouts up to this comment is published.

This design still address #563, but I closed #561 as it was fixed and #558 is no longer in Openverse priorities. For the first, [Image](https://www.figma.com/file/GIIQ4sDbaToCfFQyKMvzr8/Openverse-Design-Library?type=design&node-id=4050-9023&mode=design&t=044xRYHIlqFd3AyC-4) and [Box image](https://www.figma.com/file/GIIQ4sDbaToCfFQyKMvzr8/Openverse-Design-Library?type=design&node-id=4050-9025&mode=design&t=044xRYHIlqFd3AyC-4) components have new styles documented in the Design Library and pointed out as a [note](https://www.figma.com/file/bfe7wowCpMxsle7vHBAVMe/Image-results-grid-improvement?type=design&node-id=1013-22528&mode=design&t=CUqZpu6JZ0fHZyFo-4) in the design file for this issue.

## Image results layout

The All content results layout does not change, but in the image results layout, rows have `200px` for height; as the first design shared.

<img width="1343" alt="Image results in XL breakpoint showing three images in default, hover, and focus states" src="https://github.com/WordPress/openverse/assets/895819/37dfaf7f-7128-439d-b234-777366966d01">

The results grid should follow #1178 implementation and change its behavior based on its container instead of the device size. The improvement should make the experience smoother.

In `XS`, the layout keeps its single column grid, but in `SM` the current grid tends to show images in one column even when it changes to a row arrangamente. I would your thoughts about what row size is better for this breakpoint to display more results in the screen. The mockup named "SM" in Image results section is open to changes as per the definition we end up with.

For `MD` and beyond, the idea is to show the rows in `height: 200px` **every time it shifts to a new breakpoint.** So as the viewport increase from `MD` to `LG` and rows increase their height to fit the container area, once it reaches `LG` breakpoint, rows changes back to `height: 200px`.

I hope the explanation above conveys the behavior. Otherwise, we can schedule a call for a walkthrough. 

On the other hand, and similar to what we did the top maring of All content's grid, image results' grid also has `8xp` as top margin in `XS` to ensure a visible focus ring.

## Single result image

In the SRP page, the image grid in Related images section needs to follow this core update.

---

## Design mockups

**Figma file:** [Designs in dev mode](https://www.figma.com/file/bfe7wowCpMxsle7vHBAVMe/Image-results-grid-improvement?type=design&node-id=501-35753&mode=design)

Figma now allows you to preview components in a Playground view. Worth trying it.

https://github.com/WordPress/openverse/assets/895819/d24f78aa-c428-4dcd-8cf7-73a64527ba97
