### ISSUE TITLE
Related images showing bigger than the main image in the Details page

### ISSUE THREAD

**Issue by krysal** [WordPress/openverse#550]
## Description

This is happening with certain images only but I'm seeing it more and more often. Related images shouldn't take full width of the section as they're supposed to be displayed in a grid.

## Reproduction

1. Go to https://wordpress.org/openverse/image/579222e6-cf91-4d3c-bfb9-f7c28c9db7f6/
2. See related images are shown bigger and make several rows taking full width

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by obulat** [comment]
This issue might be solved when the solution to #547 is merged.

**Comment by obulat** [comment]
The issue was solved by #2891.
![Uploading Screenshot 2023-10-20 at 7.17.27 PM.png…]()
