### ISSUE TITLE
Use the image size information provided by the API instead of making head requests

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse#551]
**_Blocked by https://github.com/WordPress/openverse-catalog/issues/521_**
**_Blocked by https://github.com/WordPress/openverse-api/issues/711_**

## Problem

Currently, we are making a `head` request to the image source to get the image dimensions if they are not available in the API response. After the changes in the linked issues, we will get all the information from the API.

## Description

We will need to delete the code that makes a `head` request to the image provider to get the image dimensions 🎉

**Comment by krysal** [comment]
The frontend already uses the value from the API:

https://github.com/WordPress/openverse/blob/1cf6c6ad555a0afca4ed766fe7fa9480ceb38173/frontend/src/pages/image/_id/index.vue#L197

Closing.
