### ISSUE TITLE
Show 3d model content in the single result view

### ISSUE THREAD

**Issue by fcoveram** [WordPress/openverse#557]
## Problem

For the [3D model support milestone](https://github.com/WordPress/openverse-frontend/milestone/6), we need to show the information of a 3D model result in the single result view. This view considers a modal and page version.

## Considerations
Review the back to results action as modal implementation is still in progress
- WordPress/openverse-frontend#1266
- WordPress/openverse#565

## Solution
Here are two screen recordings with the whole flow from the search results page to the single result view, and the mockups related to the single results views.

#### Screen recording
https://user-images.githubusercontent.com/895819/169101493-7185bbeb-9f77-48d5-81e5-61d8ea895bde.mp4

#### Mockups
|Single result. Modal|Single result. Page|
|:---|:---|
|<img width="500" alt="Single result : Modal  3D model" src="https://user-images.githubusercontent.com/895819/169153183-58a92317-76f8-43c8-a9a6-81a4f2f93b12.png">|<img width="500" alt="Single result : Page  3D model" src="https://user-images.githubusercontent.com/895819/169153207-96ff0e67-a704-4544-8959-aff9bba00a44.png">|

#### Screen recording
https://user-images.githubusercontent.com/895819/169101916-9ffe5a59-152d-45a8-92aa-ceefd640835c.mp4

#### Mockups
<img width="150" alt="M  Single result : 3D model" src="https://user-images.githubusercontent.com/895819/169153436-49f4894d-74cd-45cc-b36a-c27baa4ef426.png">

## Figma file
Figma: [3D model support](https://www.figma.com/file/IFIqt7Q3MEKMLSnBedzHBO/)

## Description
On desktop, the modal view wraps the 3D model with the same spacings as the content details, the information below. Whereas on the page version, the content is `width: 1000px` and `height: 500px` as discussed before, and the `back to search` action is a row section placed above the main content that applies to all page views.

On mobile, the 3D model content is the same as the rectangular component displayed on the 3d model results, while all remaining content pieces below keep the current styles.

What do you think of the idea? There might be related comments on issue WordPress/openverse#558 as both tickets belong to the same search experience.

**Comment by sarayourfriend** [comment]
Closing as 3d models are indefinitely on hold and no work should be done on them until we re-plan this project.
