### ISSUE TITLE
Show 3d model results in the search result page

### ISSUE THREAD

**Issue by fcoveram** [WordPress/openverse#558]
## Problem
For the [3D model support milestone](https://github.com/WordPress/openverse-frontend/milestone/6), we need to display 3D model results on the search results page in two ways, as part of the All content layout and as a unique view.

## Considerations
Try reusing the **All content** layout for the standalone view showing only 3D model results.

## Solution
Here are two screen recordings with the whole flow from the search results page to the single result view, and the mockups related to the search results.

#### Screen recording
https://user-images.githubusercontent.com/895819/169101493-7185bbeb-9f77-48d5-81e5-61d8ea895bde.mp4

#### Mockups
|All content|All content + Switcher open|
|:---|:---|
|<img width="350" alt="Search results  All content" src="https://user-images.githubusercontent.com/895819/169101051-7b925e00-5667-4ad5-8824-0b8fe5f98920.png">|<img width="350" alt="Search results  Switcher open" src="https://user-images.githubusercontent.com/895819/169101059-3368dddf-1cd0-41b1-a210-730f7bf2834e.png">|

|Search results. 3D models|
|:---|
|<img width="350" alt="Search results  3D model" src="https://user-images.githubusercontent.com/895819/169105554-706e2aa4-3ec1-4ee4-bdf3-df5fd1cdb3e9.png">|

#### Screen recording
https://user-images.githubusercontent.com/895819/169101916-9ffe5a59-152d-45a8-92aa-ceefd640835c.mp4

#### Mockups
|All content|Content switcher|Search results. 3D models|
|:---|:---|:---|
|<img width="150" alt="M  Search results  All content" src="https://user-images.githubusercontent.com/895819/169105315-6532cfa0-9dd4-4047-84bd-2bc390b2aa70.png">|<img width="150" alt="M  Content switcher  3D model" src="https://user-images.githubusercontent.com/895819/169102602-33a1ed1d-cfe5-44e7-958f-af2ae28c75db.png">|<img width="150" alt="M  Search results  3D models" src="https://user-images.githubusercontent.com/895819/169105290-f4972dc7-8851-4fa8-9e11-dfb05c4d205f.png">|

## Mockup
Figma: [3D model support](https://www.figma.com/file/IFIqt7Q3MEKMLSnBedzHBO/)

## Description
On desktop, the 3D model component is the same box as the image one for both search results and 3d model results. Following the currently implemented behavior, the box also resizes as the filter sidebar appears.

On mobile, the element is the same image box as in all content results; but on 3d results-only, the element is wider like in the single result view and it has the license visible below. I am thinking of using the same single-column layout for image results after we discussed keeping the row layout on desktop. This should ease the arrangement of elements.

I am hesitant about showing the content links to see Images, Audio, or 3D models on both desktop and mobile. They fit perfectly on desktop, despite not working well with future content integrations, but also because the list pushes the content downwards significantly on mobile. What are your thoughts on this?

Looking forward to see your comments

**Comment by sarayourfriend** [comment]
Closing as 3d models are indefinitely on hold and no work should be done on them until we re-plan this project.

The information and plans from this thread _will_ absolutely be taken into account if/when we revisit 3d models.
