### ISSUE TITLE
Audio track seeking does not support infinite values

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse#559]
## Description

It appears that when either `frac` or `duration.value` is infinite, the `HTMLMediaElement` rejects it as a `currentTime` value:

https://github.com/WordPress/openverse-frontend/blob/d8f63c0444790208300f36dfd813d5517ca21c0d/src/components/VAudioTrack/VAudioTrack.vue#L340

## Reproduction

I was not able to reproduce this myself by scrolling past either end of the audio track while seeking.

## Additional context

https://sentry.io/share/issue/7bae5c3efcfb42c19f289f7be47dcaa5/

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by krysal** [comment]
We haven't seen this error in a while, so it should be resolved.
