### ISSUE TITLE
Make tags clickable - add a `search by tag` feature

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse#562]
## Problem

Currently, the tags for single media result are not clickable. It breaks users' expectations. 

## Description

The API provides the ability to search media by tags. We need to design for the `Search by tag` search page, and implement it.

## Alternatives

Leave the tags not interactive.

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by zackkrida** [comment]
I'm going to close this as it is included in the #410 project.
