### ISSUE TITLE
Search results do not display the image license without hovering

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse#563]
## Description

The search result page on "Images" and "All Content" views on mobile does not display license names, only their icons.
Here is a sample mockup of how the license names should be displayed: https://www.figma.com/file/w60dl1XPUvSaRncv1Utmnb/Audio-Release?node-id=1548%3A21328

## Reproduction

1. Search for images on mobile.
2. You can only see the license icons on hover. You should always be able to see license icons and license names below the images.

## Screenshots

<img width="342" alt="Screen Shot 2022-05-02 at 12 13 54 PM" src="https://user-images.githubusercontent.com/15233243/166211927-ad9557ed-a320-4609-acd8-c73e4dc514db.png">

## Environment

 - Device: mobile

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by sarayourfriend** [comment]
This will be fixed by https://github.com/WordPress/openverse/issues/547.
