### ISSUE TITLE
Enabling filters feels clumsy on mobile

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse#564]
## Description

The UX flow of enabling filters on mobile needs to improve. The action of _**Applying filters**_ needs to be more explicit.

First reported by @panchovm 

## Reproduction

1. Go to search results, open the filters, tap on some filters, close the menu. 
2. That UX flow doesn't feel solid as the "applying filters" action is not very explicit

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by zackkrida** [comment]
I think it's fair to say this is much-improved in the new mobile flow. Please re-open if anyone disagrees. 

![CleanShot 2023-02-22 at 10 15 42](https://user-images.githubusercontent.com/6351754/220665985-96a138c1-79e8-4fae-aa41-4674e3bb0e81.png)
