### ISSUE TITLE
Single image result page's top padding is too large without 'Back to search results' link 

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse#565]
## Description

On screen widths above `md` breakpoints, the single image result page has a large padding above the image even when there's no `Back to Search Results` link.
First reported by @AetherUnbound 

## Reproduction

1. Go to single image result page (server-rendered, i.e. go to the page directly, or refresh after you load it from search) on a screen that is at least `md` wide (768px). 
2. You will see a large gray padding at the top. The padding is 3rem (48px) whereas the mockup has 32 px padding: https://www.figma.com/file/w60dl1XPUvSaRncv1Utmnb/Audio-Release?node-id=1228%3A21558

## Screenshots

- Padding with "Back to Search Results" link (expected)
<img width="400" alt="Large padding with Back to search results link" src="https://user-images.githubusercontent.com/15233243/166192965-49cf0c01-a3bf-43c9-a103-de7491414eea.png">

- Padding is too large when no link is present
<img width="400" alt="Padding is too large when no link is present" src="https://user-images.githubusercontent.com/15233243/166192961-770c042b-2e51-4d99-bfc4-1b9261c41a95.png">

## Additional context

"Back to search results" link is only displayed when you navigate to this page from search results, and not on direct load, or when navigating from the related images.
The `z-index` is used for "Back to search results" because for 3d models the Sketchfab viewer is displayed a little differently, so it might make sense to test implementation with a Sketchfab model: https://search-staging.openverse.engineering/image/ee8c9894-0155-4a12-96d4-e099e1f02900

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by Saksham-garg** [comment]
@obulat, I want to contribute to this issue, Can I get started ?

**Comment by dhruvkb** [comment]
Since this issue needs design work and is not ready for dev work, I'm removing the "good first issue" label.

**Comment by fcoveram** [comment]
Closing this issue as it the implementation is done
