### ISSUE TITLE
Content report popover appears over the pages modal

### ISSUE THREAD

**Issue by krysal** [WordPress/openverse#569]
## Reproduction

1. Go to a result page on mobile and open the content report popover. 
2. Then open the pages modal by clicking the three dots button in the header. The content report popover will appear over the modal. It should close due to "click outside".

## Screenshots

![photo_2022-04-29 15 48 30](https://user-images.githubusercontent.com/9145885/166061020-36a5bc75-66b2-45af-90c5-dd853caaa7f7.jpeg)

## Environment

 - Device: Phone

## Additional context

Originally reported by @sarayourfriend. Possibly related to WordPress/openverse-frontend#1280. 

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by obulat** [comment]
We have specifically disabled closing the report form popover on click outside. Is it better to reverse this, or to update the `z-index` of either the content switcher modal or the report popover? We need the content switcher modal to be below the license explanation popover, so we can't make its z-index too high.

**Comment by zackkrida** [comment]
My opinion would be that we shift the z indexes around so the drawer is above the reporting form.

**Comment by obulat** [comment]
Currently, clicking outside the report popover has no effect at all. So, you cannot open a pages modal at all, if the report popover is open.
We need to update the report popover to be similar to the meta search modal on the mobile as in #460

**Comment by fcoveram** [comment]
This problem was addressed in #3582, so replacing the `design: needed` label with `design: ready`

**Comment by obulat** [comment]
Fixed by #4800
