### ISSUE TITLE
Back to top button stays in `active` state after it's been used once

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse#570]
## Description

The scroll to top button should be lighter pink (`resting` state) when you can scroll using it, even after you've used it once. Now, on mobile, once you pressed it, it always stays dark pink (`active`/`hover` state). The behavior is correct on desktop.

First reported by @sarayourfriend 

## Reproduction

1. Visit image results on mobile, scroll down a bit, then press the "back to top" button.
2. Scroll back down so that it re-appears and note that it is still in the "active/hovered" state (you can tell because it is a darker color)

## Screenshots

Notice the color of the button when it appears for the second time:

https://user-images.githubusercontent.com/15233243/165698356-5af00a6b-51bb-49a7-a6a5-9394f568e6c3.mp4

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by zackkrida** [comment]
Resolved.
