### ISSUE TITLE
Source filter is empty

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse#571]
## Description

In the filter pane for both images and audio, the "Source" filter section is empty. This can be confusing for entries where the "Creator" checkbox is below the source section, since it may look like "Creator" is a source.

## Reproduction

1. Visit https://search-staging.openverse.engineering/search/audio?q=many
1. Open the filters tab
1. Observer that there are no selections under `Source`

## Screenshots

![image](https://user-images.githubusercontent.com/10214785/165647288-e21a1a59-be39-4007-b032-f939d30ba25c.png)

## Environment

 - Device: Desktop
 - OS: Ubuntu
 - Browser: Firefox

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by fcoveram** [comment]
Closing this issue as currently Creator filter is not displayed
