### ISSUE TITLE
Homepage images are cut off by the informational footer when mobile keyboard is open

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse#574]
## Reproduction

1.  Open the homepage in a mobile browser like Firefox for Android and select the search input. See the screenshot below for example.

## Screenshots

![Screenshot_20220419-174959](https://user-images.githubusercontent.com/24264157/164165953-bc6ffd8c-59c6-48ce-a1f7-dfdf958a7857.png)

## Environment

 - Device:  Pixel 6
 - OS:  Android
 - Browser:  Firefox

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by obulat** [comment]
Closing this issue because the new homepage design does not contain images on mobile.
