### ISSUE TITLE
Mobile content switcher is missing information

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse#586]
## Description

The mobile content switcher doesn't show the beta status of audio, for example. It does not have design room to show `additional sources` either.

Mobile users should get the same context as desktop users.

This might require some design work from @panchovm; without any design suggestions, I would offer that we make the list a horizontally scrollable one and create a smaller label to indicate that audio is in beta, something like this:

<img width="425" alt="CleanShot 2022-03-28 at 14 22 16@2x" src="https://user-images.githubusercontent.com/6351754/160461951-8cb0f704-9e8b-480a-a943-9a56f312cca5.png">

**Comment by obulat** [comment]
This issue is not present anymore; the design of the mobile content switcher has changed.
