### ISSUE TITLE
Translate audio genres

### ISSUE THREAD

**Issue by krysal** [WordPress/openverse#589]
## Description

As categories, audio genres should be translated as well.

## Reproduction

Go to the details page of any audio in a non-English locale and observe genres are not translated, e.g. 
https://search-staging.openverse.engineering/es/audio/2a4de138-1015-4dd1-8826-9ce172e78651

## Screenshots

<img width="932" alt="CleanShot 2022-03-22 at 16 48 14@2x" src="https://user-images.githubusercontent.com/9145885/159573473-b1a67176-2333-43c6-9e91-b5edbab6732c.png">

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by sarayourfriend** [comment]
Closing as won't do. We don't have this capacity for any other provider-provided metadata (like tags). If we want to do this, it would take a big project to do so (due to needing to wrangle ongoing genre additions into a translation workflow that gets fed back into the frontend and somehow used.
