### ISSUE TITLE
[Feature] Aspect labels for i18n and a11y

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse#59]
Not required, but it might be nice to have dedicated aspect labels for internationalization and accessibility, to make it easy for contributors who value that type of work to find relevant issues.

**Comment by dhruvkb** [comment]
Since the i18n work happens in GlotPress, I don't think there will be PRs for that anymore. Also the [aspect: a11y] label would overlap heavily with the [aspect: interface] label.

**Comment by zackkrida** [comment]
Sure, I think it's fine to use the `a11y` label in the future for issues like "Switch to i18n method for hardcoded strings".
