### ISSUE TITLE
Landing pages for sources without a search query

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse#590]
## Problem

Previously, Openverse allowed users to go to a queryless search results page to view images from the different sources. An example url would be something like:

`https://wordpress.org/openverse/search/image/?source=rawpixel`

Notice the lack of the search (`q=dog&`) parameter.

## Description

Restoring this feature would be nice, but it would _also_ be nice to make it more robust. It could be a really nice way to showcase the sources with more detail. Some potential ideas:

- Add a header to the search results that shows the name, a textual description, and logo of the source, along with how many pieces of various media they have in each media type.
- Have an external link to the source
- Link to the source's content moderation policy and other relevant documents to Openverse.

This would require us to maintain more metadata for providers in the API.

## Alternatives

Do nothing, and simply merge WordPress/openverse-frontend#1008. 

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by obulat** [comment]
These pages will be implemented as part of [Additional search views for the frontend#410](https://github.com/WordPress/openverse/issues/410).
