### ISSUE TITLE
Move search type path part computation into searchStore

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse#597]
## Problem

We evaluate the current pattern in a few places to build the frontend search path: `searchType.value === ALL_MEDIA ? '' : searchType.value`.

## Description
We could just move this into the search store to prevent having to evaluate this in several different places.

Depends on the search store being merged in WordPress/openverse-frontend#1040

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by obulat** [comment]
This issue has already been solved.
