### ISSUE TITLE
Update of Switcher item component

### ISSUE THREAD

**Issue by fcoveram** [WordPress/openverse#600]
## Problem
The existing content switcher popover was designed with three content types in mind and did not consider a significant change in its height. However, we are adding a new section for additional types as new ways of looking at CC-licensed content, and new content types are upcoming. 

## Description
The `Switcher Item` component has the following changes:
1. Two variants were added: **3D models** and **Videos**.
2. In **Medium** size, paddings were reduced to be `12px` in all sides
3. In **Medium** size, background color changed for 3d models and video variants.
   - `dark-charcoal-6` in `Resting` and `Focus` states.
   - `dark-charcoal-20` in `Hover & Active` and `Active Focus` states.

### Medium size
<img width="1341" alt="CleanShot 2022-03-16 at 11 23 08@2x" src="https://user-images.githubusercontent.com/895819/158611883-64cc8183-3102-43c1-9b1a-23cfe9002403.png">

### Small size
<img width="1367" alt="CleanShot 2022-03-16 at 11 24 17@2x" src="https://user-images.githubusercontent.com/895819/158612112-961bf938-8375-438d-89fd-469d8e7c5df9.png">

Note: Background colors were not updated in **Small** size since mobile mockups have a separated area for the additional types.

## Additional context
[Switcher item](https://www.figma.com/file/GIIQ4sDbaToCfFQyKMvzr8/Openverse-Design-Library?node-id=558%3A2283) in Figma.

This change impacts the ongoing work:
* Updating the content switcher popover by adding additional types options. WordPress/openverse-frontend#739
* Requirement of adding the 3d model icon. WordPress/openverse-frontend#1122

**Comment by obulat** [comment]
@fcoveram, do we still need to update the Switcher component?

**Comment by fcoveram** [comment]
I completely forgot this ticket. I need to revisit this proposal with all the design library changes that occurred after. I will back with an answer ASAP.

**Comment by fcoveram** [comment]
This ticket is no longer necessary. Closing this ticket.
