### ISSUE TITLE
Page title briefly becomes `undefined | Openverse` when navigating between related results

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse#603]
## Description

The page title will briefly read `undefined | ...` when navigating between related results

## Reproduction

1.  Go to https://search.openverse.engineering/audio/38118e81-8e92-4335-ade6-1c59d2f6fd45
2.  Click a related result and keep an eye on the page title
3.  Note that it reads `undefined | ...` before switching to use the actual title of the newly selected result

## Expectation

The page title should never read "undefined"

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by zackkrida** [comment]
This is resolved.


https://user-images.githubusercontent.com/6351754/221874514-6d217563-e6f1-4e27-8fb5-dc5ece743a01.mp4
