### ISSUE TITLE
Use URLSearchParams to parse query params instead of using regexes

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse#605]
## Problem

We currently parse URL search params by hand using a regex in this module: https://github.com/WordPress/openverse-frontend/blob/aa2af2086e01407f5a3a9a36b05c9af6172ecda8/src/utils/get-parameter-by-name.js#L1

We should use the built in `URLSearchParams` which has support for this already: https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams/URLSearchParams

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by obulat** [comment]
We are now relying on the Vue router's parsing of the query params, so this issue is no longer present.
