### ISSUE TITLE
Add explicit image width and height properties to the VImageCell components

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse#606]
## Problem

Adding explicit height and width properties to `<img>` tags is now used to prevent layout shift in browsers. Images set to 100% width and auto height, for example, can not be sized by the browser until the image is loaded. 'Auto' actually uses the dimensions of the image to calculate itself. 

## Description

We should add these properties to our image cell components and images on the single result view.

Ideally, we would base these dimensions off of the _actual_ width and height as provided by the API, but we do not have that functionality in the API yet. This is blocked until we have this functionality.

Until we can fully do this, we can use values that roughly match the displayed size of images, like 200x200 for the square image cell. We could also use this opportunity to give images a light grey background, so that they look better while they are loading. 

## Implementation

- [x] 🙋 I would be interested in implementing this feature.

**Comment by dhruvkb** [comment]
This has been implemented now.

https://github.com/WordPress/openverse/blob/7d0fc83f4b844a358daa3f14efc65bff642362c1/frontend/src/pages/image/%5Bid%5D/index.vue#L261-L262

Due to project restructuring, I could not determine the exact commit/PR where it was implemented.
