### ISSUE TITLE
Translation strings partials should be linked with the whole sentence.

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse#617]
## Problem

Currently, we are using the Vue-i18n's json file format for our strings that need to be translated. To use an HTML element within a string, we split a string into 2 values.

For example, the disclaimer from the homepage contains a link within it. Below you can see the HTML result and the JSON values that are used for it:
`<p>All Openverse content is under a <a href="{CCLicensesLink}">Creative Commons license</a> or is in the public domain.
```
"disclaimer": {
  "content": "All Openverse content is under a {license} or is in the public domain.",
  "license": "Creative Commons license"
},
```
In the PolyGlot interface, the translators see the two parts of this sentence as separate strings, and it is not possible to understand that they are part of the same sentence. This can be fine for languages that don't change the word forms based on their sentence role (as English). But for Russian, for example, translating the `license` key value cannot be done correctly without knowing the sentence it is used in. Here you can see the two strings in the translation interface: 
<img width="922" alt="Screen Shot 2022-02-16 at 4 58 01 PM" src="https://user-images.githubusercontent.com/15233243/154412286-ce49d8b8-3e13-460c-b0e5-71f90877715c.png">

## Description

We should investigate the best way of linking the strings that are part of a sentence in the Vue JSON format.

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by lidialab** [comment]
I totally agree with @obulat.
These difficulties are there also for the Italian locale.
