### ISSUE TITLE
Update e2e tests to not rely on specific text copy, instead use translation tokens

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse#619]
## Problem

Take this test as an example:

https://github.com/WordPress/openverse-frontend/blob/26af972f90f3f9b8081131d8c61a2aefb8329991/test/e2e/search.spec.js#L29

If we try to run it in another language that is translated, it will fail. But we shouldn't have to write unique tests for every language we'd like to test. Likewise, if the copy is changed then the test will fail. This is even worse for languages outside of the token language of English because the copy is controlled externally and can change at any time, thus causing the e2e tests to fail if we write them against another language (which we should, for example, write them for RTL languages and other non-latin alphabet languages).

## Description

Create some method for the e2e tests to only rely on static tokens for the selectors rather than actual page copy that can change arbitrarily (when compared to the behavior, which should stay the same unless intentionally changed and should not change due to a simple copy update).

Using the translation token might be way around this but I'm not sure how that would work for RTL languages or testing non-latin alphabet languages.

## Alternatives

Use `data-test-id` style selectors instead of copy or tokens. Maybe that's better when there aren't any other accessibility based selectors to use.

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by sarayourfriend** [comment]
I'm combing through older issues, and wanted to see if this was still needed. A lot of the places we select by text in the e2e tests use regexs instead of strings, which took me a while to realise.

There are a lot of examples like this:

https://github.com/WordPress/openverse/blob/1f6be8289d095570fb859ada435e6711f4ca7151/frontend/test/playwright/e2e/all-results-analytics.spec.ts#L105

We can replace these with the `t` utility from `test/playwright/utils/i18n`.

**Comment by sarayourfriend** [comment]
@obulat is this issue still needed? I wasn't sure 🤔

**Comment by obulat** [comment]
I was planning to audit the tests and either create a PR or close it. Hope to get this done in the next 2 weeks
