### ISSUE TITLE
Image results are stretched vertically on mobile safari

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse#622]
## Description

Images on the single results page are stretched vertically on mobile safari

## Reproduction

1. Go to an image result page for an image that is wider than it is tall on mobile safari on `main`
2. The image is stretched vertically.

## Expectation

The image should have the correct proportions retained.

## Screenshots

![IMG_1556](https://user-images.githubusercontent.com/24264157/152859021-531c615a-52b9-43ad-80d2-55f64b197781.PNG)

## Environment

 - Device: iPhone 12 Pro Max
 - OS: iOS 15
 - Browser: Safari

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by zackkrida** [comment]
Resolved
