### ISSUE TITLE
Load more button styles

### ISSUE THREAD

**Issue by fcoveram** [WordPress/openverse#628]
## Description
The **Load more** component does not have the [Figma component](https://www.figma.com/file/GIIQ4sDbaToCfFQyKMvzr8/Openverse-Design-Library?node-id=1684%3A3684) styles for `hover`, `focus`.

`hover` should have a different background color.

<img width="1097" alt="CleanShot 2022-01-27 at 11 48 55@2x" src="https://user-images.githubusercontent.com/895819/151382453-f58d2cce-70ad-4e68-a040-a393bfe2cbef.png">

`focus` should not have the internal white border. 

<img width="1104" alt="CleanShot 2022-01-27 at 11 49 08@2x" src="https://user-images.githubusercontent.com/895819/151382482-293686dc-8a18-4cd6-b75e-66fddacbe5b1.png">

**Comment by zackkrida** [comment]
This can also be closed. This button was updated as part of #415
