### ISSUE TITLE
Replace external artist links with links to the relevant creator search on Openverse

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse#630]
## Problem

Rather than link to the external resource for the creator, which may or may not give the user quick access to the artist/creator's content, let's replace the links and mentions of creator names everywhere with links to the relevant Openverse search.

## Description

According to @zackkrida we can use the following format to build the search link:

```
/search/audio?searchBy=creator&q=<creator name>&source=<creator source>
```

We need to include the source because there could be two separate creators by the same name on different sources and they should be distinguished (we don't want to misattribute).
 
We could also explore making the source clearer on the artist name to help disambiguate multiple sources coming back with the same creator name representing separate people.

We could also continue to include the external link to the creator's page on the source when it exists as a separate link (?).

This probably needs some extra thought from @panchovm on the UX side to make sure we're delivering the correct information and not making things more confusing.

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by sarayourfriend** [comment]
We could, yup! If you do, please add it to the project thread. We handled an existing issue similarly for the #377 project (specifically https://github.com/WordPress/openverse/issues/750).

**Comment by obulat** [comment]
I added this issue to the Prior Art section in Project thread #410. Closing this as won't do.
