### ISSUE TITLE
Add the Safe browsing filter

### ISSUE THREAD

**Issue by fcoveram** [WordPress/openverse#636]
## Problem
We need to add a filter for showing/hiding mature content in the search results. We discussed time ago to not include the filter in the filter sidebar as it is a sensitive criterion.

## Alternatives
The proposal shows a Safe browsing link that opens a popover showing a description and a toggle filter. The interaction goes as it follows:

1. On hover, the **Safe browsing** turns `dark-charcoal`.
2. On click, it opens a popover with a description and a toggle.
3. When enabling the toggle, the results load again without closing the popover.
4. Clicking outside closes the popover.

https://user-images.githubusercontent.com/895819/146781237-8cad38bd-124c-4962-9520-bd9f8b757b6e.mp4

## Additional context
The popover design has a **shadow popover** style from the [WordPress Design Library](https://www.figma.com/file/e4tLacmlPuZV47l7901FEs/WordPress-Design-Library).

**Comment by zackkrida** [comment]
Closing, this was redesigned and refined as part of #791
