### ISSUE TITLE
Implement Lighthouse CI (original #1130)

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse#646]
This issue has been migrated from the [CC Search Frontend repository](https://github.com/creativecommons/cccatalog-frontend/issues/1130)

```
Author: zackkrida
Date: Mon Aug 10 2020
Labels: ✨ goal: improvement,🏷 status: label work required,💻 aspect: code,🔒 staff only,🙅 status: discontinued,🤖 aspect: dx
```
We will implement [Lighthouse CI](https://github.com/GoogleChrome/lighthouse-ci) to get some CI on front-end performance and a11y.

## Implementation

- [ ] I would be interested in implementing this feature.

--------
### Original Comments: 

Issue author *neeraj-2* commented on Thu Sep 03 2020:

>Can ,i work on this?But ,please guide me what exactly we need to do?

[source](https://github.com/creativecommons/cccatalog-frontend/issues/1130#issuecomment-686620180)

*zackkrida* commented on Tue Sep 08 2020:

>Hi @neeraj-2, this actually needs to be done by CC staff, since there's some edits to the repo configuration needed. 
[source](https://github.com/creativecommons/cccatalog-frontend/issues/1130#issuecomment-688975054)

**Comment by sarayourfriend** [comment]
Given the WP Accessibility week coming up, I'm going to put this one in the background for my infrastructure work, as it will provide a11y advice for each change to the frontend. I think getting the baseline set up with reporting on individual PRs will be pretty simple, and we can work on refining our "assertions" and such later.
