### ISSUE TITLE
Thumbnail request will infrequently raise `SSLError`

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse#652]
## Sentry link

https://openverse.sentry.io/share/issue/a6cdaf8cea524f84a9c83403c5eaf5a5/

## Description

```
HTTPSConnectionPool(host='i0.wp.com', port=443): Max retries exceeded with url: /live.staticflickr.com/214/495853548_1b74b5493d_b.jpg?w=600&quality=80&ssl=true (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:2396)')))
```

From what I gather, this appears to be an intermittent issue that occurs when performing a large number of requests against a server in Python. Here's an [SO answer](https://stackoverflow.com/a/46387660/3277713) and [GitHub issue](https://github.com/psf/requests/issues/3391) which corroborates that hypothesis. We've also seen this in the catalog with https://github.com/WordPress/openverse-catalog/pull/330.

The two links above suggest wrapping the `.get` in a `requests.Session` set up with retries. We could potentially add **one** retry for the thumbnail retrieval, although this would extend the total timeout (potentially) to 20 seconds for both requests.

## Reproduction

As this is an intermittent issue based on multiple client/server interactions, I was unable to reproduce it.

**Comment by krysal** [comment]
This issue hasn't appeared since February 14, so it might be resolved; therefore I will close it.
