### ISSUE TITLE
SystemExit

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse#658]
## Sentry link

https://sentry.io/share/issue/877df096da704c489499fec10762d95b/
https://sentry.io/share/issue/061ba99fc3df4c23bdb7643d337bbda0/
https://sentry.io/share/issue/b02d92b6b1f64b7987a1d817ab298ce9/

The second is associated with an already resolved issue but has come back.

## Description

The errors started back in [this Sentry issue](https://sentry.io/share/issue/061ba99fc3df4c23bdb7643d337bbda0/) a couple days after the latest API deployment, which was this version: https://github.com/WordPress/openverse-api/releases/tag/v2.7.2

However, note that 2.7.1 was skipped for deployment so it also includes these changes: https://github.com/WordPress/openverse-api/releases/tag/v2.7.1

The errors start a few days after this was deployed, however, so I'm not sure whether they're actually related. If they are, it might be a dependency change as the errors are being thrown in randomish places in the search_controller, but not any specific area related to the code changes we made in those releases.

To confirm, neither CPU nor traffic to the production API have changed. We do not currently have visibility into memory usage on the EC2 boxes (I may try to rectify this in the coming couple of weeks).

If the issue is related to the changes linked above, we could try a revert. This would be slightly more complicated and require a revert back to serving thumbnails via our local thumbnail service rather than Photon. This requires a change to the infrastructure repository (a selective revert of the changes to remove the thumbnail service).

Setting as critical because there are a lot of 500s for this.

**Comment by AetherUnbound** [comment]
We care continuing to see these SystemExit errors. Sentry suspects they are the result of https://github.com/WordPress/openverse/commit/d78abb98cb7be564c644c6601dbe6335fa8f1e51, but the transactions show that the issue is not exclusive to the thumbnails endpoint:

![image](https://github.com/WordPress/openverse/assets/10214785/39049e7e-5b5c-4da9-a35e-94031030a39a)

In the most recent alert, this has happened 540+ times since May 18th, 2023.

**Comment by sarayourfriend** [comment]
We're working on https://github.com/WordPress/openverse-infrastructure/pull/545 to help debug whether this is a thumbnails issue.

**Comment by sarayourfriend** [comment]
We confirmed this is a thumbnails issue and are working on the Django ASGI milestone with #2843 project thread to track this work.

@AetherUnbound Do you think we can close this issue now that the investigation is over?

**Comment by AetherUnbound** [comment]
Great call @sarayourfriend, I believe so!
