### ISSUE TITLE
Upgrade catalog to Python 3.11

### ISSUE THREAD

**Issue by dhruvkb** [WordPress/openverse#663]
## Problem
We should upgrade the Python version used in the project to Python 3.11.

## Description
Python 3.11 has some nice [new features and improvements](https://docs.python.org/3/whatsnew/3.11.html) so upgrading makes sense. It's also 10-60% faster (although our mileage may vary).

Changes will be needed in the following areas:
- GitHub actions: `actions/setup-python`
- `Dockerfile`
- `Pipfile`
- `Pipfile.lock`

## Alternatives

We could continue to remain on Python 3.10 till it reaches EOL, although that's not a real alternative.

**Comment by AetherUnbound** [comment]
Marking this as blocked - #1852 took care of all services but the catalog, which is blocked by Airflow. Once Airflow supports Python 3.11, we can tackle this and close it.

**Comment by dhruvkb** [comment]
Airflow supports Python 3.11 since [v2.6.2, released 2023-06-17](https://airflow.apache.org/docs/apache-airflow/2.7.0/release_notes.html#airflow-2-6-2-2023-06-17). Since we're on a newer version already, we can consider this unblocked!

https://github.com/WordPress/openverse/blob/5678bdcd64357bce1f5f390239d7a5dda97c34d3/catalog/requirements_prod.txt#L5

**Comment by AetherUnbound** [comment]
This has already been completed! (We're now on 3.12 😄)

https://github.com/WordPress/openverse/blob/50fe56e1a94659d91c1959f9d5d156cc7851d4e2/catalog/requirements-prod.txt#L1
