### ISSUE TITLE
Allow entire dataset to be downloaded en-masse

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse#669]
## Description

Presently if users want our entire dataset, they must crawl through all possible searches in hopes of pulling up the results we have. We've discussed this in the past, but it would be ideal to have a bulk download option available for those who would like to use the entire dataset (e.g. iNaturalist's dataset: https://github.com/inaturalist/inaturalist-open-data)

This could be parquet or TSV files on S3 which have public accessibility, or some other means of pulling the entire dataset.

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by Skylion007** [comment]
Interested in discussing this, even for a one time export.

**Comment by zackkrida** [comment]
Closing this in favor of tracking via this project: https://github.com/WordPress/openverse/issues/2545
