### ISSUE TITLE
`ReadTimeout` raised from general exception catching

### ISSUE THREAD

**Issue by krysal** [WordPress/openverse#672]
## Sentry link

https://sentry.io/share/issue/89863f561e9146fba39bb084e6310a68/

## Description

This produces most of the events we are receiving from errors on the API, with 3.2k observations in the last 14 days at the moment of writing.

Origin in source code:
https://github.com/WordPress/openverse-api/blob/9f8b15773df511b0900e2a0adf7785382abee450/api/catalog/api/views/media_views.py#L206

## Reproduction

visit https://api.openverse.engineering/v1/images/b312f615-6c9e-46e4-8738-d97e7836a8e1/thumb/

**Comment by krysal** [comment]
Rising this to high priority because this has been the main source of events in Sentry.

**Comment by sarayourfriend** [comment]
@krysal If it is okay with you, I'm going to close this issue in favour of https://github.com/WordPress/openverse/issues/1231 which has details more relevant to the current situation. The solution is probably still what @dhruvkb suggested, however, to just increase the timeout.
