### ISSUE TITLE
Release drafting improvements

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse#68]
- [ ] Switch from `🤖 aspect: dx` to `🧰 goal: internal improvement` for the "Internal Improvement" section of our changelogs.
- [ ] Find a way to  for the release drafter config to be migrated to this repo and then synced downstream so that it's consistently across all repositories.
	- Current release drafter files:
	  - [Frontend](https://github.com/WordPress/openverse-frontend/blob/main/.github/release-drafter.yml)
      - [API](https://github.com/WordPress/openverse-catalog/blob/main/.github/release-drafter.yml)
      - [Catalog](https://github.com/WordPress/openverse-catalog/blob/main/.github/release-drafter.yml)

**Comment by dhruvkb** [comment]
There has to be a way for the release drafter config to be migrated to this repo and then synced downstream so that it's consistently across all of them. Maybe that can be accomplished when solving this issue?

**Comment by dhruvkb** [comment]
**Update:** GItHub is working on an [autogenerated release notes feature](https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes).
