### ISSUE TITLE
Add setup instructions for contributors

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse#690]
## Description

It would be useful to have some setup documentation for the API. In the catalog, we have a section for this in the README: https://github.com/WordPress/openverse-catalog#development-setup-for-airflow-and-api-puller-scripts

We don't have a similar section for the API, and that can make it unclear for contributors that they need some initial setup steps/additional software.

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by dhruvkb** [comment]
As of 13a4a2b, the [`CONTRIBUTING.md` file](https://github.com/WordPress/openverse/blob/13a4a2be924e8bf2bb50614558fd57f4a98eba8c/CONTRIBUTING.md) contains references to the [General setup guide](https://wordpress.github.io/openverse/guides/general_setup.html) and the [Quickstart guide](https://wordpress.github.io/openverse/guides/quickstart.html).

This is pretty comparable to the catalog's setup and startup documentation.
