### ISSUE TITLE
Update or remove ingestion server ES mapping from README

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse#691]
## Description

> Ingestion server Readme has a very old ES mapping schema

Originally reported by @obulat

We could potentially generate this mapping dynamically, or at least point to where it is defined in the code rather than copying the text into the markdown file.

~~Link: https://github.com/WordPress/openverse-api/blob/b114de9d4bf6ac581c0075fa65877686e5def2ff/ingestion_server/README.md#mapping-database-tables-to-elasticsearch~~

Updated link: https://github.com/WordPress/openverse/blob/c0ef50c4fd26776c64ae1dc9f3aa30b63331c49a/ingestion_server/README.md#mapping-database-tables-to-elasticsearch

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by sarayourfriend** [comment]
We changed how this is documented in c94dee4a7bf6d0ffa2d1b87775df584376876fab. Specifically, we've removed the duplication of the documentation and the code.
