### ISSUE TITLE
API Docs Guides root page is empty

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse#693]
## Description

https://wordpress.github.io/openverse-api/guides/index.html

Reported by @krysal

> We should at least write what the user can expect in the guides.

One quick solution would be to remove the `:hidden:` directive in the `toctree` in guides/index.md, so that at least the TOC for the guides shows.

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by dhruvkb** [comment]
The monorepo docs at https://wordpress.github.io/openverse/guides/index.html, updated in #443, have a populated guides page. This was done in PR
