### ISSUE TITLE
The mature filter is not working

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse#694]
## Description

Search for something setting the mature filter to true, e.g.: https://api-dev.openverse.engineering/v1/images/?q=car&mature=true
This returns items that have `mature=false` in them.

## Additional context

The check for `mature` parameter being a boolean works correctly. When I use `mature` as the value for `mature` query parameter, it returns an error:
```
GET /v1/images/?q=car&mature=mature

HTTP 400 Bad Request
Allow: GET, HEAD, OPTIONS
Content-Type: application/json
Vary: Accept
{
    "detail": {
        "mature": [
            "Must be a valid boolean."
        ]
    }
}


```

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by sarayourfriend** [comment]
Closing as won't do. `mature` is deprecated, and the `include_sensitive_results` has a much clearer name here (specifically, that it _includes_ sensitive results, rather than only searches sensitive results).
