### ISSUE TITLE
Add 3D models to `qa.py` for ingestion server

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse#710]
## Description

I'm not totally clear on what [`qa.py`](https://github.com/WordPress/openverse-api/blob/main/ingestion_server/ingestion_server/qa.py) is supposed to do yet, but we have references to both audio and image media types there. We should make sure that we add 3D models if it's necessary and desired. 

## Additional context

It may be that we don't actually need to do this for 3D models - I'm not sure!

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by krysal** [comment]
QA indexes were removed on #2322.
