### ISSUE TITLE
Add any 3D-model specific logic to `queries.py` and `tasks.py`

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse#713]
## Description

It is possible that the 3D model data refresh may require some specific extra steps in [`queries.py`](https://github.com/WordPress/openverse-api/blob/main/ingestion_server/ingestion_server/queries.py) and [`tasks.py`](https://github.com/WordPress/openverse-api/blob/main/ingestion_server/ingestion_server/tasks.py). 

Example from audio:

https://github.com/WordPress/openverse-api/blob/dbb1abf3faee7cffa1d123de76da251721bcaeed/ingestion_server/ingestion_server/tasks.py#L132-L133

This ticket may not need any work, depending on how straightforward the data refresh steps are for 3D models.

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by sarayourfriend** [comment]
Closing as 3d models are indefinitely on hold and no work should be done on them until we re-plan this project.
