### ISSUE TITLE
Add 3D model Elasticsearch model

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse#714]
## Description

We will need to add a 3D model model (model<sup>2</sup>?) to our list of Elasticsearch syncable models in `elasticsearch_models.py`. This commit may prove as a useful reference: https://github.com/WordPress/openverse-api/commit/cf21b73b4cb7609aea74f6a6e0080695aa2fd8d2

The ES models represent the fields that we will want to search against. This may not be all of the fields available for the media type, we'll need to check against images & audio to see what feels we should include/exclude.

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by sarayourfriend** [comment]
Closing as 3d models are indefinitely on hold and no work should be done on them until we re-plan this project.
