### ISSUE TITLE
Task thread for 3D models in data refresh & Elasticsearch

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse#717]
Corollary to WordPress/openverse#719

The following changes need to be made to the ingestion server in order to support 3D models in the data refresh and Elasticsearch.

- https://github.com/WordPress/openverse/issues/711
- https://github.com/WordPress/openverse/issues/714
- https://github.com/WordPress/openverse/issues/713
- https://github.com/WordPress/openverse/issues/712
- https://github.com/WordPress/openverse/issues/710

**Comment by sarayourfriend** [comment]
Closing as 3d models are indefinitely on hold and no work should be done on them until we re-plan this project.
