### ISSUE TITLE
Task thread for 3D models in API

### ISSUE THREAD

**Issue by dhruvkb** [WordPress/openverse#719]
The following changes need to be made on the API side to add 3D models as a category. During the addition of audio, a lot of the code was refactored to make adding more media types easier so this should be fast. 

- [ ] Create the Django models
  - [ ] Model3d
- [ ] DRF Serializers
  - [ ] Search request
  - [ ] Search result
  - [ ] Report serializer
  - [ ] ? Serializers for 3d-model specific views (like audio has waveform)
- [ ] DRF Viewset
  - list
  - stats
  - retrieve
  - related
  - thumbnail
  - report
  - ? 3d-model specific URLs (like audio has waveform)
- [ ] Request/response examples
  - 1:1 correspondence with viewset endpoints
- [ ] Swagger docs
- [ ] URLs

**Comment by sarayourfriend** [comment]
Closing as 3d models are indefinitely on hold and no work should be done on them until we re-plan this project.
