### ISSUE TITLE
[Feature] Setup bot to automerge Dependabot PRs after approval

### ISSUE THREAD

**Issue by dhruvkb** [WordPress/openverse#72]
## Problem

Dependabot PRs should automatically be merged when both:
- all checks pass
- they have the required number of approvals

## Description

This can be set up as a workflow in `.github/workflows` that is synced to all sub-repositories.

An open-source bot named [Kodiak](https://github.com/chdsbd/kodiak) can be setup for this purpose. It's very versatile.

## Alternatives

The second person to approve Dependabot PRs should merge them as well. It's just a choice between cultivating a habit vs. letting a bot handle it.

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by MustkimKhatik** [comment]
hey @saurabhan, you are working on this issue?

**Comment by sarayourfriend** [comment]
Completed as part of #3312 here:

https://github.com/WordPress/openverse/blob/19f5c5b41f1c294f349193b3b000642931b7c3b4/.github/renovate.json#L11-L12
