### ISSUE TITLE
Sequence deleted by ingestion server

### ISSUE THREAD

**Issue by dhruvkb** [WordPress/openverse#720]
## Description

The ingestion server destroys the auto-incrementing sequence of the `id` key during the ingestion making it impossible to add objects from the Django admin.

## Reproduction

- To see the database before ingestion, stop the `load_sample_data.sh` script at line 46 using `exit` and run `just init`. 
- To see the database after ingestion, remove the `exit`, comment out lines 9 to 45 and run `just init`.

## Screenshots

Before ingestion:

```
openledger=# \d audio
                                                Table "public.audio"
            Column            |           Type           | Collation | Nullable |              Default              
------------------------------+--------------------------+-----------+----------+-----------------------------------
 id                           | integer                  |           | not null | nextval('audio_id_seq'::regclass)
```

After ingestion:
```
openledger=# \d audio
                                   Table "public.audio"
            Column            |           Type           | Collation | Nullable | Default 
------------------------------+--------------------------+-----------+----------+---------
 id                           | integer                  |           | not null | 
```

## Additional context

There is code for setting up a temporary sequence for the `id` column but the sequence does not exist on the final table.

https://github.com/WordPress/openverse-api/blob/1ed4146889fd8c455d00e8bc01417f9e62885a40/ingestion_server/ingestion_server/queries.py#L111

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by sarayourfriend** [comment]
I think this is okay and I'm going to close as won't do. A workaround to this is to use the factories, which already handle this issue themselves: https://github.com/WordPress/openverse/blob/21f09eb78e6190b21d4e9359910622ac53254fc0/api/test/factory/models/media.py#L99-L108

Usage:

```
# from `just api/ipython`
> from test.factory.models.image import ImageFactory
> a = ImageFactory.create()
> a.id
5003
```

```
# from `just api/dbshell`
openledger=# select id from image order by id desc limit 1;
  id  
------
 5003
(1 row)
```
