### ISSUE TITLE
[Feature] Configure ESLint and Prettier for JS scripts

### ISSUE THREAD

**Issue by dhruvkb** [WordPress/openverse#73]
## Problem

The JS scripts in the repo, located in `js/` follow an arbitrary code style that's unrelated to the Openverse frontend repo.

## Description

These JS scripts don't have linters, formatters and Git hooks configured. This should be set up in order to match the code style used in `openverse-frontend`.

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by zackkrida** [comment]
Completed in #90
