### ISSUE TITLE
Incorrectly formatted OAuth requests cause uncaught errors

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse#734]
## Description

https://sentry.io/share/issue/48770754fc364b67ae219941798970cf/

If you send a malformed OAuth request it will raise a 500.

## Reproduction

1. Run the API
2. Send an OAuth POST with query params
3. Note the unhandled error

## Expectation

We should `expect` this error and respond with a normal Bad Request and not 500.

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by krysal** [comment]
I receive a correct "400 Bad request" response for a request like this:

```sh
curl --request POST \
  --url 'https://api-dev.openverse.engineering/v1/auth_tokens/token/?client_id=<valid_client_id>' 
```

**Response**
```js
{"error": "invalid_request", "error_description": "URL query parameters are not allowed"}
```

So it seems this is not an issue anymore. Please reopen if you have a specific case (maybe a combination of query params) when this fails.
