### ISSUE TITLE
Unify environment names

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse#737]
## Description

We have several different, inconsistent names we use for different environments (see WordPress/openverse-api#474 and WordPress/openverse-api#475). We should unify these across all services in the API repository, and ideally make them consistent with the environment names in [WordPress/openverse-frontend](https://github.com/WordPress/openverse-frontend). This may also require adjusting some settings in [WordPress/openverse-catalog](https://github.com/WordPress/openverse-catalog) and the infrastructure repo.

## Additional context

I think ideally we would have:

 - Any dev environment: `development`
 - Our pre-production environment: `staging`
 - Our production environment: `production`
 - Any environment where testing is being performed: `testing`

 That seems to coincide with the values we have for the frontend. 

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by dhruvkb** [comment]
Additional notes:

- The API notably uses `local` for the Docker dev environment, any other value prevents the CSS styles from loading.
- Our CI + CD workflow is also a potential environment to consider, some package managers have different locking behaviour when the `CI` env var is set.

**Comment by sarayourfriend** [comment]
> Any dev environment: development

`local` is used everywhere _but_ the catalog. This issue should not use `development` as it conflicts with a legacy name for our pre-production environment (where `dev` was used).

**Comment by sarayourfriend** [comment]
Updated the issue to be staff only and moved into todo. Now that the catalog is in `next`, we need to it to use the unified environment names, and move away from the legacy ones.

**Comment by sarayourfriend** [comment]
Just a note that I've updated the issue body to reflect usage of "local" for local development environment instead of "dev" to avoid conflation/confusion with the legacy staging environment name.
