### ISSUE TITLE
Silence insecure HTTPS warnings

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse#738]
## Description

We're getting lots of the following messages in the API logs:

```
/var/www/openverse_api/.venv/lib/python3.9/site-packages/urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 'live.staticflickr.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
```

We should probably just silence them, although there might be another way to rectify this that I'm not aware of!

## Reproduction

1. Run the API
2. Attempt to look at an image hosted on flickr
3. Observe the warning in the logs

## Additional context

https://urllib3.readthedocs.io/en/stable/advanced-usage.html#tls-warnings

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by krysal** [comment]
I can't reproduce this issue anymore either.
