### ISSUE TITLE
Notifications when receiving content reports

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse#739]
## Problem

The Openverse API accepts reports on images for mature content, copyright violations, and any other custom reason. We do not know when these reports have come in without some kind of alerting system.

## Description

Ideally we would have an aggregated weekly report, or instant Slack notifications whenever a report comes in. 

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by sarayourfriend** [comment]
Obviated by #383
