### ISSUE TITLE
[Feature] Configure pre-commit with Black, Flake8 and isort for Python scripts

### ISSUE THREAD

**Issue by dhruvkb** [WordPress/openverse#74]
## Problem

The Python scripts in the repo, located at `python/` follow an arbitrary code style that's unrelated to the Openverse catalog and API repos.

## Description

These Python scripts don't have linters, formatters and Git hooks configured. This should be set up to match the code style used in `openverse-catalog` and `openverse-api`.

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by krysal** [comment]
Done in #101.
