### ISSUE TITLE
Add Rawpixel to authority data as `CURATED`

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse#744]
Rawpixel is a curated source of CC0 images, the results seem particularly good. Regardless of result quality, they should likely be classified as a `CURATED` collection in the https://github.com/WordPress/openverse/blob/cf62650ca3528acc599ab755e1397a2adffe01a3/ingestion_server/ingestion_server/authority.py code.

## Description

Add `"rawpixel": AuthorityTypes.CURATED` to the `authority_types` dictionary:
https://github.com/WordPress/openverse/blob/04a36fcb320063aa8b42ea703c8059d7254d6990/ingestion_server/ingestion_server/authority.py#L42-L59

**Comment by obulat** [comment]
Fixed in #3668
