### ISSUE TITLE
[Feature] Automatically label PRs with the aspect and goal labels

### ISSUE THREAD

**Issue by dhruvkb** [WordPress/openverse#75]
## Problem

Automatically set the aspect and goal labels on PRs to be the same as their linked issues.

## Alternatives

We can also have a default "needs labels" label that is applied on PRs by default. That way we won't have to find linked issues and just set this label.

## Additional context

Since GitHub API does not offer a way to quickly find the issue linked to a PR, scraping the issue page is an [inelegant but functional solution](https://stackoverflow.com/a/60780499).

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by zackkrida** [comment]
I'm wondering if we could overload our label _check_, which we know runs every time a PR is created, to apply the correct labels and pass, when the following conditions are met:

- the PR does not have `goal` and `aspect` labels
- there _is_ a linked issue that has `goal` and `aspect` labels
