### ISSUE TITLE
[Feature] Use metadata keywords to help detect if something is NSFW (original #482)

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse#750]
This issue has been migrated from the [CC Search API repository](https://github.com/creativecommons/cccatalog-api/issues/482)

```
Author: aldenstpage
Date: Tue Apr 21 2020
Labels: 🏷 status: label work required,🙅 status: discontinued
```
## Problem Description
We are trying to make NSFW content in CC Search "opt-in". We can catch a lot of NSFW content by using API specific filters and relying on moderation "upstream" at the source, but sometimes things slip through.

## Solution Description
One way we can help prevent this is scanning for NSFW profanity and slurs in the title/tags/artist name and settings `nsfw = True` in the metadata field if it fails the check. There are [3rd party lists of dirty words](https://www.cs.cmu.edu/~biglou/resources/) that can help us achieve this. In my experience moderating content on CC Search, this will help prevent a lot of embarrassment and indignant emails from teachers.

We can do a one-time scan-and-filter relatively easily, but we will also need a way to filter new content as it is ingested.

## Additional Context
[The Scunthorpe Problem](https://en.wikipedia.org/wiki/Scunthorpe_problem)

--------
### Original Comments: 

***aldenstpage* commented on Tue Apr 21 2020:**

>Also: we're going to need to review the list of words carefully, because the lists that I linked to are too broad in what they consider NSFW and could have some unwanted inadvertent censorship effects.
[source](https://github.com/creativecommons/cccatalog-api/issues/482#issuecomment-617324185)

**Issue author *brenoferreira* commented on Tue Apr 21 2020:**

>One thing to watch out for in this word list is the potential for false positives that can end up filtering out a lot of content with words that aren't necessarily NSFW.
Edit: when I commented I had the tab open for a while so @aldenstpage comment hadn't loaded yet :D
[source](https://github.com/creativecommons/cccatalog-api/issues/482#issuecomment-617367517)

***kss682* commented on Wed Apr 22 2020:**

>For the new content we could have a validator method in ImageStore class that checks against title,author and relevant attributes before inserting into tsv , so that the NSFW contents  could be flaged and segregated at an early stage. @aldenstpage 
[source](https://github.com/creativecommons/cccatalog-api/issues/482#issuecomment-617562955)

**Comment by AetherUnbound** [comment]
@sarayourfriend should we close this issue in favor of some of the other plans/RFCs currently ongoing? Or will we just end up using this issue for that work?

**Comment by sarayourfriend** [comment]
The project thread references it: https://github.com/WordPress/openverse/issues/377

We could close this issue once the project thread is closed or close it now as a duplicate, I have no preference.

**Comment by AetherUnbound** [comment]
I'll go ahead and close the issue, it's linked for context as you mention anyway 🙂
