### ISSUE TITLE
Collect data on API usage

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse#754]
This issue has been migrated from the [CC Search API repository](https://github.com/creativecommons/cccatalog-api/issues/476)

```
Author: kgodey
Date: Fri Apr 10 2020
Labels: ✨ goal: improvement,🏷 status: label work required,🙅 status: discontinued
```
## Problem Description
We should collect data on how our API is being used. We should be able to create reports of non-CC Search API usage
- by API key
- from unauthenticated users (per user, anonymized)

## Solution Description
Append API keys (when available) to uwsgi logs.

**Comment by AetherUnbound** [comment]
Based on the solution criteria here:

> Append API keys (when available) to uwsgi logs.

I believe this was #3369 and can be closed!
