### ISSUE TITLE
Update "Week in Openverse" script to support monorepo

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse#760]
## Problem

The current week in openverse script splits PRs by repository:

https://github.com/WordPress/openverse/blob/main/automations/js/src/last_week_tonight.js

## Description

We'll need to update this to split the monorepo PRs by their stack.

## Alternatives

it should work as-is but will have empty sections for the frontend and api repos now.

**Comment by dhruvkb** [comment]
Since the JS script uses `data/github.yml` as the source for repo names, this was fixed in #763 by @AetherUnbound.

**Comment by krysal** [comment]
We haven't had a "[Week in Openverse](https://make.wordpress.org/openverse/tag/week-in-openverse/)" Make blog post since the [monorepo merge](https://make.wordpress.org/openverse/2023/02/22/openverse-is-now-a-monorepo/) so this is unsolved.
