### ISSUE TITLE
Define aliases for `just` recipes

### ISSUE THREAD

**Issue by dhruvkb** [WordPress/openverse#771]
## Problem

Some just recipes are run more often than others, like `install` or `lint`. Typing them repeatedly is not very fun.

## Description

We can use `just` [aliases](https://github.com/casey/just#aliases) to map them to shorter names like `i` and `l` so that running them requires fewer keystrokes. Combining this with the the global alias `j="just"` means that commands can be extremely short.

```console
$ j i # short for just install
$ j l # short for just lint
```

**Comment by AetherUnbound** [comment]
Fully support this!! Especially since we can more easily maintain consistency with the monorepo 😄 Maybe we could even leverage the newer `!include` directive on `just` too to reduce repetitive recipes in subdirectories 😮 https://github.com/casey/just#include-directives

**Comment by dhruvkb** [comment]
The short-recipe names listed in the original issue are taken: `l` is taken by `logs` and `i` is taken by `ingestion_server/up`. Open to alternative suggestions, what are your thoughts on `L` and `I`?

**Comment by AetherUnbound** [comment]
Had another thought here, what about `li` for `lint` and `ins` for `install`? If anything I think that the _more frequently used_ alias should be lower case, so we should probably have `just lint` as `j l` and `just logs` as `j L` if we go with upper case letters.

**Comment by dhruvkb** [comment]
Multi-character aliases don't seem like a very good idea to me, I'd rather use `just`'s completions (we should link to the [instructions for setting up completions](https://github.com/casey/just#shell-completion-scripts) in the [docs](https://docs.openverse.org/general/general_setup.html#just)) or bck-i-search. I agree with the more commonly used ones being lowercase.
