### ISSUE TITLE
Unify ESLint configuration between the JS automations and the frontend

### ISSUE THREAD

**Issue by dhruvkb** [WordPress/openverse#778]
## Problem

The JS automations are currently on a separate ESLint configuration that does not respect the top-level ESLint file (due to historical differences). 

https://github.com/WordPress/openverse/blob/840b56e7bf2b59c8c897d44bfc4baa7bed32b9c2/automations/js/.eslintrc.js#L2

Removing the `root` field here will raise a lot of ESLint errors, which is good because it brings that codebase in line with the rest of the JS in the repo.

## Description

The goal is to remove the `automations/js/.eslintrc.js` file and ensure that the code can pass the lint checks.

## Alternatives

We can continue to use a separate set of lint checks for both codebases, but that's not very cohesive.

**Comment by sarayourfriend** [comment]
Done in #2200, which unified the configuration. The only rule disabled for the automations JavaScript is the filename case rule: https://github.com/WordPress/openverse/blob/dfc96354fa5daf691296688ad54743b28cc7bf46/.eslintrc.js#L227-L236
