### ISSUE TITLE
`setSearchTerm` fails when `query.q` is an array

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse#781]
## Sentry link

https://openverse.sentry.io/share/issue/b026fd5844184021960d531dd32d23d4/

## Description

The code expects that there is only one `q` parameter. Some users add a second `q` parameter manually, and this causes a server error and a Nuxt gray screen.

## Reproduction

Go to https://openverse.org/search?q=email&q=

**Comment by zackkrida** [comment]
Fixed via https://github.com/WordPress/openverse/pull/806
