### ISSUE TITLE
[Feature] Make Openverse a browser's search engine

### ISSUE THREAD

**Issue by panchovm** [WordPress/openverse#79]
## Description
I am a Firefox user, and I use many different search engines through shortcuts on the search bar to reach content. This feature significantly improves the experience by using personal settings to browse the web. For me, it is another touchpoint to interact with Openverse, similar to the browser extension.

![browser search](https://user-images.githubusercontent.com/895819/134955879-d6cd0d52-d79a-4a0b-8322-3a55676131dd.gif)

## Additional context
I was looking for how to [add other searches](https://support.mozilla.org/en-US/kb/add-or-remove-search-engine-firefox#w_add-a-search-engine-from-the-search-bar), under a browser-agnostic approach, and saw that it is based on [OpenSearch](https://developer.mozilla.org/docs/Web/OpenSearch)

**Comment by zackkrida** [comment]
This reminds me for CC Search, there is a `!cc` flag for DuckDuckGo where if you search `!cc dogs` it will go right to CC Search.

https://duckduckgo.com/

**Comment by zackkrida** [comment]
> I guess this will have to be added to the WP theme?

Yes, great point. We should probably actually _remove_ the file in the frontend repo so we aren't somehow duplicating this functionality.

**Comment by AetherUnbound** [comment]
Bump! :smile: I would SO love to see this feature!

**Comment by dhruvkb** [comment]
I just realized that the DuckDuckGo search now directs to Openverse which is very awesome.

**Comment by AetherUnbound** [comment]
> I just realized that the DuckDuckGo search now directs to Openverse which is very awesome.

Really? In what way? :O

**Comment by dhruvkb** [comment]
Because DuckDuckGo search with `!cc` (I missed this condition which I believe was the reason for your surprise) redirects to CC Search, which now redirects to Openverse.

**Comment by obulat** [comment]
> I just realized that the [`!cc` DuckDuckGo search](https://github.com/WordPress/openverse/issues/79#issuecomment-929112606) now directs to Openverse which is very awesome.

I think we need to document it somewhere. We could also add it to the text in the search guide or about us page.

**Comment by sarayourfriend** [comment]
Shall we close this issue? After moving out of the iframe, the application's `opensearch.xml` file should start working properly again, right? If I go to staging.openverse.org and right-click the search box, I get an option from Firefox to add a keyword for Openverse search.

**Comment by panchovm** [comment]
I added the search engine from staging, but it redirects me to the wp.org site. Here is the flow I followed.

|Step|Screenshot|
|:---|:---|
|Adding Openverse staging as search engine|<img width="450" alt="CleanShot 2023-01-10 at 12 12 42@2x" src="https://user-images.githubusercontent.com/895819/211536757-5508552e-be68-4ea7-942f-bc671fd76010.png">|
|Assigned a keyword|<img width="450" src="https://user-images.githubusercontent.com/895819/211536979-4e86ff11-2475-442c-bf0c-5339a503e072.png">|
|Search from the browser|<img width="450" src="https://user-images.githubusercontent.com/895819/211537583-a5ea52ae-bf61-4164-a17c-fe558cd27d0a.gif">|
|Landing in wp.org site|<img width="669" alt="CleanShot 2023-01-10 at 12 18 40@2x" src="https://user-images.githubusercontent.com/895819/211537654-b84087e7-5c09-44f6-bb16-e4de6d03f4a6.png">|

**Comment by obulat** [comment]
We'll need to update the URL in the opensearch.xml:

https://github.com/WordPress/openverse-frontend/blob/77dc0b5ea091a88116ce6b258cd2c2275d69a4fe/src/static/opensearch.xml#L9

The logo URL there will also need to be updated.

**Comment by obulat** [comment]
The URL was fixed in https://github.com/WordPress/openverse-frontend/pull/2166, so now you can search from your search bar in Firefox using Openverse! 🎉

**Comment by AetherUnbound** [comment]
I just tried it and it works great!!! Thank you all 🤩
