### ISSUE TITLE
Playwright VR artifact is not uploaded on failure

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse#792]
## Description

Something is wrong with the VR artifact paths, so when the tests fail, we can't get the artifact:
`No files were found with the provided path: test-results. No artifacts will be uploaded.`

## Reproduction

1. See error in this run: https://github.com/WordPress/openverse/actions/runs/4294105790

## Screenshots

<img width="713" alt="Screenshot 2023-02-28 at 6 04 23 PM" src="https://user-images.githubusercontent.com/15233243/221893508-4575a290-2927-43d0-9e20-6c36bd01e206.png">

## Additional context

Related to the migration to monorepo.

**Comment by dhruvkb** [comment]
Very likely the path is nested inside `frontend/`.
