### ISSUE TITLE
Configure Dependabot for `documentation/` and `automations/python/`

### ISSUE THREAD

**Issue by dhruvkb** [WordPress/openverse#801]
## Description

Depdendabot PRs are failing PR label checks. Exhibit: https://github.com/WordPress/openverse/pull/789

This will happen when Dependabot will make PRs updating depdendencies for packages that are not configured in `.github/dependabot.yml`.

## Solution

Dependabot is configured via `.github/dependabot.yml` (https://github.com/WordPress/openverse/blob/857dc4ec26fd3553aa7daddfb598978b271849ed/.github/dependabot.yml) to apply the right set of labels on the PRs. The directories `documentation/` and `automations/python/` have not been configured in that file.

**Comment by AshwanthramKL** [comment]
Hey @dhruvkb, Can I try my hand at this?

**Comment by dhruvkb** [comment]
Sure @AshwanthramKL, please go ahead.
