### ISSUE TITLE
HMR is broken after the monorepo move

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse#817]
## Description

Working on the frontend became much more inefficient because when you change something, you often have to re-build the app manually.

## Reproduction

1. Start the Nuxt app by running `just frontend/run dev`
2. Delete one of the imports. The app will re-build and will show an error.
3. Re-add the deleted import. The app should re-build and start working again.
4. See the build error:
```
in ./src/styles/tailwind.css (../node_modules/.pnpm/css-loader@5.2.7_webpack@4.46.0/node_modules/css-loader/dist/cjs.js??ref--4-oneOf-1-1!../node_modules/.pnpm/postcss-loader@4.3.0_4dftvqknpgmotzmzzqmnfvmmye/node_modules/postcss-loader/dist/cjs.js??ref--4-oneOf-1-2!./src/styles/tailwind.css)
Module build failed (from ../node_modules/.pnpm/postcss-loader@4.3.0_4dftvqknpgmotzmzzqmnfvmmye/node_modules/postcss-loader/dist/cjs.js):
SyntaxError
```

**Comment by dhruvkb** [comment]
@obulat I am not able to consistently reproduce this. But it looks to me like it's an issue with the automatic resolution of the `tailwind.config.js` file. Could you try the methods defined in the Tailwind docs for [specifying a file path](https://tailwindcss.com/docs/configuration#using-a-different-file-name) and see if that works?

**Comment by dhruvkb** [comment]
**Update:** I tried setting the absolute path in the config and it seems to fix the issue. HMR worked for me after this change.
