### ISSUE TITLE
Improve Openverse Project board

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse#818]
## Problem

This is a meta issue for tracking the improvements on the new [Openverse Project board](https://github.com/orgs/WordPress/projects/75).
Please add any issues that will improve the board here.

## Description

- [x] Add "design: in discussion", "design: ready" labels in addition to the existing "design: needed" label. Use them to filter the "Design-related" view. Suggestions about naming the labels are welcome!
- [x] Check that "add new issues" workflow is synced ans correctly adds new issues from the catalog and infrastructure repositories to the project
- [x] #868
- [ ] #1163
- [ ] Move the issue to In progress when a PR is opened
- [ ] #1168
- [x] #1170

**Comment by AetherUnbound** [comment]
Okay I've been trying to figure out where all of our automations are and what our flows would look like and I _believe_ this captures everything:

- New issue added:
    - Add to board "backlog" with priority type
- Issue label changed:
    - Update priority in board (if changed)
    - Move to board "blocked" (if set to blocked)
- Issue closed:
    - Move issue to "done"
- New PR made:
    - Move issue to "in-progress" (from either backlog or todo)
    - Add to board "in-progress" with priority type
    - Add the appropriate "project" label if applicable
    - Add it to the discussion/project board if applicable
- PR closed:
    - Move issue back to "backlog"
    - Remove PR from board
- PR merged:
    - Move PR to "done"
- Schedule:
    - Clear "done" column weekly

**Comment by obulat** [comment]
I've updated the Project tracker workflow to automatically add all issues with a label "project: thread".

**Comment by sarayourfriend** [comment]
Does https://github.com/WordPress/openverse/issues/1931 replace this issue @obulat @krysal @zackkrida?

**Comment by zackkrida** [comment]
I think it should. I'm going to close this.
