### ISSUE TITLE
Add UI to opt out of or in to analytics

### ISSUE THREAD

**Issue by dhruvkb** [WordPress/openverse#822]
## Description

People might understandably not want to be analysed. Provide a UI to allow them to opt-out out (and opt-in to) analytics.

Currently the proposal is to put a checkbox in `/privacy` but there are designs in #791 by @panchovm to create a UI to manage preferences (which is also needed in the content safety project).

## Additional context

RFC: https://github.com/WordPress/openverse/blob/3fa9f03937d2af356535f158f7f80b20a6bd79d2/rfcs/analytics/20221006-implementation_plan_frontend.md

**Comment by panchovm** [comment]
Thanks for bringing this up. I added the `design: needed` label to link it with future design ideas I will share.

**Comment by dhruvkb** [comment]
A working demonstration of this was added in the #821 at the `/preferences` page but that is for internal use. A user-facing version of this needs to be developed.
