### ISSUE TITLE
[Feature] PR Slack notifier

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse#83]
## Problem

We would like a way to see new Pull Requests in our PR slack channel. We don't want this integration to generate too much noise, these notifications are intended to be a quick, casual ping "hey, check out this new PR if you want!". The native GitHub Slack integration is not a good fit, it produces a "wall of text" response for each PR, with too much clutter.

## Description

We could write a script in JS or Python in this repository, similar to @mkaz's work on `TinkerNotifier`, the bot for the tinker team (https://github.com/mkaz/octoack), that simply posts all new `openverse-*` repo pull requests to our slack channel, with a link. 

We could use that bot, my initial thoughts for _not_ using it are:

- It's written in Rust, which isn't used by our other projects, so makes it more difficult to edit if needed
- We'd have to host it, and I'm less sure about deploying/hosting/maintaining Rust applications, particularly as GitHub actions
- It's a relatively _simple_ piece of code to re-implement, and we already have similar scripts for working with the GitHub API
- We might want to customize the output or emojis used 😆 
- We don't need user-level tracking, as is included in that script

**Comment by AetherUnbound** [comment]
I thought we might be able to have the Tinker Bot accomplish this - do we need to write our own tool or can we use that?

**Comment by zackkrida** [comment]
Just updated my initial comment with more detail @AetherUnbound 😄

**Comment by AetherUnbound** [comment]
I wish there was a way to do a condensed preview using the default integration, but alas it seems like it's been an [open issue for a while](https://github.com/integrations/slack/issues/564) :disappointed:

**Comment by mkaz** [comment]
I see it as an opportunity to play with Rust :grin: 

If you want to modify that existing script to support multiple accounts/repos/channels, I'll host it and run it on the same instance I'm running ours. I can help with any tweaks too, but also totally understand it's a simple easy script that rewriting in Python would be pretty quick.

**Comment by zackkrida** [comment]
> I'll host it and run it on the same instance I'm running ours.

Well that sounds easy 😄 let's go for it!
