### ISSUE TITLE
Add pre-commit hook to format shell scripts

### ISSUE THREAD

**Issue by dhruvkb** [WordPress/openverse#847]
## Problem

We have quite a lot of shell scripts in the codebase. Prettier doesn't format them.

## Description

[`shfmt`](https://github.com/mvdan/sh#shfmt) is a tool for formatting shell programs. It is available as a [pre-commit hook](https://github.com/scop/pre-commit-shfmt#pre-commit-shfmt) and can be readily integrated with our linting setup.

## Additional context

This will undoubted cause our existing scripts to be slightly changed to match the style guide. It might be worth discussing if the changes are worth it.

**Comment by msolorio** [comment]
Hi @WordPress/openverse-maintainers! I would like to pick this up if that is alright.
