### ISSUE TITLE
Cannot comment about Playwright on PRs from forks

### ISSUE THREAD

**Issue by dhruvkb** [WordPress/openverse#853]
## Description

The action that comments about Playwright failures does not work on PRs from forks. This is a [known limitation](https://github.com/peter-evans/create-or-update-comment#action-inputs) and the workaround (using `pull_request_target`) is not acceptable because we want the tests to run in the context of the PR and not `main`.

## Reproduction

See this [failed run](https://github.com/WordPress/openverse/actions/runs/4330608751/jobs/7591849919).

## Solution

It would seem that the only solution is to print the debugging message in the failed Playwright job itself and skip the comment job for PRs from forks.

**Comment by dhruvkb** [comment]
Marked the priority as high because it fails (and blocks) PRs from contributors.

**Comment by sarayourfriend** [comment]
@dhruvkb Is it not possible to work around this by using `GITHUB_TOKEN` to give the action permissions to comment as the Openverse Bot?

Otherwise, your suggested solution of skipping the comment for forks makes sense to me and is additionally pretty easy to implement :+1:
