### ISSUE TITLE
Add non-production feature flag for marking half of results as sensitive

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse#854]
For the sensitive content flow we are designing in #791 we need a way to test sensitive results. For two reasons, I'd like to create a feature flag which marks 50% of results as sensitive:

- Folks testing this functionality should not have to see *actual* sensitive content if they do not want to.
- Because marking results as sensitive is a largely manual process, we do not actually have many results marked as sensitive.

By creating this feature flag we can mark non-sensitive results as sensitive in order to test these features. I propose when this flag is active, we manipulate the API results to set every other result to have a true value in their `mature` field. 

This flag will also need to set `mature=true` to API requests.

This flag should be `disabled` in production, and switchable everywhere else.

**Comment by dhruvkb** [comment]
> This flag will also need to set mature=true to API requests.

@zackkrida could you elaborate why? If we are mocking sensitive results, the point is to not see mature content, setting the flag to 'true' would mix fake-mature results with actual-mature ones, causing the very accidental exposure that we're trying to prevent in point 1.

**Comment by zackkrida** [comment]
@dhruvkb i didn't explain well, or correctly, what I was trying to convey. More like the opposite in fact. When this flag is enabled, I was think that we need the frontend to _think_ "mature" is enabled so that the ui toggle works properly without actually showing sensitive results, but not actually send the paremeter to the api.

**Comment by dhruvkb** [comment]
@zackkrida so you meant that this feature flag should have no effect if the user has opted to filtering out mature content in the UI?
