### ISSUE TITLE
Exclude tests and test assets from frontend image build context

### ISSUE THREAD

**Issue by dhruvkb** [WordPress/openverse#856]
## Description

The `test/` directory inside frontend is over a 100MB in size. Excluding it from the build context will make the images smaller and make the build a little faster. We don't need tapes and visual regression snapshots in our staging/prod containers.

## Screenshots

<img width="377" alt="image" src="https://user-images.githubusercontent.com/16580576/223350570-793926d3-ee27-49c3-a38f-0f236f0f3329.png">

<img width="1265" alt="Screenshot 2023-03-07 at 11 14 26 AM" src="https://user-images.githubusercontent.com/16580576/223350862-8c012e84-126b-4f8c-b4b4-1fa80664ad68.png">

**Comment by sehgxl** [comment]
Hey @dhruvkb I would like to work on this. But I have no idea where should I look for to understand how the build process works and make the required changes. Would appreciate if you point me in some direction. Thanks

**Comment by dhruvkb** [comment]
Hey @sehgxl, you can read about Docker's build context from [their docs](https://docs.docker.com/build/building/context/). For our frontend image, the `.dockerignore` file (https://github.com/WordPress/openverse/blob/main/frontend/.dockerignore) determines which files are excluded when building the Docker image. Adding the `test/` directory to this file will prevent it from being copied into the container and will reduce the size of the images.

**Comment by sehgxl** [comment]
@dhruvkb I have done the change and raised a [PR](https://github.com/WordPress/openverse/pull/2713). 

Was curious to how you are initiating the build process to verify the result. I tried doing `docker build .` while being in the `frontend/` directory but faced the following error. 

![Screenshot from 2023-07-25 16-06-37](https://github.com/WordPress/openverse/assets/83122406/46f0f65d-89d6-4f0a-b8a7-54b8724edfdc)

**Comment by dhruvkb** [comment]
Our Docker images need a bunch of information to compile, like Node version, pnpm version etc. So we use a [`just` recipe](https://github.com/casey/just) to build them. Instead of directly accessing `docker`, try this:

```console
$ just frontend/build-img
```

This runs the build-img recipe inside `frontend/justfile`, which populates the necessary env vars and then builds the Docker image.

https://github.com/WordPress/openverse/blob/6de944472d188e351af5058675af42f66f12256e/frontend/justfile#L36
