### ISSUE TITLE
Consider JSON5 for `package.json` files

### ISSUE THREAD

**Issue by dhruvkb** [WordPress/openverse#859]
## Problem

We've seen that JSON5 is a much improved and friendlier version of JSON. We use it in several places like our Talkback tapes and the `en.json5` translation file.

## Description

pnpm supports using `package.json5` as the package manifest. Using it might help us document the many many scripts we have and their pre-scripts. I often get confused because we have too many `i18n` anmd `test` scripts.

<img width="557" alt="Screenshot 2023-03-07 at 12 06 15 PM" src="https://user-images.githubusercontent.com/16580576/223361575-f4d5bd71-5bff-4193-9e75-38cabfaf5076.png">

## Alternatives

pnpm also supports YAML but it's got a bad reputation (I personally like it a lot). It's still popular than JSON5 and wider adoption (see syntax highlighting difference in screenshots) but it's more of a change which might turn off some people.

<img width="582" alt="Screenshot 2023-03-07 at 12 07 56 PM" src="https://user-images.githubusercontent.com/16580576/223361904-5759274f-86d4-43d1-bc5a-2d01eca26c7c.png">

**Comment by zackkrida** [comment]
We don't want to introduce something so non-standard despite the clear benefits, for the sake of compatibility with existing tooling and standards in the JS developer ecosystem.
