### ISSUE TITLE
Re-running failed Playwright tests leaves failure comment

### ISSUE THREAD

**Issue by dhruvkb** [WordPress/openverse#864]
## Description

The order of Playwright tests is

- <4 parallel>
  - clean-playwright-failure-comment
  - nuxt-playwright-e2e
  - nuxt-playwright-vr
  - storybook-playwright
- playwright-test-failure-comment

When any one of the 3 Playwright test jobs fails, the CI workflow fails with it. If you re-run the workflow to run only the failed jobs, the job `clean-playwright-failure-comment` is not executed (as it had passed in the previous run), which leaves the failure comment even if the Playwright tests pass in the re-run.

## Solution

An easy solution is to move the comment removal steps from the `clean-playwright-failure-comment` job to the `playwright-test-failure-comment` job so that it can delete the existing comment, if any, and post a new comment, if needed.

**Comment by AdarshRawat1** [comment]
Please guide me further on how I work on this issue.
