### ISSUE TITLE
Do not require labels on project planning PRs

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse#875]
## Problem

A PR with a project plan, an RFC or a project implementation plan is marked as failing the CI because it doesn't have the required label.

## Description

It doesn't always have sense to have the required label on the project planning PRs.
I'm not sure what labels we should use here. My first thought was to add a single "project" label, so any PR that has all four required labels OR a "project" label pass the CI action.

## Alternatives

We could also create (and reuse) labels for project planning, something like:
- goal: planning
- aspect: text
- goal: addition
- priority: medium / high

What do you think, @WordPress/openverse-maintainers?

**Comment by krysal** [comment]
I don't see why project planning issues/PRs can't have the usual required labels. I don't think "planning" is a goal in itself either, so I vote for keeping the regular labels. The aspect can be always "text" as you suggest. The priority and the goal depend on what is being proposed. We could add "project" and "skip-changelog" and document this in the [Project in Openverse guidelines](https://github.com/WordPress/openverse/tree/main/docs/projects) as well.

**Comment by obulat** [comment]
I can see your point, and it makes sense, @krysal . Closing this issue as not planned
