### ISSUE TITLE
Update `DEPLOYMENT.md` with information for the API and move it to the documentation site

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse#876]
## Problem

The existing [`DEPLOYMENT.md`](https://github.com/WordPress/openverse/blob/main/frontend/meta_docs/DEPLOYMENT.md) file was written for the frontend, but it can be easily updated to apply to the API with the addition of API specific details like migrations and new links for the different workflows for each app and environment.

## Description

Update the existing DEPLOYMENT.md with information about the API and move it into the documentation website.

**Comment by dhruvkb** [comment]
I would recommend adding a `deploy.md` page under [`documentation/guides/api`](https://github.com/WordPress/openverse/tree/bc60edc64fe34e59bbda5b880db76f4b1b41b9da/documentation/guides/api) or adding the content to the existing doc @ https://github.com/WordPress/openverse/blob/bc60edc64fe34e59bbda5b880db76f4b1b41b9da/documentation/guides/deploy.md.

This is a good chance to move as much documentation as possible to the docs site, which is a much more natural place imo to look for help. It becomes more useful as more content gets added to it.
