### ISSUE TITLE
Update reverse proxy to allow for path prefix rewriting on the API

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse#878]
## Problem

In order to facilitate eventually deploying the API as a path at `openverse.org/api`, we must develop a method for either re-writing incoming path requests to remove the `/api` path prefix or change our Django configuration to accommodate a path prefix. In principle it is not difficult to simply add a path prefix configuration option to Django, but in practice, for our application and especially for our tests and swagger documentation, it is a nightmare of fiddly unit test changes and impossibly tangled circular imports that will boggle the mind (believe me, I tried HARD to make it work!). Instead, we can use our reverse proxy to rewrite the path and remove the path prefix. This will require zero changes to the Django application.

## Description

Using the `alias` feature, we should be able to strip any path prefixes we want: https://nginx.org/en/docs/http/ngx_http_core_module.html#alias

For example, the following should work (theoretically):

```
location /api/ {
    alias /;
}
```

I've read somewhere that Nginx potentially has issues caching this sort of thing. If we try this and notice a performance issue, we could switch to Caddy (which might not be a bad idea generally, but it's not strictly necessary otherwise) which does do this with caching and supports all the other features we use in Nginx (with much simpler configuration).

**Comment by dhruvkb** [comment]
I don't remember the specifics but I think we had learned that a subdomain `api.openverse.org` could be a potentially easier place to to host the API. I am not sure if the work generated by this issue would be applicable if the subdomain route was taken instead.

**Comment by sarayourfriend** [comment]
Hosting it as a subdomain would definitely be easier but is a deviation from decisions we made in November (this discussion was held privately, so I can't link it here). If we've changed course to stick with a subdomain then we can close this issue for sure!

**Comment by dhruvkb** [comment]
<sub>(Not adding anything valuable to the conversation but)</sub> I like subdomains.
