### ISSUE TITLE
Yellow background when reporting an image from Gutenberg

### ISSUE THREAD

**Issue by panchovm** [WordPress/openverse#879]
## Description

When you click on "Report image" from the Media tab in Gutenberg, the report page shows a full-size yellow background.

## Reproduction

This process requires having edit access to Gutenberg and be able to insert media content from the block inserter
1. Go to Gutenberg.
2. Click on the insert block toggle.
3. Click on Media tab, and then in Openverse.
4. Click on the ellipsis menu in any image.
5. Click on "Report image".
6. You will land on a page with a full-size yellow background.

## Screenshots
https://user-images.githubusercontent.com/895819/224041940-948f1a15-7744-4b26-aef3-be4a36526615.mp4

**Comment by krysal** [comment]
To confirm: the expected fix is to make the background white, right? Or is there another design change required here?

**Comment by panchovm** [comment]
The expectation is a white background. Thanks for asking ✨

**Comment by zackkrida** [comment]
Increasing this to high priority. This integration may be folks first exposure to Openverse and I would hate for them to see such an obvious visual bug.
