### ISSUE TITLE
"Openverse Syntax Guide" content page missing placeholder for "*"

### ISSUE THREAD

**Issue by lidialab** [WordPress/openverse#880]
## Description

Page "Openverse Syntax Guide" is probably not matching the placeholder for the "*" symbol in the sentence: "You can use the to mark a prefix term. This will match anything after the *."

Consequently it does not appear in the corresponding translated page either (for Italian, as an example, we translate it here:  https://translate.wordpress.org/projects/meta/openverse/it/default/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=12384656&filters%5Btranslation_id%5D=92161213 ; we can see there is a placeholder for it, "###operator-name###", but it doesn't even appear in the English version).

## Reproduction
Search the sentence here: https://openverse.org/search-help

**Comment by obulat** [comment]
Thank you for reporting this issue, @lidialab. We have greatly reduced the amount of text on the Syntax Guide  page, and this phrase was removed.
