### ISSUE TITLE
Use label.yml to determine required labels

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse#884]
## Description

We currently have a list of the required labels explicitly defined in the `label_pr.py` script:

https://github.com/WordPress/openverse/blob/bc60edc64fe34e59bbda5b880db76f4b1b41b9da/automations/python/label_pr.py#L25

This list is redundant with the `is_required` field in the list of labels defined in `labels.yml`:

https://github.com/WordPress/openverse/blob/89953c6aec63260b9d49b86e0764d667fea4e8a4/automations/data/labels.yml#L17

We could leverage the latter in the script instead to find out which stacks are required. We could also add an `apply_all_available` boolean field to a group to replace the `GET_ALL_CATEGORY_LABELS` value:

https://github.com/WordPress/openverse/blob/bc60edc64fe34e59bbda5b880db76f4b1b41b9da/automations/python/label_pr.py#L27

**Comment by dhruvkb** [comment]
@AetherUnbound you've explained the steps fairly clearly so I think this can be a "good first issue".

**Comment by AetherUnbound** [comment]
Thanks @dhruvkb!
