### ISSUE TITLE
Absorb `actionlint` into pre-commit

### ISSUE THREAD

**Issue by dhruvkb** [WordPress/openverse#896]
## Problem

Currently `actionlint` is a separate workflow that runs on `push` (to the `main` branch) and `pull_request`.

https://github.com/WordPress/openverse/blob/38af21c359703d3faee9e160f1ac69372661d6a2/.github/workflows/actionlint.yml

This is a problem because it reports issues after they have been pushed instead of locally before pushing.

## Description

`actionlint` offers [`pre-commit` hooks](https://github.com/rhysd/actionlint/blob/main/docs/usage.md#pre-commit).

This means that we can
- run the checks locally before committing and pushing
- get rid of the separate workflow and run the check as a part of the Lint job inside the CI + CD workflow.

**Comment by AdarshRawat1** [comment]
Please, guide me on how I can get started on this issue.

**Comment by dhruvkb** [comment]
@AdarshRawat1 to resolve this issue you will need to 
- add actionlint to our `.pre-commit-config.yaml` file as described [here](https://github.com/rhysd/actionlint/blob/main/docs/usage.md#pre-commit)
- delete the `actionlint.yml` file from `.github/workflows`.

**Comment by AetherUnbound** [comment]
To add some additional clarity, you'll actually need to edit the pre-commit-config template here: https://github.com/WordPress/openverse/blob/main/templates/.pre-commit-config.yaml.jinja

That template is then rendered into `.pre-commit-config.yaml` (see our template README for more info: https://github.com/WordPress/openverse/tree/main/templates). You can check out #963 for a good example of making modifications to the pre-commit files. I'll go ahead and assign you the issue!

**Comment by AdarshRawat1** [comment]
Thank you, @dhruvkb  @AetherUnbound
