### ISSUE TITLE
Port conflict with Slack

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse#906]
## Description

I tried `just recreate` to bring up the API today and it turns out we have a port conflict with Slack. It seems these port conflicts will continue to be a frustration! There appear to be no safe ranges :sob: 

```
Error response from daemon: driver failed programming external connectivity on endpoint openverse-proxy-1 (053504d5eed22ae976700dbae73cd6d53c874d2d8b46b3dd9ad2651be53ed877): Error starting userland proxy: listen tcp4 0.0.0.0:50200: bind: address already in use
error: Recipe `dc` failed on line 116 with exit code 1
error: Recipe `up` failed on line 124 with exit code 1
error: Recipe `recreate` failed on line 133 with exit code 1
➜  openverse git:(add/save_cleanup_info) ✗ lsof -i:50200
COMMAND  PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
slack   2645 sara   32u  IPv4 119794      0t0  TCP saras-laptop.lan:50200->ec2-3-25-24-78.ap-southeast-2.compute.amazonaws.com:https (ESTABLISHED)
```

I don't know if this occurs on other OSs than Linux or if it has to do with the particular version of slack I'm running:

```
➜  openverse git:(add/save_cleanup_info) ✗ slack --version
4.28.171
```

I'm on Arch and using this AUR package to manage my Slack installation: https://aur.archlinux.org/packages/slack-desktop

I've also updated my version of slack to `4.29.149` and am not seeing it the issue now. However, I'm not sure if the binding is a transient thing. Of course nothing else shows up online when I search for "Slack 50200", I'm sure it's just bad luck that we've happened to land on the same port. I'm marking this issue as blocked so that I confirm that I can reproduce it with the newest version.

## Reproduction

1.  Run the application Slack (potentially needs to be on Linux)
2.  Run `just up` to run the API
3. See the error pasted above. Check `lsof` to see if Slack is the thing causing the conflict.

**Comment by dhruvkb** [comment]
This is unfortunate. But it's not reproducible with Slack version 4.29.149 and Docker version 20.10.22 (Docker Desktop) on macOS.

**Comment by AetherUnbound** [comment]
I am also unable to reproduce on Slack 4.29.149 and Docker 20.10.12 on Ubuntu.

**Comment by sarayourfriend** [comment]
I haven't been able to reproduce it since, either. I'll note thought that Docker version shouldn't have anything to do with it :sweat_smile: Slack was just using one of the same ports that we have configured for our services, it's a natural thing that might happen in the future, even though we're theoretically using the "safest" range possible.
