### ISSUE TITLE
Implementation Plan: Blurring sensitive results

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse#938]
## Description

Part of https://github.com/WordPress/openverse/issues/377
Project Proposal: 

<s>https://github.com/WordPress/openverse/blob/main/rfcs/detecting_sensitive_textual_content/20230309-project_proposal_detecting_sensitive_textual_content.md#required-implementation-plans</s>

https://github.com/WordPress/openverse/blob/main/documentation/projects/proposals/trust_and_safety/detecting_sensitive_textual_content/20230309-project_proposal_detecting_sensitive_textual_content.md#required-implementation-plans

The implementation plan must cover the following key aspects in addition to the baseline expectations:

- Must cover the UI changes requested by design, management of both new settings, and displaying the blurred image with the ability to unblur.
- Must cover accessibility testing for the new UI elements, especially the unblur/reblur controls.

[Figma designs by @panchovm are here](https://www.figma.com/file/bDTfGzBit8rGRPktOR1cu4/Safe-content-browsing-flow?node-id=22-13656). Refer to the origin design issue for the historical progression of those designs: https://github.com/WordPress/openverse/issues/791

Please request Francisco as a reviewer on the implementation plan.

**Comment by zackkrida** [comment]
Designs are finalized in #791 and this implementation plan can be unblocked.
