### ISSUE TITLE
Quickstart guide doesn't mention `just env`

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse#964]
The quickstart guide as written will error upon the first `just up` because there's no `.env` file.

We can either ask users to `just env`, or we can consider including it elsewhere as part of `just install`, or again some alternative approach.

**Comment by dhruvkb** [comment]
`.env` should not be needed for use with Docker when running `just up`. Whatever environment variable is in that file should be be defined in `env.docker` if different from the default.

**Comment by AdarshRawat1** [comment]
Requesting permission to contribute to this feature. . Can you please advise on how I can get involved? Thanks

**Comment by dhruvkb** [comment]
@AdarshRawat1 the scope of this issue has increased a bit since my comment https://github.com/WordPress/openverse/issues/964#issuecomment-1476928594, as @sarayourfriend pointed out that we need the `.env` file as a way to configure the local setup without Git tracking the file. 

I would recommend picking something else while we update this issue.

**Comment by obulat** [comment]
Hi @AdarshRawat1, are you still interested in contributing with this issue based on the latest comments? I assigned this to you :)

**Comment by AdarshRawat1** [comment]
@obulat I'll work on this issue. Please guide me.
@dhruvkb I believe this matter would benefit from your expertise and recommendations.

**Comment by zackkrida** [comment]
@AdarshRawat1 I've unassigned you from this issue. If you _do_ want to work on it though, please let me know! The next steps are:

1. Update our `just env` script to check for if the file exists before creating it (inspired by the [example here](https://github.com/WordPress/openverse/issues/964#issuecomment-1481989279))
2. Make the `env` script a dependency to the `up` script in our `justfile`.
