### ISSUE TITLE
[Improvement] Diagrams with transparent background are not great in dark mode

### ISSUE THREAD

**Issue by milktea02** [WordPress/openverse#968]
## Description

Readme diagrams that have a transparent background are not legible when in dark mode.

## Reproduction

1. Set your github [appearance to one with a dark background](https://github.com/settings/appearance)
<img width="795" alt="image" src="https://user-images.githubusercontent.com/5224106/226455872-665c8e58-2d31-4f24-b37a-9b449e04d2f0.png">

3. Go to a [README that has a diagram using transparent background](https://github.com/WordPress/openverse/tree/main/ingestion_server)
4. Be sad because the text is hard to read
5. Complain about it to @AetherUnbound during a conference

## Screenshots

<img width="1104" alt="image" src="https://user-images.githubusercontent.com/5224106/226454607-04b81611-6bb5-4e59-b324-23aecbd09769.png">

Vs image against a lighter background

<img width="601" alt="image" src="https://user-images.githubusercontent.com/5224106/226455580-6f9ef9bd-51b9-4c70-a28e-5535d485d87b.png">

## Environment

I've only accessed this page on MacOs and chrome

## Additional context

This should be as easy as opening the image on your favourite image editor and saving the image with alpha turned off.

<img width="313" alt="image" src="https://user-images.githubusercontent.com/5224106/226456163-8ff87517-cf42-4412-b7e3-72fa3b4ea000.png">

**Comment by dhruvkb** [comment]
The diagram is generated from the XML file at https://github.com/WordPress/openverse/tree/main/readme_assets/system_diagram. Loading that XML into Draw.io and exporting a fresh PNG should fix this.
