### ISSUE TITLE
Links in CONTRIBUTING.md are not working 

### ISSUE THREAD

**Issue by AdarshRawat1** [WordPress/openverse#999]
## Description

The hyperlinks* listed in the "[Code and code-related contributions](https://github.com/WordPress/openverse/blob/main/CONTRIBUTING.md#code-and-code-related-contributions)" section of the `CONTRIBUTING.md` file are leading to a 404 error page.

* **Broken hyperlinks** 
the developer documentation
Storybook (UI components)
Tailwind Config Viewer (design tokens)
GitHub contribution practices
Dev flow
General setup guide
Quickstart guide

## Screenshots
![image](https://user-images.githubusercontent.com/100958893/227149488-d8979002-6668-4e51-b4b1-0ed4243da6f7.png)

## Additional context
In preparation for submitting a pull request, kindly furnish me with the necessary links.

**Comment by dhruvkb** [comment]
@AdarshRawat1 please use https://wordpress.github.io/openverse/ in the meantime, while we identify and fix the issue.

**Comment by AdarshRawat1** [comment]
https://github.com/WordPress/openverse/blob/main/documentation/index.md#related-documentation
The links under this section are also redirecting to error 404.

Can I update these links? Should I make a PR for updating the links of documentation?

**Comment by obulat** [comment]
Thank you for opening the issue, @AdarshRawat1! This issue happened during the migration to the monorepo and to the new domain, https://docs.openverse.org, and has since been fixed. Please, feel free to look through other issues with "good first issue" or "help wanted" labels.
